### ISSUE TITLE
Exception when disabled session tracking

### ISSUE THREAD

**Issue by awyl** [ravendb/ravendb#10044]
When we turned off tracking of a session, like it was described [here](https://ravendb.net/docs/article-page/4.1/csharp/client-api/session/configuration/how-to-disable-tracking), we get 

`InvalidOperationException: Cannot execute 'GetDocument' before operation execution.`
> Raven.Client.Documents.Session.Operations.LoadOperation.GetDocument<T>() in C:\Builds\RavenDB-Stable-4.2\42027\src\Raven.Client\Documents\Session\Operations\LoadOperation.cs
> Raven.Client.Documents.Session.AsyncDocumentSession.LoadAsync<T>(string id, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42027\src\Raven.Client\Documents\Session\AsyncDocumentSession.Load.cs

We only get this when the supplied `id` into `LoadAsync` was non existent.  If we took off `NoTracking = true` and everything stayed the same, it worked as expected (no exception).

**Comment by ppekrol** [comment]
Hi,

thank you for submitting a bug. I'm looking into this: https://issues.hibernatingrhinos.com/issue/RavenDB-14461

**Comment by ppekrol** [comment]
PR: https://github.com/ravendb/ravendb/pull/10045

**Comment by awyl** [comment]
Hi,

I tested with 4.2.8.  I still get the same error.


> System.InvalidOperationException: Cannot execute 'GetDocuments' before operation execution.
>    at Raven.Client.Documents.Session.Operations.LoadOperation.GetDocuments[T]() in C:\Builds\RavenDB-Stable-4.2\42034\src\Raven.Client\Documents\Session\Operations\LoadOperation.cs:line 133
>    at Raven.Client.Documents.Session.AsyncDocumentSession.LoadAsync[T](IEnumerable`1 ids, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42034\src\Raven.Client\Documents\Session\AsyncDocumentSession.Load.cs:line 45
>

**Comment by ppekrol** [comment]
@awyl can you show me your session code? Or create a failing test: https://ravendb.net/docs/article-page/4.2/csharp/start/test-driver

**Comment by awyl** [comment]
Here is a test that generate the same error on my machine.

```csharp

[Fact]
public async Task FindByEmptyCollectionShouldWork()
{
    using var store = GetDocumentStore();
    using var session = store.OpenAsyncSession(new Raven.Client.Documents.Session.SessionOptions
    {
        NoTracking = true
    });

    var ids = new string[] {};
    var objs = await session.LoadAsync<Art>(ids);

    Assert.NotNull(objs);
}
```

**Comment by ppekrol** [comment]
@awyl Many thanks for a repro. This is something that we haven't considered.

I've opened a PR: https://github.com/ravendb/ravendb/pull/10092

**Comment by awyl** [comment]
Thanks!  Any idea when a new nuget will be released?

**Comment by ppekrol** [comment]
We just released stable, expected date of next one is in around 6 weeks. We are now in a process of migrating to .NET Core 3.1, before the release we need to test it properly.

What I would suggest, since this is a Client API issue only, is to use 4.2.9 nightly package from https://myget.org/gallery/ravendb

Once this PR is merged I will release a nightly for you to check.

**Comment by ppekrol** [comment]
I've merged the PR, it should be available on MyGet in around 1h. Closing for now.
