### ISSUE TITLE
Unable to start server on Mac OS Catalina

### ISSUE THREAD

**Issue by awyl** [ravendb/ravendb#10091]
MacOS: 10.15.2

The gatekeeper blocks it.

1. Download latest MacOS package
2. Run ./run.sh

Error:
`"Raven.Server" cannot be opened because the developer cannot be verified.`

Tried to allow it specifically, but it then prompts me for all others `dylib`.

**Comment by ayende** [comment]
See workaround here: https://support.apple.com/en-il/guide/mac-help/mh40616/mac

Our binaries are signed, but it appears that Mac now requires a key from Apple.

**Comment by ayende** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-14528

**Comment by garayx** [comment]
try to use `sudo spctl --master-disable` to allow all apps
