### ISSUE TITLE
ramdisk issue

### ISSUE THREAD

**Issue by vishal-h** [ravendb/ravendb#10141]
https://github.com/ravendb/ravendb/blob/9b5313689310f4938c0c2f9a4385e9fad2708cfe/src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs#L421

Going by comments in https://askubuntu.com/questions/703576/fdisk-l-shows-16-ram-disks-dev-ram0-ram15

What seems to have changed is that the kernel did not used to list ramdisks in /proc/partitions, but now does

so the hashset result of https://github.com/ravendb/ravendb/blob/9b5313689310f4938c0c2f9a4385e9fad2708cfe/src/Sparrow.Server/Platform/Posix/KernelVirtualFileSystemUtils.cs#L158

contains "ram" (ram0..ram15 -> remove digit -> remove duplicates) and this is not a valid sys/block but gets invoked in https://github.com/ravendb/ravendb/blob/9b5313689310f4938c0c2f9a4385e9fad2708cfe/src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs#L421

It is strange that this issue was not present earlier. Maybe it's to do with kernel changes related to showing ramdisks in /proc/partitions

**Comment by vishal-h** [comment]
Google group link
https://groups.google.com/forum/#!searchin/ravendb/rotational%7Csort:date/ravendb/vdA66PE0p6o/wSCLNjDUAAAJ

**Comment by vishal-h** [comment]
This might give an idea
https://source.puri.sm/guido.gunther/linux-next/commit/53978d0a7a27eb036b9bf33c4caa06257a9dbed7

**Comment by vishal-h** [comment]
Fix can be a simple one liner at/after https://github.com/ravendb/ravendb/blob/9b5313689310f4938c0c2f9a4385e9fad2708cfe/src/Sparrow.Server/LowMemory/CheckPageFileOnHdd.cs#L423

if (disk.Equals("ram", StringComparison.CurrentCultureIgnoreCase)) continue;

**Comment by ayende** [comment]
Can you send a PR for this?

**Comment by vishal-h** [comment]
I sent a PR but did cla/sign and fixed commit message after sending the PR.

**Comment by ppekrol** [comment]
Closed via https://github.com/ravendb/ravendb/pull/10292
