### ISSUE TITLE
Consider supporting an alternate format for HiLo IDs that does not use '/'

### ISSUE THREAD

**Issue by feO2x** [ravendb/ravendb#10365]
In our last projects with RavenDB, we had issues with HiLo IDs when transmitting them in HTTP URLs. The projects were all structured as a distributed system with a Web API implemented in ASP.NET Core MVC and a React SPA client (which is quite a common scenario I would guess).

We had the following issues:

- as the default HiLo IDs contain a slash '/', e.g. `users/115-A`, the developer needed to use the JS `encodeURIComponent` function before sending an HTTP Request so that every slash is URL-encoded to `%2F`.
- On the backend, we had to manually call `WebUtility.UrlDecode` to tranform the HiLo ID into its proper format for querying RavenDB (this is only necessary if the ID was part of the sub path of the URL - query parameters were automatically transformed by ASP.NET Core MVC).
- Our developers often forgot to apply this pattern in new client views / Web APIs, so this kind of developed to defect that we observed several times in different locations in our code base.
- In projects where we used an Apache Proxy Server in front of our Web API service, the server immediately responded with an HTTP 404 to URLs that contained an escaped slash (`%2F`). We had to specifically disable this blocking feature.

**Thus, I sugggest we should make HiLo IDs more web-friendly so that these issues do not occur in future projects that incorporate RavenDB.** The HiLo algorithm should support another format that does not use slashes and that users can opt into. I would simply replace the slash '/' with a dash '-', e.g. `organizations-500-A`. I don't think this is a breaking change as RavenDB sees IDs as just strings (and the HiLo algorithm calculates the next ID based on a document with a specific ID).

I'm looking forward to your opinion on this matter.

**Comment by garayx** [comment]
There is already options to do so:
https://ravendb.net/docs/article-page/4.2/Csharp/client-api/configuration/identifier-generation/global#identitypartsseparator

**Comment by ppekrol** [comment]
Starting from 5.0 you will be able to define IdentityPartsSeparator server-side. Relevant issue is here: https://issues.hibernatingrhinos.com/issue/RavenDB-13456

**Comment by feO2x** [comment]
Thank you both for pointing me in the right directions. As this is already possible, I will close this issue.
