### ISSUE TITLE
ApplyDeleteCommands for default collection doesn't work well with scripts using a filter on document properties

### ISSUE THREAD

**Issue by vvanderkroef** [ravendb/ravendb#10486]
I'm using a transform script in which I filter documents I want to load into another database based on certain conditions.

For example I use this script to ETL documents only when the property SiteStatus is equal to "Running":

```
if (this.SiteStatus === "Running")
{
 loadToPortals(this);
}
```
This is working fine whenever the SiteStatus switches to "Running". The document is loaded to the other database. But when the SiteStatus changes from "Running" to "Stopped", nothing happens. There is no DELETE triggered.

This problem only occurs when using the default collection. This is caused by the if "operation == OperationType.Delete" condition on line 477 of RavenEtlDocumentTransformer.

https://github.com/ravendb/ravendb/blob/d2eb93144de2dd955737a04f460c55504d789c9f/src/Raven.Server/Documents/ETL/Providers/Raven/RavenEtlDocumentTransformer.cs#L477

Because the ApplyDeleteCommands method is called with OperationType.Put it will not delete the document when loading documents to te default collection.

Isn't this a bug?

**Comment by arekpalinski** [comment]
Yes, it is a bug. It's reported here: https://issues.hibernatingrhinos.com/issue/RavenDB-14708. 

If you could create a PR that would be awesome. See our contribution guidelines https://github.com/ravendb/ravendb/blob/v4.2/CONTRIBUTING.md#submitting-a-pull-request

ETL related tests can be found here: https://github.com/ravendb/ravendb/tree/v4.2/test/SlowTests/Server/Documents/ETL

Here is the base class for Raven ETL tests:
https://github.com/ravendb/ravendb/blob/v4.2/test/SlowTests/Server/Documents/ETL/Raven/BasicRavenEtlTests.cs
