### ISSUE TITLE
RavenDb.Embedded Microsoft.AspnetCore.App dependency

### ISSUE THREAD

**Issue by gxsham** [ravendb/ravendb#10714]
Hi All,

We are using RavenDb.Embedded for our tests and we love it, but we have an issue running the tests on the agent. Our docker setup uses the major and minor version of the dotnet core runtime, currently, 3.1 and it will pull the latest patch available, currently 5. Your package has a hardcoded dependency on Microsoft.AspnetCore.App version (currently 3.1.4) and if there is a new patch on dotnet core the test setup gets broken. Are there any plans to relax that dependency? We can use the exact version of the runtime, including the patch in docker, but that's harder to maintain and it will cause other issues.

**Comment by ayende** [comment]
Can you take a look at this? 
https://groups.google.com/g/ravendb/c/fsCHcnET_Y4

It explains our reasoning and a workaround for you to use.

**Comment by gxsham** [comment]
The workaround worked as expected. We will still try to use the latest version when possible. Thanks a lot!
