### ISSUE TITLE
FYI - ASP.NET Core Libuv transport being obsoleted

### ISSUE THREAD

**Issue by Pilchie** [ravendb/ravendb#10776]
Hi

I noticed that RavenDB has an option to use the Libuv transport from ASP.NET Core.

I just wanted to give you a heads up that ASP.NET Core plans to obsolete the Libuv transport in .NET 5.0, and remove it in .NET 6

See https://github.com/aspnet/Announcements/issues/424 for details.

**Comment by ayende** [comment]
That is for compatability with some (quite old) mode of operation. We can safely remove it with no issues.
Thanks, we'll remove that soon

**Comment by ppekrol** [comment]
Thank you @Pilchie 

I've created an issue to track it (https://issues.hibernatingrhinos.com/issue/RavenDB-15286). We will remove it once the project moves to .NET 5.0.
