### ISSUE TITLE
Lucene.Net.dll signature problems

### ISSUE THREAD

**Issue by gitfer** [ravendb/ravendb#11060]
We are considering porting our company application from RavenDB 3.5 to RavenDB 5.

Our application actually runs on .net framework 4.7.2 and while testing our application we bumped into this same sign error on Lucene.Net.dll referenced by RavenDB.
https://stackoverflow.com/questions/21763822/how-to-disable-strong-name-verification-for-all-net-assembly 

We are using RavenDB-5.0.2-windows-x64 with its Lucene.Net.dll included (3.0.32.0).

I've just pushed https://github.com/gitfer/MyWebApplication472 where you could reproduce our problem (which is not an implementation problem I think).

I've managed to have my webapp working by putting

 ` <system.web>`
`<hostingEnvironment shadowCopyBinAssemblies="false" />`
  `</system.web>`

but I think that's just a signing problem that should be fixed on Raven-side.

**Comment by ppekrol** [comment]
Hi @gitfer 

We have signed the Lucene.Net.dll: https://github.com/ravendb/ravendb/pull/11061
You can download the 3.0.34 nupkg from our repository, extract the DLL (I'm using Nuget Package Explorer) and use it in your project.

Thank you for submission of this issue.

**Comment by gitfer** [comment]
Just tried that 3.0.34.0 out, 👍 . Thanks!
