### ISSUE TITLE
[3.5] BulkIngestion fails with `SynchronizationLockException`

### ISSUE THREAD

**Issue by danielmarbach** [ravendb/ravendb#11112]
Besides getting #11108 we are also running into `SynchronizationLockException` with bulk ingestion. Something seems to be off with bulk ingestion potentially not freeing up system resources fast enough. 

```
System.Threading.SynchronizationLockException: Could not get the PUT serial lock in (un)reasonable timeframe, aborting operation
   at Raven.Database.Impl.PutSerialLock.Lock()
   at Raven.Database.DocumentDatabase.Batch(IList`1 commands, CancellationToken token)
   at Raven.Database.Server.Controllers.DocumentsBatchController.<BulkPost>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
```

**Comment by arekpalinski** [comment]
Do you run multiple bulk insert operations concurrently?

**Comment by arekpalinski** [comment]
I see you do - https://github.com/ravendb/ravendb/issues/11108#issuecomment-692164183

**Comment by danielmarbach** [comment]
Doesn't this design lead to thread pool starvation under load?

```
            // if we haven't flushed the previous one yet, we will force
            // a disposal of both the previous one and the one before, to avoid
            // consuming a lot of memory, and to have _too_ much concurrency.
            if (previousTask != null)
            {
                previousTask.ConfigureAwait(false).GetAwaiter().GetResult();
            }
            previousTask = current.DisposeAsync();
```

**Comment by danielmarbach** [comment]
Also raised https://github.com/ravendb/ravendb/pull/11114

**Comment by arekpalinski** [comment]
The original issue `Could not get the PUT serial lock in (un)reasonable timeframe, aborting operation` means there was a write operation that took more that 2 minutes. 

What is the typical size of you bulk insert batches?

**Comment by danielmarbach** [comment]
It depends. Let me give you a little bit of history. ServiceControl ingests audit messages from an audit queue and stores them in an embedded ravendb for indexing purposes to extract and visualize conversations across message flows. Historically we have been using a single session per message and we have gotten several hints from support of RavenDB over the past few years that this is not an efficient way of ingesting data into RavenDB (due to the overhead of the session management as well as the scalability limits due to max concurrent sessions). In recent releases, we have introduced a batching approach that batches multiple ingestions together and then inserts many of them in bulk into RavenDB. In general, this has given us a great improvement for cloud disks in our test environments as well as decreased the pressure on RavenDB indexing quite a bit as well as increasing the ingestion throughput.

So technically an audit queue can have varying degrees of message sizes only restricted by the limitations of the transport (i.ex. Azure Storage Queues max 64KB, Azure Service Bus 256 KB or 1 MB max...). We have not seen in the previous non-batching mode the serial lock problem quite often but since we have switched to batching and bulk ingestion we are falling into this and the other related problem I commented on.

It might be important to note that the batching is not time-based and it takes into account that individual inserts can fail (that will be released and retried from a transport perspective). In essence, we take what we get from the transport (based on the transports latency) and process a batch of messages, once done take the next batch of messages to bulk insert.

**Comment by ayende** [comment]
The issue here is likely that the transaction are _very_ big and take time to hit the disk properly.
You are writing to the bulk insert while this is happening, but this gets queued up, and eventually we are too late.

Can you also check your disk I/O during that time frame?

**Comment by danielmarbach** [comment]
Isn't the bulk insertion design supposed to adjust the bulk operations according to the document sizes and batch size?

```
                            //essentially for a BatchSize == 1024 and stream of 1MB documents - the actual batch size will be 128
                            // --> BatchSize = 1024 / (dataSize = 1024/BigDocumentSize = 250) * 2 == 128
```

at least this is what this hints and the documentation is not really making any indications of these limitations in https://ravendb.net/docs/article-page/3.5/csharp/client-api/bulk-insert/how-to-work-with-bulk-insert-operation#limitations

Or is the logical conclusion of this discussion that original recommendations of batching are not holding up because of the generic problem that we cannot predict the size of the document and therefore by batching multiple of those together things are actually becoming worse than doing individual session stores due to the overall transaction size increase?

**Comment by ayende** [comment]
The problem is that you have a convoy in the process.
We are able to accept writes from the client at a rate that is faster than the rate of writing to the disk.
We are able to hold on for a while, but eventually we time out. On the cloud, that is usually when we are seeing IO credits exhaustion.

RavenDB assumes that the rate of writing to the disk is roughly the same. If you are suddenly have a drop in the IO perf, that can cause this issue.
