### ISSUE TITLE
Switch to System.Text.Json for .NET 5?

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#11264]
Now that .NET 5 has a passable replacement for Newtonsoft.Json and is MUCH faster, is there a plan to switch?

The reason I ask is that I'm doing a blockchain that needs to hash the data of the row (plus timestamp, and previous hash of course).  My worry is that if RavenDb changes later, and the structure of the json changes because of this, the hashes won't be able to be validated directly with the data in the future.

Thanks!

**Comment by ppekrol** [comment]
@JohnGalt1717 

For near future I would say no, for longer, yes. The first RavenDB working on .NET 5.0 will be RavenDB 5.1. There is an interface 'ISerializationConventions' that we introduced in RavenDB 5.0 that can be used to switch the default serializer.

That being said, even if we will introduce new serializer in the future, we do not see a reason to immediately drop the old one (or drop it at all), especially when the old one is based on JSON.net - one of the most popular and broadly used JSON serialization frameworks in .NET world.

Hope that this answers your question.

**Comment by ayende** [comment]
Another aspect to consider is hashing of JSON data. You need to ensure proper ordering of the properties, removing whitespace, etc.

How do you currently compute the hash?

**Comment by JohnGalt1717** [comment]
I'm in the process of investigating this, but my plan is to put in an interceptor that looks if the type implements an interface. If it does, then I know that the timestamp field is there as is the previous hash. and then I would just take the object, convert it to json, use that + the previous hash and the timestamp to create an SHA256 hash and then store that in the hash field of the object based on the interface.

And then have another interceptor that doesn't allow delete on an object that is of interface type.

Of course, it would be super cool if this was more low level and we could define a collection as a blockchain and that would cause all objects that are stored in that collection in Raven to have to implement the interface, and RavenDB would enforce read/insert only, and would automatically find the previous record, get the hash and then hash everything together and store the hash in the hash field from the interface (and optionally encrypt the record itself)

The reason why it would be cool if Raven did this at a low level is that it would be definition create a distributed block chain, it would be implemented in database itself, and would be faster because we wouldn't have to pull the previous record (and be assured that it was the previous record) to get the hash and then do the write.  And on these collections, all servers would have to be in sync, and you could also tell it what other replicated servers in other geographic environments have to be in sync too before the write is complete.

The first obvious use case for this is a banking ledger.  And the geographic environments are required because to be a FI or Acquiring processor you must have at least 2 geographic regions that your system is up in.

Make sense the use case?  My short term was just a thought of "how do I get the data to be consistent always and not have to worry about the serializer to be able to hash the string representation of the data?

But the more I think about it, the best solution would be in database deep in the plumbing.  This would make for an absolutely killer use case for RavenDb.

**Comment by JohnGalt1717** [comment]
I should mention that the ordering of fields I deal with because I use DataContract and DataMember(Order) attributes so it's known.

**Comment by ayende** [comment]
If you want to ensure consistent hashing, you _have_ to ensure proper ordering.

**Comment by ayende** [comment]
FYI: 
https://ayende.com/blog/192260-B/putting-json-in-a-block-chain-first-decide-what-your-json-is?key=e9a34829acf14d0c9735146a39e57fb8

**Comment by thepirat000** [comment]
Why is this issue closed? Is there a way to honor System.Text.Json attributes?

**Comment by ayende** [comment]
You can use `ISerializationConventions` to handle this. You can implement that using `System.Text.Json`

**Comment by thepirat000** [comment]
That looks pretty hard to accomplish, but maybe I'm missing something.

Does it mean I have to implement `ISerializationConventions` using System.Text.Json?

That will require also to implement `IJsonWriter`, `IJsonSerializer`, `IJsonReader`, etc

**Comment by ayende** [comment]
Yes, that is correct.
The problem is that RavenDB's JSON usage is quite extensive.

Note that `IJsonWriter` is implemented for `BlittableJsonWriter` (inheriting from JSON.Net type) to output the RavenDB internal format, not JSON text.

The core of that is probably at `IJsonSerializer`, which is far simpler.

**Comment by kamranayub** [comment]
Now that it is 2026 and .NET 10 is here, I think the world is moving (has moved?) onto System.Text.Json. The benchmarks clearly show that memory and performance is much better now than even it was back in .NET 5:

https://jkrussell.dev/blog/system-text-json-vs-newtonsoft-json-benchmark/

I'm sure the team has thought about this, and this is more complex than it appears from the outside, but it would be great to see System.Text.Json as a first-class option (with an easy-ish migration!) for RavenDB 8+. 

I feel like `PipeReader` would be pretty huge for all the data RavenDB has to pump through. Plus, less reflection if you could rely on the source generator.

![Image](https://github.com/user-attachments/assets/75fdd387-990d-4ac0-a99f-580d480d3df6)

**Comment by ayende** [comment]
There haven't been a lot of requests for that over the year, and note that we are actually using our own parser for most JSON tasks, then go from blittable to your domain objects.

The scope of this change is *big*, in particular with regards to customizations and backward compatibility.
