### ISSUE TITLE
The database is currently locked because of Checking if we need to recreate index.

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#11261]
Calling this with V5:

store.Maintenance.Server.Send(new CreateDatabaseOperation(new DatabaseRecord(dbName)));

Begets this error:

Raven.Client.Exceptions.Database.DatabaseDisabledException: 'Raven.Client.Exceptions.Database.DatabaseDisabledException: The database Test03484b96-d12f-480e-88df-295729c3de9f is currently locked because Checking if we need to recreate indexes
   at Raven.Server.Documents.DatabasesLandlord.UnloadAndLockDatabase(String dbName, String reason) in C:\Builds\RavenDB-Stable-5.0\50011\src\Raven.Server\Documents\DatabasesLandlord.cs:line 884
   at Raven.Server.Web.System.AdminDatabasesHandler.Put() in C:\Builds\RavenDB-Stable-5.0\50011\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 356
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.0\50011\src\Raven.Server\Routing\RequestRouter.cs:line 196
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.0\50011\src\Raven.Server\RavenServerStartup.cs:line 243
The server at /admin/databases?name=Test03484b96-d12f-480e-88df-295729c3de9f&replicationFactor=1&raft-request-id=c0e7dc18-7230-42fe-b437-a46c7c2c1ac2 responded with status code: ServiceUnavailable.'

**Comment by ayende** [comment]
Are you trying to create a database that already exists on disk?

**Comment by JohnGalt1717** [comment]
No, it's completely clean on a RavenDb cloud server using a random database name for test purposes for CI/CD. The reason why I encountered this is that the TestServer is hard coded into a .NET Core version and it blew up when Visual Studio 2019 updated to 3.1.9 of the .net core runtime and removed 3.1.8 which it's hard coded to.

It would be nice to fix this, but more importantly not hard code TestServer to a specific point release of the framework.

**Comment by ppekrol** [comment]
Hi @JohnGalt1717 

We will take a look at the initial problem.

Regarding the Test Server and framework issue. There is a possibility to turn that off, I've gave explanation why it is like that here: https://groups.google.com/g/ravendb/c/fsCHcnET_Y4/m/yh22h3v4CAAJ

**Comment by garayx** [comment]
@JohnGalt1717 @jhancock4d I created more than 1000 dbs using guid as a name with the provided code `store.Maintenance.Server.Send(new CreateDatabaseOperation(new DatabaseRecord(dbName)));`  and could not reproduce the error.

Can you share a sample code or app that demonstrate the issue?

**Comment by jhancock4d** [comment]
Here's the code that works with the test server, but fails in Raven Cloud:

```
			var store = new DocumentStore
			{
				Database = connectionStrings.RavenDbMaster.DatabaseName,
				Urls = connectionStrings.RavenDbMaster.Uris.ToArray(),
				Certificate = connectionStrings.RavenDbMaster.UseCertificate ? RavenDbSettings.GetClientCertificate(connectionStrings.AzureKeyVault) : null,
			};

			store.Conventions = new DocumentConventions
			{
				Serialization = new NewtonsoftJsonSerializationConventions
				{
					JsonContractResolver = new StrictTypeContractResolver()
				},
				MaxNumberOfRequestsPerSession = overrideMaxRequests ? int.MaxValue : 30,
				FindCollectionName = (type) =>
				{
					var constName = GetCollectionName(type);
					if (!string.IsNullOrEmpty(constName))
						return constName;

					var name = type.Name;
					if (name.EndsWith("s"))
						return name;

					if (name.EndsWith("y"))
						return name[0..^1] + "ies";

					return name + "s";
				}
			};

			store.Initialize();

			try
			{
				store.Maintenance.ForDatabase(connectionStrings.RavenDbMaster.DatabaseName).Send(new GetStatisticsOperation());
			}
			catch (DatabaseDoesNotExistException)
			{
				if (!createIfNotExist)
					throw;

				try
				{
					store.Maintenance.Server.Send(new CreateDatabaseOperation(new DatabaseRecord(connectionStrings.RavenDbMaster.DatabaseName)));
				}
				catch (ConcurrencyException) { } //Database was created while this was occuring
			}

```

It's implemented in an extension method that is called in Startup.cs if that matters.

**Comment by ayende** [comment]
@gregolsky Please take a look

**Comment by gregolsky** [comment]
At first I thought it could be related to CPU credits or low IOPS, but I checked your instance logs and metrics and there's nothing there like it.
I created an instance like yours and tried to reproduce this, but with no luck so far.

**Comment by JohnGalt1717** [comment]
@gregolsky Could it be because multiple tests were running in parallel?

I'm fine with this not working. Just would be better if the error message said something useful about what actually happened.

(And the Test Driver wasn't so sensitive about 3.1.x releases of .net core. (the x part)

**Comment by ayende** [comment]
@JohnGalt1717 Are you creating the _same_ database name for parallel tests? If so, that can cause the issue, yes.
In tests, you are expected to have a different db for each test

**Comment by JohnGalt1717** [comment]
No, the guid that’s appended to the name is changed every time and then torn down after so that tests can execute in parallel on a clean database with seed information.

**Comment by ayende** [comment]
Is it possible that you are creating enough to cause slowdown on the server?

**Comment by JohnGalt1717** [comment]
Quite possibly.  Testing on a 48 core processor that runs all of the tests in parallel.

**Comment by ppekrol** [comment]
Please reopen if needed.
