### ISSUE TITLE
Setting license on Embedded Instance does not appear to work

### ISSUE THREAD

**Issue by mikeminutillo** [ravendb/ravendb#11314]
We are trying to specify a license on an embedded instance by setting either `License` or `License.Path` like this:

```csharp
var options = new ServerOptions
{
  AcceptEula = true,
  DataDirectory = @"...",
  LogsDirectory = @"..."
};

options.CommandLineArgs.Add("--License.Path=C:\Temp\RavenLicense.json");
// OR
options.CommandLineArgs.Add("--License={licenseText}");

EmbeddedServer.Instance.StartServer(options);
```

Neither of these works as expected. The server claims to be unlicensed.

I grabbed a copy of the repo and added `--License.Path=C:\Temp\RavenLicense.json` to the debug arguments. I can confirm that the value is being picked up from the command line arguments and written to the [config object](https://github.com/ravendb/ravendb/blob/v5.0/src/Raven.Server/Config/Categories/LicenseConfiguration.cs#L22). It gets read back [during the folder permissions check](https://github.com/ravendb/ravendb/blob/v5.0/src/Raven.Server/Config/RavenConfiguration.cs#L386) but never again.

**Comment by mikeminutillo** [comment]
I have tested this with versions 5.0.2 and 5.0.3 of the package

**Comment by garayx** [comment]
Hi,

I tested the both settings, and they work properly.
Make sure to bootstrap the server or create a database on first server run:
https://ravendb.net/docs/article-page/4.2/Csharp/studio/server/cluster/add-node-to-cluster#bootstrap-cluster

**Comment by mikeminutillo** [comment]
Confirmed. I created a database and the license is accepted. It may be worth adding a hint to the license config page as I had no idea about the server being in passive mode. Feel free to close.

**Comment by garayx** [comment]
[https://issues.hibernatingrhinos.com/issue/RDoc-1827](https://issues.hibernatingrhinos.com/issue/RDoc-1827)

**Comment by ppekrol** [comment]
Handled here: https://github.com/ravendb/ravendb/pull/11419
