### ISSUE TITLE
No browser prompts to choose client certificate

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#11391]
I have ravendb behind haproxy on kubernetes configured per the instructions with a cert that was way too hard to configure.

I've loaded the pfx into my Personal store in Windows.

When I got to the website I get an auth error saying that the server requires a client certificate for authentication but none was provided by the client. Looking up this error it says restart the browser. I've restarted every browser and NONE including Internet Explorer prompt for a certificate when going to the site.

The certificate was generated using your "generate-server-cert.ps1" script if it matters.

How do I get this fixed so that it works properly?

**Comment by iftahbe** [comment]
Hi,
Did you read this? Especially the part about self-signed certificates.
https://ravendb.net/docs/article-page/4.2/csharp/start/installation/setup-examples/kubernetes/azure-aks#deploying-secrets
The easiest way to go here is to use a certificate from a well known certificate authority. Either a paid one, or from Let's Encrypt.

**Comment by JohnGalt1717** [comment]
Yes, but this is test environments and we use let's encrypt in production generated using cert-manager in kubernetes.

Ravendb is requiring a double cert because of the way it's setup to work.

Ravendb should recognize that it's behind a proxy, so that it doesn't need a server cert. Then the first time it runs it should generate a client certificate.

This is how raven would be configured in kubernetes or any docker envirnment.

So since it doesn't do this, I'm trying to get it working with a self-signed cert because what RavenDB uses litterally doesn't matter at all because the end user will NEVER see it because kubernetes' ingress will https everything and passes the request to RavenDb.

So how do I reliably get this to work under kubernetes with cert manager generating the certificate that haxproxy is providing and have Ravendb behave properly and just use the self-signed cert for client authentication?

**Comment by iftahbe** [comment]
Well, I'm not sure we can do that.
RavenDB must be the one to do the ssl termination.

In our example we put the following setting in ravendb.yaml:
ingress.kubernetes.io/ssl-passthrough: "true"

@ayende can you confirm?

**Comment by JohnGalt1717** [comment]
My point is that I don't want, nor would anyone using Kubernetes to EVER have RavenDb doing SSL termination. There is absolutely NEVER case where this is desirable.  The same is true for anyone using docker itself correctly.

You ALWAYS want your ingress doing SSL termination and you want everything internal to the kubernetes cluster to eliminate the overhead. i.e. the clusters talking to each other should always be unencrypted in the kubernetes cluster so all of the SSL overhead goes away because it simply isn't necessary.

Here's an example:

1. External client makes request of API - ingress decrypts and passes to API
2. api within kubernetes cluster talks to ravendb directly without encryption - No SSL encryption overhead.
3. RavenDB cluster talks to one or more nodes to get data directly without encryption - No SSL Encryption overhead.
4. RavenDB responses to API directly without encryption - No SSL Encryption overhead.
5. API responds to kubernetes external client without encryption but because of how kubernetes works, that goes to the ingress proxy unencrypted, the increase proxy reencrypts it and responds to the client.

Your way:

1. Encryption
2. Encryption.
3. Encryption (x however many nodes)
4. Encryption
5. Encryption

i.e. exponentially more encryption routines for no reason because Kubernetes has created the security envelop that RavenDb thinks it should be in charge of when it shouldn't be making it WAY less efficient than it should be for no security benefit.

All TCP communication should be done internally unencrypted, and external TCP communication should be blocked off outright or should be proxied by HA proxy or similar ingress.

**Comment by ayende** [comment]
@JohnGalt1717 I would contend otherwise. Even inside your K8s environment, you don't want to have potentially sensitive data going over the wire. There are other parties running there, and ensuring that the data is always encrypted is a best practice.

For example, if another node in the cluster was compromised, if the data is passing in plain text, it can be eavesdropped. If it is encrypted, you have to compromise the database node to get to the data.

In our mode, there is actually the exact same amount of encryption.

1) external encrypt the data and send to k8s
2) K8s doesn't touch the data, just route it to RavenDB

The data is encrypted and decrypted once in both cases.
That is key, since there isn't multiple levels of encryption going on here.

**Comment by JohnGalt1717** [comment]
@ayende In your K8s cluster properly configured there is NOTHING running inside your k8s environment that you didn't put there and NO container has access to packet sniffing unless explicitly granted with NET_CAP or HOST networking thus no container can sniff traffic that isn't destined for that container directly and thus it is irrelevant if other services are communicating directly within the non-routable k8s internal network without encryption. NO consumer of your database within the k8s environment should EVER be communicating with RavenDb that is inside your k8s environment with a publicly accessable dns or ip. It should ALWAYS be communicating directly within the k8s network using the k8s dns for the non-routable ip address.

2. You're assuming that you're using k8s as a deticated RavenDb cluster that is publically available. While this is one use of k8s for RavenDB (as a 0 trust hosted service effectively) it isn't how a properly configured environment should be implemented. EVERYTHING that talks to RavenDb should be within the k8s cluster and RavenDb shouldn't be publically accessible at all. Only Studio should be directly available and even then only as needed, never perpetually.

The intent of k8s is to create a complete, closed environment of everything that you need to run whatever it is you're doing and only expose your publicly facing services to the public internet or even your intranet. It's a walled garden of safety and reproducibility and security who's access to those public endpoints is carefully controlled by your ingress. It isn't designed to go and stand up a RavenDb cluster and then have another k8s cluster talk to that cluster publicly over the internet. That would be both not cost effective and insecure by design. (or at least significantly less secure)

Let's say I wanted something else to do reporting against RavenDb that is in the cluster. In a properly configured cluster I have 2 options: Run that something else within the k8s cluster itself, OR provide a microservice that is secured and publicly accessible that that something else talks to, and the microservice then talks to RavenDb.  The way you're designing it is no different than me using Azure SQL and just blindly trusting that Microsoft got their security so right that it's safe to have SQL Server available on the public cloud directly accessible. (which is also inefficient)
