### ISSUE TITLE
Add support for Certificates by Key + Crt

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#11390]
The reason why is that if you're using cert-manager in Kubernetes it generates a crt and key file in a secret (tls.crt and tls.key within the secret). It would be really nice to be able to use the cert that is linked up automatically from this cert.

And more so, it would be really nice to have it automatically update when those values change.

I still don't have it working from the instructions for Azure Kubernetes because of certificate issues, and I've been at it for hours because this is WAY too complex as it stands right now.

**Comment by iftahbe** [comment]
Converting the crt and key to pfx is something you can easily automate using OpenSSL. 
Regarding automatic certificate renewal, it's not possible. In order to renew a certificate, one must have control of the domain. RavenDB cannot renew your private certificate.

**Comment by JohnGalt1717** [comment]
You're miss understanding:

In kubernetes you will use cert-manager (https://www.jetstack.io/cert-manager/) or some other certificate acquisition mechanism which will then store that as a secret. In the case of cert-manager it generates tls.crt and tls.key within the kubernetes secret.

Further RavenDb on kubernetes will always be behind a reverse proxy and shouldn't require a certificate for server encryption at all because RavenDb should be recognizing the reverse proxy and understanding that it is encrypted. This is what should be in the Configure method of your Startup.cs for at least Studio to get going:

```
			var forwardOptions = new ForwardedHeadersOptions
			{
				ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
				RequireHeaderSymmetry = false,
			};

			forwardOptions.KnownNetworks.Clear();
			forwardOptions.KnownProxies.Clear();

			app.UseForwardedHeaders(forwardOptions);

```

In RavenDb insists on requiring its own cert, per the documentation that lets you specify a base64 encoded kubernetes secret mounted as a file, I should be able to mount the above .crt and .key files as files in a folder for RavenDb to read and RavenDb should be able to use those (tls.key and tls.crt in this case) for all of it's encryption from cert-manager's automatic domain wildcard generation that already happened so that I don't have to do this twice since I already have a valid wild-card certificate from cert bot using dns validation.

Further, RavenDb should be monitoring the pfx and or key/crt files and if they change reloading it's certificates automatically.

Given that RavenDb is already using cert bot in the background for the let's encrypt environment (which requires public access on port 80 which is not viable in any configuration other than a direct hosted VM or similar), there should be no reason why RavenDb can't be setup to accept key/crt files instead since that's what cert bot generates anyhow, so you're already either generating a pfx file yourselves or you're using key/crt in your C# code to create the x509Certificate2.

Hence I'm requesting that in addition to accepting a pfx, you let us specify the paths for a .key and .crt file that you'd then make the pfx from so that this will work with 3rd party cert bot or any number of other automated services that don't cater to window's insistence on pfx files and that we can't automate generating a pfx file from because it's an opaque service.

There's documentation here: https://stackoverflow.com/questions/55456807/create-x509certificate2-from-cert-and-key-without-making-a-pfx-file that would allow you to facilitate this easily.

**Comment by iftahbe** [comment]
Yes, you're right, I misunderstood.

We actually have a mechanism that recognizes and refreshes the certificate if it changed on disk.
So all you have to do is convert the renewed crt+key to pfx with OpenSSL and then replace the file on disk.

@ayende, do we want to support crt+key?

**Comment by JohnGalt1717** [comment]
@ayende @iftahbe 

I would suggest for kubernetes, you MUST support crt+key because of the scenario above.

And I'd suggest that your kubernetes sample be altered to use haproxy to do SSL offload and if you must, just ALSO use the same certificate from cert-manager for ravendb.

**Comment by ayende** [comment]
This is a supported scenario, yes. 
See: https://ravendb.net/docs/article-page/5.0/csharp/server/configuration/security-configuration#security.certificate.exec

The idea is that you provide a script and register it via Security.Certificate.Exec, it can get the certificate using its own logic.
In this case, by getting the certificate from K8s.

**Comment by JohnGalt1717** [comment]
This doesn't really address the issue.  First, I can't find any documentation on HOW that's supposed to work.  What exactly does that exec return?  What is ravendb then monitoring for changes?  I can't find any documentation that shows how this is intended to function, only that it exists.

I.e. the k8s secret will always be key and cert files. Thus ravendb MUST know to watch the key and cert files, not a resulting pfx file.  If I used this presumably to run openssl to convert the key and cert to pfx, and told ravendb to use the resulting pfx, ravendb would simply watch the pfx file, not the key/cert files for changes and thus would end up with invalid certificates within 90 days because of course the pfx won't have changed, and thus openssl won't be called again to regen the pfx file.

**Comment by ayende** [comment]
Detailed description on how to make use of this feature is here:
https://ravendb.net/learn/inside-ravendb-book/reader/4.0/13-securing-your-ravens#externalizing-certificate-management

The idea is that you can run a script that would return the update cert to RavenDB when run. 
RavenDB will run the script on a regular basis, giving you the chance to update this.

**Comment by JohnGalt1717** [comment]
As far as I'm aware this won't work for openssl. If you have a specific example of using openSSL that will output the cert to the STDOut for this, I'm all ears.  But this also induces overhead of generating the pfx from the key/crt files on a periodic basis instead of just using the files that make up the pfx itself anyhow directly.

In general we're just running around in circles while I try and jam a square ravendb peg into the round k8s hole because RavenDb is not designed to work in an environment as k8s is designed to provide.

**Comment by iftahbe** [comment]
Here's an example: https://ravendb.net/docs/article-page/4.2/csharp/server/security/authentication/lets-encrypt-certificates#automatic-renewal-for-self-obtained-certificates

**Comment by JohnGalt1717** [comment]
I did the following:

```
            - name: RAVEN_Security_Certificate_Load_Exec
              value: "openssl pkcs12 -inkey /ssl/tls.key -in /ssl/tls.crt -password pass:<redacted> -export"
```

which didn't work with "failed to start process".

Then I tried this:
```
            - name: RAVEN_Security_Certificate_Load_Exec
              value: openssl
            - name: RAVEN_Security_Certificate_Load_Exec_Arguments
              value: pkcs12 -inkey /ssl/tls.key -in /ssl/tls.crt -password pass:<Redacted> -export

```

Unable to load the server certificate due to invalid configuration! Admin assistance required.
 ---> System.InvalidOperationException: Got invalid certificate via openssl pkcs12 -inkey /ssl/tls.key -in /ssl/tls.crt -password pass:<Redacted> -export
 ---> Interop+Crypto+OpenSslCryptographicException: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure


It's pulling from a let's encrypt certificate issued by cert-manager in k8s.

**Comment by ayende** [comment]
Pretty sure that the problem is with the command you send.
You need to use:

```
- name: RAVEN_Security_Certificate_Load_Exec
value: openssl
- name: RAVEN_Security_Certificate_Load_Exec_Arguments
pkcs12 -inkey cert.key -in cert.crt  -passin pass:<Redacted> -passout pass: -export
```

Note that in this case, the output PFX should be generated without a password. 
That is why it didn't work for you.

**Comment by JohnGalt1717** [comment]
That appears to work.  Wish you could specify the default client certificate separately.

**Comment by ayende** [comment]
What do you mean, default client certificate?

**Comment by JohnGalt1717** [comment]
Right now if you use your own certificate the sever (transport) certificate and the default client certificate are in a single certificate chain.

I'm not sure why this decision was made but it makes life more difficult.  It would be better if we could have a standard transport certificate that just does transport encryption that we can trust on the local machine. And then a client certificate that is issued separately for encryption.

Better yet, have the setup wizard, or the first run, automatically generate the first client certificate for you, and once complete, require that certificate or another issued one for all further communication.  This way, there's no hacking around trying to generate this (the only way I've successfully generated a cert that works is with your powershell script, nothing I do can cause openssl to generate one) AND the certificates have separation of concerns.

Of course it would still be better if the server itself over tcp could use certs and Studio could use l/p over ssl so that this worked properly the way k8s is designed.

**Comment by ayende** [comment]
I'm afraid that I'm not following you here. This thread (and others) are getting pretty big. It would probably be much faster to setup a call and discuss this live, rather than in these exchanges.

Note that there is no requirement to use the server certificate as a client certificate. The setup wizard _will_ generate the first admin certificate for you to use. This is generated from the server cert, but you can also register any other certificate you want as well.

**Comment by ayende** [comment]
You can ping us at support@ravendb.net with your time zone and we'll setup a call
