### ISSUE TITLE
Docker for 4.2 installs outdated libcurl3

### ISSUE THREAD

**Issue by AlexeyDemidov** [ravendb/ravendb#11468]
Dockerfile for 4.2 installs outdated `libcurl3` explicitly. 

https://github.com/ravendb/ravendb/blob/9f4173ab143a18a2a00df3a72d766bab15a51b5d/docker/ravendb-ubuntu/Dockerfile.x64#L5

Does it really need this dependency? If I install `curl` in a derived Dockerfile then `libcurl3` gets replaced by `libcurl4` automatically without an option to have both versions installed. Would the absence of `libcurl3` break anything?

**Comment by ayende** [comment]
Looks like this is no longer required:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

**Comment by ppekrol** [comment]
Moved this to our bugtracker: https://issues.hibernatingrhinos.com/issue/RavenDB-17058
