### ISSUE TITLE
Studio Error listing certificates in 5.1.1 with WellKnownCertificate

### ISSUE THREAD

**Issue by jonstelly** [ravendb/ravendb#11535]
I'm running ravendb in kubernetes.  It's deployed from a custom helm chart that borrows some of the things mentioned in the ravendb docs for kubernetes.

I've set a thumbprint for an admin WellKnownCertificate like:

```yaml
  - name: RAVEN_Security_WellKnownCertificates_Admin
    value: {{ .Values.security.adminCertificate }}
```

The nodes come up fine, and I can add a license, add them to a cluster.  But when I go to the certificates page in studio (/studio/index.html#admin/settings/certificates), I get the error below and the page shows up empty (no well known certificate, no server certificate):

![image](https://user-images.githubusercontent.com/967068/101708371-bbf42100-3a52-11eb-9cdb-8f1c9bf1b4d6.png)

If I then upload the PFX for my admin certificate, the page starts to load without the error:

![image](https://user-images.githubusercontent.com/967068/101708897-e4c8e600-3a53-11eb-833c-b4b05ca54ece.png)

Should I have to upload/include the PFX files for the WellKnownCertificates?  I like the wellknowncertificates feature because I can use a thumbprint and don't have to worry about protecting/unprotecting my PFX files.

**Comment by HibernatingRhinosServiceAccount** [comment]
Hi,
You shouldn't need to upload a pfx for the WellKnownCertificates feature to
work. A thumbprint is enough.

What do you mean when you say: "If I then upload the PFX for my admin
certificate"?
How do you upload the pfx and to where? I thought the page doesn't load.
Can you be more specific?

Also, how did you install the server certificate?
Are all these certificates self-signed? Did you take care of installing
your CA on the OS?
What OS are you using?

Best regards,
<https://ravendb.net/> *Iftah Ben Zaken*
*Senior Developer   /   Hibernating Rhinos LTD
<https://hibernatingrhinos.com/>*
E-mail:    iftah@ravendb.net
Support:  support@ravendb.net
Skype:  live:iftahbe

**Comment by jonstelly** [comment]
> What do you mean when you say: "If I then upload the PFX for my admin
certificate"?
How do you upload the pfx and to where? I thought the page doesn't load.
Can you be more specific?

Loading ravendb studio after my initial deployment, the list of certificates fails to load but the `Client Certificate` and `Server Certificate` buttons still render and function correctly.  So I use the `Client Certificate` dropdown to upload the certificate I use as my well known admin cert.  Once I do this I stop seeing the error in the javascript console and my certificate list shows the well known cert thumbprint, the server cert, and the client cert that I just uploaded.

> Also, how did you install the server certificate?
Are all these certificates self-signed? Did you take care of installing
your CA on the OS?
What OS are you using?

Yes, custom server and client certificates.  All signed with a custom CA that is installed in the OS.  My docker image is based on `ravendb/ravendb:5.1-ubuntu-latest` and the only thing it does is install my CA certificate into the OS store:

```docker
FROM ravendb/ravendb:5.1-ubuntu-latest

# Install My CA Certificate
RUN echo "..." | base64 -d > /usr/local/share/ca-certificates/my-ca.crt && update-ca-certificates
```

From a quick look at the code, it seems that `loadCertificates()` makes an assumption that the well known admin certificate is present on the server:

```typescript
const serverCert = mergedCertificates.find(x => _.includes(x.Thumbprints, this.serverCertificateThumbprint()));
const clientCert = mergedCertificates.find(x => _.includes(x.Thumbprints, this.clientCertificateThumbprint()));
const orderedCertificates = mergedCertificates.filter(x => x !== serverCert && x !== clientCert);
orderedCertificates.unshift(clientCert);
orderedCertificates.unshift(serverCert);
                
this.updateCache(orderedCertificates);
```

When I debug and catch the exception from the screenshot above, `orderedCertificates` has the server certificate in array element 0, array element 1 is undefined, and it's the undefined certificate that causes the exception in `updateCache(...)`

It may be as simple as the following but I'm not sure if this might cause other problems:

```typescript
const serverCert = mergedCertificates.find(x => _.includes(x.Thumbprints, this.serverCertificateThumbprint()));
const clientCert = mergedCertificates.find(x => _.includes(x.Thumbprints, this.clientCertificateThumbprint()));
const orderedCertificates = mergedCertificates.filter(x => x !== serverCert && x !== clientCert);
if(!!clientCert) {
  orderedCertificates.unshift(clientCert);
}
orderedCertificates.unshift(serverCert);
                
this.updateCache(orderedCertificates);
```

**Comment by HibernatingRhinosServiceAccount** [comment]
Thanks a lot, we'll fix it.
https://issues.hibernatingrhinos.com/issue/RavenDB-16001

<https://ravendb.net/> *Iftah Ben Zaken*
*Senior Developer   /   Hibernating Rhinos LTD
<https://hibernatingrhinos.com/>*
E-mail:    iftah@ravendb.net
Support:  support@ravendb.net
Skype:  live:iftahbe
