### ISSUE TITLE
Statistics for Revisions.GetFor

### ISSUE THREAD

**Issue by netclectic** [ravendb/ravendb#11610]
I'm using Revisions.GetFor but I do not see a way to get the equivalent of Query Statistics that will tell me the total number of revisions for a document, so I have to just page through the results until there are no more results returned.

Is there some other way I can find out the number of revisions up front to better support paging?

**Comment by ayende** [comment]
We are actually providing that information over the REST call, but it isn't exposed in the API.
You can ping the endpoint directly via a custom `GetRevisionsCommand` instead.

**Comment by ayende** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-16059

**Comment by ppekrol** [comment]
Handled here: https://github.com/ravendb/ravendb/pull/11678
