### ISSUE TITLE
RevertRevisions through Client Api?

### ISSUE THREAD

**Issue by netclectic** [ravendb/ravendb#11653]
Is it possible to Revert Revisions through the client API?

I can see there is a method for it on the server, but I don't see any way to call it through the client api. 

I could get the individual revisions I want using the document change vectors and just store them over the top of the current documents, but that seems terribly inefficient.

**Comment by ppekrol** [comment]
Hi, the Client API is written in an extensible way, you should be able to easily add needed operation. Draft (haven't tested):

```
        public class RevertRevisionsOperation : IMaintenanceOperation<OperationIdResult>
        {
            private readonly RevertRevisionsRequest _request;

            public RevertRevisionsOperation(RevertRevisionsRequest request)
            {
                _request = request ?? throw new ArgumentNullException(nameof(request));
            }

            public RavenCommand<OperationIdResult> GetCommand(DocumentConventions conventions, JsonOperationContext context)
            {
                return new RevertRevisionsCommand(_request);
            }

            private class RevertRevisionsCommand : RavenCommand<OperationIdResult>
            {
                private RevertRevisionsRequest _request;

                public RevertRevisionsCommand(RevertRevisionsRequest request)
                {
                    _request = request;
                }

                public override bool IsReadRequest => false;

                public override HttpRequestMessage CreateRequest(JsonOperationContext ctx, ServerNode node, out string url)
                {
                    url = $"{node.Url}/databases/{node.Database}/revisions/revert";

                    return new HttpRequestMessage
                    {
                        Method = HttpMethod.Post,
                        Content = new BlittableJsonContent(stream => ctx.Write(stream, DocumentConventions.Default.Serialization.DefaultConverter.ToBlittable(_request, ctx)))
                    };
                }

                public override void SetResponse(JsonOperationContext context, BlittableJsonReaderObject response, bool fromCache)
                {
                    if (response == null)
                        ThrowInvalidResponse();

                    Result = DocumentConventions.Default.Serialization.DefaultConverter.FromBlittable<OperationIdResult>(response);
                }
            }
        }
```

after that you should be able to use it as follows:

```
var operation = store.Maintenance.ForDatabase("myDatabase").Send(new RevertRevisionsOperation(...));
operation.WaitForCompletion();
```

Hope that it helps.

**Comment by netclectic** [comment]
Thanks!

I managed to get that working, I had to pull `BlittableJsonContent` into my project as its marked as internal, and I had to just create my own instance of `DocumentConventions` as the Default is also marked internal.

Could you possibly explain what the `Window` parameter is actually doing? 
It's not clear to me what I should be setting it to.

**Comment by ayende** [comment]
The `Window` means how long back should we scan the revisions to find them.
In general, the revisions aren't absolutely sorted by date, but by arrival time. If a change happened on a separate server, you may be notified about it later.

So the idea is is how far back do you scan to find the records you want. You usually will set it to about 25% of the range you'll want to revert.
So if you want to revert 6 hours back, you'll tell it to scan 8 hours, etc.

**Comment by netclectic** [comment]
Ok, that makes sense. I can work with that, thanks.

**Comment by netclectic** [comment]
One small thing I noticed... after executing the revert, the Revisions Bin does not show up in the studio until I refresh my browser tab.

**Comment by ayende** [comment]
I think that this is one of those things that aren't pushed live, but loaded at page load.
