### ISSUE TITLE
System.NotSupportedException: 'Optimistic concurrency for 'Taxes/353-A' is not supported when using a cluster transaction.' despite change vector is provided

### ISSUE THREAD

**Issue by arashcomsense** [ravendb/ravendb#11712]
We are using cluster-wide transactions and we get the error mentioned in the subject line when updating a document. To update the document, first, we load it from the database, modify some fields and then have it saved using the provided ChangeVector and the document's Id. My understanding is that supplying ChangeVector enables optimistic concurrency for that session only which is our intention. Here is the code snippet:

```csharp
var taxToUpdate = await session.LoadAsync<Tax>(myTax.Id, cancellationToken);
taxToUpdate.Description = "Updated description";
await session.StoreAsync(taxToUpdate , myTax.ChangeVector, myTax.Id, cancellationToken);
await session.SaveChangesAsync(cancellationToken);
```
The stack trace reads as:

> Raven.Client.Documents.Session.InMemoryDocumentSessionOperations.ValidateClusterTransaction(SaveChangesData result) in C:\Builds\RavenDB-Stable-5.1\51010\src\Raven.Client\Documents\Session\InMemoryDocumentSessionOperations.cs:line 883 at Raven.Client.Documents.Session.Operations.BatchOperation.CreateRequest() in C:\Builds\RavenDB-Stable-5.1\51010\src\Raven.Client\Documents\Session\Operations\BatchOperation.cs:line 41 at Raven.Client.Documents.Session.AsyncDocumentSession.d__31.MoveNext() in C:\Builds\RavenDB-Stable-5.1\51010\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 157 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

Not sure if this is an issue with the code or there is a bug in the client library.

**Comment by grisha-kotler** [comment]
Optimistic concurrency at the document level isn't supported.
It is handled using the compare exchange feature.
https://ravendb.net/docs/article-page/5.1/Csharp/server/clustering/cluster-transactions#case-1-multiple-concurrent-cluster-transactions

**Comment by ayende** [comment]
To explain further, imagine that you have two concurrent transactions, using optimistic concurrency.
Both of them hit different servers, but one of them is a cluster wide transaction and one is local transaction.

It is possible for the cluster wide transaction to be accepted, but the node processing the local transaction to not be updated yet. The optimistic concurrency transaction will _work_, but it would be wrong.

For that reason, for cluster wide transactions, you need to use compare exchange for optimistic concurrency.

**Comment by arashcomsense** [comment]
@ayende @grisha-kotler Thanks for clarification. Is there a code example related to updating an existing document in this context to take a look?

**Comment by ayende** [comment]
This is a good one: https://ayende.com/blog/183426-C/ravendb-4-1-features-cluster-wide-acid-transactions
