### ISSUE TITLE
How to pull random records like EF Core allows using UDFs

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#11734]
I have a stable of practice questions that I'd like to be able to pull X random questions for a child to work on in a given lesson.

I'm in EF Core I could just use a UDF that returns a random value and tack it on as a column and order by that column and then do a take and volia, random recordset.

Is this possible in RavenDb?  Suggestions on how to make this work?

**Comment by ppekrol** [comment]
Hi @JohnGalt1717 

I think that Random Ordering would be sufficient for that? Check it out here: https://ravendb.net/docs/article-page/5.1/Csharp/indexes/querying/sorting#random-ordering
