### ISSUE TITLE
Attached files do not seem to be downloaded properly

### ISSUE THREAD

**Issue by arashcomsense** [ravendb/ravendb#11740]
There's a binary file uploaded as an attachment to RavenDB successfully by RavenDB;s client API using the following code:

```csharp
var details = store.Operations.Send(new PutAttachmentOperation(customer.Id, "filename.pfx", filestream));
```

The downloaded version of the uploaded file (attachment) by RavenDB client API does not match the original file when comparing both contents byte by byte using byte array comparison technique as below:

```csharp
       public static bool Compare(byte[] a, byte[] b)
        {
            int x = a.Length ^ b.Length;

            for (int i = 0; i < a.Length && i < b.Length; ++i)
            {
                x |= a[i] ^ b[i];

                if(x != 0)
                {
                    Console.WriteLine($"{i} - {a[i]} - {b[i]}");
                }
            }

            return x == 0;
        }
```

Further info and a small C# project to reproduce this issue is available in a private repo. Please let me know so that I can share that repo privately for further investigation. Thanks.

**Comment by ayende** [comment]
You can send the details to support @ ravendb.net
