### ISSUE TITLE
The example related to generating client certificate needs to be fixed

### ISSUE THREAD

**Issue by arashcomsense** [ravendb/ravendb#11760]
The following code snippet illustrated on [this page ](https://ravendb.net/docs/article-page/5.0/csharp/client-api/operations/server-wide/certificates/create-client-certificate#operations-server-how-to-generate-a-client-certificate ) fails due to the null permissions. The example needs to be revised in the scope of instnatiating `CreateClientCertificateOperation` object :

```csharp
// With user role set to Cluster Administrator or Operator the user of this certificate 
// is going to have access to all databases
CreateClientCertificateOperation operation = 
    new CreateClientCertificateOperation(
        "admin", null, SecurityClearance.Operator);
CertificateRawData certificateRawData = 
    store.Maintenance.Server.Send(operation);
byte[] cert = certificateRawData.RawData;

```

**Comment by ayende** [comment]
Hi,
I'm not sure that I understand. What do you mean with regards to: `in the scope of instnatiating CreateClientCertificateOperation object`

**Comment by arashcomsense** [comment]
What I meant was that `operation` object cannot be instantiated (an exception is thrown) if one puts `null` after "admin" in the constructor (`CreateClientCertificateOperation`)

**Comment by ayende** [comment]
You are correct, further tracking this here: https://issues.hibernatingrhinos.com/issue/RDoc-1879
