### ISSUE TITLE
[PowerShell Script] certificate-renewal-and-rotation documentation is not RIGHT

### ISSUE THREAD

**Issue by farhadnowzari** [ravendb/ravendb#11918]
Hi,

we recently were trying to deploy raven to our test server and we realized some points that are not complete/not quit right in the documentation.
The script which renews the certificate in the link below will throw 500, because based on the code which is also attached here from ravendb corresponding method the password property is missing.

**The link to the documentation:** https://ravendb.net/docs/article-page/4.2/csharp/server/security/authentication/certificate-renewal-and-rotation#replace-the-cluster-certificate-using-powershell

**The link to the method's code:** https://github.com/ravendb/ravendb/blob/dcad3a1a8ee038548892b58b130be47dc3bf2650/src/Raven.Server/Web/Authentication/AdminCertificatesHandler.cs#L975

**Comment by ayende** [comment]
I'm not sure that I'm following. If you don't have a password for the certificate, you won't need that property.
This is used if you have it.

Are you talking about the docs missing an example with a password?

**Comment by farhadnowzari** [comment]
yes that would be nice. because we just did a copy paste from the doc and was wondering were to put the password as a property we guessed it is in the payload ofcourse but we just looked into the code to see where is it.

**Comment by ayende** [comment]
Okay, created an issue about that here: https://issues.hibernatingrhinos.com/issue/RDoc-1898
