### ISSUE TITLE
generateClientCert documentation is not complete

### ISSUE THREAD

**Issue by farhadnowzari** [ravendb/ravendb#11919]
Hi,

based on the attached link, the `generateClientCert` command must work like below
```
generateClientCert <name> <path-to-output-folder> [password]
```
But it will **Complain** about the expiration date. so it should be like below, it worked for us
```
generateClientCert <name> <path-to-output-folder> <expiration> [password]
```

The link to documentation: https://ravendb.net/docs/article-page/4.2/Csharp/server/administration/cli#generateclientcert

**Comment by reebhub** [comment]
thanks, right. we'll fix it
https://issues.hibernatingrhinos.com/issue/RDoc-1902
