### ISSUE TITLE
IAsyncDocumentSession.StreamAsync method forcedly cast IAsyncDocumentQuery<T> to concreate AsyncDocumentQuery<T> class implementation.

### ISSUE THREAD

**Issue by dkogithub** [ravendb/ravendb#11914]
Hi Acid Raven team, :)

We are experiencing the issue with our **MiniProfiler** implementation which is based on implementation of **RavenDB** async interfaces like **IAsyncDocumentSession, IAsyncDocumentQuery** etc..
Let's say we have something like: **class ProfilerAsyncDocumentQuery : IAsyncDocumentQuery {...}**.

If we call in this class **IAsyncDocumentSession.Task<IAsyncEnumerator<StreamResult<T>>> StreamAsync<T>(IAsyncDocumentQuery<T> query, CancellationToken token = default)** metohd.
we are getting the **InvalidCastException**, because of this line:
https://github.com/ravendb/ravendb/blob/649dc64525966b03e2f1e5c226bcb03b1ba60e99/src/Raven.Client/Documents/Session/AsyncDocumentSession.Stream.cs#L173

So, can you please take a look on that? From my point of view there is a design issue - if I see an interface within the method signature, I don't expect that somewhere inside of this method it would be casted to any concreate implementation. 

Thanks!

P.S. RavenDB Rocks! ;)

Best regards,
Dmitriy

**Comment by mbenedykconfigit** [comment]
+1

**Comment by ppekrol** [comment]
Hi there,

I've moved this to our YT. We will take a look. Link is here: https://issues.hibernatingrhinos.com/issue/RavenDB-16418

Thanks!
