### ISSUE TITLE
Custom JsonContractResolver ignores CreateArrayContract => ItemConverter

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#11916]
I'm trying to make it so that the exact type that a list is defined as actually is what is serialized instead of it serializing whatever inherited type was set. This is necessary because we have base "ref" classes that our full objects inherit from so that we can put references into other documents instead of the entire thing and the fields we need are there most of the time. By default all properties defined as a ref type and all lists that have a generic set to be a ref type are serializing the full object instead of just serializing it as the ref base type.

So I have this:

```
	public class StrictTypeContractResolver : DefaultContractResolver
	{
		private readonly FieldInfo _IsSealedField = typeof(JsonContract).GetField("IsSealed", BindingFlags.Instance | BindingFlags.NonPublic)!;

		public override JsonContract ResolveContract(Type type)
		{

			var resolveContract = base.ResolveContract(type);
			_IsSealedField.SetValue(resolveContract, true);
			return resolveContract;
		}

		protected override JsonArrayContract CreateArrayContract(Type objectType)
		{
			var contract = base.CreateArrayContract(objectType);
			//contract.item = true;

			if (contract.CollectionItemType != null)
				contract.ItemConverter = new ItemJsonConverter(contract.CollectionItemType);

			return contract;
		}
	}

	public class ItemJsonConverter : JsonConverter
	{
		private readonly PropertyInfo[] properties;
		private readonly Type destinationType;
		public ItemJsonConverter(Type destinationType)
		{
			this.destinationType = destinationType;
			properties = destinationType.GetProperties();
		}

		public override bool CanConvert(Type objectType) => objectType.IsAssignableTo(destinationType);
		public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
		{
			throw new NotImplementedException();
		}

		public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
		{
			//serializer.Serialize(writer, value, destinationType);

			if (value == null)
				return;

			JToken t = JToken.FromObject(value);

			if (t.Type != JTokenType.Object)
			{
				t.WriteTo(writer);
			}
			else
			{
				JObject o = (JObject)t;
				var propNames = o.Properties().Where(p => !properties.Any(pp => pp.Name == p.Name)).Select(p => p.Name).ToArray();
				foreach (var propName in propNames)
					o.Property(propName)?.Remove();

				serializer.Serialize(writer, o, destinationType);
				//o.WriteTo(writer);
			}
		}
	}

```

Which works fine if I use the json.net serializer and specify the serializer settings myself and just return a string and inspect it and debug break points hit on the serializer.Serialize(writer, o, destinationType) and all is right with the world. However, when RavenDb serializes, the ItemConverter is ignored and it serializes these lists with the full objects that were passed in instead.

How do I convince RavenDb to not ignore the ItemConverter OR only serialize the explict type that was defined in the object property/list generic?

Or is this a bug?

Thanks!

**Comment by ppekrol** [comment]
Hi @jhancock4d 

I think it would be best for us to understand the full picture. Would you be so kind to prepare a unit test https://ravendb.net/docs/article-page/5.1/csharp/start/test-driver#unittest ? How are you configuring our serializer? Have you considered using only converter? We have conventions.Serialization.CustomizeJsonSerializer and CustomizeJsonDeserializer available.

In 5.1 we have introduced conventions.Serialization.IgnoreByRefMembers and IgnoreUnsafeMembers, but not sure if this would be what you want.

**Comment by jhancock4d** [comment]
[RavenDbSerializationExample.zip](https://github.com/ravendb/ravendb/files/6221747/RavenDbSerializationExample.zip)

The included example shows the full example and shows where the asserts fail but the standard Json.net serailizer honors it and it works.

In essence I want RavenDb to serialize exactly the defined types of the properties for both a direct type (public PropType prop {get; set;}) and for Generics (public IList<PropType> listProp {get; set;}) instead of serializing the entire thing. This happens all the time in document dbs (because you want to store refs in the DB but already have the full object, and you don't want to have to convert it explicitly every time to get just the data you wanted) and with the exception of polymorphism, there is never a case where this is desirable. You want to store exactly what you defined.

In the case of polymorphism, I'd really like to have whatever is setup have an Attribute that will cause it to revert to the default behavior if the property has the attribute, so that polymorphism will work in that lone explicit case.

I'd suggest that an example would be great, but a flag in RavenDb configuration that would cause the database to default to this behavior would be even better (I realize it can't be changed by default at this point) because polymorphism is the exception, not the rule and in all other cases you'd expect the serializer to do what was explicitly defined and not serialize the inherited object's properties.

**Comment by ppekrol** [comment]
Handled here: https://issues.hibernatingrhinos.com/issue/RavenDB-16512
