### ISSUE TITLE
Please document how to use .map to return a projection

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#11928]
Using GraphApi and/or RQL, there are examples of using Map within the select to return a single property of an object with join etc. But I can't find any examples of using .map to return an array of objects.

for instance: 

```
select {
   chain: chain
}
```

returns an array of objects of the entire object.

But I can't find any way to do:
```
select {
   chain: chain.map(x => { Property1, property2...})
}

```

**Comment by ayende** [comment]
That should actually just work.
Using the sample data, you have:


```
from Orders  as o
where id(o) = 'orders/830-A'
select {
    Lines: o.Lines.map(l => {
        return { 
            FinalPrice: l.PricePerUnit * l.Quantity * (1-l.Discount) 
        };
    })
}
````

**Comment by jhancock4d** [comment]
@ayende from that I generated this:

```
match (Content as content
    where id() = "Content/0000000000000000133-A")-
    recursive as chain(all)
    {
        [DependsOn[].Id as parentId]->
        (Content as parent)
    }
select 
{
    Id: id(content),
    Name: content.Name,
    depends: chain.map(x => {
        return {
            Id: id(x),
            Name: x.Name
        }
    })
}

```
It returns the base item that I want the chain on, and an array of depends being the right length, but both properties are null.

If I change it back to depends: chain, it works fine.

I'd suggest this needs to be in the docs though, because in the examples for project this isn't included as far as I can tell.

**Comment by ayende** [comment]
Note that the items inside the chain are _named_, you can see that as the JSON output from the query without a select.

Using the sample data, you have:

```
match (Employees as e where id() = 'employees/6-A')-
    recursive as chain(all) {
        [ReportsTo]->(Employees as boss)
    }
select {
    Id: id(e),
    Name: e.FirstName + " " + e.LastName,
    bosses: chain.map(x=>{
        return {
            Id: id(x.boss),
            Name: x.boss.FirstName + " " + x.boss.LastName
        };
    })
}
```

Your code should probably be:

```
match (Content as content
    where id() = "Content/0000000000000000133-A")-
    recursive as chain(all)
    {
        [DependsOn[].Id as parentId]->
        (Content as parent)
    }
select 
{
    Id: id(content),
    Name: content.Name,
    depends: chain.map(x => {
        return {
            Id: id(x.parent),
            Name: x.parent.Name
        }
    })
}
```

**Comment by jhancock4d** [comment]
Thanks, that worked!
