### ISSUE TITLE
Please document how to use Graph API to create edges where Ids are from multiple fields

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#11929]
I have some collections that have registered Id conventions similar to this:

$"{COLLECTION_NAME}/{contactId}/{questionId}";

The issue is that while I know the questionId from the linked data, I don't know the contactId from the data, I know it from a parameter for the query.

I can do this with LoadDocument in a standard linq query because I can construct the Id string easily and the load occurs.

But I can't determine how to do the same with Graph API using the - notation.

(I also can't determine how to do a nullable link (i.e left join in relational database land) so that I can say "doesn't have or has some sort of parameter value of in the where)

**Comment by ayende** [comment]
You must have the document id to follow an edge.
Alternative, you can use the JS API to construct these at query time dynamically.


```
declare function AllBosses(e) {
    var names = [];
    while(e.ReportsTo){
        var boss = load(e.ReportsTo); // can apply logic here
        names.push(boss.FirstName);
        e = boss;
    }
    return names;
}
from Employees  as e
select {
    Name: e.FirstName,
    Bosses: AllBosses(e)
}
```

**Comment by jhancock4d** [comment]
It would be nice if you could use simple string concatenation in the edge to build the compound id instead of having to generate javascript to make it work.

Also, how would you handle nullability? I.e. there might not be a record at all, but I still want to traverse the recursive query. It's just that there is no data there which is the same as failed data. (i.e. they got the question wrong is the same as not taking questions at all in general, but worse obviously)

**Comment by ayende** [comment]
In that case, use functions and handle that directly, it would be better than a graph query.

**Comment by jhancock4d** [comment]
So given all of this incredibly complex stuff, can we please have joins in linq that build this stuff? It's doing exactly the same thing and you could put the same limitations on the joins that are being created as you have elsewhere on linq that doesn't exist in say EF, and we wouldn't have to stand on our heads and use special syntax. (Load document is just FirstOrDefault in a projection)

This would also open up the one to many case of using LoadStartsWith... in linq based on the join clause.

**Comment by ayende** [comment]
I'm afraid that this is out of our hands. Expressing something like this in Linq isn't really possible. Linq supports only expressions, not statements. That, in turn, means that trying to do this leads to unreadable mess.

See the way to try here:
https://ravendb.net/docs/article-page/4.2/csharp/indexes/querying/projections#example-v---projection-with-

I would recommend just expressing this as JS directly.
