### ISSUE TITLE
LongCountAsync?

### ISSUE THREAD

**Issue by ar0311** [ravendb/ravendb#11960]
Is it possible to extend the RavenDB client to provide this method on a query?

**Comment by ayende** [comment]
Yes, that is possible. 
Moving this to our issue tracking, you can follow the progress there.

**Comment by ayende** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-16469

**Comment by ar0311** [comment]
Thanks Ayende, will follow it there.
