### ISSUE TITLE
CountAsync Fails if RavenQuery.Load is used

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#11991]
```
await (from cc in DbSession.ContactContent.ListSecure(Identity)
		where
		cc.ContactId == contactId
		let content = RavenQuery.Load<ContentRefDto>(cc.ContentId)
		select new ContentRefWithProgressDto
		{
			ContentType = content.ContentType,
			PercentComplete = cc.PercentComplete,
			CoverArtUrl = content.CoverArtUrl,
			Description = content.Description,
			Goal = content.Goal,
			Id = content.Id,
			Milestone = content.Milestone,
			MonetizationRule = content.MonetizationRule,
			Name = content.Name,
			ReleaseOn = content.ReleaseOn,
			RevShareRule = content.RevShareRule
		}).CountAsync();
```

I need to do this for paging reasons. I need the total possible records that can be returned, and then I need to do top/skip after that to apply the paging.

Otherwise, it can't know how many more there are.

But when I run this query, as soon as it has the load function, it fails saying that You can't run a sync query in an async session.

I can't do it without the projection, because odata $filter has to apply to the projection so that the users have the shape of the object to apply $filter with.

**Comment by ppekrol** [comment]
Can you show us the implementation for `DbSession.ContactContent.ListSecure(Identity)` ? CountAsync comes from https://github.com/ravendb/ravendb/blob/v5.1/src/Raven.Client/Documents/LinqExtensions.cs ?

**Comment by JohnGalt1717** [comment]
@ppekrol  It's literally just IRavenQueryable<T> at this point. We haven't added logic to it yet.

**Comment by jhancock4d** [comment]
@ppekrol It's literally just IRavenQueryable at this point. We haven't added logic to it yet.

**Comment by ppekrol** [comment]
Does not throw:
```
                using (var session = store.OpenAsyncSession())
                {
                    var count = await (from cc in session.Query<User>()
                        where cc.LastName == "John"
                        let content = RavenQuery.Load<Address>(cc.AddressId)
                        select new
                        {
                            LastName = cc.LastName,
                            City = content.City
                        }).CountAsync();
                }
```

Throws `You can't use an async query from a sync session`:
```
                using (var session = store.OpenSession())
                {
                    var count = await (from cc in session.Query<User>()
                        where cc.LastName == "John"
                        let content = RavenQuery.Load<Address>(cc.AddressId)
                        select new
                        {
                            LastName = cc.LastName,
                            City = content.City
                        }).CountAsync();
                }
```

The `DbSession` in your code is a sync or async session?

**Comment by jhancock4d** [comment]
It's OpenAsyncSession

**Comment by ppekrol** [comment]
Does `CountAsync` come from our https://github.com/ravendb/ravendb/blob/v5.1/src/Raven.Client/Documents/LinqExtensions.cs ? Do you have `Raven.Client.Documents` using added?

**Comment by ayende** [comment]
Also, it looks like you are trying to run the query twice. Once to get the results, once to get the count.
In RavenDB, you don't need to do that. You can do that in one call to the database:

https://ravendb.net/docs/article-page/5.1/Csharp/client-api/session/querying/how-to-get-query-statistics

**Comment by jhancock4d** [comment]
@ppekrol Yes.

@ayende I don't think I can do that.

This is odata with paging, so it you take a base query, apply $filter, get the total number of results of that base query, then you apply $orderby, $top, $skip to it.

Query
Filter
TotalCount
order
skip
top

IAsyncEnumerable + totalCount in response header.

Thus the query itself that actually runs and returns results isn't the query that would have the right count because it has where clauses applied.

And this only happens on the first .CountAsync() which occurs BEFORE the query is materialized or any other $filter stuff etc. is applied as if CountAsync is trying to execute sync instead?

**Comment by ayende** [comment]
That would work. You run the query once, and return the TotalCount from RavenDB.
The `Statisitics(out var stats)` will give you an instance of `QueryStatistics`, which has `TotalResults` that you can return.

Once call to the DB, all the work being done.

**Comment by jhancock4d** [comment]
@ayende how would it know which count to take?  The query that is executed is top/skiped, so the total should be Math.min(top/total records - skip) not total records of the query without top wouldn't it?

**Comment by jhancock4d** [comment]
@ayende The other reason why this doesn't work, is that the query doesn't execute until the result is being streamed because it's IAsyncEnumerable with WebAPI.  So I can't use the statistics because the query hasn't been run by the time the method ends.

**Comment by ayende** [comment]
The `TotalResults` value is going to be the number of matches to the query, without top / skip, etc. 
We do that explicitly to handle this scenario and save an unneeded query.

**Comment by ayende** [comment]
You can fake that out, and I would recommend doing that (eval the first result, then stream it back). 
Saving an extra roundtrip is much more efficent.

**Comment by JohnGalt1717** [comment]
The problem is that that way defeats .NET 6's forthcoming support for streaming encoding of the resultset from IAsyncEnumerable. Thus, while it might be faster computationally, it scales significantly less well memory wise since .NET is almost always, especially on docker with that overhead) constrained by memory, not CPU.

My approach has an API that is simply working as a passthrough after applying logic to the filter, your way requires the API to hold the entire resultset in memory, and the translated value of the json in memory too.  

By not materializing the IQueryable and returning the IAsyncEnumerable my overhead is vastly lower on the api.

But either way, I'm at a loss as to why my approach throws the error given that I'm calling CountAsync on an Async Session.

**Comment by jhancock4d** [comment]
The problem is that that way defeats .NET 6's forthcoming support for streaming encoding of the resultset from IAsyncEnumerable. Thus, while it might be faster computationally, it scales significantly less well memory wise since .NET is almost always, especially on docker with that overhead) constrained by memory, not CPU.

My approach has an API that is simply working as a passthrough after applying logic to the filter, your way requires the API to hold the entire resultset in memory, and the translated value of the json in memory too.

By not materializing the IQueryable and returning the IAsyncEnumerable my overhead is vastly lower on the api.

But either way, I'm at a loss as to why my approach throws the error given that I'm calling CountAsync on an Async Session.

**Comment by jhancock4d** [comment]
This also fails with the same error message.

```
from c in DbSession.Content
where c.Categories.Any(cc => cc.Id == categoryId)
select c

```

Of course you can't do an AnyAsync there because it isn't boolean so there's no way to find all of the content, where there is a CategoryRef of the type passed in as this currently sits.

**Comment by ayende** [comment]
No, it works just fine with that. Consider this code:

```
                    var query = session.Advanced.AsyncDocumentQuery<User, Users_ByName>().Where(x => ...);
                    StreamQueryStatistics stats;
                    IAsyncEnumerator<StreamResult<User>> reader = await session.Advanced.StreamAsync(query, out stats);

```

This will give you the results in `stats` and give you an `IAsyncEnumerator`

**Comment by jhancock4d** [comment]
Ok, so .Statistics doesn't seem to be an extension on IQueryable<T> nor does ToArrayAsync nor ToListAsync have an override with out statistics)

Also this doesn't resolve this example that has the same issue:

from c in DbSession.Content
where c.Categories.Any(cc => cc.Id == categoryId)
select c

Which is just standard "find me something that has at least one list item with a property of" which I would think would be supported and work fine with async.

**Comment by ayende** [comment]
Let's see if I can explain things better.
If you want to use `IAsyncEnumerable` properly, without caching things in memory, you need to use `StreamAsync` API, which will give you the `stats` as you call it.

One query to the server, all the data in one go.

**Comment by jhancock4d** [comment]
Ok, but why does c.Categories.Any also throw the error just using .ToArrayAsync() on it?

**Comment by ayende** [comment]
Can you send a failing test case? I'm not sure that I follow

**Comment by JohnGalt1717** [comment]
Litterally just: (from c in DbSession.Content
where c.Categories.Any(cc => cc.Id == categoryId)
select c).ToArrayAsync() fails

**Comment by jhancock4d** [comment]
Litterally just: (from c in DbSession.Content
where c.Categories.Any(cc => cc.Id == categoryId)
select c).ToArrayAsync() fails

**Comment by ayende** [comment]
What is ` DbSession.Content` ?

**Comment by jhancock4d** [comment]
It's just a IRavenQueryable.  We lazily create them on demand as part of a Session wrapper that we use so that it looks more like the surface area of EF Core which both means way less code and developers that have lots of esperience with EF Core can use RavenDB in most cases without having to learn the details of RavenDb too much so that the advanced developers on the team do the hard stuff in RavenDb. (time series, counters, cross document queries etc.)

**Comment by ayende** [comment]
This passes without issue, which is why I would like to see a failing code.

```
  var q = await (from o in s.Query<Orders.Order>()
                 where o.Lines.Any(l => l.Discount != 0)
                 select o).ToArrayAsync();
```
