### ISSUE TITLE
InvalidOperationException count(doc, name) 'doc' must be a string argument or the actual document instance itself

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#12011]
I have the following:

```
		public static IQueryable<ContentRefWithProgressDto> SelectToContentRefWithProgressDto(this IQueryable<Content> query, IIdentityUser identity) =>
			from c in query
			let cc = RavenQuery.Load<ContactContent>(string.Format(ContactContent.ID_TEMPLATE, identity.Id, c.Id))
			select new ContentRefWithProgressDto
			{
				ContentType = c.ContentType,
				CoverArtUrl = c.CoverArtUrl,
				Description = c.Description,
				Dislikes = RavenQuery.Counter(c, ContentRef.DISLIKE_COUNTER) ?? 0,
				Likes = RavenQuery.Counter(c, ContentRef.LIKE_COUNTER) ?? 0,
				Goal = c.Goal,
				Id = c.Id,
				Milestone = c.Milestone,
				MonetizationRule = c.MonetizationRule,
				Name = c.Name,
				PercentComplete = cc.PercentComplete,
				ReleaseOn = c.ReleaseOn,
				RevShareRule = c.RevShareRule
			};
```

Where c a content object.  Presumably this error message is coming from Dislikes and Likes in this.  I've tried c and c.Id and in both cases I get the above error message.

Only some documents have these because they're created when someone actually likes or dislikes the content for the first time.

Why does this throw that error? It appears to be doing exactly what the error message demands. I would assume if it doesn't exist that it would return null hence the ?? 0 on each.

(ContentRef.DISLIKE_COUNTER etc are just constants for consistency)

**Comment by ayende** [comment]
What is the `ToString` of this query?
Can you create a failing test case that we can run here?

**Comment by jhancock4d** [comment]
I worked around this by inverting the query.  The root problem appears to be that the document load had happened in another part of the query (this is a helper function to project that doesn't work with AutoMapper) so it was happening twice which confused the parser I would imagine.

Which brings up a separate issue of odata $filter on projected results and if it's loading everything and then filtering as a result of the fact that the linq where in that case is happening after the projection but this itself isn't an issue.
