### ISSUE TITLE
from/from in Linq Query doesn't work, but does work in an index

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#12013]
Why does this:  

```
from c in this.DbSession.Contacts
  from d in c.Domains
  where c.Id == contactId
  select d
```

Work if you specify it in an index, but won't work when you query it directly?  There is a ton of cases where you want to get a sub list from a document with the document id. (i.e. email addresses, phone numbers etc.)

Do I have to manually write an index every time to get this type of data?

(the specific case is that you want to return a stream from the sublist and not just a materialized array)

**Comment by ayende** [comment]
Yes, that can't work as you written it.
The actual problem is that this would require us to either generate a separate entry for each sub item (and if you have multiple `from`, a cartesian product of them).

We'll also need to store the related value in the index, doubling the storage consumption. 
The alternative would be to do a scan of the values, which would be expensive.

Note that you can use this mode, instead:

```
var q = from o in s.Query<Orders.Order>()
        where o.Lines.Any(l => l.Discount != 0)
        select new
        {
            Discounted = o.Lines.Where(x => x.Discount != 0)
        };
```

This gives you a similar mechanism, works with the dynamic queries, and is very effeicnt.

**Comment by jhancock4d** [comment]
Right, but I can't actually stream that because I have to mutate it from a single object with an array, to an  IAsyncEnumerable.  Which is back to the same problem as before.

Normally I'd write this:

(from c in DbSession.contacts where c.Id == contactId select c).SelectMany(c => c.Domains).AsAsyncEnumerable(...)

Which shouldn't require any indexing at all other than the Id of the document because it's saying "go find me this document. Then once you have, return the domains which can then be streamed"

So wouldn't that completely eliminate what you're saying about the index and this wouldn't be a scan either because it's an Id index, and then only stream the array inside that document?

I was just trying to hack around this limitation that we're constantly having to do a FirstOrDefaultAsync to get an array and then just IEnumerable that out on webapi instead of being able to stream the values.

**Comment by ayende** [comment]
Why can't you stream that?
You surely can do:

```
IAsyncEnumerable<Item> source = ...;

await foreach(var item in source)
{
    foreach(var inner in item.Inners)
    {
       yield reutrn inner;
    }
}
```

That keeps the streaming nature.

**Comment by jhancock4d** [comment]
You haven't accomplished anything by doing that. It's no more efficient than just getting the IEnumerable and dumping it in webapi because the entire resultset is still in memory.

My way results in ravendb returning a stream of results, which I then push out as a stream of results to the client.

Your way loads the root item with the inner array into memory entirely, and then streams that out to the client. (which is what the default serializer is doing anyhow)

I'm trying to optimize this so that the api applies security and tells Ravendb how to transform the each projection into a dto, that I'm going to use, and then works as nothing but a broker for the remainder of the call passing the results from ravendb one by one into the response stream of the serializer using .net 6's support for this.  I can do this for all root documents without issue. But I can't seem to do this for sub lists within a document like email addresses within a contact. The end user sees the email addresses on screen and nothing else, and thus everything else is overhead in the process that I'd like to avoid.  Raven is fast and scales.  WebAPI can be a pig if you're not careful and doesn't scale well on memory especially in k8s because of the container overhead + webapi's serializer and how it does garbage collection on that serializer and all of your materialization is held in memory way too long and not cleaned out until there's memory pressure or spare cycles which almost never happens on a well used api endpoint.

**Comment by ayende** [comment]
My approach lead will lead to a single array for each matching document, correct. 
Unless you expect to have _really_ big arrays, that isn't an issue.

In general, RavenDB currently require a single output for each matching document, so you can't flatten the results server side.

**Comment by jhancock4d** [comment]
Ok, well consider this a request for some form of functionality to do something similar (if not identical) to SelectMany on sub arrays of a document. 

I would use it like this: (from c in contacts where c.Id == contactId select c.EmailAddresses).SelectMany(c => c.EmailAddresses).ProjectTo<EmailAddressDto>().AsAsyncEnumerable()


The problem isn't a single request, it's thousands of requests all taking more memory than they should, having their memory disposed of lazily by .net because they have to be held in memory until the serialization is completed so  you can't actively dispose of the resultsets so you're relying on the GC to release the memory, which .net has a bad habit of using all available memory before it starts cleaning stuff up if the cpu is in use.

Add on the overhead of the linux stuff in the docker container and you start spinning many pods on many clusters and using massive amounts of memory to do so, while you still have CPU time in the 30% range all because of .net GC and the serialization pipeline.

.net 6 fixes this (I requested it and Damian Edwards pushed it) by allowing us to return an IAsyncEnumerable that streams the results to the json serializer (or any other serializer including Protobuf etc.)  What it does is allows the asyncenumerable to complete and immediately upon doing so, everything is shut down and released by the design and it's imperatively released not passsively with GC.

**Comment by ayende** [comment]
There is a feature request on our roadmap:
https://issues.hibernatingrhinos.com/issue/RavenDB-9996

Note that it doesn't actually matter, because the same amount of memory is actually being used and released.
You can, if you want, to handle the raw data from RavenDB, which is using native memory and can manage that directly, but I'm guessing that this isn't something that you'll like to do.

And again, the async enumerable you get here _will stream the results_.

**Comment by jhancock4d** [comment]
How is that possible with newtonsoft json?

It can pull a single root object, but as far as I'm aware it can't pull part of a root object row by row in an enumerable so the first call to StreamAsync() that gets the first document with the moveNext will load all EmailAddresses into memory as an example which streaming that as an IAsyncEnumerable is pointless because it will actually consume more resources than just dumping the IEnumerable.

And the above approach blocks Odata filtering in any generic implementation way because the sub data list projected into the dto is what odata has to work on do it means that there's no way for api users to filter/order/top/skip.

**Comment by ayende** [comment]
The simple answer is that we aren't actually processing this via Newtonsoft. The `StreamAsync` API is using our own blittable json parser, which is able to provide inner objects in a streaming fashion.

I don't think that I follow what you mean WRT to the filtering, though.
