### ISSUE TITLE
Cannot understand the query - Standard filter for security, project and then apply user odata

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#12032]
```
DbSession.Query<PlayList>().Where(p => p.OwnedBy.Id == userId ||
				(
					p.ReleaseOn != null && p.ReleaseOn <= DateTimeOffset.UtcNow &&
					(p.IsPublic || userId.In(p.AssignedTo))
				)
			).ProjectTo<PlayListRefDto>(Mapper.ConfigurationProvider)
```
                         
   
   This is pretty standard stuff. It just filters if it's owned by the current user, and if not, that the play list is released and public or assigned to the user. AssignedTo is just: public HashSet<string> AssignedTo { get; set; } = new HashSet<string>();
   
   The sub error is: Expression type not supported: System.Linq.Expressions.TypedParameterExpression
   
   Here's the automapper: CreateMap<PlayList, PlayListRefDto>();

Here's the tostring:

`Could not understand expression: from 'PlayLists'.Where(p => ((p.OwnedBy.Id == value(Data.Content.PlayListCollection+<>c__DisplayClass4_0).userId) OrElse (((p.ReleaseOn != null) AndAlso (p.ReleaseOn <= Convert(value(Data.Content.PlayListCollection+<>c__DisplayClass4_0).now, Nullable`1))) AndAlso (p.IsPublic OrElse value(Data.Content.PlayListCollection+<>c__DisplayClass4_0).userId.In(p.AssignedTo))))).Select(dtoPlayList => new PlayListRefDto() {Channel = IIF((dtoPlayList.Channel == null), null, new ChannelRefDto() {CoverArtUrl = dtoPlayList.Channel.CoverArtUrl, CreatedOn = dtoPlayList.Channel.CreatedOn, Description = dtoPlayList.Channel.Description, Id = dtoPlayList.Channel.Id, Name = dtoPlayList.Channel.Name, OwnedBy = IIF((dtoPlayList.Channel.OwnedBy == null), null, new ContactRefDto() {ContactType = dtoPlayList.Channel.OwnedBy.ContactType, FirstName = dtoPlayList.Channel.OwnedBy.FirstName, Id = dtoPlayList.Channel.OwnedBy.Id, LastOrCompanyName = dtoPlayList.Channel.OwnedBy.LastOrCompanyName, MiddleName = dtoPlayList.Channel.OwnedBy.MiddleName}), ReleaseOn = dtoPlayList.Channel.ReleaseOn, UpdatedOn = dtoPlayList.Channel.UpdatedOn}), CoverArtUrl = dtoPlayList.CoverArtUrl, CreatedOn = dtoPlayList.CreatedOn, Description = dtoPlayList.Description, Id = dtoPlayList.Id, IsPublic = dtoPlayList.IsPublic, Name = dtoPlayList.Name, OwnedBy = IIF((dtoPlayList.OwnedBy == null), null, new ContactRefDto() {ContactType = dtoPlayList.OwnedBy.ContactType, FirstName = dtoPlayList.OwnedBy.FirstName, Id = dtoPlayList.OwnedBy.Id, LastOrCompanyName = dtoPlayList.OwnedBy.LastOrCompanyName, MiddleName = dtoPlayList.OwnedBy.MiddleName}), PlayListType = dtoPlayList.PlayListType, ReleaseOn = dtoPlayList.ReleaseOn, UpdatedOn = dtoPlayList.UpdatedOn})`

If I remove the where, it works fine.

Looking here: https://ravendb.net/docs/article-page/5.1/csharp/indexes/querying/filtering I don't see any documentation on dates, but I'd assume it would just work and the query still fails even with out it.

**Comment by ayende** [comment]
*Please* create those issues with a failing test case. It makes it a lot easier to diagnose the issue.

As it currently stands, I have to guess on what your data structures looks like. I think that I found what the issue is, but it takes a lot longer.

Here is an example:

```
public class OwnerRef{
        public string Name;
        public string Id;
    }
    public class PlayList
    {
        public OwnerRef OwnedBy;
        public DateTimeOffset? ReleaseOn;
        public bool IsPublic;
        public string[] AssignedTo;
    }
    class Program
    {
        static void Main(string[] args)
        {
            var store = new DocumentStore
            {
                Urls = new[] { "http://live-test.ravendb.net" },
                Database = "test"
            }.Initialize();

            string userId = "users/1";
            using(var s = store.OpenSession())
            {
                s.Query<PlayList>().Where(p => p.OwnedBy.Id == userId ||
                (
                    p.ReleaseOn != null && p.ReleaseOn <= DateTimeOffset.UtcNow &&
                    (p.IsPublic || userId.In(p.AssignedTo))
                )).ToList();
            }
        }
    }
```

The problem is here: ` userId.In(p.AssignedTo)`
This doesn't do what you think it does, this is the other way around. The proper way to express this is with:

` p.AssignedTo.Any(a => a == userId)`

Which will generate the following query.

```
from 'PlayLists' where OwnedBy.Id = $p0 or (((ReleaseOn != $p1 and (ReleaseOn <= $p2 and ReleaseOn != $p3))) and (IsPublic = $p4 or AssignedTo = $p5))
{"p0":"users/1","p1":null,"p2":"2021-04-28T18:16:03.8124845Z","p3":null,"p4":true,"p5":"users/1"}
```

**Comment by jhancock4d** [comment]
This still doesn't work:

(from p in session.Products select new ProductDto {Name: p.Name, ...}).Where(p => p.Name = "OdataFilter").ToArrayAsync(cancellationToken);

You'll get the above error consistently. And this is required for oData to work because the user will be querying against your api using the shape of the DTO, not the data object that is stored in the database, so the where clause has to apply to the projection, not the collection in the session.

This is required for say kendo grid, or any other grid control that does server side filtering, order by and paging even if you're not using oData because the user will define the fields to filter on and the values to filter by, and there can be multiple fields. So either you have to create a map of fields from Database class to DTO and somehow map that using expression trees to the session, or you need to be able to do a where/orderby clause on the projection.

How does one solve this to handle this VERY common use case?

**Comment by ppekrol** [comment]
Have you considered using DocumentQuery where you have more control over the generated RQL?

e.g. 
```
                    var products = session.Advanced.DocumentQuery<ProductDto>(collectionName: "Products")
                        .WhereEquals("Name", "Flotemysost")
                        .ToList();
```

**Comment by jhancock4d** [comment]
That's what session.products is in my example.

The issue is that oData looks like this:

$filter = startsWith(FieldName, 'value') AND <something else>

Because the client is doing the requesting the client doesn't have any knowledge of what your database looks like, thus they specify FieldName by what the end field name is that they see. If that's different or a composite, then RavenDB falls over wit hthe above error because Where after ProjectTo doesn't work (unlike Entity Framework which does for this very reason)

As a result, oData and any other client side dynamic querying that you'd see with Kendo Grid etc. fails in any complex scenario under RavenDb which is a major issue given that a grid with filterable, orderable and paging characteristics is HIGHLY desirable in most scenarios.

**Comment by ayende** [comment]
Can you provide a failing test case showcasing this issue?
