### ISSUE TITLE
Please add Recursive to Linq

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#12119]
It would greatly simplify things for us and I suspect many others if the graph query functionality of recursive was brought to linq similar to how Load works.

What I'd like to see is something like this:

```
from c in Content
select new {
   DependsOn = RavenQuery.Recursive(c.DependsOn, r => new Dependant { DependsOn = r.DependsOn, (other fields including loads) },
   c.Name,
   c.Id
}
```

This would provide the nice functionality of the recursive graph without the difficult syntax and difficulty projecting that into C# objects making it way more accessible to people that know linq.

**Comment by ppekrol** [comment]
We marked Graph API as deprecated in 5.4. It will be removed in 6.0.

What you are doing here should be possible via JS projection IMO.

**Comment by JohnGalt1717** [comment]
Do you have an example that I can apply to the above? This is vital to us for our use case so 6.0 will be a major blocker.

**Comment by jhancock4d** [comment]
Do you have an example that I can apply to the above? This is vital to us for our use case so 6.0 will be a major blocker.

**Comment by ayende** [comment]
From the JS API, it's pretty easy, from the Linq API, it is more complex, depending on what you want, you may be able to start with this:

```
var q = from i in newSession.Query<Item>()
    let recursive = (Func<Item, object>)((item) => RavenQuery.Load<Item>(item.Parent))
    select new
    {
        Parents = recursive(i),
        i.Name
    };
```

Here is the way to inject JS directly to Linq:

```
                    var q = from i in newSession.Query<Item>()
                        let load = RavenQuery.Raw<object>(@"function load(i) {
    var parents = [];
    var parent = i.Parent;
    while(parent != null) {
        var p = load(parent);
        parents.push({Name: p.Name});
        parent = p.Parent;
    }

    return { i.Name, Parents: parents};
")
                        select new
                        {
                            Parents = RavenQuery.Raw<object>("load(i)"),
                            i.Name
                        };

```

**Comment by JohnGalt1717** [comment]
So I'm just getting to this and trying to understand how this works:

I'm creating an index like this:

```
		Map = mutators => from m in mutators
						  select new EventMutatorDependencyTree {
							  Mutator = m,
							  Children = Recurse(mutators, x => x.Where(x => x.SourceType == m.TargetType))
						  };

```

Question 1: Is Recurse keyword going away?

Question 2: If not, how do you do shortest?
Question 3: If not, how do you do a where that says "last thing in the recurse has a TargetType of Y"?

Question 4: If yes, how would you do the same?

**Comment by jhancock4d** [comment]
So I'm just getting to this and trying to understand how this works:

I'm creating an index like this:

```
public record EventTypeMutator : EntityDto {
	public string SourceType { get; init; }
	public string TargetType { get; init; }
}

public record struct EventMutatorDependencyTree {
	public EventTypeMutator Mutator { get; init; }
	public IEnumerable<EventMutatorDependencyTree> Children { get; init; }
}


```
Then an index that resembles the following (not sure how to complete it since the hierarchy isn't pre-defined, it's a function of the type fields)

```
		Map = mutators => from m in mutators
						    select new EventMutatorDependencyTree {
							    Mutator = m,
							    Children = Recurse(mutators, x => x.Where(x => x.SourceType == m.TargetType).Select(mt => new EventMutatorDependencyTree {
								    Mutator = mt,
								    Children =  ??
							    })
						    };

```


Question 1: Is Recurse keyword going away?

Question 2: If not, how do you do shortest?
Question 3: If not, how do you do a where that says "last thing in the recurse has a TargetType of Y"?

Question 4: If yes, how would you do the same?

**Comment by ayende** [comment]
`Recurse` is used in the _indexing_, the top post was on _queries_.
