### ISSUE TITLE
Could not understand expression - Anything oData.

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#12172]
Could not understand expression: from 'Playlists'.Where(p => ((p.OwnedBy.Id == value(Data.Content.PlayListCollection+<>c__DisplayClass4_0).userId) OrElse (((p.ReleaseOn != null) AndAlso (p.ReleaseOn <= Convert(value(Data.Content.PlayListCollection+<>c__DisplayClass4_0).now, Nullable`1))) AndAlso (p.IsPublic OrElse value(Data.Content.PlayListCollection+<>c__DisplayClass4_0).userId.In(p.AssignedTo))))).Select(dtoPlayList => new PlayListRefDto() {ChannelId = dtoPlayList.ChannelId, CoverArtUrl = dtoPlayList.CoverArtUrl, CreatedOn = dtoPlayList.CreatedOn, Description = dtoPlayList.Description, Id = dtoPlayList.Id, IsPublic = dtoPlayList.IsPublic, Name = dtoPlayList.Name, OwnedBy = IIF((dtoPlayList.OwnedBy == null), null, new ContactRefDto() {ContactType = dtoPlayList.OwnedBy.ContactType, FirstName = dtoPlayList.OwnedBy.FirstName, Id = dtoPlayList.OwnedBy.Id, LastOrCompanyName = dtoPlayList.OwnedBy.LastOrCompanyName, MiddleName = dtoPlayList.OwnedBy.MiddleName}), PlayListType = dtoPlayList.PlayListType, ReleaseOn = dtoPlayList.ReleaseOn, UpdatedOn = dtoPlayList.UpdatedOn}).OrderBy(p => p.Name)

Here's the where (which is done first before the projection):

```
			if (user.IsInRoles(RoleTypes.SystemAdmin))
				return this;

			var userId = user.Id;
			var now = DateTimeOffset.UtcNow;

			return this.Where(p => p.OwnedBy.Id == userId ||
				(
					p.ReleaseOn != null && p.ReleaseOn <= now &&
					(p.IsPublic || userId.In(p.AssignedTo))
				)
			);

```

The projection has to occur first because without it, odata can never work because the field names could be different from the projection to the actual object. (And theoretically the same could occur with $filter applying an additional where to the end)

It seems Raven is just refusing to do anything after the projection. If this is the case, how can one ever support OData or anything similar to it given the reality that the end user won't know the internal field names etc. to use thus the $filter and $orderBy (or whatever variation on that theme)  can never run?

**Comment by ayende** [comment]
Didn't I already answer this (or something very similar)?

The issue is with: `userId.In(p.AssignedTo)`

You need to use: `p.AssignedTo == userId`

**Comment by jhancock4d** [comment]
p.AssignedTo is an array thus that won't work. This example (and there are a ton of cases, this is just the most simplistic) is literally a playlist where specific people have subscribed to it.  The subscription (AssignedTo) is just an array of string ids.

So how would you solve this specific issue then?

**Comment by ayende** [comment]
`p.AssignedTo.Equals(userId)` will work

Or `p.AssignedTo.In(userId)`.

**Comment by jhancock4d** [comment]
???

String userId
Hashset<String> AssignedTo

p.AssignedTo.Equals(userId) will always be false unless there is something magical going on that defies what equals does in .net.

p.AssignedTo.In(userId) doesn't even compile.

**Comment by ayende** [comment]
`p.AssignedTo.Equals(userId) ` isn't actually evaluated on the client side.
This will be transalted to `p.AssignedTo == $userId`, which will work using RQL (we don't care about the types).

**Comment by jhancock4d** [comment]
This is in my class that this is in:

using Raven.Client.Documents.Linq;

even in RQL p.AssignedTo = $userId would be comparing a json collection of strings to a single string wouldn't it be?

**Comment by ayende** [comment]
`p.AssignedTo = $userId ` No, we'll compare that to the _values_ in the array, not to the full array

**Comment by jhancock4d** [comment]
Wild.  That's just completely not consistent with any implementation anywhere.

Why wouldn't userId.In(p.AssignedTo) work given that that's what the documentation says "In" is supposed to be for?

(and why does p.AssignedTo.Contains(userId) not ever work given that that is the consistent Linq implementation?)

**Comment by ayende** [comment]
`userId.In(p.AssignedTo)` is comparing the value to the array, it isn't currently supported by the Linq provider.

**Comment by jhancock4d** [comment]
??? The docs say that userId.In(...) is comparing the value to the elements of the array like .Contains works in traditional linq.

What you're saying seems to contradict that doesn't it?

**Comment by ayende** [comment]
No, the docs say that the left side is the document property, the right side is an array you provide.

**Comment by jhancock4d** [comment]
//
		// Summary:
		//     Implementation of In operator
		public static bool In<T>(this T field, IEnumerable<T> values);
		
	//
		// Summary:
		//     Implementation of In operator
		public static bool In<T>(this T field, params T[] values);

And if you put p.AssignedTo.In(userId) (i.e. Array.In(string)) you get the compile time error that you'd expect with the definition here.

Which indicates that the left side is the singular, and the right side is the array.

Are you saying that We can't do the inverse and check that a value that I provide is in an array in the document? (becuase .Equals in .NET is an absolute hash equality operator unless overriden and still is only intended to match property to property like an record, not match if any element in an array matches hence my cognitive dissonance)

**Comment by ayende** [comment]
The `In()` method is meant specifically for the `in` operator in RQL. Documented here:
https://ravendb.net/docs/article-page/5.1/csharp/indexes/querying/what-is-rql#operator--1

The left side _must_ be a field, the right side must be a value or set of values.

But you are correct, `Contains` is the way to go, I forgot about it, see:

https://github.com/ravendb/ravendb/blob/6f75fe0297bbcbd854c7f7ab3b82576ea8ff466f/test/SlowTests/Tests/Linq/Contains.cs#L38

**Comment by jhancock4d** [comment]
Ok... friendly feedback.  In and contains are the same thing. Right now they have 2 different meanings in RavenDB which shouldn't be the case. 

Contains should work on the left side always and it shouldn't matter if it's a field or a value the same as standard linq works.  IN EF Core this means that Value.Contains(something) translates to an In Query that lists the items in Value.  If it's a field, it transltes to a EXISTS.  In Linq to Objects it just works either way.

In is just the opposite definition.  But in both cases it should just work in either direction.
