### ISSUE TITLE
There is no Git tag for v5.1.7

### ISSUE THREAD

**Issue by AKlaus** [ravendb/ravendb#12182]
There are NuGet packages available for **v5.1.7** ([link](https://www.nuget.org/packages/RavenDB.Client/)) published 23-Apr, but there is no Git tag for that version - the latest is **v5.1.6**.
Can you please publish the Git tag for that version as well to make it more legitimate (and also allow viewing its code online)?

**Comment by ppekrol** [comment]
5.1.7 was an emergency build released from a branch. This is why there is no tag.

**Comment by AKlaus** [comment]
No worries.

But if it's not stable then should it be marked as 'preview' on NuGet.org?
Or if it is stable then are you going to create a tag from that commit?

**Comment by ppekrol** [comment]
It is a stable, but released from a branch, so I do not have a commit in master to mark. It would require a lot of infrastructure changes, which at this point I would prefer to avoid.

**Comment by AKlaus** [comment]
All good.
Thank you for the explanation.
