### ISSUE TITLE
Export visible cells only not working with objects

### ISSUE THREAD

**Issue by tobiaszuercher** [ravendb/ravendb#12316]
selecting just a couple of fields of objects in the studio like this:

![image](https://user-images.githubusercontent.com/516373/120816690-470d2a00-c551-11eb-8a91-8b5f083a7f11.png)

then clicking on "export visible cells only" -> those values won't be in the csv

**Comment by garayx** [comment]
I tried this locally and it seem to be working,  

Are the `SubsessionId` or `CustomerId` of the first results null ? 
What version do you use?

Can you share a sample database that reproduce the issue ? you can send it to support@ravendb.net email)
