### ISSUE TITLE
Include by document ID

### ISSUE THREAD

**Issue by jamotaylor** [ravendb/ravendb#12404]
Let's say I have a document `BlogEntry` with a `Username` property that references the user document.

Blog entry:
``` json
{
  "Username": "jbloggs",
  "Title": "How to use RavenDB",
  "PublishedDate": "2021-05-24"
}
```
User:
``` json
{
  "Username": "jbloggs",
  "FirstName": "Joe",
  "LastName": "Bloggs"
}
```
The user document is stored with the ID `users/jbloggs`

I want to load the blog entry and include the user document, but the API will only allow me to include the document by path such as:

``` csharp
using var session = _store.OpenSession();

var blogPost = await session
  .Include(p => p.Username)
  .Load("BlogEntry/1-A");

var user = session.Load($"users/{blogPost.Username}");
```

Of course, this won't include the user document in the first load, because the user document ID is `users/jbloggs`, not `jbloggs`. 

What I would like to suggest is that the API allows for including documents based on the "raw" document ID, something like:

LINQ expression version:
``` csharp
using var session = _store.OpenSession();

var blogPost = await session
  .IncludeRaw(p => $"users/{p.Username}")
  .Load("BlogEntry/1-A");

var user = session.Load($"users/{blogPost.Username}");
```
AND/OR literal string version:
``` csharp
string username = "jbloggs";

using var session = _store.OpenSession();

var blogPost = await session
  .IncludeRaw($"users/{username}")
  .Load("BlogEntry/1-A");

var user = session.Load($"users/{blogPost.Username}");
```

**Comment by mcrio** [comment]
this doesn't work?

```csharp
var blogPost = await session
  .Include(p => $"users/{p.Username}")
  .Load("BlogEntry/1-A");
```

**Comment by ppekrol** [comment]
Hi, we do not support computations in includes as you wrote, but you could take advantage of JavaScript includes in the querying mechanism.

e.g.
```
declare function myIncludes(b) {
    include("users/" + b.Username);
    return b;
}
from Blogs as b
where id(b) == 'BlogEntry/1-A'
select myIncludes(b)
```

Would that work for you?

**Comment by jamotaylor** [comment]
> this doesn't work?
> 
> ```cs
> var blogPost = await session
>   .Include(p => $"users/{p.Username}")
>   .Load("BlogEntry/1-A");
> ```

@mcrio Nope, it doesn't work, but seems like it should hey?

There is an overload for Include() that takes a string, but that string is the property path, not the ID.

**Comment by jamotaylor** [comment]
> Hi, we do not support computations in includes as you wrote, but you could take advantage of JavaScript includes in the querying mechanism.
> 
> e.g.
> 
> ```
> declare function myIncludes(b) {
>     include("users/" + b.Username);
>     return b;
> }
> from Blogs as b
> where id(b) == 'BlogEntry/1-A'
> select myIncludes(b)
> ```
> 
> Would that work for you?

@ppekrol Well, not really, cos that's JavaScript (that you would have to run on the server right?) and I'm using the C# API. 

I'm not wanting to do a calculation on the server, just give the server the ID directly for it to include in the load.

**Comment by ayende** [comment]
This is supported, but you need do write the output in this manner:

```
var blogPost = await session
  .Include(p => "Username(users/)")
  .Load("BlogEntry/1-A");
```

The idea is that the value in the `()` is used as a prefix to the value inside `Username`.

Suffix is also supported, using `CustomerId[{0}/customer]` syntax. 

Both are considered fairly advanced usages, I would consider holding the full document id as well, since that makes many thigns easier.
