### ISSUE TITLE
Warn in Setup Wizard if self created certificate does not fit

### ISSUE THREAD

**Issue by mmattes** [ravendb/ravendb#12486]
Hi, 

we struggled yesterday to get a new Raven DB Setup fully running. The Server started, and we could access the Raven Studio without any problems. But database creation failed and in the logs we constantly saw the error ```Exception was thrown while collecting info from A...```. As we could find nothing on the web why the error is caused i am rasing this issue to help others. 

This morning i found the solution as I found out that the self created certificate we used for the server missed the KeyUsage ```DigitalSignature``` like described [here](https://ravendb.net/docs/article-page/4.2/csharp/server/security/authentication/certificate-configuration)

I think it would be good to have a warning within the Setup Wizard, when the certificate got selected if it does not fit the requirements.

**Comment by ayende** [comment]
We are actually validating certain aspects of the certificate here:

https://github.com/ravendb/ravendb/blob/66be352cf235ef8c4dc375babb08866c568018f1/src/Raven.Server/ServerWide/SecretProtection.cs#L780

Looks like we missed that, fixed here: https://github.com/ravendb/ravendb/pull/12489
