### ISSUE TITLE
WhatChanged and Array changes

### ISSUE THREAD

**Issue by matrichard** [ravendb/ravendb#12508]
Hi, 

I'm probably misunderstanding the WhatChanged method for arrays but when changing the value of a property in an array of object the WhatChanged method is returning every changes as `ChangeType.FieldChanged`. Since the value has changed for this item in the array I would have expected a change of type `ChangeType.ArrayValueChanged`.

Consider this gist for a better example of what I'm trying to explain: https://gist.github.com/matrichard/17691c323822a8f33e228aa99413912b

Apologies if I misundertood the use of the method

**Comment by lastav5** [comment]
Hi,

This is happening because you are changing an object inside the array, which means you are actually changing a field.
If you were to change one of the values in the array ["a", 1, "b"] for example, then you would get 'ArrayValueChanged'.

Hope this helps

**Comment by matrichard** [comment]
Yes, thank you for the quick reply
