### ISSUE TITLE
TimeSeries Replication Error

### ISSUE THREAD

**Issue by alexandernuta** [ravendb/ravendb#12500]
RavenDB 5.2.0
When Server Wide External Replication is enabled (may also apply to other replication types), TimeSeries Value(0) that are updated with a value less than the previous one are not replicated to the other server database.

For example if we have a Document with 2 TimeSeries

Date | Value #0
2021-07-13 00:00:00.000Z | 1000
2021-07-14 00:00:00.000Z | 1000

on insert on Node 1 both timeseries will replicate to Node 2
if we update Node 1 timeseries values like so

2021-07-13 00:00:00.000Z | 500
2021-07-14 00:00:00.000Z | 1500

Node 2 will only get timeseries
2021-07-14 00:00:00.000Z | 1500 - greater than  (1000 previous)

the first one with date 2021-07-13 00:00:00.000Z and value 500 - lower than (1000 previous) will not be replicated

The end result after the changes with external replication is as bellow, only timeseries with greater values are updated.

Node 1 TimeSeries Data
2021-07-13 00:00:00.000Z | 500
2021-07-14 00:00:00.000Z | 1500

Node 2 TimeSeries  Data
2021-07-13 00:00:00.000Z | 1000
2021-07-14 00:00:00.000Z | 1500

Temp workaround is to have a timestamp on value #0 and use the other values for data

**Comment by ayende** [comment]
Hi,
I can confirm that this is an issue, we'll resolve that.

**Comment by alexandernuta** [comment]
Hello,
Tested in 5.3.0 still not working properly.

**Comment by ayende** [comment]
Hi,
I'm sorry, we have a few PR still pending in the process, you can track these here. 
https://github.com/ravendb/ravendb/pull/12982/

**Comment by alexandernuta** [comment]
Hi Ayende,
Thank you very much for your time and effort.

**Comment by alexandernuta** [comment]
The issue has been fixed! Thank you for your time and effort.
