### ISSUE TITLE
Docker container for linux/arm64

### ISSUE THREAD

**Issue by Jeroen-Sturm** [ravendb/ravendb#12531]
Hello, please support `arm64 container` for docker,
I now only see `linux/amd64` and sinds i'm running docker on a Apple Silicon this will not work properly according to the [Docker known issues](https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues). I experience a lot of struggle when developing because I have to restart the container over and over again because it crashes too often.

specs
---
```
MacBook Pro (13-inch, M1, 2020)
macOS Big Sur 11.4
Docker version : 3.5.2 (66501)
DockerHub : 4.1-ubuntu-latest
Docker Script : docker run -d -p 8080:8080 -p 38888:38888 --platform linux/amd64 --name ravendb-5 -e RAVEN_Indexing_MaxStepsForScript=50000 -e RAVEN_Setup_Mode=None -e RAVEN_License_Eula_Accepted=true -e RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork ravendb/ravendb:4.1-ubuntu-latest
```

**Comment by gregolsky** [comment]
Hello @Jeroen-Sturm I added a ticket to our YouTrack:
https://issues.hibernatingrhinos.com/issue/RavenDB-17024

However most of the building blocks are there and if you'd like you can try building that image on your own using our `build-ubuntu.ps1` script. https://github.com/ravendb/ravendb/blob/v5.2/docker/build-ubuntu.ps1#L5

To do that you'd need to add support for `arm64` in the `$Arch` option and put `arm64` linux build in the artifacts directory.
You can get it on our Downloads page:
![image](https://user-images.githubusercontent.com/1541805/126479303-f41fd7bb-4d84-41f2-91b7-5c23b1501e91.png)


Then in theory just run `build-ubuntu.ps1 -Arch arm64` and you're done.

**Comment by scotteau** [comment]
I myself was checking out RavenDb and I'm on a m1 Mac as well. For whoever not sure what to do to generate images.
Here is what I did.

01. Download `Linux arm64` version of the installer as shown above.

02. Create a folder called `artifacts` and copy the downloaded file in there.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/1281209/126873516-796792c3-067f-4a1e-93c0-6a00f59ed9a0.png">

03. Go to `ravendb-ubuntu` and duplicate the file `Dockerfile.arm32v7`, then renamed to `Dockerfile.arm64v8`
<img width="190" alt="image" src="https://user-images.githubusercontent.com/1281209/126874037-e54ba918-6816-43fa-adcd-f2f9729d9dfa.png">

04. Go into the file, and modify the last bit of the first line, to `arm64v8`

5. Go to `build-ubuntu.ps1`, copy the `arm32v7` condition, and change it to `arm64v8` accordingly
<img width="855" alt="image" src="https://user-images.githubusercontent.com/1281209/126874157-d9119ce9-55d1-4eb3-bb6d-4e00227f2d31.png">

6. Go to `common.ps1`, copy the whole `x64` bit and modify it to `arm64v8`
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1281209/126874191-7329996f-5dc5-408f-a06c-51ca4c7d4dc0.png">

7. Run the script with args `build-ubuntu.ps1 -Arch arm64`

8. You should then have a bunch of images generated in docker.

9. Delete the everything but `latest`.

10. Now you have the ravendb arm64 image ready to go.

**Comment by jhancock4d** [comment]
It would be really nice if this was done automatically as part of the deploy process so that this is more automated for new devs that we're onboarding that need docker to run our services for testing of apps on ios.

**Comment by ayende** [comment]
This will be part of the next release.

**Comment by JohnGalt1717** [comment]
I have the following docker-compose now with V6:

```
  ravendb:
    restart: always
    image: ravendb/ravendb:latest

```

And on MacOS with Apple silicon it still tries to pull the x64 version not the arm64 version. I'm trying to create a generic docker-compose.yaml that will work on dev machines that are windows x64, linux x64 and mac with arm64 and in every other docker case, (i.e. redis) it pulls the right version when I just use :latest, but with Raven it isn't. What am I doing wrong and how can I make sure it stays generic in this scenario?

**Comment by gregolsky** [comment]
@JohnGalt1717 We do not have a "redirection" to the platform you run on implemented in the image manifest. Please use the platform-specific tag `ravendb/ravendb:ubuntu-arm64v8-latest`

**Comment by JohnGalt1717** [comment]
This becomes very problematic when team members are on both Windows and mac.  Please strongly consider adding the redirection so that the :latest tag takes you to the right platform for your machine.

**Comment by ayende** [comment]
Note that `ravendb/ravendb:latest` is now a multi-arch manifest

**Comment by JohnGalt1717** [comment]
Fantastic!
