### ISSUE TITLE
In/Contains/Any with enum array list doesn't return values properly

### ISSUE THREAD

**Issue by jhancock4d** [ravendb/ravendb#12589]
Given the following data:

```
{
    "Divisions": [],
    "Location": null,
    "Country": null,
    "SourceContactId": "Contacts/00000000000000001-A",
    "DestinationContactId": "Contacts/0000000000000000004-A",
    "Roles": [
        1,
        100
    ],
    "JobId": "Jobs/0000000000000000153-A",
    "JobStartsOn": null,
    "JobEndOn": null,
    "@metadata": {
        "@collection": "Relationships",
        "Raven-Clr-Type": "Data.Contacts.Relationship, Data"
    }
}
```

And the following query:

```
var destinationContactIds = await (from r in DbSession.Relationships
	 where r.DestinationContactId == contactId && r.Roles.Any(rr => rr == RoleTypes.Employee)
	 select r.SourceContactId).ToArrayAsync(cancellationToken);

```
Or
```
var relationships = (from r in DbSession.Relationships
	 where r.DestinationContactId == contactId && r.Roles.Contains(RoleTypes.Employee)
	 select r.SourceContactId);
```

Where contactId = "Contacts/0000000000000000004-A"

I would expect that this record would be returned. It isn't. I get back a 0 length list result.

But nothing comes back.

Here's what it generated: (This has a more complex projection but same idea)

`{from 'Relationships'.Where(r => ((r.DestinationContactId == value(Api.Controllers.Contacts.ContactsController+<>c__DisplayClass34_0).contactId) AndAlso r.Roles.Contains(Employee))).Select(r => new <>f__AnonymousType13`2(r = r, employer = Load(r.SourceContactId))).Select(<>h__TransparentIdentifier0 => new ContactRefDto() {ContactType = <>h__TransparentIdentifier0.employer.ContactType, FirstName = <>h__TransparentIdentifier0.employer.FirstName, Id = <>h__TransparentIdentifier0.employer.Id, LastOrCompanyName = <>h__TransparentIdentifier0.employer.LastOrCompanyName, MiddleName = <>h__TransparentIdentifier0.employer.MiddleName}).Distinct()}`

It would appear that in this case RavenDB isn't translating the enum properly to the int that is stored in the database.

Using: 5.2.1 (docker)

**Comment by grisha-kotler** [comment]
Did you set the `SaveEnumsAsIntegers` to `true` in the `Conventions`?

**Comment by jhancock4d** [comment]
So, if it's set explicitly, then it works everywhere. If you don't set it, it appears that if there is a list of enums it is storing ints while looking for the string version.  This wasn't the case in 5.0, but appears to be the case in 5.2.  Regular property fields store as strings normally, just lists enums don't.  If you switch it to store ints, then it stores them everywhere and works as you'd expect.  One would presume that using ints instead of strings would be more performant so I'm fine with that but the odd behavior seems like a bug.

**Comment by grisha-kotler** [comment]
This works and stores strings
```
private class EnumAsInteger
{
    public string Id { get; set; }

    public List<Enum> MyEnum { get; set; }

    public enum Enum
    {
        Idle,
        Running
    }
}

using (var session = store.OpenAsyncSession())
{
    var user = new EnumAsInteger
    {
        MyEnum = new List<EnumAsInteger.Enum>
        {
            EnumAsInteger.Enum.Idle,
            EnumAsInteger.Enum.Running
        }
    };
    await session.StoreAsync(user);
    await session.SaveChangesAsync();
}
```

Can you submit a failing test?
