### ISSUE TITLE
.NetCore version 3.1.411 is not supported

### ISSUE THREAD

**Issue by Zevenberge** [ravendb/ravendb#12628]
Hey,

We are using the RavenDB testdriver (and RavenDB itself in a Docker container). We try and keep up to date with the package manager's updates. Recently, NetCore version 3.1.411 was released. Is it possible to bump the version number of the required .NetCore version?

It would be even better if the server and testdriver did not depend on a hardcoded (patch) version number, so that upgrades can be more seamless.

Thanks!

**Comment by ppekrol** [comment]
From: https://groups.google.com/g/ravendb/c/fsCHcnET_Y4/m/yh22h3v4CAAJ

> Hi,
> there is a possibility to use latest installed runtime, by setting 'null' in 'FrameworkVersion' of `ServerOptions` (https://ravendb.net/docs/article-page/4.2/csharp/start/test-driver#configureserver). This might be acceptable for your case (testing), but we would prefer you, our user, to make that call, because newer frameworks contains stability fixes, and what we think is more important, security fixes. So from our perspective this is prioritized first.
> If you want to have 'automatic' setup, then you can create an instance of 'ServerOptions' and read the value of a 'FrameworkVersion' property. Then you can download that runtime, unzip it and set it in 'ServerOptions.DotNetPath' programatically.
> The problem with using NuGet as a container for runtimes is that it needs to contain all of the runtimes for all of the platforms where .NET core can be used. Each runtime is 60mb+, so we are talking here about packages of 200mb+.

Note: latest versions also support `3.1.x` or `5.0.x` as a 'FrameworkVersion' and will look for latest runtime then.

**Comment by Zevenberge** [comment]
Awesome, thank you so much! This was exactly what we needed :)
