### ISSUE TITLE
RavenClient hangs on LoadAsync

### ISSUE THREAD

**Issue by kamilslusarczyk** [ravendb/ravendb#12652]
Hi,

This issue occurs for `C#`'s RavenDB.Client in version 5.1.7. Sometimes during execution of line as the one below code execution simply hangs forever. No exception, no response from that line.

`await _session.LoadAsync<SomeDao>(someDaoIds)`

I upgraded version of a nuget package but it didn't change a thing. DB server is in 5.1.5 version.

**Comment by ayende** [comment]
Any additional information you can give?
Specific document? Are you using the session in a multi threaded context?

**Comment by kamilslusarczyk** [comment]
I am injecting `IAsyncDocumentSession` through a constructor. It is correctly injected and works in other cases but sometimes it just freezes. No multi threaded setup, I think.

**Comment by ayende** [comment]
See who is injecting this. One reason you may see that is that this is used concurrently.
Other than that, do you have a way to reproduce?

**Comment by kamilslusarczyk** [comment]
I've changed it to synchronous session and it works fine. Not sure why, because we use both `IAsyncDocumentSession` and `IDocumentSession` in different layers without issues.

As for reproducing it - not really, unfortunately. Seems like case dependant on a usage in our solution..
