### ISSUE TITLE
[Feature request] Make patch queries strongly typed

### ISSUE THREAD

**Issue by AKlaus** [ravendb/ravendb#12650]
Just an idea. I leave it here for you to decide if it's any good.

**Idea**
Add a way to form a [patch request](https://ravendb.net/docs/article-page/latest/csharp/client-api/operations/patching/set-based) (that gets passed to `PatchByQueryOperation`) partially from strongly typed data (not just a string as it is now)

That would be used in this way
```csharp
var patchRequest = GetPatchQueryForIndex<Order, Orders_List>(
	o => o.ClientName == "Bob", 
	"o", 
	"o.Lines.forEach(line=> line.Discount = 0.3);"
);
store.Operations.Send(new PatchByQueryOperation(patchRequest));
```

With `GetPatchQueryForIndex()` implementation like

```csharp
string GetPatchQueryForIndex<T, TIndexCreator>(Expression<Func<T, bool>> whereExpr, string itemName, string updateCode) where TIndexCreator : AbstractIndexCreationTask, new()
{
	return $@"FROM INDEX '{new TIndexCreator().IndexName}' AS {itemName}
			  WHERE {ConvertLamdaWhereToString(whereExpr,itemName)}
			  UPDATE
			  {{
			 	{updateCode}
			  }}";
}
```

**Benefits**
 - reducing the area of hand-crafted strings with code down to just the JavaScript for updating an item;
 - less of syntax mix as `updateCode` would be 'almost' pure JavaScript.

**Comment by ayende** [comment]
Our expectation is that you'll usually build the query using `session.Query()`, to be honest. 

Something like:

```
    var index = GetIndexQuery(session.Query<PrimarySkills.Result, PrimarySkills>()
        .Where(result => result.SkillId == 1));

                    index.Query += @" update { 
for (var i = 0; i < this.Skills.length; i++) {
    this.Skills[i].IsPrimary = false
}
}";
var operation = store.Operations.Send(new PatchByQueryOperation(index));
```

**Comment by AKlaus** [comment]
It would be great to form them via `session.Query` but what `GetIndexQuery` method are you referring to? It seems that the magic is happening in there.

I can't find it in the docs or in the Client SDK code (there are some with that name but different parameters).
The [docs on Set Based Operation](https://ravendb.net/docs/article-page/5.2/csharp/client-api/operations/patching/set-based) show examples with hand-written  queries.

**Comment by ayende** [comment]
That is implemented as:

```
 public static IndexQuery GetIndexQuery<T>(IQueryable<T> queryable)
 {
     var inspector = (IRavenQueryInspector)queryable;
     return inspector.GetIndexQuery(isAsync: false);
 }
```

Sorry, forgot that it isn't available directly. 

My concern is mostly about what kind of API you'll have then.
