### ISSUE TITLE
Docker Ubuntu release for 5.2.2 missing

### ISSUE THREAD

**Issue by lahma** [ravendb/ravendb#12666]
Only Windows version seems to be there:

https://hub.docker.com/r/ravendb/ravendb/tags?page=1&ordering=last_updated&name=5.2.2

**Comment by gregolsky** [comment]
Hi,
Missing images were just published. Sorry for the inconvenience!
![image](https://user-images.githubusercontent.com/1541805/129718119-787c7a11-f2b6-45d0-9de5-846c221161b5.png)

**Comment by lahma** [comment]
Thanks for the quick action!
