### ISSUE TITLE
IsLoaded returns true for id that was missing (v5)

### ISSUE THREAD

**Issue by ryanheath** [ravendb/ravendb#12726]
With client v3 we have this code

```
if (session.Advanced.IsLoaded(obj.Id))
{
    session.Delete(obj);
}
```

v3 succeeds, but v5 fails when obj.Id was not loaded but missing in the session.

To fix it, we need to see if the obj.Id was missing.
[IsDeleted](https://github.com/ravendb/ravendb/blob/49086f551a2ec7349c0922f6ec96c189f94fb7a6/src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs#L392) is available but not through the interface.

Currently we fix it by trying to load the object, which works, but seems awkward.

```
if (session.Advanced.IsLoaded(obj.Id))
{
    var other = await session.LoadAsync<ObjectType>(obj.Id) // obj might be missing
    if (other != null)
    {
        session.Delete(obj);
    }
}
```

**Comment by ppekrol** [comment]
Hi @ryanheath 

We have a ticket to document behavior: https://issues.hibernatingrhinos.com/issue/RDoc-1944

I'm wondering if we should maybe rename that method to `IsTracked()` ? cc @ayende 
Or maybe introduce some out parameter indicating if it is a tracked entity or tracked missing id?

**Comment by ayende** [comment]
That was actually a change that was made because we have to track the missing values, otherwise `Load(foo)` will return null (after a request) and then `Load(foo)` will do the same.

Note that the same thing applies if you call `Delete()` on the document, it is still consider loaded.

**Comment by ppekrol** [comment]
Yes, but user does not know if entity is tracked because it exists and is loaded to session or that it is known missing one.

Was thinking of sth like this (draft naming):
```csharp
public bool IsTracked(string id, out TrackingType result);

enum TrackingType 
{
    None,
    Loaded,
    Missing
}
```

**Comment by ayende** [comment]
You can also check `IsDeleted`, which will be true for this scenario

**Comment by ryanheath** [comment]
Yes, IsDeleted would be a better choice, but it is not available through the interface, yet.

**Comment by ryanheath** [comment]
> Yes, but user does not know if entity is tracked because it exists and is loaded to session or that it is known missing one.
> 
> Was thinking of sth like this (draft naming):
> 
> ```cs
> public bool IsTracked(string id, out TrackingType result);
> 
> enum TrackingType 
> {
>     None,
>     Loaded,
>     Missing
> }
> ```

If you go this route, you might need TrackType.Deleted too?

**Comment by ayende** [comment]
Note that we don't distinguish between deleted and missing internally
