### ISSUE TITLE
A high level overview of the code would be nice

### ISSUE THREAD

**Issue by snuup** [ravendb/ravendb#12749]
a short readme for each project would be nice, explaining the project / assembly.

**Comment by ayende** [comment]
To learn about RavenDB from a user perspective: https://ravendb.net/learn/inside-ravendb-book
That will give you the proper grounding in how we designed RavenDB and the high level on its usage.

If you are interested in how it is implemented, see: 
* https://ayende.com/blog/posts/series/173859/the-design-of-ravendb-4-0
* https://ayende.com/blog/posts/series/179873/ravendb-4-0-unsung-heroes
* https://ayende.com/blog/posts/series/179873/ravendb-4-0

There are quite a bit of discussion on the internals on my blog, see:
* https://ayende.com/blog/posts/series/189665-C/ravendb-5-0
* https://ayende.com/blog/posts/series/188641-A/searching-through-text
* https://ayende.com/blog/posts/series/182756-C/ravendb-4-1-features
* https://ayende.com/blog/posts/series/180897/queries-in-ravendb


Details on the low level storage:
* https://ayende.com/blog/posts/series/176961/low-level-voron-optimizations
* https://ayende.com/blog/posts/series/175073/voron-internals
* https://ayende.com/blog/posts/series/175842/optimizing-read-transaction-startup-time
* https://ayende.com/blog/posts/series/175041/database-building-101
* https://ayende.com/blog/posts/series/174337/the-guts-n-glory-of-database-internals

**Comment by snuup** [comment]
I wondered what the Sparrow and Sparrow Server projects do and did not find something about it on your page.

**Comment by ayende** [comment]
Code separation for util functions that are required for both Voron and RavenDB projects, mostly.
