### ISSUE TITLE
Document Store is generating non-consecutive identity for new documents

### ISSUE THREAD

**Issue by KevinHu-au** [ravendb/ravendb#12752]
We have a legacy ASP.NET Web App (.NET Framework 4.6.2) with RavenDB 4.2.8. Recently the RavenDB had an issue when generating an identity for the new document.

As we need the identity for the new document to save the data to a SQL db (for reporting purpose), the app is generating the identity before saving the document to RavenDB. 

Below is the code for RavenDB client (3.5.8) to generate the identity:
```
var documentStore = new DocumentStore
 {
         ConnectionStringName = "RavenDBConnectionString"
};
var nextId = documentStore.DatabaseCommands.NextIdentityFor("StoreName");
```
In most of the case, it will generate consecutive values (For example: 1,2,3,.....1000). But recently, the code above will generate some random values which are causing the existing document overridden by the newly created documents.

**Comment by ayende** [comment]
Do you have anything that will reset the value? 
Did you restore from backup or something like that?

Is that something that you can reproduce?

**Comment by KevinHu-au** [comment]
Hi @ayende , Thank you for the response. I don't think the app has anything which might reset the value. And I cannot somehow to reproduce the issue.  But ​I would like to give some further details.

This issue only occurred on our UAT environment recently. It is good so far on the Production. Both UAT and Prod environments have been running for a couple years. We concern that this issue may happen on the Prod. That would a sever issue for the app. 

1.  The app has a couple data stores (one of main db store is called "CaseStore").
2. The app does have the set a SeedId to 1000 for the main db store ("CaseStore"). So the actual values for the document identities are 1000, 1001, 1002,....
3.  During the App_Start, an IDocumentStore instance is setup and register as a singleton. When setting up the IDocumentStore, the app checks the Next Identity to see if it is below then 1000. If that is the case, the app set the identity starting from 1000. After IDocumentStore instance is registered, an IDocumentSession instance is registered for the store based. Below is the code to setup the instance.
```
        public static ContainerBuilder Configure()
        {
                // Autofac container builder
                 var builder = new ContainerBuilder();
                 ...
                 builder.RegisterInstance(SetupRaven()).As<IDocumentStore>().SingleInstance();

                 builder.Register(c => c.Resolve<IDocumentStore>().OpenSession("CaseStore"))
                      .As<IDocumentSession>()
                      .Named<IDocumentSession>("cases")
                      .InstancePerLifetimeScope();       
                ....
         }

        private static IDocumentStore SetupRaven()
        {
            var documentStore = new DocumentStore
            {
                ConnectionStringName = "RavenDBConnectionString"
            };

             documentStore.Initialize();
            //For the other released data stores, the app is ensuring the store exists
            documentStore.DatabaseCommands.GlobalAdmin.EnsureDatabaseExists("PatientStore");
           documentStore.DatabaseCommands.GlobalAdmin.EnsureDatabaseExists("PcrDataStore");

            //Make sure the id for "CaseStore" starts from 1000 
            var nextId = documentStore.DatabaseCommands.NextIdentityFor("CaseStore");

            if (nextId < 1000)
            {
                documentStore.DatabaseCommands.SeedIdentityFor("CaseStore", 1000);
            }
            else
            {
                documentStore.DatabaseCommands.SeedIdentityFor("CaseStore", nextId - 1);
            }
            return documentStore;
        }

```
4.  When saving the document, the app is getting the next identity from the IDocumentSession instance (resolved from Autofac container).
```
     var nextId = _documentSession.Advanced.DocumentStore.DatabaseCommands.NextIdentityFor("StoreName");
```

**Comment by ayende** [comment]
`documentStore.DatabaseCommands.SeedIdentityFor("CaseStore", nextId - 1);`

what if you have two document stores that are running at the same time? You are likely to get into a situation where you'll have such a scenario, no?

**Comment by ayende** [comment]
The two doc stores may be from different devs?

**Comment by KevinHu-au** [comment]
The IDocumentStore is a singleton and the SeedIdentityFor() only runs when app starts up. But for different data stores (or database), the app is registering a seperate IDocumentSession.

```
            builder.Register(c => c.Resolve<IDocumentStore>().OpenSession("PcrDataStore"))
               .As<IDocumentSession>()
               .Named<IDocumentSession>("pcrRetrieval")
               .InstancePerLifetimeScope();
```

**Comment by ayende** [comment]
Are you using the same database from different devs? What happens when you have two devs starting up at the same time?

**Comment by KevinHu-au** [comment]
No. The UAT is just for the QA testers to have a test. We have a seperate Dev environment for developer test (apart from the developer's local development environment)

**Comment by KevinHu-au** [comment]
The UAT is almost a copy of production environment (both UAT and Prod are upgraded by Release pipeline). The only difference is the Prod is public-faced, and UAT is just internal QA team-faced.

**Comment by ayende** [comment]
What is the output of http://live-test.ravendb.net/admin/debug/cluster/history-logs on your instances?

**Comment by KevinHu-au** [comment]
Good question. Can you please give me more details about the steps to get the output for the UAT? Should I just open the link on the UAT environment? Thanks.

**Comment by KevinHu-au** [comment]
I cannot try at this moment. I have to wait till tomorrow morning (current the local time is 9:37 pm) to get a VPN access passcode from our IT infrastructure team.

**Comment by ayende** [comment]
Ping the endpoint `/admin/debug/cluster/history-logs` on your instance URL

**Comment by KevinHu-au** [comment]
Sure. Thanks @ayende . I will try it tomorrow morning and let you know what I find.

**Comment by KevinHu-au** [comment]
Hi @ayende. the endpoint on UAT is not found. Not sure if I missed anything.
Here is the Admin portal on the UAT RavenDB server.
![Screen Shot 2021-09-14 at 10 02 20 am](https://user-images.githubusercontent.com/8989917/133172530-67904bc1-979c-44ca-b7b6-3c3e2f96983e.png)
Here is the endpoint access.
![Screen Shot 2021-09-14 at 10 03 05 am](https://user-images.githubusercontent.com/8989917/133172567-e0e2710c-e61c-4fff-9372-07a866713a4d.png)

**Comment by ayende** [comment]
Hi, this isn't a 4.2 server, this is a 3.5 server, which is out of support at this point.
Note that a 4.2 client cannot talk to a 3.5 server.

**Comment by KevinHu-au** [comment]
Hey @ayende , The build number is #35281.
![Screen Shot 2021-09-14 at 6 39 36 pm](https://user-images.githubusercontent.com/8989917/133225412-936e9f63-af97-4140-adb8-48143e694610.png)

and the client package is 3.5.8
![Screen Shot 2021-09-14 at 6 42 26 pm](https://user-images.githubusercontent.com/8989917/133225595-315955ec-0776-438b-ab78-58ad313edfa8.png)

We haven't upgraded the environment for years.

**Comment by ayende** [comment]
Are you using a cluster in this environment? It is possible that you'll get a different value from different nodes.
Otherwise, we'll need to open a support call to investigate further and that requires an active support contract.

Beyond this, I would recommend moving to the 5.x release very strongly.

**Comment by KevinHu-au** [comment]
Thanks @ayende , I don't think we have a cluster for the environment. I will check with the team for the support contract.
