### ISSUE TITLE
Docker deployment with custom port

### ISSUE THREAD

**Issue by TheAsda** [ravendb/ravendb#12799]
# Description

There is a virtual machine deployed somewhere in the cloud. It has public ip and docker installed. I'm trying to deploy ravendb via docker but 8080 port is already in use. So i'm trying to change configuration so that ravendb could listen to another port and accept connections from public internet (Ports are opened).

# What i've tried

I tried to provide `ServerUrl` with `http://localhost:9600`, `http://0.0.0.0:9600`, `http://<public ip>:9600`. I also tried combinations of `ServerUrl` and `PublicServerUrl`. None of them worked.

Can anyone provide a way to deploy ravendb so that it could be reachable from internet with custom port?

**Comment by ayende** [comment]
Which port is taken, on the docker instance, or on the host machine?

**Comment by TheAsda** [comment]
I have traefik container that is listening 8080 port for it's ui

**Comment by ayende** [comment]
So what you need is to change the port that docker is mapping, you don't change the ravendb setting, but the docker one.
IIRC, it is something like `-p 8080:8080`, so you can change that to `-p 8080:9090` which will map the 8080 port on the docker container to port 9090 on your system.

**Comment by TheAsda** [comment]
I removed everything except for ports and mapped `8080:9600`. Now container does not even start, it fails with error `Bind for 0.0.0.0:8080 failed: port is already allocated`.

**Comment by TheAsda** [comment]
Oh god, for some reason i thought that value on the right is the one that is exposed from container 😡 The right configuration is `9600:8080`. Thanks for quick reply!
