### ISSUE TITLE
Unobserved ObjectDisposedException - DatabaseConnectionState

### ISSUE THREAD

**Issue by k-u-s** [ravendb/ravendb#12839]
When using inside [orleans](https://github.com/dotnet/orleans) their [SiloUnobservedExceptionsHandler](https://github.com/dotnet/orleans/blob/3.4.4/src/Orleans.Runtime/Utilities/SiloUnobservedExceptionsHandler.cs) catches exception mentioned in title. It happens pretty often (every 1-3 minutes) and usually there are around 5 log entries like below

Raven is only db used by server. Client was using PatchByQueryOperation(IndexQuery), long living IAsyncTimeSeriesSessionStreamRawResultOperations.StreamAsync, and other crud operations exposed by IAsyncDocumentSession

Unfortunately I was not able to reproduce on local machine. 
From my perspective it is not anything important since besides unnecessary logs it did not affect system in noticeable way.
Just reporting in case you find that interesting. 

Runtime versions: .net5
Orlenas Server version: 3.4.2
Client version: 5.2.1
Server version: 5.2.1

Example logs:

> {
>  "@t": "2021-10-13T01:42:11.7431298Z",
>  "@mt": "Exception remained UnObserved!!! The subsequent behavior depends on the ThrowUnobservedTaskExceptions setting in app config and .NET version.",
>  "@l": "Error",
>  "EventId": {
>    "Id": 100006
>  },
>  "SourceContext": "Orleans.Runtime.SiloUnobservedExceptionsHandler"
> }
> {
>  "@t": "2021-10-13T01:42:11.7431785Z",
>  "@mt": "Silo caught an unobserved exception thrown from context {Context}: {Exception}",
>  "@l": "Error",
>  "@x": "System.ObjectDisposedException: Cannot access a disposed object.\nObject name: 'DatabaseConnectionState'.",
>  "Context": null,
>  "Exception": "System.ObjectDisposedException: Cannot access a disposed object.\nObject name: 'DatabaseConnectionState'.",
>  "EventId": {
>    "Id": 100104
>  },
>  "SourceContext": "Orleans.Runtime.SiloUnobservedExceptionsHandler"
> }
> {
>  "@t": "2021-10-13T01:42:11.7432075Z",
>  "@mt": "Silo Caught an UnobservedTaskException event sent by [Id=1640871, Status=Faulted]. Exception = \nExc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a disposed object.\nObject name: 'DatabaseConnectionState'.)\nExc level 1: System.ObjectDisposedException: Cannot access a disposed object.\nObject name: 'DatabaseConnectionState'.",
>  "@l": "Error",
>  "EventId": {
>    "Id": 100005
>  },
>  "SourceContext": "Orleans.Runtime.SiloUnobservedExceptionsHandler"
> }

**Comment by ayende** [comment]
what is the full exception?

**Comment by k-u-s** [comment]
Unfortunately that how this handler formats those exception so I do not have it right now but will try to replaced it with different one to get it.

**Comment by k-u-s** [comment]
It looks like that after removing 

- PatchByQueryOperation(IndexQuery) (var o = await session.Advanced.DocumentStore .Operations.SendAsync(patchOperation); await o.WaitForCompletionAsync())
- IAsyncTimeSeriesSessionStreamRawResultOperations.StreamAsync (await asyncSession.Advanced.StreamAsync(query))

It stopped happening. That makes capturing it a little bit harder then I expected.

**Comment by ayende** [comment]
Did you not call `await DisposeAsync()`, maybe?

**Comment by k-u-s** [comment]
Removed code loked like:

```
        public async IAsyncEnumerable<Model> Get(....)
        {
            using var session = DocumentStore.OpenAsyncSession();
            var query = session.Query<Model>()
                .Where(....)
                ;
            await using var stream =  await session.Advanced.StreamAsync(query);
            while(await stream.MoveNextAsync()) 
                yield return stream.Current.Document;
        }
```

and in worker which was suppose to run indefinitely

```
                try
                {
                    var stream = Get(...);
                    await foreach (var x in stream)
                    {
                         ...
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, $"Error ...");
                }
```

So here is missing DisposeAsync()

Closing since it is not possible to replicate and most probably it was caused by missing Dispose


Thanks for help
