### ISSUE TITLE
Docker Ubuntu release for 5.1.11 missing

### ISSUE THREAD

**Issue by sergiomcalzada** [ravendb/ravendb#12907]
![image](https://user-images.githubusercontent.com/1726913/138724611-32285c50-3ea2-48a5-a250-ffe0e385f923.png)

**Comment by gregolsky** [comment]
Thanks for reporting. Should be available now.

![image](https://user-images.githubusercontent.com/1541805/138819198-8b291fbe-d5c8-4226-8a16-ce2fa332e98e.png)
