### ISSUE TITLE
How can get a gap between the date range?

### ISSUE THREAD

**Issue by MohMehrnia** [ravendb/ravendb#12957]
How can get gaps between the date range?

**Comment by haludi** [comment]
Hi,

Can you elaborate?

Best regards,
Igal

**Comment by MohMehrnia** [comment]
I have a time series dataset and I want to show the fragmentation of this data. My data must be saved minute by minute.

**Comment by haludi** [comment]
There is no efficient way to do that.
If you want to do the calculation on the server (again this is not efficient) you can use something similar to the above query:
```
declare timeseries ts(){
    from 'HeartRates'
}

declare function getGaps(tsResults){
    var gaps = []
    for (var i = 0; i < tsResults.Results.length - 1; i++ ){
        var gap = {};
        gap['From'] = tsResults.Results[i].Timestamp
        gap['To'] = tsResults.Results[i + 1].Timestamp
        gaps.push(gap)
    }
    
    return gaps;
}

from "Employees" where id () = 'employees/1-A' select getGaps(ts()) 
```

* You can create sample data and run this query in the studio to test it
