### ISSUE TITLE
Not able to delete revisions if revisions disabled

### ISSUE THREAD

**Issue by Yuzal** [ravendb/ravendb#13003]
for our GDPR process we automatically delete all revisions of a specific document.
But i noticed... it is not possible to delete available revisions while revisions for the database itself was deactived
it was a strange situation where we had to disable the revisions for a database but needed to keep already created revisions.

Is this an oversight/bug or how do i delete revisions of a specific document while the revisions are disabled?

**Comment by ayende** [comment]
I'm not sure that I'm following on what you mean? 

In general, there is no API for deleting revisions. That is required for audit purposes, you shouldn't be able to remove revisions from the system. You can define expiry policies, however.

**Comment by Yuzal** [comment]
a year ago i asked how i could delete specific revisions to satisfy gdpr standards:
https://groups.google.com/g/ravendb/c/GO05NZWMFhk/m/hUhW1AwHCQAJ

And this very endpoint is now throwing an exception while trying to delete revisions.

**Comment by ayende** [comment]
Okay, sorry, admin only endpoint, I forgot about that.
You can enable revisions, but set them as `0`, which will ensure that this will work, but no revisions will be created automatically.

**Comment by Yuzal** [comment]
Yeah this was the solution we used at the end.
I just wanted to report this behaviour because it seemed to me like a bug, not being able to delete available revisions while revisions are disabled.

**Comment by ayende** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-17494
