### ISSUE TITLE
Jepsen testing for correctness, safety, validity, and defaults

### ISSUE THREAD

**Issue by dumblob** [ravendb/ravendb#13218]
I wonder whether a third party has already checked the correctness, safety, validity, and defaults of RavenDB (especially with the Voron backend as that's what's being comercially available). If so, could you point me to the comprehensive results?

If not though, I'd strongly suggest asking [Jepsen](https://jepsen.io/ ) as the most famous and highly capable company to do the appropriate testing.

**Comment by ayende** [comment]
We have tested it using Jepsen, yes. You can find it here: https://github.com/ml054/jepsen

**Comment by dumblob** [comment]
Thanks! That looks like a good preparation for Jepsen actually testing your DB. Do you plan to contract with them (him?)?

The whole point of Jepsen is to (sometimes quite significantly) tailor the tests (esp. write new ones) to the whole setup, not just run the regular existing-so-far tests. This tailoring and checking the "big picture" is what makes Jepsen stand out IMHO.

**Comment by ayende** [comment]
We talked with Aphyr, and we have successfully run the test suite and found no issue. 

Going full bore on that isn't something that we are currently planning.

**Comment by dumblob** [comment]
Ah, ok. Do you run the Jepsen test suite regularly as part of release engineering?

**Comment by ayende** [comment]
This gets run whenever we make modifications to the cluster / raft implementation,yes.

**Comment by dumblob** [comment]
Hm, Jepsen is testing among other things also the defaults which presumably change much more often (any addition of a new configuration parameter is a change to defaults). But more importantly Jepsen adds new tests and even corrects old ones several times a year, so I'd expect the test suite to rune (much) more frequently.

But thanks anyway for the insights and undergoing this scrutiny and answering all my pesky questions :wink:.
