### ISSUE TITLE
Distributed transactions support

### ISSUE THREAD

**Issue by dumblob** [ravendb/ravendb#13215]
I'm a bit puzzled about the degree to which ravendb supports distributed transactions and what are the subtle properties and (dis)advantages. Could you elaborate on that a bit?

**Comment by ayende** [comment]
Distributed transactions in RavenDB are called Cluster Wide transactions, see the discussion on the current behavior here:
https://ravendb.net/articles/ravendb-5-2-simplifying-atomic-cluster-wide-transactions

They are run through the Raft cluster and ensured consistency of operations
