### ISSUE TITLE
Docker: RAVEN_ServerUrl can't be overwritten

### ISSUE THREAD

**Issue by YouriT** [ravendb/ravendb#13254]
Not sure why the [run-raven.sh](https://github.com/ravendb/ravendb/blob/v5.2/docker/ravendb-ubuntu/run-raven.sh) exports the `RAVEN_ServerUrl`?

This prevents us from changing the port it listens on. Only way around is to make a custom dockerfile just because of that line.

If no specific reason, mind switching to `[ -z "$RAVEN_ServerUrl" ] && export RAVEN_ServerUrl="http://$(hostname):8080"`?

**Comment by ayende** [comment]
A PR is welcome, of course.

Note that the general idea is that this is the _local_ port inside the docker container. You are free to expose that port on any other port for the rest of the world. That is why it is not configurable.

**Comment by YouriT** [comment]
Yes but when running into a docker-compose and you want to have same "network config" (name + port) resolution as in the cluster, it's easier to change the exposed port within the bridge network (= local port) rather than doing a host network and using the exposed port. I'll pack a PR :)

**Comment by gregolsky** [comment]
You can use RAVEN_ARGS="--ServerUrl YOURSERVERURL", but I think your idea with `-z` makes sense.

**Comment by YouriT** [comment]
> You can use RAVEN_ARGS="--ServerUrl YOURSERVERURL", but I think your idea with -z makes sense.

Good to know in the meantime this gets through thx!
