### ISSUE TITLE
RavenTestDriver on M1 Mac / .NET 6 ARM

### ISSUE THREAD

**Issue by kkuepper** [ravendb/ravendb#13250]
When trying to run the tests with the RavenTestDriver I'm getting the following error:
`Could not find a matching runtime for '5.0.12+'. Available runtimes: - 6.0.0`

I tried installing .net 5 in parallel to .NET 6 but I think that's not possible on an ARM Mac.
Running the web application and everything else is working fine. Only the RavenTestDriver is failing.

**Comment by haludi** [comment]
Hi,

You can also just download the DotNet DLLs and config the `DotNetPath`
(like it done in RavenDB embedded -
https://ravendb.net/docs/article-page/4.2/querying/server/embedded#serveroptions
)

public class TestDriverExampleTest : RavenTestDriver
{
    static TestDriverExampleTest()
    {
        ConfigureServer(new TestServerOptions
        {
            DotNetPath = "....",
        });
    }


Best regards,
Igal

**Comment by kkuepper** [comment]
Awesome! That works. Thanks a lot for your quick response.
