### ISSUE TITLE
PatchByQuery fails for Incremental Timeseries using Javascript (Illegal Tag)

### ISSUE THREAD

**Issue by korkmazozcan** [ravendb/ravendb#13311]
When trying to append an incremental timeseries via a PatchByQuery operation using Javascript syntax, for example,
```
from Users as u
update {
    timeseries(u,"INC:test").append(new Date("2021-12-16T08:15:43.0030000Z"), [1,1,1])        
}
```

This gives the following error:

```
 Tag of 'INC:test' time-series for document 'users/1' are illegal (Tag:)
```

If the incremental prefix is removed ( _INC:test_ => _test_), everything works as expected.

**Comment by shiranshalom** [comment]
Hi @korkmazozcan,
sorry for the inconvenience.
You can follow the issue progress on https://issues.hibernatingrhinos.com/issue/RavenDB-17717.

**_Note_** that for Incremental Time-Series you should use `increment` instead of `append`; after the fix merge your operation should be:
```
from Users as u
update {
    timeseries(u,"INC:test")**.increment**(new Date("2021-12-16T08:15:43.0030000Z"), [1,1,1])        
}
```

**Comment by korkmazozcan** [comment]
Hi,
The PR #13312 is not included in the 5.3.2 release, when will this feature be available?

**Comment by arekpalinski** [comment]
It will be available in the next RavenDB 5.3 build which is going to be released on end of January / beginning of February

**Comment by ayende** [comment]
s/July/Feb/

**Comment by korkmazozcan** [comment]
Thanks!
