### ISSUE TITLE
.NET 6 not supported in Raven.Embedded

### ISSUE THREAD

**Issue by BullFrog13** [ravendb/ravendb#13405]
Nuget package does not have the latest support of .NET 6 added previously. The latest version in nuget is  "5.0.13+" instead of "6.0.1".

Having issues upgrading projects to .NET 6.

**Comment by BullFrog13** [comment]
![image](https://user-images.githubusercontent.com/14280303/148322143-4cf00afb-1f77-4f80-b0bb-abd2b4bacd99.png)

**Comment by BullFrog13** [comment]
![image](https://user-images.githubusercontent.com/14280303/148325261-4ff877ed-949d-44f0-8adc-94eda280f3b0.png)

**Comment by BullFrog13** [comment]
![image](https://user-images.githubusercontent.com/14280303/148325280-634469bc-9fbd-4b3e-83ad-3b3ef793fe21.png)

**Comment by ayende** [comment]
The RavenDB Client is supported for 6.0, but only the next stable release will be fully supported on the server / embedded for 6.0

**Comment by BullFrog13** [comment]
Thanks, @ayende! Do you know approx. when the next release is going to happen?

**Comment by ayende** [comment]
Week or so

**Comment by BullFrog13** [comment]
Great, thanks
