### ISSUE TITLE
RawQuery not returning all matching documents

### ISSUE THREAD

**Issue by mgnoonan** [ravendb/ravendb#13444]
I'm having an issue that seems like a timing issue but I've not been able to resolve it. I am running a document upload batch process and when the batch finishes it will export the matching documents to another database. Each document is tagged with the RunId, so I can easily query for the documents processed in the batch run.

```cs
public List<T> GetExportDocuments<T>(string collectionName, string hostId, Guid runID)
{
    string sqlQueryText = $"from Items where RunId = '{runID}' and Attributes.HostId = '{hostId}'";

    return GetDocuments<T>(collectionName, sqlQueryText);
}

public List<T> GetDocuments<T>(string collectionName, string sqlQueryText)
{
    Log.Information("Query: {query}", sqlQueryText);

    using (IDocumentSession session = _store.OpenSession(database: collectionName))
    {
        var list = session.Advanced.RawQuery<T>(sqlQueryText).ToList();
        Log.Information("Query: ({count}) documents returned", list.Count);
        return list;
    }
}
```

Not every time, but sometimes the number of documents that are returned from the `RawQuery` are one short of the actual total:
![image](https://user-images.githubusercontent.com/3255096/149056040-f26af6d0-94ff-48bb-a779-bc5c013fea26.png)

If I take the query and paste it into RavenDB Studio, I get the correct number of documents back, but the target export database is definitely short by one document. 

Am I missing a step to flush a buffer somewhere?

**Comment by haludi** [comment]
Hi,

The indexing is a background process so it may get stale results.
You can wait for non-stale results -
https://ravendb.net/docs/article-page/5.0/NodeJs/indexes/stale-indexes.

var list = session.Advanced.RawQuery<T>("sqlQueryText")
    .WaitForNonStaleResults()
    .ToList();

Best regards,
Igal

**Comment by ayende** [comment]
In addition, please use `AddParameter`, instead of string concat

**Comment by mgnoonan** [comment]
Thanks! I will update my code and report back the results.

@ayende the parameters are never user input, so I did not initially take this step, but your point is excellent so I will do that. 😄

**Comment by mgnoonan** [comment]
Looks great, everything matches! Thanks!
![image](https://user-images.githubusercontent.com/3255096/149401813-26ad3ab3-d365-4801-9d92-4b4b9bb41815.png)

Closing.
