### ISSUE TITLE
Cannot query properties with type char in LINQ-based queries

### ISSUE THREAD

**Issue by feO2x** [ravendb/ravendb#13473]
I just created a small sample project that I use to solve [Wordle](https://www.powerlanguage.co.uk/wordle/) puzzles.

I've imported all five-letter words of an [list of English words](https://github.com/dwyl/english-words/) to RavenDB using the following entity:

```csharp
public class FiveLetterWord
{
    public string Id { get; init; } = string.Empty;
    public char Character1 { get; init; }
    public char Character2 { get; init; }
    public char Character3 { get; init; }
    public char Character4 { get; init; }
    public char Character5 { get; init; }
}
```

The database now has about 15,000 entries and I wanted to write a simple LINQ-based query to filter all words:

![About 15000 Words in Database](https://user-images.githubusercontent.com/7884158/149614155-4cc44f22-164c-4084-993f-a0cad959eeb3.png)

However when I want to query with `Where`, the result is always empty:

![Words collection always empty when querying char properties](https://user-images.githubusercontent.com/7884158/149614213-2a2711f5-a2fd-4eb5-b59f-0d346c694158.png)

(And yes, there are words whose first character is 'b').

When I change the properties of the `FiveLetterWord` entity to type `string`, I can query them just fine: 

![Query successful with string properties](https://user-images.githubusercontent.com/7884158/149614333-f968e694-defb-4ada-8143-1081c16d014f.png)

Repro can be found here: https://github.com/feO2x/WordleWords

RavenDB 5.3.2 both on the server and the client
.NET 6.0 Preview 6.0.200-preview.21617.4
Xunit 2.4.1 executed in JetBrains Rider 2021.3.2
Windows 10 Pro 21H2 19044.1466

**Comment by ayende** [comment]
Well, that is _interesting_. Here is the root cause of the problem:

```
from 'FiveLetterWords' where Character1 = $p0 {"p0":98}
```

**Comment by ayende** [comment]
Okaaaay.... 
That might be a C# compiler bug, see ( https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEB0BhA9gG2wUwGMAXAS0wDsBnAblgWQgBZa4kVUAZE8gRxboDMyMInSIA3rETTEUmSCHhEASSJ4AthORCCACwCGAJ0QA1fdmqIAvnOm3tKgIoBXPIYCe+gEb4APKo0APkQAWQAKZRc3Tx88fzV1YJIEygBKCXsZZAB2RGSNSlQAdV03PDCADwBeQIrUM2xEKqrEAHIvVtSWLJsYKyA= ):

```
items.Where(x=>x.Val == 'b');
```

Is compiled to:

```
       ParameterExpression parameterExpression = Expression.Parameter(typeof(Item), "x");
        BinaryExpression body = Expression.Equal(Expression.Convert(Expression.Field(parameterExpression, FieldInfo.GetFieldFromHandle((RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/)), typeof(int)), Expression.Constant(98, typeof(int)));
        ParameterExpression[] array = new ParameterExpression[1];
        array[0] = parameterExpression;
        return Queryable.Where(items, Expression.Lambda<Func<Item, bool>>(body, array));
```

Note that it uses `typeof(int)` as the type, and the constant is 98.

**Comment by feO2x** [comment]
Interesting - seems that the LinqToDb team also stumbled upon this. And if I understood correctly, if I wouldn't have used a constant literal, it should have worked OK.

**Comment by ayende** [comment]
Yes, that is likely the root issue.
