### ISSUE TITLE
librvnpal on M1 Mac

### ISSUE THREAD

**Issue by awyl** [ravendb/ravendb#13626]
I was trying to run some unit tests to make sure our code does not break after updating to `5.3.100`.  I used `RavenDB.TestDriver`, on M1 Mac.  It is complaining about `librvnpal`.

## Issue 1, wrong file name.
It is trying to load `liblibrvnpal.mac.x64.dylib` instead of `librvnpal.mac.x64.dylib`.

> System.DllNotFoundException: Unable to load shared library 'librvnpal.mac.x64.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibrvnpal.mac.x64.dylib, 0x0001): tried: 'liblibrvnpal.mac.x64.dylib' (no such file), '/usr/local/lib/liblibrvnpal.mac.x64.dylib' (no such file), '/usr/lib/liblibrvnpal.mac.x64.dylib' (no such file), '/Users/awyl/Codebase/nyccom/test/RavenDb.Tests/bin/Debug/net6/RavenDBServer/**liblibrvnpal.mac.x64.dylib**' (no such file), '/usr/local/lib/liblibrvnpal.mac.x64.dylib' (no such file), '/usr/lib/liblibrvnpal.mac.x64.dylib' (no such file)

## Issue 2, as the filename suggested it is not arm64 binary
I copied `librvnpal.mac.x64.dylib` to `liblibrvnpal.mac.x64.dylib` in `bin` folder for the TestDriver to find file.

>  ---> System.DllNotFoundException: Unable to load shared library 'librvnpal.mac.x64.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibrvnpal.mac.x64.dylib, 0x0001): tried: **'liblibrvnpal.mac.x64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))**, '/usr/local/lib/liblibrvnpal.mac.x64.dylib' (no such file), '/usr/lib/liblibrvnpal.mac.x64.dylib' (no such file), '/Users/awyl/Codebase/nyccom/test/RavenDb.Tests/bin/Debug/net6/RavenDBServer/liblibrvnpal.mac.x64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/liblibrvnpal.mac.x64.dylib' (no such file), '/usr/lib/liblibrvnpal.mac.x64.dylib' (no such file)

**Comment by ppekrol** [comment]
Hi @awyl 

Thanks for reporting this. We are looking into the x64 problem and this should be handled soon. The M1 compatibility is also on our roadmap, but I cannot give you any ETA here.

As a workaround I would suggest using Docker for the time being.

**Comment by kramnos** [comment]
I'm also experiencing this issue on an M1 Mac. Oddly, downgrading to version `5.2.6` of `RavenDB.Client` appeared to fix the problem for me.

**Comment by ppekrol** [comment]
@SourceStudio this is due to lack of native Zstd library for that platform. As a workaround you can disable compression in DocumentStore.Conventions.DisableTcpCompression.

We will add support that later on, for now we have added a check for MacOS to assert if compression should be used or not.
PR: https://github.com/ravendb/ravendb/pull/13796

**Comment by kramnos** [comment]
I've updated to version `5.3.100` of `RavenDB.Client`, but this exception now appears to be thrown when executing any query against the database (_regardless_ of whether `DisableTcpCompression` is set to true or not):

```
System.ArgumentException: Type 'System.String' does not have a default constructor (Parameter 'type')
   at System.Linq.Expressions.Expression.New(Type type)
   at Sparrow.Json.JsonDeserializationBase.GenerateJsonDeserializationRoutine[T]() in C:\Builds\RavenDB-Stable-5.3\53004\src\Sparrow\Json\JsonDeserializationBase.cs:line 45
```

This can be reproduced on an M1 Mac using (for example) the following code:

```cs
using Raven.Client.Documents;
using Raven.Client.ServerWide.Operations;

var documentStore = new DocumentStore
{
    Urls = new[] { "http://localhost:8080" },
    Database = "database",
};
documentStore.Initialize();

var buildNumber = await documentStore.Maintenance.Server.SendAsync(new GetBuildNumberOperation());

Console.WriteLine(buildNumber.FullVersion);
```

**Comment by ayende** [comment]
Hi,

This is really strange, the error is correct, in the sense that string has no empty ctor, but it also shouldn't be in any way different from the rest of the systems we run on.

Can you share the full error stack ? Including what generated this?
We don't have a M1 to debug this at the moment, we are waiting for it to arrive, so I'm afraid that I can't tell more at this point in time.

**Comment by kramnos** [comment]
Apologies, I've only just found the time to look into this.

Version `5.3.101` of `RavenDB.Client` has suppressed the `DllNotFoundException` and correctly disables TCP compression as a result. The `ArgumentException` I referred to above was actually being thrown silently - it was my debugger that was picking it up as I had it configured to break on all exceptions. So there isn't necessarily a problem per se, as execution now appears to continue unabated, but might possibly indicate an underlying problem, so probably worth noting regardless.

For references, these two exceptions are now silently thrown in sequence when executing the code above:

### DllNotFoundException (which suppresses TCP compression in `DocumentConventions`)

```
System.DllNotFoundException: Unable to load shared library 'libzstd.mac.x64.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibzstd.mac.x64.dylib, 0x0001): tried: 'liblibzstd.mac.x64.dylib' (no such file), '/usr/local/lib/liblibzstd.mac.x64.dylib' (no such file), '/usr/lib/liblibzstd.mac.x64.dylib' (no such file), '/Users/markallison/Projects/Temp/RavenDBTest/RavenDBTest/bin/Debug/net6.0/liblibzstd.mac.x64.dylib' (no such file)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at Sparrow.Utils.DynamicNativeLibraryResolver.Resolver(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath) in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow\Utils\DynamicNativeLibraryResolver.cs:line 63
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Sparrow.Utils.ZstdLib.ZSTD_compressBound(UIntPtr srcSize)
   at Sparrow.Utils.ZstdLib.GetMaxCompression(Int32 size) in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow\Utils\ZstdLib.cs:line 51
   at Raven.Client.Documents.Conventions.DocumentConventions..cctor() in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Client\Documents\Conventions\DocumentConventions.cs:line 159
```

### ArgumentException (which is caught within `GenerateJsonDeserializationRoutine`)

```
System.ArgumentException: Type 'System.String' does not have a default constructor (Parameter 'type')
   at System.Linq.Expressions.Expression.New(Type type)
   at Sparrow.Json.JsonDeserializationBase.GenerateJsonDeserializationRoutine[T]() in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow\Json\JsonDeserializationBase.cs:line 45
```

**Comment by ayende** [comment]
For both of those issues, this is handled internally and shouldn't be a problem for your code / usage.
