### ISSUE TITLE
[WPF C#] Incompatibility : RavenDB and Dynamic LINQ Library

### ISSUE THREAD

**Issue by 3threeFX** [ravendb/ravendb#13666]
I use Ravendb Embedded v5.3 in .Net6 WPF [C#] with[ Dynamic LINQ Library](https://dynamic-linq.net/) ... before using Ravendb I used [EF Core+SQLite](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite/) and the code works fine without any errors or exceptions but after migrating to Ravendb and integrating all DBs in Raven {With a little change in connecting (dbContext EF Core & ...)} it seems Ravendb is Incompatible with System.Linq.Dynamic.Core or Or I'm wrong! ...

I got the following exceptions : (And it is not limited to these cases )

> System.NotSupportedException: 'Could not understand expression: from 'Symbols'.Select(Param_0 => new {symbol_type = Param_0.symbol_type}).Distinct().Where(Param_1 => Not(IsNullOrWhiteSpace(Param_1.symbol_type))).OrderBy(Param_2 => Param_2.symbol_type).Select(Param_3 => Param_3.symbol_type)'
NotSupportedException: Method not supported: IsNullOrWhiteSpace

![Screenshot 2022-02-18 134536](https://user-images.githubusercontent.com/63404512/154665591-d044e566-f04e-4c72-9920-2ddd294977a3.png)

> System.InvalidCastException: 'Unable to cast object of type 'Raven.Client.Documents.Session.DocumentQuery`1[<>f__AnonymousType0`1[System.String]]' to type 'Raven.Client.Documents.Session.IDocumentQueryBase`1[System.String]'.'

![Screenshot 2022-02-18 134734](https://user-images.githubusercontent.com/63404512/154665608-b4085623-3f49-4bb1-aed5-53ff719dd089.png)

> System.NotSupportedException: 'Could not understand expression: from 'Symbols'.Select(Param_0 => new {asset_id_base = Param_0.asset_id_base}).Distinct().Where(Param_1 => Param_1.asset_id_base.ToUpper().StartsWith("ذ")).OrderBy(Param_2 => Param_2.asset_id_base).Select(Param_3 => Param_3.asset_id_base)'
NotSupportedException: Cannot understand how to translate method 'ToUpper' of 'System.String' type. Param_0.asset_id_base.ToUpper()

![Screenshot 2022-02-18 140212](https://user-images.githubusercontent.com/63404512/154666041-5ed3b8a2-1dc2-4b97-9d1c-50a9f6d37939.png)

It seems all methods like ToUpper, [String.IsNullOrWhiteSpace(String)](https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace), ... is not defined or can't translate for Ravendb also cast result object as string List is a problem now :(

**Comment by ayende** [comment]
I assume that the output of `DynamicLinq` isn't matching what we are expecting. But in general, if you want to build queries dynamically with a great degree of freedom, we offer a dedicated API for that.

Wouldn't be able to tell much without having code to reproduce this issue.

Your query could be expressed more easily with the `DocumentQuery` API, like so:

```
var q = session.Advanced.DocumentQuery<Symbol>();
foreach(var pair in newDictionary)
{
    // matches default to case insensitive in RavenDB
    q.WhereEquals(pair.Key, pair.Value);
}
```

It will also have better performance, see the documentation about the API here:
https://ravendb.net/docs/article-page/5.3/Csharp/client-api/session/querying/document-query/what-is-document-query


https://ravendb.net/docs/article-page/5.3/Csharp/indexes/querying/query-vs-document-query

**Comment by 3threeFX** [comment]
Thanks, @ayende, This is bad news for me because [Dynamic LINQ Library](https://dynamic-linq.net/) is a powerful and flexible tool ...
I think in your code snippets, the correct correspondence has not been established : (to insure comparing strings is case-insensitive)

in classic Linq:
```
string someCity = "Paris" ;
var result = context.Customers
          .Where(c => c.City.ToUpper() == someCity.ToUpper() )
```

is equal to [Dynamic Linq]:
```
string someCity = "Paris" ;
string fieldName = "City";
var result = context.Customers
          .Where(String.Format("{0}.ToUpper().Equals(\"{1}\")", fieldName , someCity.Value.ToUpper()));
```

but It is obvious that in DocumentQuery, the WhereEquals method is Not equivalent to them and It does not have the same output (Due to the Case sensitivity): 
```
var result = session.Advanced.DocumentQuery<Customers>()
                                                  .WhereEquals(c.City, someCity);
OR Dynamic term
                                                  .WhereEquals(fieldName , someCity);
```

we don't have any access to the instance value... just pass the field name of the entity.
Although as you know usually recommended  to use InvariantCultureIgnoreCase instead of ToUpper for case-insensitive string comparisons:
```
var result = context.Customers.Where(c => String.Equals(c.City, 
                                  someCity , 
                                  StringComparison.InvariantCultureIgnoreCase) );
```
that can easily change to dynamic Linq like this :

```
 .Where(String.Format("String.Equals( {0},\"{1}\"
                            ,StringComparison.InvariantCultureIgnoreCase)", fieldName , someCity ));
```

in this case What's the alternative for case-insensitive string comparisons dynamically in Ravendb DocumentQuery API? 

Also these Scenarios :

### Case 1:

Linq : 
`result.Select(x => new { x.City });`

is equivalent in Dynamic Linq to:
```
string columnName = "City" ;
result.Select(String.Format("new {{{0}}}", columnName))
```

in DocumentQuery ?!? :
```
string columnName = "City" ;
result.SelectFields<string>(columnName) ?!?!
```

this worked! but I think something was **wrong** because It was done in a **longer time** than similar operations (select one column and distinct ) in **SQLite**  and the lag was noticeable in combo boxes. (because u said It will also have better performance In comparison with EF and ...)

this snippet takes 3.25 seconds : (250K samples select and distinct to 7 values)
```
  List<string> resultList = new List<string>();
            using (IDocumentSession session = DocumentStoreHolder.Store.OpenSession(dbName))
            {
                var result = session.Advanced.DocumentQuery<Symbol>();
                resultList = result.SelectFields<string>(columnName)
                                    .Distinct()
                                    .OrderBy(columnName)
                                    .ToList();         
            }
```
but in SQLite, This process takes **less than a second**! I'm a newbie in Ravendb... Did I miss something that caused performance has dropped so much??

### Case 2:

Linq : 
`.Where(c =>!string.IsNullOrWhiteSpace(c.City) )`

Dynamic Linq:
```
string columnName = "City" ;
 .Where(String.Format("!string.IsNullOrWhiteSpace({0})", columnName))
```

in DocumentQuery perhaps ?!? :
`.WhereNotEquals($"string.IsNullOrWhiteSpace({columnName})",true)`

???????? 

unfortunately, didn't work :( I think it can Be semi-equated with : 
```
    .Advanced()
    .Not()
    .OpenSubclause()
    .WhereEquals(columnName, null)
    .AndAlso()
    .WhereEquals(columnName, " ")

or : 

     .WhereNotEquals(columnName, null)
      .AndAlso()
     .WhereNotEquals(columnName," ")
```

but not in the right way I think!

**Comment by grisha-kotler** [comment]
- Case 1 - It might not be efficient for large sets of data due to the need to scan all of the index results in order to find all the unique values. You'll get much better results with a map-reduce index.

See the Performance section:
https://ravendb.net/docs/article-page/4.2/Csharp/indexes/querying/distinct#querying-distinct

- Case 2 - What was the result of the last query?

**Comment by 3threeFX** [comment]
Thanks for your response @grisha-kotler 
In case 1 According to your answer is there a dynamic solution like :

```
var numberOfCountries = session
    .Advanced
    .DocumentQuery<dynamic_mapReduce.Result, dynamic_mapReduce>()
    .Count();
```
that dynamic_ mapReduce field referenced to : 

> Order_Countries ,
> Order_Cities ,
> Order_Districts 
> or ... 

and we pass this as an argument to query and build map-reduce index class for each of them?? or not?

for case 2 as you know String.IsNullOrWhitespace(string value) returns true if the string is null, empty, or contains only whitespace characters such as a space or tab and that is similar to the following code, except that it offers superior performance:[due to[ this ref](https://stackoverflow.com/questions/18710644/difference-between-isnullorempty-and-isnullorwhitespace-in-c-sharp)]

`return String.IsNullOrEmpty(value) || value.Trim().Length == 0;`

As you see in the snippet code I just checked null and whitespace not empty or multi-space like "  " or "          &nbsp; &nbsp; &nbsp; &nbsp;" and so on ...
Although the result here seems acceptable, as I said before it will not necessarily be the right answer. (Regardless of performance and execution speed)
```
     .WhereNotEquals(columnName, null)
      .AndAlso()
     .WhereNotEquals(columnName," ")
```
