### ISSUE TITLE
AggressiveCache() much slower in 5.3.100

### ISSUE THREAD

**Issue by elitastic** [ravendb/ravendb#13725]
The first call to `DocumentStore.AggressiveCache()` is very slow in current Raven DB 5 version compared to version 5.2.2.

It only occurs when using a real (not in memory) document store. Please have a look at the unit test pasted below.

`store.AggressiveCache()` takes about 30ms in version 5.2.2, and about 2'500ms since version 5.2.3.

Could you please check that? Thank you.

```
using System;
using System.Diagnostics;
using Raven.Client.Documents;
using Raven.TestDriver;
using Xunit;

namespace RavenUnitTest
{
    public class RavenUnitTests : RavenTestDriver
    {
        [Fact]
        public void Test()
        {
            using (var store = UseRealDocumentStore())
            {
                var sw = Stopwatch.StartNew();
                using (store.AggressivelyCache())
                {
                }

                sw.Stop();

                Console.WriteLine($"AggressivelyCache took {sw.ElapsedMilliseconds:N0}");
            }
        }

        private IDocumentStore UseRealDocumentStore()
        {
            var store = new DocumentStore
            {
                Database = "[DATABASE]",
                Urls = new[]
                {
                    "http://localhost:8081"
                }
            };

            store.Initialize();

            return store;
        }
    }
}
```

**Comment by omerlewitz** [comment]
Hi @elitastic,
I'm looking into it.

**Comment by omerlewitz** [comment]
HI @elitastic,

I checked again the time differences between the versions and the difference is around `20ms`
I'm attaching my test.

```
    [Fact]
    public void Test()
    {
        using (var server = GetNewServer(new ServerCreationOptions
               {
                   RunInMemory = false,
               }))
        using (var store = GetDocumentStore(new Options
               {
                   Server = server,
                   RunInMemory = false,
               }))
        {
            var sw = Stopwatch.StartNew();
            using (store.AggressivelyCache())
            {
            }

            sw.Stop();
            Console.WriteLine($"AggressivelyCache took {sw.ElapsedMilliseconds:N0}");
        }
    }
```

**Comment by elitastic** [comment]
@omerlewitz What do you do within `GetNewServer()`?

When you look at my initial test (using a REAL document store) you'll see that you'll get much different times.

(about 30ms in version 5.2.2, and about 2'500ms since version 5.2.3.)

And yes, it's only the first call to `AggressivelyCache()`, but anyway, it was much faster in 5.2.2 than it is in 5.2.3 and newer.

Could you please check that again? As we deploy every night, it causes a first slow response in production every morning to the first user connecting to our system.

**Comment by ayende** [comment]
Are you _reusing_ the document store? Where is your database located (local, remote, etc) ?

**Comment by elitastic** [comment]
@ayende What do you mean by "reusing"?

I use any database of a "local" RavenDb server instance (installed on local Windows machine) without any other client connections.

If you try to run the unit test from my first post, I'm pretty sure you'll be able to reproduce the issue.

To summarize:
First call to store.AggressiveCache() takes about 30ms in version 5.2.2, and about 2'500ms since version 5.2.3.

**Comment by ayende** [comment]
I mean, are you creating a `new  DocumentStore` instance per call, or are you using the same one (which you should).

Your numbers are also not something that we were able to reproduce. 
If you are calling this:

`using (var store = UseRealDocumentStore())` each time, then you are creating a new instance.
If you are running against a real database (as the code seems to imply), ensure that the `UseRealDocumentStore` returns the same isntance all the time.

Then the call to `AggressiveCache()` establish the very first connection, which is costly.

We made a change there, is to fix a race condition where you won't get an aggressive cache update in some cases because the changes connection wasn't established yet, so now we wait to the actual connection before proceeding. 

You can time it using:

```
  var sw = Stopwatch.StartNew();
                using (store.AggressivelyCache())
                {
                }

                sw.Stop();

// first time - establish connection

sw = Stopwatch.StartNew();
                using (store.AggressivelyCache())
                {
                }

                sw.Stop();
// second time - should be *fast*
```

Note that the 2.5 seconds is _really_ high regardless on a local instance, what happens if you simply time a `session.Load` ?

**Comment by elitastic** [comment]
I did some further analysis with the following setup:

- Windows 10 PC
- RavenDB running locally as a service (installed via setup-as-service.ps1)
- This settings.json config
  ```conf
  {
    "DataDir": "RavenData",
    "License.Eula.Accepted": true,
    "Setup.Mode": "Unsecured",
    "Security.UnsecuredAccessAllowed": "PublicNetwork",
    "ServerUrl": "http://127.0.0.1:8080",
    "ServerUrl.Tcp": "tcp://127.0.0.1:38888"
  }
  ```
---

Now I can replicate the following scenarios *consistently* with my Unit Test described in my first post on *different PCs* with the same setup:

#### Scenario 1
- *ServerUrl* (in settings.json) is set to http://127.0.0.1:8080
- *DocumentStore URL* is set to http://localhost:8080

**Result:** First AggressivelyCache()-Call takes **≈ 4500ms**

#### Scenario 2
- *ServerUrl* (in settings.json) is set to http://127.0.0.1:8080
- *DocumentStore URL* is set to http://127.0.0.1::8080

**Result:** First AggressivelyCache()-Call takes **≈ 300ms**

#### Scenario 3
- ServerUrl (in settings.json) is set to http://localhost:8080
- *DocumentStore URL* is set to http://localhost:8080

**Result:** First AggressivelyCache()-Call takes **≈ 300ms**

#### Scenario 4
- ServerUrl (in settings.json) is set to http://localhost:8080
- *DocumentStore URL* is set to http://127.0.0.1:8080

**Result:** First AggressivelyCache()-Call takes **≈ 300ms**

---

I don't think that **Scenario 1** is the expected behaviour? I was thinking that there could be some timeout the request is running into as the delay is almost always exactly the same.

**Comment by ayende** [comment]
Can you run `nslookup localhost` ?

On my end, we get:

```
>  nslookup localhost

Name:    localhost
Addresses:  ::1
          127.0.0.1
```

And that is _important_, note that `::1` is there first? What I think is happening is that you are running in IPv6 vs IPv4 mix.
Basically, with `localhost` you have both addresses, but if you bind to `127.0.0.1` you are bound only to IPv4. That means that on connection, we first try the `::1` and only after timeout we'll try the `127.0.0.1`.

**Comment by elitastic** [comment]
Is it a requirement of RavenDb that the corresponding DNS server must return the loopback address for localhost?

The output below is from my computer at work:

```
>   nslookup localhost
Server:  UnKnown
Address:  192.168.200.10

*** localhost wurde von UnKnown nicht gefunden: Non-existent domain.

>   ping localhost

Ping wird ausgeführt für MACHINE-NAME [::1] mit 32 Bytes Daten:
Antwort von ::1: Zeit<1ms
Antwort von ::1: Zeit<1ms
```

I tried the same on my private windows computer at home where DNS queries are forwarded to my internet provider. There I got the same non-existent domain response:

```
>   nslookup localhost
Server:  UnKnown
Address:  192.168.0.254

*** localhost wurde von UnKnown nicht gefunden: Non-existent domain.
```

**Comment by ayende** [comment]
Is that the _full_ output of `nslookup` ?  Note that for `ping`, it used IPv6 to connect, so that supports my theory.

There is no requirement on the loopback device, no, but I do wonder what it will resolve to.

In PowerShell, what do you get from:

```
Resolve-DnsName localhost

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
localhost                                      AAAA   1200  Question   ::1
localhost                                      A      1200  Question   127.0.0.1
```

**Comment by elitastic** [comment]
Yes, this is the full output.

Below the desired powershell output:

```
Resolve-DnsName localhost                                                                    
Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
localhost                                      AAAA   1200  Question   ::1
localhost                                      A      1200  Question   127.0.0.1
```

**Comment by ayende** [comment]
Okay, so that match my expectation, you are first trying to connect to IPv6, then to IPv4, which is causing the slowdown.
See: https://en.wikipedia.org/wiki/Happy_Eyeballs

You should probably ensure that they are matching, which is the simplest way to resolve the issue.
Note that this is happening at a level below RavenDB, directly at the network stack

**Comment by elitastic** [comment]
OK, we'll change the document store url, thanks very much for your help.

I'm still a little surprised that it only affects (first) calls to `store.AggressivelyCache()`. Calls to `store.Initialize()` or `session.Load()` are always fast (even the first ones), regardless of whether the url is set to localhost or 127.0.0.1.

**Comment by ayende** [comment]
I agree, on our end, we are seeing < 5 ms for those times.
It might be worth it to run your scenario with a profiler like `dotTrace`. I'm fairly certain that this is probably something like the localhost issue, environment related.
