### ISSUE TITLE
IAsyncAdvancedSessionOperations has a smaller set of operations than IAdvancedSessionOperations

### ISSUE THREAD

**Issue by adambajguz** [ravendb/ravendb#13749]
Hi, I've found that ` IAsyncAdvancedSessionOperations ` has a smaller set of operations than `IAdvancedSessionOperations`, which is a strange API decision for me, e.g. `IAsyncAdvancedSessionOperations` does not contain:

- `void AddOrPatch<T, TU>(string id, T entity, Expression<Func<T, TU>> path, TU value);`
- `void AddOrPatch<T, TU>(string id, T entity, Expression<Func<T, List<TU>>> path, <Func<JavaScriptArray<TU>,object>> arrayAdder);`
- `void AddOrIncrement<T, TU>(string id, T entity, Expression<Func<T, TU>> path, TU valToAdd);`

**Comment by ppekrol** [comment]
Hi, we will look into that. Thanks for feedback.

You can track the progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-18152
