### ISSUE TITLE
Studio creates success pop-up on failing patch command

### ISSUE THREAD

**Issue by Roy-Goldreich** [ravendb/ravendb#13840]
When tying to execute a patch command on a Map-Reduce Index, the studio pop up both an operation failed message, and a scheduled patch based on query message. 
![image](https://user-images.githubusercontent.com/74922421/158632827-9667093a-0de9-4f42-99e7-9d962bdfb655.png)

**Comment by ppekrol** [comment]
RavenDB is scheduling an operation which fails instantly. I do not see a problem here?

**Comment by ayende** [comment]
UX issue, basically. If it instantly failed, it should say so.
I was confused when I saw this behavior.

**Comment by ml054** [comment]
Moved to our official bugtracker: https://issues.hibernatingrhinos.com/issue/RavenDB-18330
