### ISSUE TITLE
FindIdentityProperty doesn't iterate over base class private properties

### ISSUE THREAD

**Issue by montyclt** [ravendb/ravendb#13893]
Example entities:
```cs
public class Entity
{
    private string __RavenId { get; set; }
}

public class Person : Entity
{
    public string GivenName { get; set; }
    public string FamilyName { get; set; }
}
```

Then I have this convention:
```cs
var documentStore = new DocumentStore
{
    Conventions =
    {
        FindIdentityProperty = member => member.Name == "__RavenId",
    }
};
```

The problem here is that `__RavenId` property is private and doesn't belongs to `Person` class, so the convention cannot find it and ever returns false.

**Comment by ayende** [comment]
I would recommend that you'll use an explicit interface implementation, that'll work.

**Comment by montyclt** [comment]
My workaround is having `__RavenId` protected property instead of private property, but I hope that the convention find private members too.
