### ISSUE TITLE
Outdated example in documentation

### ISSUE THREAD

**Issue by montyclt** [ravendb/ravendb#13905]
The [example of this command](https://ravendb.net/docs/article-page/5.3/csharp/client-api/commands/documents/put), in 5.3 is outdated due since 5.0, should be `session.Advanced.JsonConverter.ToBlittable()`.

**Comment by ppekrol** [comment]
Hi,

thank you for submitting this issue, we will fix it shortly. I've moved that to our bugtracker: https://issues.hibernatingrhinos.com/issue/RDoc-2147
