### ISSUE TITLE
GetDocumentStore for static classes 

### ISSUE THREAD

**Issue by akbar-ehsaan** [ravendb/ravendb#14051]
I have a class that inherits RavenTestDriver.
I need to initialize the IDocumentStore just for the first time . Because for some reason I need just one object of this class .
So here is my code :

```
       public sealed class mystatic : RavenTestDriver
        {
    
    
            public static IDocumentStore store;
            // here something like this store= GetDocumentStore()
            public static IHostBuilder host = easy.api.Program.CreateHostBuilder(new string[0])
            .ConfigureWebHost(webHostBuilder =>
            {
                webHostBuilder.UseTestServer();
            }).ConfigureAppConfiguration(config =>
            {
                //config.AddJsonFile("appsettings.json", optional: true);
            })
           .ConfigureServices(services =>
           {
               services.AddScoped<ICurrentUserService, InitRequest>();
               services.AddScoped<ICacheStorage>(provider =>
               {
                   return new Mock<ICacheStorage>().Object;
               });
               services.AddTransient<IAsyncDocumentSession>((c) =>
               {
                   return store.OpenAsyncSession();
               });
    
           });
            public static IHost cli = host.Start();
        }
```

My question is how can I initialize the store variable ??
Or How can I initialize the store with GetDocumentStore() in static class?

**Comment by haludi** [comment]
Hi,

You must have an instance of a RavenTestDriver derived class.
With regular use, xUnit will instantiate it for you and we recommend this
approach.
If you want a static DocumentStore you can use embedded RavenDB -
https://ravendb.net/docs/article-page/4.2/csharp/server/embedded
If you still want to use RavenTestDriver you can do something like the
following code:

public class DocumentStoreHolder : RavenTestDriver
{
    private IDocumentStore _store;

    public IDocumentStore Store => _store;

    public DocumentStoreHolder()
    {
        _store = GetDocumentStore();
    }
}

public sealed class mystatic
{
    private static readonly IDocumentStore _store;

    static mystatic()
    {
        var storeHolder = new DocumentStoreHolder();
        _store = storeHolder.Store;

    }
}

Best regards,
Igal

**Comment by ayende** [comment]
What is it that you are trying to do? It looks like you are trying to use this for a website? Is that for tests?

**Comment by akbar-ehsaan** [comment]
> What is it that you are trying to do? It looks like you are trying to use this for a website? Is that for tests?

Yes It is for tests.and in my test I have used Akka.net so I have to initialize just one instance of each class

**Comment by akbar-ehsaan** [comment]
> var storeHolder = new DocumentStoreHolder(); _store = storeHolder.Store;

Thank you haludi.It works .thank you .

**Comment by akbar-ehsaan** [comment]
As you know the session is static , so as a another question would you please let me know that can I remove and add data to this session ?

**Comment by mcrio** [comment]
Why not just use the store in DI so no need to change anything else. Like:

```
hostBuilder.ConfigureTestService(services => {
    services.AddSingleton(store);
});
```

**Comment by akbar-ehsaan** [comment]
> Why not just use the store in DI so no need to change anything else. Like:
> 
> ```
> webHostBuilder.ConfigureTestService(services => {
>     services.AddSingleton(store);
> });
> ```

I need the store object in some part of my tests .how can I access the store session ?

**Comment by mcrio** [comment]
So you need a particular session, like you cannot just open a new one on that store?

**Comment by akbar-ehsaan** [comment]
> So you need that particular session, like you cannot just open a new one on that store?

Yes exactly

**Comment by mcrio** [comment]
Your test classes inherit from `RavenTestDriver` ?

**Comment by akbar-ehsaan** [comment]
> Your test classes inherit from `RavenTestDriver` ?

one of the my test class 

```
public class DraftControllerTests
    {
        [Fact]
        public async Task GetDraftControllerTest()
        {
            //Arrange
            var data = new DraftEntity()
            {
                CautionAgreementSelected=true,
                CorrelationId=Guid.NewGuid().ToString(),
                CreateDateTime=DateTime.Now,
                CustomerIsin=Constants.customerIsin,
                FinancialProviders=domain.Enums.FinancialProviders.TBRFinancialDataProvider,
                Iceberg=1,
                Id="commandId",
                MinimumQuantity=1,
                OrderType =domain.Enums.OrderType.LimiteOrder,
                Price  =22,
                Quantity=1,
                Side=domain.Enums.OrderSide.Buy,
                SymbolIsin ="132",
                SymbolName="122",
                TriggerPrice=444,
                ValidityDate=DateTime.Now,
                ValidityType=domain.Enums.OrderValidityEnum.GOOD_TILL_DATE
            };

            IAsyncDocumentSession session = mystatic._store.OpenAsyncSession();
            await session.StoreAsync(data);
            await session.SaveChangesAsync();
            //Act
            using (var client = mystatic.cli.GetTestServer().CreateClient())
            {
                var response =await client.GetAsync($"api/draft");

                response.EnsureSuccessStatusCode();
                var Result = JsonConvert.DeserializeObject<List<DraftEntity>>(await response.Content.ReadAsStringAsync());
                //Assert
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);
                Assert.Equal(22, Result[0].Price);

            }


        }
```

This class now works with 

```
  public sealed class mystatic : RavenTestDriver
    {

        public static readonly IDocumentStore _store;

        static mystatic()
        {
            var storeHolder = new DocumentStoreHolder();
            _store = storeHolder.Store;

        }


        public static IHostBuilder host = easy.api.Program.CreateHostBuilder(new string[0])
        .ConfigureWebHost(webHostBuilder =>
        {
            webHostBuilder.UseTestServer();
        }).ConfigureAppConfiguration(config =>
        {
            //config.AddJsonFile("appsettings.json", optional: true);
        })
       .ConfigureServices(services =>
       {
           services.AddScoped<ICurrentUserService, InitRequest>();
           services.AddTransient<ICacheStorage>(provider =>
           {
               return new Mock<ICacheStorage>().Object;
           });
           services.AddTransient<IAsyncDocumentSession>((c) =>
           {
               return _store.OpenAsyncSession();
           });

       });
        public static IHost cli = host.Start();
    }
```

As you can see in my test class I call mystatic class to access static session and static host

**Comment by mcrio** [comment]
From the example, I don't see access to a static session, only to a static host. Am I missing something? 

In case you need to use the same session in the service you'd need to pass that to DI the same way you pass the store (but see carefully if that is really what you need).

I guess you have your reasons why these need to be static. _Another way is to not use statics but to generate a store for each test or for a test class (IClassFixture  in this case don't forget to make the fixture disposable to clean up ravendb data)._

**Comment by akbar-ehsaan** [comment]
Thank you .
You are right it is my wrong .
I should use static session not static documetStore .So here I asked the problem :
[https://github.com/ravendb/ravendb/issues/14055](https://github.com/ravendb/ravendb/issues/14055)

**Comment by akbar-ehsaan** [comment]
https://github.com/ravendb/ravendb/issues/14055
