### ISSUE TITLE
[docs] Document that RavenTestDriver.ConfigureServer() can only be called once and update example to show correct initialization

### ISSUE THREAD

**Issue by ngbrown** [ravendb/ravendb#14117]
The example of using `RavenTestDriver.ConfigureServer()` has it called from within a test case. But normally one would have many test cases. Also, there would be more than one test fixture, that is more than one instance of `RavenTestDriver`. It's not clear from the documentation, what the limitations are, but calling `RavenTestDriver.ConfigureServer()` more than once per test run will generate the following error:

> System.InvalidOperationException : Cannot configure server after it was started. Please call 'ConfigureServer' method before any 'GetDocumentStore' is called.

Link to docs:

https://ravendb.net/docs/article-page/5.3/csharp/start/test-driver

https://github.com/ravendb/docs/blob/0362d08d46621d761e26bf3bb517c7c36ad109d9/Documentation/4.2/Raven.Documentation.Pages/start/test-driver.dotnet.markdown?plain=1#L61-L64

xUnit was used in the example, and the documentation should show how to initialize once per test run. The [code in the repo](https://github.com/ravendb/ravendb/blob/166836322d23a41b5ac9abe3b6b281c143b7e52a/test/EmbeddedTests/TestDriver/TestDriverExampleTest.cs#L15-L21) does this, but still with a single test fixture. In NUnit, I would create a stand-alone class in the root namespace like this:

```cs
using NUnit.Framework;
using Raven.TestDriver;

namespace RavenDBTestDriverFullExample
{
    [SetUpFixture]
    public class RavenTestDriverConfigureServer
    {
        [OneTimeSetUp]
        public void RunBeforeAnyTests()
        {
            RavenTestDriver.ConfigureServer(new TestServerOptions { DataDirectory = "C:\\RavenDBTestDir" });
        }
    }
}
```

**Comment by arekpalinski** [comment]
@reebhub please have a look

**Comment by reebhub** [comment]
@arekpalinski [RDoc-2174](https://issues.hibernatingrhinos.com/issue/RDoc-2174)

**Comment by garayx** [comment]
We will add this, you can track the progress here: [RDoc-2174](https://issues.hibernatingrhinos.com/issue/RDoc-2174)
