### ISSUE TITLE
RavenDB Studio Thai Text Issue

### ISSUE THREAD

**Issue by murshex** [ravendb/ravendb#14232]
Thai text doesn’t work properly in the RavenDB Studio document/query/patch text editor due to accents for example, try to put this in a document string property as the value: หมีอ้วนสีขาวอยากกินส้มตำ

and you will see how the text cursor is not where it’s supposed to be.

**Comment by ml054** [comment]
Hi, @c0nd3v 

The root issue is related to lack of variable width fonts support, here: https://issues.hibernatingrhinos.com/issue/RavenDB-16558

And issue inside our code editor: https://github.com/ajaxorg/ace/issues/4142

I'm sorry for inconvenience.

I can see 2 options here: Fix that in ace editor or replace our editor with something different.
