### ISSUE TITLE
How to clone/copy a collection?

### ISSUE THREAD

**Issue by tzm1119** [ravendb/ravendb#14254]
I am new to RavenDB.
I want to know what is the best way to clone a collection with new collection name and keep the data  same.

**Comment by ayende** [comment]
You can use a patch for that, see:

https://ravendb.net/docs/article-page/5.3/csharp/studio/database/documents/patch-view

```
from CollectionA
update 
{
    var clone = Object.assign({}, this);
    clone["@metadata"]["@collection"] = "NewCol";
    put("new-col/", clone);
}
```

**Comment by tzm1119** [comment]
It seems not support.

Changing '88f97762-ea76-4991-b979-e1137d999ef3' from 'UserMessages' to 'newCol' via update is not supported. Delete it and recreate the document '88f97762-ea76-4991-b979-e1137d999ef3'.
Raven.Client.Exceptions.Documents.DocumentCollectionMismatchException: Changing '88f97762-ea76-4991-b979-e1137d999ef3' from 'UserMessages' to 'newCol' via update is not supported. Delete it and recreate the document '88f97762-ea76-4991-b979-e1137d999ef3'.
   at Raven.Client.Exceptions.Documents.DocumentCollectionMismatchException.ThrowFor(String documentId, String oldCollection, String newCollection) in C:\Builds\RavenDB-Stable-5.3\53016\src\Raven.Client\Exceptions\Documents\DocumentCollectionMismatchException.cs:line 36

**Comment by haludi** [comment]
Can you share your script with us?
My guess is that you missed something in the `id` argument of the `put` function.
Does it end with '/'

**Comment by tzm1119** [comment]
This is my document
```
{
    "Passwd": "",
    "WorkTitles": [],
    "RoleType": "User",
    "Name": "A",
    "LastModifyTime": "0001-01-01T00:00:00.0000000",
    "LastModifyUserId": "",
    "LastModifyUseName": "",
    "CreateTime": "0001-01-01T00:00:00.0000000",
    "CreateUserId": "",
    "CreateUseName": "",
    "TagList": [],
    "IsDeleted": false,
    "@metadata": {
        "@collection": "SysUsers",
        "Raven-Clr-Type": "FuSa.Domain.SysUser, FuSa.Domain",
        "@flags": "HasRevisions"
    }
}
```

This is my patch script
```
from SysUsers
update 
{
    var clone = Object.assign({}, this);
    clone["@metadata"]["@collection"] = "SysUsers2";
    put("newId/", this);
}
```

**Comment by haludi** [comment]
```
from SysUsers
update 
{
    var clone = Object.assign({}, this);
    clone["@metadata"] = {
        "@collection": "SysUsers2"
    }
    put("newId/", clone);
}
```

**Comment by haludi** [comment]
By the way, this will not clone attachment, counters, time series

**Comment by tzm1119** [comment]
![image](https://user-images.githubusercontent.com/36020806/169982145-a5ce44dc-8937-427b-8d90-9b7fcb595b21.png)

I want to create a new collection. but this script only copy the data. no collection is created.

**Comment by haludi** [comment]
How do you run the patch?
Do you run it with RavenDB studio?

I checked that and it works fine.
![image](https://user-images.githubusercontent.com/37696258/169983443-1a91caa7-64ca-4148-af46-7ad8db9425dc.png)

**Comment by tzm1119** [comment]
It is ok now. thank you very much.😊😊😊
