### ISSUE TITLE
Patch throws Raven.Client.Exceptions.Documents.Patching.JavaScriptException when from a generic methode

### ISSUE THREAD

**Issue by oiBio** [ravendb/ravendb#14331]
I was refactoring some code and created a generic methode to patch some simple field with new data. Unfortunatly i got a runtime error that tells me that my property does not exist - but it does!
After some debugging and testing i figured this has to do something with my newly created generic methode.

As far as i see the generated patch command lookes identical to one that is created then i use the direct type. I think this is a bug, or some non-obvious behaviour. 

see this this test to reproduce

```
 public class RavenDBTestDriver5
    {
        [Fact]
        public void PatchWithGeneric_Test()
        {
            string entityId = "Model/1";
            
            EmbeddedServer.Instance.StartServer();
            using var store = EmbeddedServer.Instance.GetDocumentStore("Embedded");

            using (var session = store.OpenSession())
            {
                var model = new Model() { Name = "Test 1", Timestamp = DateTime.MinValue };
                session.Store(model, entityId);
                session.SaveChanges();
            }

            using (var session = store.OpenSession())
            {
                // Working
                session.Advanced.Patch(entityId, (Model e) => e.Timestamp, DateTime.Now);
                session.SaveChanges();
            }
            using (var session = store.OpenSession())
            {
                // Not Working...
                PatchWithGeneric<Model>(session, entityId, DateTime.MaxValue);
                session.SaveChanges();  // Throws Raven.Client.Exceptions.Documents.Patching.JavaScriptException: At 0:4 {"message":"Timestamp is not defined" ...
            }
        }


        private void PatchWithGeneric<TEntity>(IDocumentSession session, string entityId, DateTime timestamp) where TEntity : IHasTimestamp
        {
            session.Advanced.Patch(entityId, (TEntity e) => e.Timestamp, timestamp);
        }

        public class Model : IHasTimestamp
        {
            public string Name { get; set; }
            public DateTime? Timestamp { get; set; }
        }

        public interface IHasTimestamp
        {
            public DateTime? Timestamp { get; set; }
        }
    }
```

**Comment by ayende** [comment]
Your code _looks_ the same, but it actually isn't.

We have: `Convert(e, IHasTimestamp).Timestamp` in the generic case vs. `e.Timestamp` for the non generic case.

The proper way to do it is like so:

```
        private void PatchWithGeneric(IDocumentSession session, string entityId, DateTime timestamp)
        {
            session.Advanced.Patch<IHasTimestamp, DateTime?>(entityId, e => e.Timestamp, timestamp);
        }
```

That would work

**Comment by oiBio** [comment]
mmh yes this works in my case, but also does not use generic anymore. 
before your answer i helped myself and used session.Advanced.Defer which also works

**As a rule of thumb - never use patch with a generic type?**

is this an intended behaviour? is this documented?

**Comment by ayende** [comment]
Generics are fine, but the problem is that you are doing a (unseen) conversion here.
Basically, the `Patch` and friends are there to be of assistance for straightforward things.
To give a complete solution there you have to go _deep_ into the internals of the compiler, and that isn't what we want to do here.

**Comment by oiBio** [comment]
i can understand that this is a hard one to fix, but is there a scenario where you can use your

`void Patch<T, U>(string id, Expression<Func<T, U>> path, U value);`

within a generic and "where T : ISomeInterface" without a (unseen) conversion?

**Comment by ayende** [comment]
I would doubt that. Note that there is _no need for that_. 
We aren't actually using the types. You can use: `Patch<ISomeInterface, ...>` directly.

**Comment by oiBio** [comment]
Yeah... i see. But i stick with my new rule 
**never use any Patch<> with a generic type T, always use the interface/class directly**

but thank you very much for your time and your explanations -  as always!
I would love to see this working anyway, or maybe a compiler warning - but also understand if nothing changes. if you do not want to track this issue here just close it as you like

**Comment by ayende** [comment]
In order to resolve this, we'll need to go and update a dependency (`Lamba2Js`), the problem is here:

https://github.com/ravendb/ravendb/blob/fbe69146e0a78e1af11aff1e1778d9d4892ab023/src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.Patch.cs#L183

Where it doesn't understand that the `Convert` should be skipped.
