### ISSUE TITLE
RavenDb Linq query using a dictionary or a dictionary inherited model.

### ISSUE THREAD

**Issue by a-haddaji-neoventive** [ravendb/ravendb#14489]
We have faced a problem working with linq using a model that inherits from a dictionary, so that when we do a certain where condition  where one of the operands is an element with a specific key it results in an exception.

![image](https://user-images.githubusercontent.com/108685044/177190831-d375a1d9-645b-4be0-bb63-7ef681f1dcaa.png)

**Comment by arekpalinski** [comment]
It got fixed in https://github.com/ravendb/ravendb/pull/14546
