### ISSUE TITLE
GetMetadataFor and GetChangeVectorFor Documentation

### ISSUE THREAD

**Issue by murshex** [ravendb/ravendb#14596]
https://ravendb.net/docs/article-page/5.4/csharp/client-api/session/how-to/get-and-modify-entity-metadata
https://ravendb.net/docs/article-page/5.4/csharp/client-api/session/how-to/get-entity-change-vector

If we look at the documentation of the return value for both these methods, we will see that it says:
![image](https://user-images.githubusercontent.com/32241825/180043161-817c9a93-8c2b-4d97-93e5-a3013bd411d5.png)
**_Throws an exception if the instance is not tracked by the session._**

In the RavenDB.Client code summary it says:
![image](https://user-images.githubusercontent.com/32241825/180043463-527e5511-2d10-4959-8d76-ebb4ea20a980.png)
**_If the entity is transient, it will load the metadata from the store and associate the current state of the entity with the metadata from the server._**

So obviously these two definitions cannot coexist. Can you please tell me which definition is correct?

Thank you!

**Comment by ppekrol** [comment]
Hi, the entity needs to be tracked by the session. It will throw in any other case. We will make a fix. 

Thanks for pointing this out!

Issue link: https://issues.hibernatingrhinos.com/issue/RavenDB-18996/Invalid-GetChangeVectorFor-code-summary

**Comment by murshex** [comment]
@ppekrol And how about for GetMetadataFor method?

**Comment by ppekrol** [comment]
Same logic as for `GetChangeVectorFor`

**Comment by c0nd3v** [comment]
I think you might want to update the issue link to include that the code summary is wrong for both GetMetadataFor and GetChangeVectorFor 😃🫡

**Comment by ppekrol** [comment]
Fixe in latest Client API
