### ISSUE TITLE
How to find max and min?

### ISSUE THREAD

**Issue by antontuz** [ravendb/ravendb#14723]
I need to find the maximum date from the list of dates. How can I do it?
I do following:
```
from 'event' as e
where e.Header.Name in ('territory_entry', 'territory_exit')
and e.Payload.Id in ('123', '456')
select {
    Lines: e.Lines.map(l => {
      return {
          maxTime: Math.max(e.Header.Timestamp)
      }
    })
}
```

But.. It doesn't work

For example,
I have list of objects:
```
['123', territory_entry, '2022-04-06T12:31:13']
['123', territory_exit, '2022-04-06T13:31:13']
['123', territory_entry, '2022-04-06T14:31:13']
['456', territory_entry, '2022-04-06T12:31:13']
['456', territory_exit, '2022-04-06T13:31:13']
['456', territory_entry, '2022-04-06T14:31:13']
```

And all I need is return minimum entry by id and maximum entry by id
query should return this:
```
min: ['123', territory_entry, '2022-04-06T12:31:13'], ['456', territory_entry, '2022-04-06T12:31:13']
max: ['123', territory_exit, '2022-04-06T13:31:13'], ['456', territory_exit, '2022-04-06T13:31:13']
```

rql doesn't have join etc, js function doesn't help me in this situation so I don't understand. Can you help me, please?

**Comment by antontuz** [comment]
Okey, I can receive all events: 
```
from 'event' as e
where e.Header.Name in ('territory_entry', 'territory_exit')
and e.Payload.Id in ('123', '456')
```
then I can get min, max for ids using linq **but** I want to do it in rql because it is faster

**Comment by ayende** [comment]
Note that what you are doing in the first version is getting the Min / Max _per document_.
If you want to do that across all match documents, the way to do it is using facets.

Using the sample data, you can use:

```
from index "Orders/Totals" 
where Company = 'companies/1-A'
select facet(Employee, min(Total))
```

That gives you the minimum value per employee for orders for ``companies/1-A'`.

If you'll do just:

```
from index "Orders/Totals" 
select facet(max(Total),min(Total))
```

Note that this sort of query must be run against an index, not a collection

**Comment by antontuz** [comment]
But I need another
I don't understand how facet can help me to select some data

**Comment by ayende** [comment]
Can you show the actual documents and expected results?

**Comment by antontuz** [comment]
I use this query for receive data:
```
from index 'Auto/event'
where Header.Name in ('territory_entry')
and Payload.identifiers.subject_id in ('222', '333')
select Header.Name, Header.Timestamp, Payload.identifiers.subject_id
```

After executing the request, I get this:
![image](https://user-images.githubusercontent.com/50873585/183912460-29621ce6-d182-4243-8b23-71f65557b377.png)

I want to return following:

["territory_entry", min timestamp, "subject_id"]
["territory_exit", max timestamp, "subject_id"]

I need to take the minimum entry date for each id and the maximum exit date for each id

**Comment by antontuz** [comment]
I can use facet:
facet(Header.Timestamp)

It return array but I need only one value with min or max timestamp

**Comment by ayende** [comment]
You should be able to run:

```
from index 'Auto/event'
where Header.Name in ('territory_entry')
and Payload.identifiers.subject_id in ('222', '333')
select facet('Header.Name', min('Header.Timestamp'), max('Header.Timestamp'))
```

No?

**Comment by ayende** [comment]
Actually, in your case, you limit the `Header.Name`, so ca do:

```
from index 'Auto/event'
where Header.Name in ('territory_entry')
and Payload.identifiers.subject_id in ('222', '333')
select facet( min('Header.Timestamp'), max('Header.Timestamp'))
```

**Comment by antontuz** [comment]
no, it doesn't work
result: 
```
[
    {
        "Name": "Header.Timestamp",
        "Max": 0,
        "Min": 0,
        "Count": 20,
        "Range": "@AllResults"
    }
]
```

**Comment by ayende** [comment]
Can you create a db with:

* Some sample doc
* The index in question

Then export and attach it there?

**Comment by antontuz** [comment]
I hope it works:
https://disk.yandex.com/d/-IjsCLYpgjxT_g

It's dump of my test database

you can write simple query:
```
from index 'Auto/AllDocs/ByHeader.NameAndPayload.identifiers.subject_id'  
where Header.Name in ('territory_entry')
and Payload.identifiers.subject_id in ('47b2-47b2-416a-91a9-98bdb15e8606', '90571ff8-47b2-416a-91a9-98bdb15e8606')
select facet( min('Header.Timestamp'), max('Header.Timestamp'))
```

**Comment by antontuz** [comment]
and I still don't understand how to group by id

 expected results after min('Header.Timestamp'), max('Header.Timestamp') and grouping
```
min: ['47b2-47b2-416a-91a9-98bdb15e8606', territory_entry, '2022-04-06T12:31:13'], ['90571ff8-47b2-416a-91a9-98bdb15e8606', territory_entry, '2022-04-06T12:31:13']
max: ['47b2-47b2-416a-91a9-98bdb15e8606', territory_exit, '2022-04-06T13:31:13'], ['90571ff8-47b2-416a-91a9-98bdb15e8606', territory_exit, '2022-04-06T13:31:13']
```

**Comment by antontuz** [comment]
hm I have an idea
```
from index 'Auto/event'
order by Header.Timestamp
where Header.Name in ('territory_entry')
and Payload.identifiers.subject_id in ('222')
select ..  limit 1
```
but I have a problem too.. What if I have two ids? I can't do limit 1

**Comment by ayende** [comment]
There are a few issues with how you did this.
First, you need to us a static index, like this one:

`Events/Search`
```
from e in docs
select new 
{
   e.Header.Name,
   TimestampTicks = e.Header.Timestamp.Ticks,
   Subjects = e.Payload.identifiers.Select(i => i.subject_id)
}
```


And then the query:

```
from index 'Events/Search'
where Name in ('territory_entry')
and Subjects in ('47b2-47b2-416a-91a9-98bdb15e8606', '90571ff8-47b2-416a-91a9-98bdb15e8606')
select facet( min(TimestampTicks), max(TimestampTicks))
```

I'm afraid that `min()` and `max()` can only handle numeric values, so I converted it to ticks.

**Comment by antontuz** [comment]
it works, thanks!
is it possible to return min and max for every Subject?

**Comment by antontuz** [comment]
and smth like this in pseudocode:

`select facet( min(TimestampTicks).Where(Name == "territory_entry"), max(TimestampTicks).Where(Name == "territory_entry"))
`
I wanna select min timestamp of entry, max timestamp of exit and some data  for each id. Is it possible to do this in one query?

**Comment by ayende** [comment]
Yes, for that, you can use:

```
from index 'Events/Search'
where Name in ('territory_entry')
and Subjects in ('47b2-47b2-416a-91a9-98bdb15e8606', '90571ff8-47b2-416a-91a9-98bdb15e8606')
select facet(Subjects, min(TimestampTicks), max(TimestampTicks))
```

**Comment by ayende** [comment]
For the other question, you can use a map/reduce index like so:

```
// map:

from e in docs
select new {
    ID = e.Header.ID,
    Entry = e.Header.Name == "territory_entry" ? e.Header.Timestamp : null,
    Exit = e.Header.Name == "territory_exit" ? e.Header.Timestamp : null,
}

// reduce:
from r in results
group r by r.ID into g
select new {
    ID = g.Key,
    Entry = g.Where(x=>x.Entry !=null).Select(x=>x.Entry).OrderBy(x=>x).FirstOrDefault(),
    Exit = g.Where(x=>x.Exit !=null).Select(x=>x.Exit).OrderBy(x=>x).LastOrDefault(),
}
```

And then the results are:

![image](https://user-images.githubusercontent.com/116915/184060516-6d50d632-e750-472f-8669-de33936470c9.png)

**Comment by antontuz** [comment]
is map/reduce index a good decision? my database will be huge and slow if I will have a lot of indexes
what do you think about it?

**Comment by ayende** [comment]
The question is what exactly you are trying to do.

Can you give the full context?

Also, your documents are now in the `@empty` collection, you probably want to put them in a dedicated one.

**Comment by antontuz** [comment]
I use ravendb to generate reports. I select the necessary data from the database, try to group it and build a report. It seemed to me that using indexes is very convenient. But, unfortunately, indexes take up disk space. I think if there are a lot of indexes, then the database will become huge and everything will start to freeze

**Comment by antontuz** [comment]
This all suggests, maybe it's worth writing a query without indexes

**Comment by antontuz** [comment]
![image](https://user-images.githubusercontent.com/50873585/184138550-c879353e-a06f-48d9-9e89-b097d3e8d374.png)
look what I mean

**Comment by antontuz** [comment]
and this is only one index

**Comment by ayende** [comment]
If you need a one of report, an index isn't worth it.
You can do a streaming and inline aggregation.

However, RavenDB is meant to be able to answer those queries _fast_ over & over again, and maintain the same response rate even under heavy read & write loads.

**Comment by antontuz** [comment]
hm, ok
For several days I tried to apply `load `in my request, but nothing works. Can you help me, please, to create a query with streaming and inline aggregation. I can create another issue

**Comment by ayende** [comment]
Please create another issue with full details, yes.
