### ISSUE TITLE
How to use streaming and inline aggregation?

### ISSUE THREAD

**Issue by antontuz** [ravendb/ravendb#14752]
I have items in database. All I need is to take the minimum entry date for each id and the maximum exit date for each id
Expected result:
![image](https://user-images.githubusercontent.com/50873585/184858832-4841fb75-ad38-49b5-9e7a-63516a7c3d17.png)

I can use map/reduce index like so:
```
// map:

from e in docs
select new {
    ID = e.Header.ID,
    Entry = e.Header.Name == "territory_entry" ? e.Header.Timestamp : null,
    Exit = e.Header.Name == "territory_exit" ? e.Header.Timestamp : null,
}

// reduce:
from r in results
group r by r.ID into g
select new {
    ID = g.Key,
    Entry = g.Where(x=>x.Entry !=null).Select(x=>x.Entry).OrderBy(x=>x).FirstOrDefault(),
    Exit = g.Where(x=>x.Exit !=null).Select(x=>x.Exit).OrderBy(x=>x).LastOrDefault(),
}
```
But in my opinion this is redundant. The index takes up too much space 
I know I can do this using streaming and inline aggregation?
For several days I tried to apply load in my request, but nothing works. I don't understand how to write the correct query

database for test:
https://disk.yandex.com/d/-IjsCLYpgjxT_g

**Comment by ayende** [comment]
Question - why aren't you using facets for that? It is meant for slicing & dicing the data in this manner.
You'll need one index, and they apply on it in various ways.

**Comment by antontuz** [comment]
Because I don't wanna have any indexes

**Comment by ayende** [comment]
You can't really have _no_ indexes.
A single one covering the fields you'll query on will suffice, unless I miss something

**Comment by antontuz** [comment]
Yes, ur right. I have auto indexes but I don't wanna create smth new for my case

**Comment by antontuz** [comment]
hm, I think I can use this index for facets
but how?..

**Comment by antontuz** [comment]
![image](https://user-images.githubusercontent.com/50873585/184863921-a1d15c39-2851-4a66-9ed3-3c406cc823a3.png)
I need this but facet can give me only one array with elements

**Comment by ayende** [comment]
Look inside, you get elements for each id

**Comment by antontuz** [comment]
can i take entire document using facet?

**Comment by ayende** [comment]
No

**Comment by antontuz** [comment]
so facet is a bad idea

**Comment by ayende** [comment]
You want two separate things. You want to get aggregation on the data, therefor, use `facets`. And the document itself? Just get that one directly.

**Comment by antontuz** [comment]
I can do it using sql
Why I can't do this using rql?

**Comment by ayende** [comment]
RavneDB isn't a relational database. The indexing engine is aimed at making RavenDB really fast for OLTP scenarios.
For reporting, we are very good in answering predictable queries. For more complex stuff, you have facets.

**Comment by antontuz** [comment]
ok, I see, thanks!
