### ISSUE TITLE
Unable to filter on a nullable DateOnly property

### ISSUE THREAD

**Issue by jac-dev** [ravendb/ravendb#14764]
Hi

When filtering a collection on a nullable `DateOnly` property, RavenDB yields no results. Performing the same query on a nullable `DateTime` property instead works fine. Please see the failing test below using the latest version of RavenDB (5.4.1).

```
public class DateOnlyBug : RavenTestDriver
{
    [Test]
    public async Task UnableToFilterOnNullableDateOnlyProperty()
    {
        using var store = GetDocumentStore();

        using (var session = store.OpenAsyncSession())
        {
            await session.StoreAsync(new Employee
            {
                Id = "employees/1",
                DateTimeDateOfBirth = new DateTime(2000, 1, 1),
                DateOnlyDateOfBirth = new DateOnly(2000, 1, 1)
            });
            await session.SaveChangesAsync();
        }

        // Querying the DateTime property works fine.
        using (var session = store.OpenAsyncSession())
        {
            var employees = await session.Query<Employee>()
                .Where(e => e.DateTimeDateOfBirth != null && e.DateTimeDateOfBirth.Value.Year == 2000)
                .ToListAsync();

            Assert.AreEqual(1, employees.Count);
        }
        
        // Querying the DateOnly property returns no results.
        using (var session = store.OpenAsyncSession())
        {
            var employees = await session.Query<Employee>()
                .Where(e => e.DateOnlyDateOfBirth != null && e.DateOnlyDateOfBirth.Value.Year == 2000)
                .ToListAsync();

            Assert.AreEqual(1, employees.Count);
        }
    }
}

public class Employee
{
    public string Id { get; init; }
    public DateTime? DateTimeDateOfBirth { get; init; }
    public DateOnly? DateOnlyDateOfBirth { get; init; }
}
```

**Comment by maciejaszyk** [comment]
Hey, 
I will check that today. Thanks for the test.

**Comment by maciejaszyk** [comment]
I checked your test. We're not supporting `DateOnly/TimeOnly` inside `AutoIndexes`. The reason why we do not support it is backward compatibility. We're detecting types manually during indexing. Some strings could be treated as dates from the introduction `DateOnly / TimeOnly` support and we didn't want to introduce a breaking change. In such case I suggest you to create a static index. Your query is fully supported there. Also, you should gain performance, because we're supporting Ticks inside the index and query.

Please check our docs about it: https://ravendb.net/docs/article-page/5.4/csharp/client-api/how-to/using-timeonly-and-dateonly#client-api-how-to-use-timeonly-and-dateonly-types

**Comment by jac-dev** [comment]
Hey maciejaszyk, thanks a lot for your investigations!

Too bad RavenDB doesn't support `DateOnly/TimeOnly` in `AutoIndexes`. As these are standard .NET types, do you consider to support them in the next major release of RavenDB?

Regarding the current version, wouldn't it make sense to throw an exception instead of ignoring a filter silently? It took quiet some time to figure out the underlying issue with the query up to the point of having a reproducable failing test 😅. Or is this not possible due to the backward compatibility?

**Comment by maciejaszyk** [comment]
Hey @jac-dev 

I've created a ticket for implementing detection: https://issues.hibernatingrhinos.com/issue/RavenDB-19205/Detects-DateOnly-TimeOnly-inside-AutoIndexes

Implementing this could lead to breaking change so it will be handled in `v6.0`.

I've also created a ticket to add info in our documentation on how Raven handles `DateOnly/TimeOnly` in AutoIndexes to avoid confusion in the future.

Thanks for understanding :)

**Comment by jac-dev** [comment]
Hey maciejaszyk, thanks again for your efforts, looking forward to version 6 then.
