### ISSUE TITLE
Implement IAsyncEnumerable in IRavenQueryable

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#14788]
Would it be possible to implement IAsyncEnumerable similar to how Entity Framework does in IRavenQueryable?

(And give AsAsyncEnumerable() as an endpoint?)

This will fix issues where you are using EF Core and RavenDb in the same project (endless problems with ToListAsync() etc. which requires an IAsyncEnumerable to work in EF core but RavenDb doesn't)

**Comment by JohnGalt1717** [comment]
PS, it would be nice too for the overlapping issue with EF Core, if Select could return IRavenQueryable instead of just IQueryable when working against an IRavenQueryable. It shouldn't break any code.  (Where already returns an IRavenQueryable)  Same deal with OrderBy.

And then all of the ToXX and FirstXX etc. if they had overloads that took IRavenQueryable instead of just IQueryable you'd always get the right version and not end up with subtle bugs in projects where you're forced to access legacy data using EF Core.

**Comment by garayx** [comment]
Hi

I have opened an issue to add `AsAsyncEnumerable`

https://issues.hibernatingrhinos.com/issue/RavenDB-19240/Add-AsAsyncEnumerable-to-RavenQueryableExtensions

There is already option for `Select` to return `IRavenQueryable`, you need to add `using Raven.Client.Documents.Linq;`

![image](https://user-images.githubusercontent.com/16625387/186395343-b2188e14-5a17-4c44-901d-61ed5f106107.png)

**Comment by ayende** [comment]
Note that in general, this is probably a bad idea to just add that. You want to stream the results, which already support async enumeration, see:

```
    public static Task<IAsyncEnumerator<StreamResult<T>>> AsAsyncEnumerable<T>(this IRavenQueryable<T> self)
    {
        var ravenQueryProvider = (IRavenQueryProvider)self.Provider;
        return ((IAsyncDocumentSession)ravenQueryProvider.QueryGenerator.Session).Advanced.StreamAsync(self);
    }
```

**Comment by JohnGalt1717** [comment]
Ok, what do you suggest? As soon as we have an endpoint that requires that we get data from the legacy database and then get data from RavenDb, we end up with C# choosing the wrong version even if both sets of usings are in.  from a in session.Table select new {} syntax returns IQueryable and then anything like ToArrayAsync or ToListAsync get shunted to the EF Core versions not the RavenDb versions. (especially bad if the query has order by)

And when this happens, you get new errors that don't show up until runtime because RavenDb doesn't support IAsyncEnumerable (I still think this should be added everywhere as a first class citizen like all of EF Core not just an Extension method you can hack in yourself) and then it blows  up because EF Core versions require IAsyncEnumerable implementation.

My thought was that if Select, Group and Orderby (and thenby) all return IRavenQueryable and all of the materialization extension methods will take IRavenQueryable then the entire process will stay using the Raven versions explicitly because the compiler prefers exact matches and then this problem goes away.

But whatever suggestions you have, I'm all ears, just fighting with naming clashes constantly and it won't go well if there are any gaps at all in our testing.

**Comment by ayende** [comment]
See the code above, that gives you the right behavior.
In general, `AsAsyncEnumerable` for RavenDB queries is not a good idea. You want to do that on a _streaming_ query, since that match the right behavior.
And RavenDB already support streaming query and async enumeration.

**Comment by JohnGalt1717** [comment]
I'm referring to a query that isn't coming from an index.

`(from x in session.Query<SomeDocumenttype>() order by x.Name where x.Date > someDate select new {...}).ToArrayAsync()`

This fails if you have EF Core usings because select here returns IQueryable not IRavenQueryable and thus it uses the EF Core version of ToArrayAsync not the RavenDb version.

And like EF Core (and I get the stream argument) I should be able to use .AsAsyncEnumerable() as an extension method that takes that IRavenQueryable and creates a stream and returns an IAsyncEnumerable from it.  This is especially important now that the entire pipeline of ASP.NET Core supports IAsyncEnumerable as a result including json serialization.  We are seeing 60% memory usage drop on queries that don't have to be materialized and worked on in endpoints and can just be streamed to users compared to .NET Core 5 when using this technique.

The other surprising one that doesn't seem to exist is .SumAsync.

**Comment by JohnGalt1717** [comment]
Bump on SumAsync? Any work around that is efficient?

**Comment by ppekrol** [comment]
Hi @JohnGalt1717 

The `.Sum` or `.SumAsync` implies that there will be calculation performed during query execution and this is by design forbidden by us, due to possible performance issues during query execution (implies full table scan). 

Best way to solve that is to use the Map-Reduce index (https://ravendb.net/docs/article-page/5.4/csharp/indexes/map-reduce-indexes) and just get the precalculated value immediately.

e.g. using our sample Northwind database you can define index as follows

Map:
```
from p in docs.Products
select new {
    Supplier = p.Supplier,
    UnitsInStock = p.UnitsInStock,
    Count = 1,
}
```

Reduce:
```
from r in results
group r by r.Supplier into g
select new {
    Supplier = g.Key,
    UnitsInStock = g.Sum(x => x.UnitsInStock),
    Count = g.Sum(x => x.Count)
}
```

And this will allow you to get count of products per supplier, but also total number of units in stock.

**Comment by ayende** [comment]
For `Sum`, you can do:

`session.Query<Users>().GroupBy(x=>x.Country).Select(g => new { Country = g.Key, Points = g.Sum(x=>x.Points)) });`

And that would also work with async enumerable.

**Comment by JohnGalt1717** [comment]
Thanks!

**Comment by JohnGalt1717** [comment]
So here's what I did in a variation using count (sum does the same):

```
		var usersActive = await dbSession.ActivityLessons.GroupBy(g => new {
			UserId = g.User.Id,
			OrganizationId = g.Organization!.Id
		}).Where(q => q.Key.OrganizationId == organizationId.Value && q.Any(a => a.DateTime >= lastMonth))
		.RavenCountAsync(cancellationToken);
```

(RavenCountAsync is just an alias I created so that Raven could co-exist with Entity Framework while we incrementally migrate)

Which results in:

```
Raven.Client.Exceptions.InvalidQueryException: Raven.Client.Exceptions.InvalidQueryException: Field 'Key.OrganizationId' isn't neither an aggregation operation nor part of the group by key
Query: from 'ActivityLessons' group by User.Id, Organization.Id where Key.OrganizationId = $p0 and '[].DateTime' >= $p1 select Lesson.Length limit $p2, $p3
Parameters: {"p0":100000,"p1":"2023-01-28T16:20:58.5515277Z","p2":0,"p3":0}
```

(Note that the error should be "is neither" not "isn't neither")

But in the example, Organization Is part of the group by key as evidenced by the fact that it's referencing the Key itself in the error message.

What am I doing wrong?

**Comment by garayx** [comment]
Try to add `Select()` after the `GroupBy()` and do the `Where()` on `Select()` results.


```
		var usersActive = await dbSession.ActivityLessons.GroupBy(g => new {
			UserId = g.User.Id,
			OrganizationId = g.Organization!.Id
		}).Select(x => new
                            {
                                x.Key.UserId,
                                x.Key.OrganizationId
                            }).Where(q => q.OrganizationId == organizationId.Value && q.Any(a => a.DateTime >= lastMonth))
		.RavenCountAsync(cancellationToken);
```

**Comment by ayende** [comment]
Your query is wrong.
You are asking to get the count of the results of the query, or the aggregated count per group by?
You are also trying to do this: ` q.Any(a => a.DateTime >= lastMonth)`

But the query happens *after* the group by operation, there is no way to ask this. 

What you want is something like:

```
	var usersActive = await dbSession.ActivityLessons.GroupBy(g => new {
			UserId = g.User.Id,
			OrganizationId = g.Organization!.Id
		}).Select(x => new
                            {
                                x.Key.UserId,
                                x.Key.OrganizationId,
                                LastDateTime = x.OrderByDecending(q=>q.DateTime).First()
                            }).Where(q => q.OrganizationId == organizationId.Value && q.LastDateTime >= lastMonth))
		.RavenCountAsync(cancellationToken);
```

**Comment by JohnGalt1717** [comment]
I have data that has:

OrganizationId
UserId
DateTime of incident 
Length of time spent viewing.

It's logging data.

I want to get the number of unique users that are in the data for a given Organization and Date range. I have a separate query that is similar that needs to get the sum of the length of time spent viewing by organization and another that is similar where I need the length of time spent viewing for the user.

Normally I could do it in one of serveral ways:

(from al in ActivityLessons where al.OrganizationId = 1234 && DateTime > lastMonth select al.UserId).Distinct().CountAsync()

and for the sum:
(from al in ActivityLessons where al.OrganizationId = 1234 && DateTime > lastMonth group al by al.UserId into g select new {UserId = g.Key, Length = g.Sum(x => x.Length)}).ToArrayAsync()

and
(from al in ActivityLessons where al.OrganizationId = 1234 && DateTime > lastMonth select al.Length).SumAsync();

These don't work in Raven, and I'm trying to understand why and how to get to the same equivalent.  The why is just as important so that I'm not failing every time I try this because this is Dashboard 101 and managers love their dashboards and I'm the "Stats Guy" so I get to do lots of stats queries.

I'm fine with forcing them into pre-defined indexes for the most part, but I have an eye on a dynamic reporting tool that allows users to pick fields and group by them, aggregate by them etc. and it dynamically generates the linq query and returns the data. (i.e. sort of like a grid driven Power BI) so I'm trying to figure out how I can generate these reliably, especially when the results are always transformed to a DTO and the filtering etc coming in will use DTO field names which may or may not match those that are actually stored in the DB.  It seems like I have to create some sort of translation table for the DTO to the database and convert the field names in the data coming in from the client to the database names to be able to do this because select then where doesn't appear to work in most cases, and then group by with aggregates seems to be even more complex.  But I think that's because the rules of the query engine in RavenDb are a black box to me, so I'm just trial and erroring to find the edges of inputs and outputs it finds acceptable and then bugging you to understand why (which I'd really like to not waste your time obviously)

**Comment by ayende** [comment]
The way to handle that is to use a map/reduce index, something like:

```
// map
from e in docs.Events
select new
{
    e.OrganizationId,
    e.HappenedAt.Date,
    e.UserId,
     e.TotalDuration // seconds
}

// reduce
from result in results 
group result by new { e.OrganizationId, e.UserId, e.Date } into g
select new
{ 
   g.Key.OrganizationId,
   g.Key.Date,
   g.Key.UserId,
   TotalDuration = g.Sum(x=>x.TotalDuration)
}
```

The end result is aggregation by user / organization and date.

You can then ask the following questions on the index:

```
from index 'Events/Aggregated'
where Date > $lastMonth
select facet(UserId, '{"PageSize": 0}') as DistinctUsers, facet(sum(TotalDuration)) as TotalDuration
```

The output here gives the number of distinct users and the total duration.

I admit that the output isn't the nicest, however. 

The distinct users value is the `RemainingHits` and the sum is in `TotalDuration.Sum`
