### ISSUE TITLE
LoadDocument in index creation throws exception for dynamic collection name

### ISSUE THREAD

**Issue by BickelLukas** [ravendb/ravendb#14784]
We want to create an index that indexes documents with dynamic fields from different collections.
Some of those fields are references to other documents and we need to resolve those references in the index.

The Lamda expression we have is this: 
```cs
from entity in entities
let definition = LoadDocument<Definition>(entity.Type)
select new {
  _ = from field in entity.DynamicFields
        let fieldDefinition = definition.Fields[field.Key]
        let value = fieldDefinition.IsReference ? LoadDocument<Entity>(field.value, fieldDefinition.CollectionName) : field.value
        select CreateField($"Fields_{field.Key}", value)
}
```

The Problem here is the following statement:
 `LoadDocument<Entity>(field.value, fieldDefinition.CollectionName)`

We get the following exception when trying to create the index: 
```
"Invalid argument in LoadDocument. String constant was expected but was 'Convert' with value 'Convert(<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.definition.Value.CollectionName, String)'."

"   at Raven.Client.Documents.Indexes.ExpressionStringBuilder.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   "
```

However, when we omit the collectionName Parameter in the Lambda Expression and then adjust the index manually through the web interface, everything works.

**Comment by garayx** [comment]
Hi

Can you submit a unit-test that reproduces the exception? 
https://ravendb.net/docs/article-page/5.4/csharp/start/test-driver

What is the index definition, after you edit the index through studio? You can see it in "Copy C#"
![image](https://user-images.githubusercontent.com/16625387/186387309-222164c5-bb1a-4068-9680-ece5cd6754af.png)

**Comment by ayende** [comment]
There is no need for a unit test. That is by design.
The string that you pass to the `LoadDocument` must be known at indexing time, so we'll know what collections we'll need to scan.
That is an important consideration for several implementation decisions.

Editing this manually will result in us not properly tracking the references.

**Comment by ayende** [comment]
If you want to track a value from multiple collections, you need to do:

```
let reference = LoadDocument<User>(doc.Owner) ?? LoadDocument<Company>(doc.Owner)
```
