### ISSUE TITLE
Indexing Consequences to using Guids?

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#14976]
Typically there is an issue with Guids and sorting and indexes getting fragmented. The documentation doesn't say so I wanted to ask before I shot myself in the foot: 

Is there a consequence for indexing on the keys if they're Guids?

If there is, do you have a recommended sequential Id generator?

Might want to add commentary to the documentation on this.

Thanks!

**Comment by ayende** [comment]
Guids are larger and unsorted. It would be easier to have a sequential ids, and RavenDB support those.
The documentation you seek is here: 

https://ravendb.net/docs/article-page/5.4/csharp/client-api/document-identifiers/working-with-document-identifiers

There is also this:
https://ravendb.net/learn/inside-ravendb-book/reader/4.0/2-zero-to-ravendb#document-identifiers-in-ravendb

**Comment by JohnGalt1717** [comment]
Thanks. I saw these. The issue is that I’m trying to avoid incremental ids passed to the client side, hence I want to use Guids because (I’m fine working with them) then I can have one Id value instead of 2 which in most cases I could think of resulted in smaller total size for the indexing. 

But if I just use Guid as the type in .net for the then the indexability is the issue.  The documentation mentions using string as the type and setting it to empty and then the server will create a guid for you.

is that a sequential and thus sortable and indexable guid it’s creating?  Using string.empty seems dangerous because then required references in other documents could easily end up with a reference of string.empty because of a bug. Ideally I was hoping to pre-assign a sequential guid at document creation so that that class of bugs could be avoided. 

I couldn’t find anything in raven that is doing this nor does the documentation outline that what raven is generating for you in the string.empty case is sequential. 

And, because I’m aware of mssql versus MySQL sorting versus whatever else for guids, I’m not satisfied that my own comb that I’ve used in the past for sql server would work here short of explicit guidance. 

Ideally there would be a client function in the c# library that would generate a sequential guid that was sortable. 

Short of that Id like some guidance on:

1. Is this string sort order for guids?  If so do you have a preferred sequential guid generator that you know works for indexing? If there isn’t, can you give guidance here?
2. Should guid ids still be of type string in .net or is there a way to use Guid as the type?


Ultimately I think it would be a significant win if there was an inbuilt sequential guid generator that we could get access to. I would then inherit all my documents from a base abstract class that on instantiating would generate the new Id for me eliminating an entire class of bugs while also obfuscating sequentialness of the ids client side. 

Alternatively, some guidance in using the standard string ids but obviscating without crazy hashing overhead(expensive when streaming transformed dtos directly to clients) as suggested elsewhere would be appreciated. 

Thanks! 

PS: 

I've been able to use the NewId library to generate these into a string field and it appears to work as expected and they're sorted properly.

Ideally I'd love to use https://github.com/andrewlock/StronglyTypedId so that I can type my references in .net, but despite implementing implicit casting and the newtonsoft type serializer with it, Raven tries to create a new id value and assign it.  Is there any way to get this working? (the holly grail would be these as strongly typed ids using NewId to generate the string values backing them that serialize to just a string in the database and everything was properly sorting so that indexes didn't get fragmented and all of the classes of bugs that these protect against would be avoided)

**Comment by ayende** [comment]
If you need Guids, use them.
There is _some_ efficencies issues, but I doubt that you'll really notice unless you are benchmarking storage performance.

The identifiers are always treated as strings, yes. You can just use `Guid.NewGuid()` to generate it, that is what we are doing on the serer side on that case.

It is not sortable, and indexable just on the full value, of course.

Note that the ID is a string, not a GUID.

If you want to make it sortable, you can use:

doc.Id = DateTime.Now.ToString("yyyy-MM-ddThh:mm") + Guid.NewGuid();

And that would give you good sorting here for the id.


To answer your questions.

1. String sort, yes. Seqeuntial, just make sure that it is sorted lexically.

2. Use a string, yes.

Note that by design, RavenDB accepts only string ids, and doesn't actually care about its content.
The details on what you put thee are entirely up to you.




This may also be a good read for your scenario: 

https://ayende.com/blog/188257-B/avoiding-non-string-identifiers-in-ravendb

**Comment by JohnGalt1717** [comment]
Ok, thanks. Might want to consider updating the documentation to make it clear about perf impacts and directly there provide guidance on using Guids that are sequential etc. (might make sense to embed a function that does so as the default when using Guids server side and provide the client side the same implementation?

**Comment by ayende** [comment]
In general, that is something that you only worry about this only at the very edge, and generally not something that you should worry about. And we would usually recommend that you use either hilo or let RavenDB handle that.
