### ISSUE TITLE
License not updated from the setting.json file.

### ISSUE THREAD

**Issue by sudiplamsal00** [ravendb/ravendb#14972]
Hi, We are having issue in changing the license from community version to developer version. Although the basic setup is fine, and the service is up, we are unable to updated the license using the  License.Path in "settings.json"  as described by the RavenDB setup guide. We tried using "License" key and value as well but no success. Is there any way to achieve that, as we need to change the license manually in the development environment.

Our setting is something like this:
```
{
"Setup.Mode": "None",
  "DataDir": "/data/RavenData",
  "Security.Certificate.Path": "/ssl/cert.pfx",
  "Security.Certificate.Password": "1",
  "ServerUrl": "https://0.0.0.0",
  "ServerUrl.Tcp": "tcp://0.0.0.0:38888",
  "PublicServerUrl": "https://${RAVENDB_URL}.url.us",
  "PublicServerUrl.Tcp": "tcp://${RAVENDB_URL}.url.us:38888",
  "Security.AuditLog.FolderPath": "/data/auditlog",
  "License.Path": "/ssl/license.json",
  "Logs.Mode": "Information",
  "License.Eula.Accepted": "true" 
}
```

**Comment by DejanMilicic** [comment]
You need to restart RavenDb for changes in settings.json to be picked up. Have you tried that?

**Comment by sudiplamsal00** [comment]
Yes, we have created service for ravendb and restarted it multiple times after the changes in the setting.json file.

**Comment by ayende** [comment]
The license is picked up from the `settings.json` only on first use. Afterward, you need to update the license through the API / Studio.
