### ISSUE TITLE
Documentation for NodeJs API

### ISSUE THREAD

**Issue by hamishcrittenden** [ravendb/ravendb#15045]
Hi Team 

I'd like to see the Node.JS docs provide the same content as c# docs assuming there is functional parity. 

I'm particularly keen to see documentation on fanout and recurse in Node.JS. 

I'm migrating an application stack from dotnet to nestjs and this would greatly assist. 

Thanks!

**Comment by ml054** [comment]
Hi @hamishcrittenden 

I'd like to make sure that you are aware that node.js can use javascript indexes which are strongly typed. 

Examples:
https://github.com/ravendb/ravendb-nodejs-client/blob/dd92506e00ad387bb25640a87e2767a3cd7b62a6/test/Issues/RDBC_615.ts#L117
https://github.com/ravendb/ravendb-nodejs-client/blob/a5d68ada49b2c8756da7e1879d3f9d6251574732/test/Ported/QueryTest.ts#L863

For fanout examples are here: 

https://github.com/ravendb/ravendb-nodejs-client/blob/6d0d19aa3f2188d2943ac5bae5d1fa0bd31be8f0/test/Ported/Indexing/JavaScriptIndexTest.ts#L559

Of course you can always fallback to c# indexes.
Example:
https://github.com/ravendb/ravendb-nodejs-client/blob/7e4621fe5348935b26b461fabd32adbbc69ffb26/test/Ported/Issues/RavenDB_16334.ts#L99

This might be quite useful when you migrate application from c# to node.js

I think most of examples are self explanatory + you can use c# documentation as reference - we try to keep syntax as close as possible to dotnet version.


I need to check if we support recurse in javascript indexes. Will get back to you on that topic. 

I hope below links helps. If not - just ping us - we will try to elaborate and explain. 

Good luck with your migration. :) I hope will go smooth.

**Comment by ml054** [comment]
For reduce I found this:
https://ayende.com/blog/185537-A/recursive-indexing-in-ravendb
