### ISSUE TITLE
Linq support for case-sensitive string comparsion

### ISSUE THREAD

**Issue by adambajguz** [ravendb/ravendb#15121]
Currently `RavenQueryProviderProcessor` forbids the usage of case-sensitive string comparison.

https://github.com/ravendb/ravendb/blob/670591c48af1a6e02ac88a0f155b58414f2d0f7c/src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs#L794-L820

Isn't it possible to add the support for `StringComparison.CurrentCulture` and `StringComparison.Ordinal` via changing the code to sth like below?

```csharp
  bool exactOverride = _insideExact;

  if (comparisonArg != null 
         && comparisonArg.NodeType == ExpressionType.Constant 
         && comparisonArg.Type == typeof(StringComparison)) 
     { 
         var comparisonType = ((ConstantExpression)comparisonArg).Value; 
         switch ((StringComparison)comparisonType) 
         { 
             case StringComparison.CurrentCulture: 
             case StringComparison.Ordinal: 
                 stringExactOverride = true,
             break;

             case StringComparison.CurrentCultureIgnoreCase: 
             case StringComparison.OrdinalIgnoreCase: 
                 break; 

             default: 
                 throw new ArgumentOutOfRangeException(); 
         } 
     } 
  
     DocumentQuery.WhereEquals(new WhereParams 
     { 
         FieldName = fieldInfo.Path, 
         Value = GetValueFromExpression(constant, GetMemberType(fieldInfo)), 
         AllowWildcards = false, 
         Exact = exactOverride
     }); 
```

Also why `StringComparison.InvariantCultureIgnoreCase` and `StringComparison.InvariantCulture` aren't included in the switch?

**Comment by ayende** [comment]
That would only be applicable for dynamic queries, however, not for static indexes.
IIRC, that is the reason for this behavior. I don't think that your proposed change would have an impact, though.

Can you send a PR for this?

**Comment by adambajguz** [comment]
I don't know what will happen for static indexes; however, for dynamic ones I've discovered that running a query with `exact()` will cause a creation of an index with some field(s) marked as exact even if there is already a similar index differing only in `exact` flag state. After finding that I've thought that adding `StringComparison.Ordinal` etc. support may be doable.

I'll prepare the PR.

**Comment by adambajguz** [comment]
@ayende I've created the PR for the issue. I don't know Raven's internals very good, so all remarks are highly appreciated.

**Comment by maciejaszyk** [comment]
Hi @adambajguz ,
the reason why Raven creates a new field with `exact()` tag is about how we analyze terms during indexing. Raven's default analyzer will lowercase your term before it is written into an index. To change this behavior you've to explicitly add config for indexing. In static indexes, you can always set `Exact` in the indexing configuration but you cannot do that for AutoIndexes, so Raven will create a second field with this option.

BTW:
Raven's `where` method in LINQ contains a second parameter for exact, so maybe this is the way to go.

**Comment by adambajguz** [comment]
Hi @maciejaszyk,
From what I've discovered during my experiments in Studio: Raven will create an auto index (not a field) with `exact` set for a field when `exact()` is used in the query, regardless whether there is already a similar index (for a query without exact) or not.

_"Raven's where method in LINQ contains a second parameter for exact, so maybe this is the way to go."_ - I know that, but it is Raven specific, I'd rather have a full support for a `StringComparison` because this does not require a dependency to Raven, which is sometimes useful.

I didn't verify how `Where with exact` works but I suspect it simply sets `_insideExact` to `true`.

For example:
```csharp
List<Employee> employees = await asyncSession
    .Query<Employee>()
    .Where(x => x.FirstName == "Robert", exact: true)
    .ToListAsync();
```
generates `from Employees where exact(FirstName == 'Robert')` instead of `from Employees where FirstName == 'Robert'`, and there is nothing in the [docs](https://ravendb.net/docs/article-page/5.4/Csharp/client-api/session/querying/how-to-query-with-exact-match) about the need of creating a static index before using `Where with exact`. 

I've created the PR that includes a few tests #15126, and everything related to the change seems to work. I don't understand the reason why `Where with exact` exists but `StringComparison.Ordinal` etc. support in `Equals`, `StartsWith`, and `EndsWith` doesn't and can't. 

Is there any possiblity that `Where with exact` is useful for comparisons on types other than string? If there's no, and `Where with exact `really simply sets `_insideExact` to `true`, then why it even exists? I hope you understand my point :)

@ayende "That would only be applicable for dynamic queries, however, not for static indexes." - what happens when `Where with exact (exact=true)` is used when a static index is queried (index name is set in `.Query()`) but exact is not set in the indexed fields? Is the query executed with case-insensitive comparisons or does the server throw some error?

**Comment by ayende** [comment]
There is an issue with issuing both exact and non exact queries on dynamic queries, see: 

https://issues.hibernatingrhinos.com/issue/RavenDB-19467/Dynamic-query-on-a-field-using-exact-and-without

See also here: https://ayende.com/blog/198401-A/ravendb-indexing-exact?key=adc0a9fa6ba544adb3b04413ec60c2f2

**Comment by arekpalinski** [comment]
Addressed in https://github.com/ravendb/ravendb/pull/15202
