### ISSUE TITLE
Menu Item "Studio Configuration" of "Manage Server" menu invokes "Server Settings"

### ISSUE THREAD

**Issue by w0pr** [ravendb/ravendb#15179]
RavenDb version 5.4.4

Studio Configuration not accessible (only by directly pasting /studio/index.html#admin/settings/studioConfiguration)

Note Cursor position and URL in browser status line.

![image](https://user-images.githubusercontent.com/8257055/198042607-d243245b-2283-432a-a99b-6d34c1a6e65b.png)

**Comment by ml054** [comment]
Hi, @w0pr 

Could you paste screenshot from tooltip you can see after hovering over green lock icon in status bar (on the left from Node A in footer)?

**Comment by w0pr** [comment]
![image](https://user-images.githubusercontent.com/8257055/198164577-d53280f7-4561-4bfe-8577-95af639df560.png)

**Comment by ml054** [comment]
Thanks for clarification. I'd opened an issue, so you can track progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-19489/Menu-items-are-not-clickable-even-when-user-has-an-access

**Comment by w0pr** [comment]
> Thanks for clarification. I'd opened an issue, so you can track progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-19489/Menu-items-are-not-clickable-even-when-user-has-an-access

As an addition: All (I haven't actually check *all*) other menu items are working, it just seems that link for serverSettings got duplicated onto studioSettings one.

**Comment by ml054** [comment]
Wait so it means there is wrong link?

**Comment by w0pr** [comment]
Yes

> Wait so it means there is wrong link?

Yes.
![image](https://user-images.githubusercontent.com/8257055/198272578-f62681f4-097c-44f0-a76d-1a332cad76ca.png)

Also issue does not seem to be public yet (https://issues.hibernatingrhinos.com/issues?q=RavenDB-19489)

**Comment by ml054** [comment]
Hi,

@w0pr I changed the visibility of this issue + managed to found root cause. Git blame says it was... me. 

We should fix that this week. Thanks again for your report.

**Comment by ml054** [comment]
fixed: https://github.com/ravendb/ravendb/pull/15190 

@w0pr Thanks :)
