### ISSUE TITLE
RavenDB Studio doesn't (visually) link related documents when the ID doesn't match the default IdentityPartsSeparator (/)

### ISSUE THREAD

**Issue by mateuszanini** [ravendb/ravendb#15177]
When viewing an eligible document, on the "Related" tab, no link to related documents is displayed. This occurs when the ID generation strategy differs from the default one (`[collectionName]/[value]-[node]`), changing the value of `IdentityPartsSeparator` when creating the DocumentStore or using Guid, for example.

**Image 1:** Customers collection.
![customers](https://user-images.githubusercontent.com/20796437/198018237-70f14f10-fd14-4fcf-9b05-840d43bb78b1.PNG) 

**Image 2:** Orders collection.
![orders](https://user-images.githubusercontent.com/20796437/198018340-6db87ce2-6e80-4c27-a887-e6f1c88c0630.PNG)

**Image 3:** Order detail with "valid" related document.
![order-1-related-document](https://user-images.githubusercontent.com/20796437/198018361-06b40539-0d90-4db2-8afd-666077923de0.PNG)

**Image 4:** Order detail with "invalid" related document.
![order-2-related-document](https://user-images.githubusercontent.com/20796437/198018374-68fd06ba-b9b5-4118-93ef-9a9fdf471036.PNG)

Note that the `Includes` feature for query works as expected, without performing an additional query to the server.
```c#
Order order = session
    .Include<Order>(x => x.Customer)
    .Load("orders-2-A");

// this will not require querying the server!
Customer customer = session
    .Load<Customer>(order.Customer);
```

- **RavenDB version:** 5.4.4
- **Backup to reproduce scenario:** [2022-10-25-17-56-52.ravendb-RelatedDocumentIssue-A-backup.zip](https://github.com/ravendb/ravendb/files/9869173/2022-10-25-17-56-52.ravendb-RelatedDocumentIssue-A-backup.zip)

**Comment by garayx** [comment]
Hi

Thanks, for the detailed reproduce, currently we only highlight ids with default `IdentityPartsSeparator` (`/`).

There is a ticket opened to fix this issue: https://issues.hibernatingrhinos.com/issue/RavenDB-16665/Show-guid-type-Ids-in-the-related-documents-list

Please note, this doesn't affect the Client API, and only studio issue.

**Comment by ayende** [comment]
For reference, this is handled here: 
https://github.com/ravendb/ravendb/blob/f20f89256180826c7e00c0048e5a4a6a266bbdac/src/Raven.Studio/typescript/common/helpers/database/documentHelpers.ts#L18

And the Studio is basically checking any string that match: `/\w+\/\w+/ig`
