### ISSUE TITLE
Warning: swap storage type warning

### ISSUE THREAD

**Issue by Stocki916** [ravendb/ravendb#15191]
Dear community,

on our cluster our cluster operator saw the attached warning with information about "swap storage type warning", which includes information about that the OS swapped pagefile to a hdd drive but there is an available ssd drive which is much faster.
But in the end, the server does not have any hdd, everything runs on a central storage, which is completely build with ssds and the available memory is enough, so that there was no need to swap some data.

Does the operator need to react here or just ignore the message? :-)

Thanks in advanve and best regards,
Sebastian

![image](https://user-images.githubusercontent.com/60972798/198576039-4db647f4-2af9-4dc6-bb47-b6e61cb3b152.png)

**Comment by ayende** [comment]
You will get this warning if ravendb things this is the situation. If it is wrong (because the way it detects that), just ignore it.
