### ISSUE TITLE
500 response with smuggler export between different raven versions

### ISSUE THREAD

**Issue by Yuzal** [ravendb/ravendb#15354]
There seems to be a breaking change between version 5.3.103 and 5.4.1 with an export function from smuggler.
Clientversion 5.4.1 cant send a valid exportrequest via smuggler when the server is 5.3.103.
I was not getting any Exceptions but thanks to the admin log in raven studio i found a http 500 response with some parsing error

`var filePath = "file.ravendbdump";`
`var exportOperation = await _store.Smuggler.ExportAsync(exportOptions, filePath );`
`_ = await exportOperation.WaitForCompletionAsync();`

i am not sure if this is an intended feature because it took a while to find the problem why my code didnt work.

**Comment by ayende** [comment]
You are using a 5.4 *client* to talk to a 5.3 *server* ?
That is not supported.

See: 
https://ravendb.net/docs/article-page/5.3/csharp/client-api/faq/backward-compatibility#compatibility---ravendb-4.2-and-higher

**Comment by Yuzal** [comment]
Ahh my bad i guess. 
rtfm!
Thanks for the link!
