### ISSUE TITLE
Running the official RavenDB Docker image throws an Exception

### ISSUE THREAD

**Issue by lalibi** [ravendb/ravendb#15375]
I tried running the [RavenDB Docker image](https://hub.docker.com/r/ravendb/ravendb/) using:

```powershell
docker run -p 8080:8080 ravendb/ravendb:windows-latest
````

, as per the official instructions, but when I hit `http://localhost:8080/` I get the following Exception.

```json
{
    "Url": "/auth/",
    "Type": "Raven.Client.Exceptions.Routing.RouteNotFoundException",
    "Message": "There is no handler for path: GET /auth/",
    "Error": "Raven.Client.Exceptions.Routing.RouteNotFoundException: There is no handler for path: GET /auth/\n   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\\Builds\\RavenDB-Stable-5.4\\54018\\src\\Raven.Server\\Routing\\RequestRouter.cs:line 230\n   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\\Builds\\RavenDB-Stable-5.4\\54018\\src\\Raven.Server\\RavenServerStartup.cs:line 176"
}
```

I even tried the [`run-linux.ps1`](https://github.com/ravendb/ravendb/blob/v5.2/docker/run-linux.ps1) script, but the result was the same. 

Is this a bug or am I missing something?

**Comment by ayende** [comment]
There is indeed no such route for ravendb.
Is it possible that you have run something else there in the past and it remembers the path?

Can you try using a different port to ensure that this isn't the case?

**Comment by lalibi** [comment]
> There is indeed no such route for ravendb. Is it possible that you have run something else there in the past and it remembers the path?

Yes, it was probably a `301` response from some other image I've run in the past. I should have thought of that.

Thank you for your time, I really appreciate it.
