### ISSUE TITLE
Failed to execute cluster transaction due to index does not match the transaction index

### ISSUE THREAD

**Issue by ryanheath** [ravendb/ravendb#15387]
Lately I see this exception increasingly:

```
Raven.Client.Exceptions.ClusterTransactionConcurrencyException: Failed to execute cluster transaction due to the following issues:
Guard compare exchange value 'rvn-atomic/[doc-id]' index does not match the transaction index's 0 change vector on [doc-id]
Concurrency check failed for putting the key 'rvn-atomic/[doc-id]'. Requested index: 0, actual index: 12536773
```

The document does not exists upon lookup. But the compare exchange value do exist.
I suspect the exchange value might be a leftover from another 'failed' clusterwide transaction?

How can I resolve this error? Can I delete the exchange value when the requested index was 0 ?
How can I find 'orphaned' compare exchange values without a corresponding document?

// Ryan

**Comment by ayende** [comment]
You are trying to save the document without loading it from the database?

**Comment by ryanheath** [comment]
Yes, that might be the case here, we save a bunch existing of documents and create new documents along with 
in the same transaction.

**Comment by ayende** [comment]
If you create a new document (by not loading it from the server), then cluster wide tx would fail, since it assumes that you are conflicting on this.

Otherwise, there is no way for the tx to know what is the _previous_ state.

**Comment by ryanheath** [comment]
That's weird, because this problem only happens occasionally, (maybe even just recently) 
and we have been creating a lot of new documents within a cluster wide tx with success.

How can I find 'orphaned' compare exchange values without a corresponding document?
It seems I cannot query those values.

// Ryan

**Comment by karmeli87** [comment]
How do you generate the id? can it be that you deleted that document and now you are trying to re-create it?
I was able to repro something similar to what you have: https://issues.hibernatingrhinos.com/issue/RavenDB-19629

**Comment by ryanheath** [comment]
Yes, in our scenario that might be possible.
We generate the id by ourselves,
clean up process can delete the document (after a few months/years),
creation process can add a document with same id again.

// Ryan

**Comment by karmeli87** [comment]
There is no easy way to find all 'orphaned' compare exchange, you need to list all of the atomic guards and try to find them in the storage.
you can list them with something like this:
```
var result = await store.Operations.SendAsync(new GetCompareExchangeValuesOperation<dynamic>("rvn-atomic/", start: 0, pageSize: 1024));
```

If your clean up process is deleting the documents via the session, you can simply delete them as part of a cluster transaction.
If you are deleting by query, currently you will need manually to take care of the compare exchange leftovers.. 

Currently, if possible best option is to have new ids.

**Comment by ryanheath** [comment]
Yes, we'll add a clusterwide tx when deleting the documents.
It also makes sense, to be honest!

I'll see what I can do with the compare exchange values.
I have no idea how many documents are effected by this.

// Ryan
