### ISSUE TITLE
Docker image runs as root

### ISSUE THREAD

**Issue by rwkarg** [ravendb/ravendb#15403]
Example Dockerfile:
https://github.com/ravendb/ravendb/blob/86c6827225608e9bcb0d9aeccf78a434b7e0744f/docker/ravendb-ubuntu/Dockerfile.x64

Ideally the image should run as a non-root user that is created and configured in the container with minimal permissions to run RavenDB.

**Comment by rwkarg** [comment]
Non-root user setup appears to happen here for a non-Docker Linux installation:
https://github.com/ravendb/ravendb/blob/5a1294432f77cb456b5a123b3c118b0e2fbf4ce4/scripts/linux/pkg/deb/assets/ravendb/debian/ravendb.postinst#L8-L75

**Comment by ayende** [comment]
There is no requirement from ravendb to run as root.
A PR on this would be greatly appreciated.

**Comment by rwkarg** [comment]
The update itself is relatively simple. Something like:
```
RUN adduser --disabled-login --disabled-password --system --shell /sbin/nologin --home /var/empty --no-create-home --quiet --group ravendb

USER ravendb
```

The issue I've run in to is that an existing database that was running as `root` would not be able to update to a new image with a non-root user since it's already created data files as `root` and the new `ravendb` user won't have access to them.

The only non-breaking update I can see is to make a new class of images with an explicit `non-root` tag designation and keep the existing images with the root user to avoid breaking existing users. Users would need to opt-in to the new tag explicitly.

We have a solution that works for us (we're already creating our own images that additionally add some internal certificates where we can also add the `ravendb` user), but that isn't a general solution.

**These are the options I see for updating the Dockerfiles**. Let me know if one of these is the desired path or if there's another option to consider to address this.
1. Create and maintain a second set of image tags with the non-root user and allow existing usages to migrate on their own schedule.
1. Update existing image to use a non-root user and document the breaking change. (Feels scary)
1. Do nothing. Offer documentation for users on how to create their own image based on the root images with a non-root user.

**Comment by ayende** [comment]
We can also grant permissions on the ravendb data directory in the docker file, no?
That would handle migrations, I think

**Comment by rwkarg** [comment]
The issue is with volumes that get mounted from outside the container (either local volumes on the host or persistent volumes) where the container itself can't set those permissions once it's running as a non-root user.

The following scenario with a mounted data volume is where there's a break:
1. Initially start cluster with existing `root` container
1. `root` container creates a database
  a. Data files created owned by `root`
1. Stop container to upgrade
1. `ravendb` (non-root) container runs
1. `ravendb` container tries to access existing Data files
  a. Data files are owned by `root`
  --> `ravendb` user is unable to get access to the existing files owned by `root`

An operator can run as `root` on the host to update the ownership of data files, but I don't see a way to automatically make that ownership update without some outside operator intervention.

**Comment by ayende** [comment]
Good point, I agree, I can't think of doing that with backward compatibility

**Comment by ppekrol** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-18888/Running-as-a-non-root-user-in-Linux-containers
