### ISSUE TITLE
Update dockerfile base images

### ISSUE THREAD

**Issue by rwkarg** [ravendb/ravendb#15402]
The 5.0 tag for `runtime-deps` has been deprecated as EoL and is on longer listed (though it can be pulled):
https://github.com/dotnet/dotnet-docker/commit/f87fbd0b02d9ad90450a32626245594baa4b0590

and is still being used as the base for images.
https://github.com/ravendb/ravendb/blob/5a1294432f77cb456b5a123b3c118b0e2fbf4ce4/docker/ravendb-ubuntu/Dockerfile.x64#L1
https://github.com/ravendb/ravendb/blob/5a1294432f77cb456b5a123b3c118b0e2fbf4ce4/docker/ravendb-ubuntu/Dockerfile.arm32v7#L1
https://github.com/ravendb/ravendb/blob/5a1294432f77cb456b5a123b3c118b0e2fbf4ce4/docker/ravendb-ubuntu/Dockerfile.arm64v8#L1

The currently published versions are 6.0 and 7.0:
https://hub.docker.com/_/microsoft-dotnet-runtime-deps

There doesn't appear to be anything specifically impacting in 5.0 vs 6.0/7.0 versions since this is just the runtime dependencies, but there do appear to be some extra certificates that are installed only in the 5.0 tag. Updating would at least resolve any confusion of referencing an unlisted tag.

**Comment by ppekrol** [comment]
Thanks @rwkarg 
We will update those. You can track the progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-19630/Update-docker-dotnet-runtime-deps-from-5.0-to-6.0-in-5.2-and-5.3-branches-and-7.0-in-5.4-branch
