### ISSUE TITLE
Intl.NumberFormat not supported in JavaScript indices

### ISSUE THREAD

**Issue by casperOne** [ravendb/ravendb#15416]
I am trying to use [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) in my JS index to create a sort-stable string (it is a value combined with other values, so a number can't be used here).

However, when I try and call `Intl.NumberFormat`, to create a formatter, I suspect it is returning `undefined`, which then causes the call to `format` to return `null`.

Version: 5.4.5 (cloud hosted, if that matters)

To replicate, populate a test database with sample data through the settings in RavenDB.

Then, create an index with the following map/reduce

Map:

````
map(
    "Orders", 
    (t) => {
        const formatter = Intl.NumberFormat(
                // NOTE: The same behavior occurs whether or not this is 'en-US' or undefined
        	'en-US',
        	{ 
        	  minimumIntegerDigits: 10 
        	  , maximumFractionDigits: 0 
        	  , useGrouping: false
        	}
        )
        
        return t.Lines.map(l => ({ 
            Product: l.Product,  
            Quantity: sortKeyIntegerFormatter.format(l.Quantity) 
        }))
    }       
)
````

Reduce:

````
groupBy(
    x => x.Product
)
.aggregate(
    g => ({
        Product: g.key,
        Quantity: g.values[0].Quantity
    })
)
````

The output will be (this is truncated):

<html>
<body>

Product | Quantity
-- | --
products/11-A |  
products/42-A |  
products/72-A |  
products/14-A |  
products/51-A |  

</body>
</html>

That said, I suspect it has something to do with the fact that this is not using V8/a JS engine more fully compliant with ES2022, etc.

**Comment by ayende** [comment]
One option is to grab the polyfill from here: https://formatjs.io/docs/polyfills/intl-numberformat/

And then add that as additional source to the index. 

Also note that you have `formatter` variable, but using `sortKeyIntegerFormatter`.

Given your needs, this is a simpler workaround.


```
map(
    "Orders", 
    (t) => {
        
        return t.Lines.map(l => ({ 
            Product: l.Product,  
            Quantity: String(Math.round(l.Quantity, 0)).padStart(10, '0') 
        }))
    }       
)
```

**Comment by casperOne** [comment]
@ayende Thanks, we've done something like this and encoded it so that it is compact and have stability when sorted.

I think the general gist of this is that the JS engine should support the latest version of JS (ES2022 IIRC), as there are a *lot* of features that have to be coded around because of lack of support.

This is one of them, lack of spread operator is another...  There's a bunch.

**Comment by ayende** [comment]
We are working on V8 integration, hopefully in 2023
