### ISSUE TITLE
RavenDB.TestDriver not working with dotnet 7.0.1

### ISSUE THREAD

**Issue by luis-fss** [ravendb/ravendb#15483]
System.InvalidOperationException : Could not find a matching runtime for '6.0.11+'. Available runtimes: - 7.0.1

**Comment by luis-fss** [comment]
This error will only occur if dotnet 7 is the only version installed.

**Comment by luis-fss** [comment]
Ah, I see the repository has already been patched, can we have a new version?

https://github.com/ravendb/ravendb/blob/0b91a4578b1f871b2e7b66f4a3663a66cec7b34d/src/Raven.Embedded/ServerOptions.cs#L14

**Comment by ppekrol** [comment]
Hi @Lukkian 

We are planning to release next 5.4 in first half of January. You can download nighty builds (5.4.100) from https://ravendb.net/download if needed. There is also a MyGet repository available here: https://myget.org/gallery/ravendb

**Comment by luis-fss** [comment]
Hi @ppekrol

Ok, thank you.

**Comment by Shaddix** [comment]
Same thing with .net 8 release
(`Could not find a matching runtime for '7.0.14+'`)

**Comment by ppekrol** [comment]
Hi @Shaddix 
The required runtime that needs to be installed is not related to your application (does not matter if you are using net462, net7 or net8), but to the Embedded RavenDB server requirement within the test driver. Underneath test driver spawns a separate process with RavenDB Server and since that server is not compiled for any specific platform, then the runtime is not embedded, hence the requirement to have the runtime installed.

**Comment by Shaddix** [comment]
yep, I understand that.
So, do you have plans to update the Embedded to net8, so net7 runtime could be removed from build agents?

**Comment by ppekrol** [comment]
Hi, yes, next 6.0 will be working on .NET 8, you already can check out nightly builds, the numbering for .NET 8 is 6.0.100-nightly-date.

We will also bump 5.4 version but this will be around May 24', since this is an LTS build we want it to run on LTS .NET version as well.

**Comment by Shaddix** [comment]
Thanks a lot!

**Comment by Shaddix** [comment]
Sorry for bothering, I noticed that 6.0.100 packages were published to MyGet twice, but were deleted shortly after.
Are there some temporary problems, or is it better not to expect 6.0.100 on MyGet soon?

**Comment by ppekrol** [comment]
Thanks @Shaddix for pointing that out. We have fixed the issue, package should appear there within next hour.

**Comment by tmofardinm** [comment]
@ppekrol I have the same problem with 6.0.4, trying to run inside docker on this image: mcr.microsoft.com/dotnet/sdk:8.0
but I get 

> Error Message:
>    System.InvalidOperationException : Could not find a matching runtime for '7.0.14+'. Available runtimes:
> - 8.0.1
> 
>   Stack Trace:
>      at Raven.Embedded.RuntimeFrameworkVersionMatcher.Match(RuntimeFrameworkVersion runtime, List`1 runtimes) in D:\Builds\RavenDB-Stable-6.0\60008\src\Raven.Embedded\RuntimeFrameworkVersionMatcher.cs:line 46
> 

So it's still depending on net7?

**Comment by ppekrol** [comment]
Hi @tmofardinm 
We will be releasing 6.0.100 with .NET 8 next week. My prev answer was about packages not being published to MyGet, apologies for the confusion.

**Comment by tmofardinm** [comment]
Great, thank you @ppekrol .
