### ISSUE TITLE
Is the 'admin' part of the HTTP REST API documented?

### ISSUE THREAD

**Issue by Bktero** [ravendb/ravendb#15565]
Hi

From [this comment](https://github.com/ravendb/ravendb/discussions/14511#discussioncomment-3259293), I have learned that it is possible to do this:

```bash
curl -X PUT -H "Content-Type: application/json" -d '{"DatabaseName": "name"}' http://localhost:8080/admin/databases
```

This 'admin' part of the REST API doesn't appear in the documentation: https://ravendb.net/docs/article-page/5.4/csharp/client-api/rest-api/rest-api-intro

Is it documented elsewhere? Thanks a lot.

**Comment by ayende** [comment]
They are not documented, mostly because the client API that uses them is the typical way to do so.
You can get a list of all the endpoints here: http://live-test.ravendb.net/debug/routes

**Comment by Bktero** [comment]
If it is not documented, then it is probably not a good idea to try using it :/

The client API doesn't seem very convenient to me when writing a script to automate the setup of an environment. I have a bash script, and, at some point, I want to start RavenDB inside a Docker container and create a new database, before starting other containers that will need this database. How can I do it?

I can't find a way to do it with `rvn` (ChatGPT tells me to use `rdb create-database` but I can't find this anywhere else). The HTTP API + curl seems like an option but this is part of the admin (undocumented) API, hence this ticket.

I use Python to interact with RavenDB and creating database from this language doesn't seem possible neither...

**Comment by poissoncorp** [comment]
Hi @Bktero,
Creating a database in RavenDB from Python is possible via the [ravendb ](https://pypi.org/project/ravendb/) package. Here is an example.
```py
from ravendb import DocumentStore, CreateDatabaseOperation
from ravendb.serverwide.database_record import DatabaseRecord

x = DocumentStore(["http://127.0.0.1:8080"])
x.initialize()
x.maintenance.server.send(CreateDatabaseOperation(DatabaseRecord("YourDatabaseName")))
```
Here you can find more examples of Python client, especially working with a secured server if you need to pass the certificate.
https://github.com/ravendb/ravendb-python-client#working-with-secured-server

I hope it's going to help you!

**Comment by Bktero** [comment]
Good to know!

Is there a way to do the same thing (create a database) from a bash script?

**Comment by ayende** [comment]
Use the REST API, as you did above
