### ISSUE TITLE
Can OrderByDescending or OrderBy identify the property type?

### ISSUE THREAD

**Issue by bruno-alencar** [ravendb/ravendb#15631]
Is there any way to use generic OrderByDescending or OrderBy? The following method used by the OrderBy can not identify the property's type, so It sorts wrongly.

We are looking to create generic method to query and order by parameter. The only way found is to create passing the name.

We are using the method OrderByDescending which is represented by the code

**Raven.Client.Documents.LinqExtensions**

![image](https://user-images.githubusercontent.com/13769562/212389344-c3b6720f-627a-4d66-b0bf-31975f615bad.png)

When we are searching only with **string path** attribute to identify the property name, the type is defined by the OrderingType. The default value is **OrderingType.String**.

Example: If the property is a numeric value, the ordering might not identify the property as OrderingType.Long based on its name.

Using OrderByDescending that receives a function, the method is able to discover the type with **typeof(TK)**

**Raven.Client.Documents.Linq.RavenQueryableExtensions**

![image](https://user-images.githubusercontent.com/13769562/212389443-13069b7d-23cd-426a-9542-955d6a23df0b.png)

**System.Linq.Queryable**

![image](https://user-images.githubusercontent.com/13769562/212389511-0b9b9696-a430-4dc0-87ca-deab499acb32.png)

In this way, we have to generate an expression without the object properly. It`s a long way.

Do you have any suggestions for creating generic method abled to OrderBy and OrderByDescending without the OrderingType flag? Can you generate a new method abled to identify the property type and order correctly?

**Comment by ppekrol** [comment]
Hi @bruno-alencar 

A lot of those methods is only an addition to the regular System.Linq methods. The question is if you need to use the one with `string path` in your code? The ones from System.Linq perform auto-detection. At the moment we cannot change the behavior, because that would be a breaking change in our API.

What you could do is to write sth like:

```csharp
        public static IOrderedQueryable<T> OrderByDescendingAuto<T>(this IQueryable<T> source, string path)
        {
                        var memberType = GetPropertyOrFieldByPath(typeof(T), path);
			if (memberType == null)
				throw new InvalidOperationException();
				
			var orderingType = GetOrderingType(memberType);
			
			return source.OrderByDescending(path, orderingType);
			
			static string GetPropertyOrFieldByPath(Type t, string p)
			{
				// check ReflectionUtil
				// implement me
			}
			
			static OrderingType GetOrderingType(Type t)
			{
				if (type == typeof(long))
					return OrderingType.Long;
					
				return OrderingType.String;
			}
        }
```

Hope that it helps.
