### ISSUE TITLE
RavenDB Docker Windows support for LTSC 2022

### ISSUE THREAD

**Issue by danielmarbach** [ravendb/ravendb#15645]
Currently RavenDB Docker Windows uses LTS1809

https://github.com/ravendb/ravendb/blob/v5.4/docker/ravendb-nanoserver/Dockerfile#L3

would it be possible to support also LTSC2022 like powershell does?

https://hub.docker.com/_/microsoft-powershell

Otherwise, it is not possible to run the container on Windows 2022 based images

**Comment by gregolsky** [comment]
Hello,

I created an issue in our internal bugtracker. You can track the progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-19839/Create-Windows-docker-images-for-LTSC-2022
