### ISSUE TITLE
ravendb/ravendb:latest is on 5.3.108, instead of 5.4.100

### ISSUE THREAD

**Issue by nithinmohantk** [ravendb/ravendb#15669]
Today i tried to upgrade my docker containers from 5.3.x assuming with latest, i would be getting 5.4.100. Instead the version embedded on the following is 5.3.108 , I think you need to optimize the pipeline to avoid such corruption. 
OS: Ubuntu 
`docker pull ravendb/ravendb:latest`

**Comment by gregolsky** [comment]
@nithinmohantk Thank you for reporting the issue. Problem has been fixed:
```
$ docker run -it ravendb/ravendb:latest /opt/RavenDB/Server/Raven.Server --version
5.4.100
```

**Comment by nithinmohantk** [comment]
> docker run -it ravendb/ravendb:latest /opt/RavenDB/Server/Raven.Server --version

Perfect, tested and it works on linux. Thanks. Why doesn't the latest provide the windows architecture one, if it is muti-arch builds?  
![image](https://user-images.githubusercontent.com/453945/213443858-6d8be521-8a9d-46b2-be15-0c9291f15358.png)

**Comment by gregolsky** [comment]
We do not support multi-arch at the moment, however there is an open issue you can track progress on https://issues.hibernatingrhinos.com/issue/RavenDB-9167/Publish-Docker-multi-arch-images-to-simplify-consumption-of-docker-images
