### ISSUE TITLE
Behaviour of nullable DateTime filtering changes between v4.2 and v5.4

### ISSUE THREAD

**Issue by antmeehan** [ravendb/ravendb#15671]
We've just upgraded RavenDB server from v4.2.123 to v5.4.100 and have noticed a regression with querying against a nullable `DateTime` field. In v4.2 documents with a `null` value are included in a result where it is filtered using `>`, where as they are excluded in v5.4.

Using the following csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="NUnit" Version="3.12.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0"/>
		<PackageReference Include="RavenDB.TestDriver" Version="4.2.113" />
	</ItemGroup>
</Project>
```

And the following test:

````cs
public class GreaterThanDateTimeNullBehaviourTests : RavenTestDriver
{

	[Test]
	public void NullValuesIncludedInResult()
	{
		// Arrange
		var documentStore = GetDocumentStore();
		using (var session = documentStore.OpenSession())
		{
			session.Store(new MyDocument() { Value = DateTime.Parse("2023-01-01") });
			session.Store(new MyDocument() { Value = DateTime.Parse("2023-01-10") });
			session.Store(new MyDocument() { Value = null });

			session.SaveChanges();
		}

		// Act
		List<MyDocument> result;
		using (var session = documentStore.OpenSession())
		{
			result = session.Advanced.DocumentQuery<MyDocument>()
				.WhereGreaterThan(x => x.Value, DateTime.Parse("2023-01-05"))
				.WaitForNonStaleResults()
				.ToList();
		}

		Assert.AreEqual(2, result.Count);
	}


	public class MyDocument
	{
		public DateTime? Value { get; set; }
	}

}
````

This passes when using version `4.2.113`. But if you change the package reference to use `5.4.100`:

```xml
<PackageReference Include="RavenDB.TestDriver" Version="5.4.100" />
```

the test fails, since the document with a `null` value is excluded.

**Comment by maciejaszyk** [comment]
Hi @antmeehan,
since RavenDB 5.0 we use ticks when handling dates in queries. silently. You can read about this on ayende blog:
https://ayende.com/blog/190305-C/ravendb-5-0-optimizing-date-range-queries


When you need to get nulls you've to add another clause like this:
`[...].OrElse().WhereEquals(x => x.Value, null)`

**Comment by antmeehan** [comment]
Thanks @maciejaszyk for confirming. We've used that approach to work around the issue. Perhaps it's worth adding this change in behaviour to a 'breaking changes' section in the documentation?
