### ISSUE TITLE
System.Text.Json support

### ISSUE THREAD

**Issue by iGeX** [ravendb/ravendb#15681]
According to this article:
https://ravendb.net/docs/article-page/5.4/csharp/migration/client-api/conventions

In 5.0 was introduced JSON abstraction layer, decoupling C# client library from specific implementation.
But despite this abstraction, implementation is still only one (for Newtonsoft Json.NET).

Do you have plans to implement support for System.Text.Json? Or Newtonsoft will be only supported library by vendor, and this abstraction is only for customers?

**Comment by ayende** [comment]
https://github.com/ravendb/ravendb/discussions/15301
