### ISSUE TITLE
Multi-Architecture Docker Image

### ISSUE THREAD

**Issue by piercetrey-figure** [ravendb/ravendb#15690]
Hi 👋 ,

I see that there are images available for different architectures (linux/amd64, linux/arm/v7, linux/arm64/v8, etc.), which is great, but we have some docker compose setups for local development that include ravendb and some team members have M1 macs, while some are on intel... Currently supporting this would involve swapping out the image via compose profiles or multiple compose files for the two architectures.

Would it be possible to start publishing a multi-architecture docker image via docker buildx that supports the common platforms? I'm thinking it could be a fresh image tag scheme (say, ubuntu-multiplatform, etc.) to prevent any chance of breaking anything that might not support multi-architecture image manifests.

Thanks

**Comment by gregolsky** [comment]
We do not support multi-arch at the moment, however there is an open issue you can track progress on https://issues.hibernatingrhinos.com/issue/RavenDB-9167/Publish-Docker-multi-arch-images-to-simplify-consumption-of-docker-images

**Comment by piercetrey-figure** [comment]
That issue appears to be pretty stale, created 5 years ago, before [Docker Buildx](https://docs.docker.com/engine/reference/commandline/buildx/) was even a thing. What are the chances of it getting traction anytime soon?

**Comment by ayende** [comment]
We would welcome a PR for this, of course.

**Comment by musialny** [comment]
Any update?

**Comment by gregolsky** [comment]
Since few last builds we issue `latest` and `latest-lts`, which are routed to the OS you pull it on using the docker manifest.
