### ISSUE TITLE
Latest Ubuntu docker image fails to start

### ISSUE THREAD

**Issue by JezhikLaas** [ravendb/ravendb#15704]
Hello,
the latest Ubuntu image
sha256:1c8e1c71f136aded6f0e92d6720b9fd05f2097b0aa407df8ad4448c7f617fc50
fails to start with
`Failed to create CoreCLR, HRESULT: 0x80070008`

Anything we can do on our side?

Thanks, Uwe

**Comment by poissoncorp** [comment]
Hello @JezhikLaas,
I tried reproducing the issue you reported with the image of the sha256 you provided, but unsuccessfully. 
Can you please give me more details on your setup? 
Specifically, what is the environment where you trying to run the container, and what version of Docker are you using?
This will help me figure out what's going wrong and how to fix it. 

Moreover, if you're running Docker on Windows, you could check Event Viewer and seek for some Docker errors. 
That'd help us to resolve this issue.

Thanks!

**Comment by JezhikLaas** [comment]
The systems on which the container fail to start are:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

Everything seems to run smoothly on:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

HTH

**Comment by JezhikLaas** [comment]
Sorry, forgot the docker version. Here it comes:
Docker version 19.03.12, build 48a66213fe
on the systems on which the containers refuse to start.

**Comment by poissoncorp** [comment]
I'm running the same image on the same system, but the Docker version is 20.10.22.
You may try to make a Docker update, while I'll make a further investigation.
Also, are there any logs from the docker daemon?
Please let me know.

**Comment by poissoncorp** [comment]
Could you give us your kernel version? `uname -srm` / `neofetch`

**Comment by JezhikLaas** [comment]
Linux 5.4.0-137-generic x86_64
Is that enough?

**Comment by poissoncorp** [comment]
Hi @JezhikLaas,
Could you try updating your kernel? Lets see if that helps
Also, have you updated the Docker?
I've seen plenty of Docker engine related issues associated with that error message.
https://www.linuxserver.io/blog/anatomy-of-an-issue#signs-of-trouble

**Comment by JezhikLaas** [comment]
Hello
and sorry for the late reply - updating docker on the failing machines did the trick.

Thanks for the help!
