### ISSUE TITLE
Feature Request: Extend cascading deletes to properties

### ISSUE THREAD

**Issue by jstafford5380** [ravendb/ravendb#15778]
There are oftentimes situations where putting all "related" documents into the "parent" document is impractical or does not meet some application requirements, and thus we need separate documents into different collections. RavenDB has a number of features that allows to work with those objects to do some "poor man's" joins, but this still leaves some gaps open when trying to manage the orphaning of files within the application. One or two of them can be handled in application code fairly easily, but when looking at a larger more complex project, or when you have teams of contractors moving in and out of a project who may never think to manage orphans  with a document database, this could pose a problem.

When I delete a record, I'd like the option of having any related documents or references to deleted objects delete along with them. I realize this is more complicated than it sounds because you have a few different scenarios, for example:

- I want all documents that have a reference to this deleted document to delete their reference. Sometimes that reference is a single string, other times that reference might be a string in an array of strings. So either way, I want that reference removed.
- I want all documents that have a 1:1 relationship with the delete document to delete themselves. This may make one immediately think "well that 1:1 document should be *part of* that delete document to begin with, but there are scenarios with applications that simply need to separate them for various reasons (like in my case)

My initial thought is this might be workable through explicit declarations that can help RavenDB understand how to behave on a per document property bases, and I think this could possibly be achieved through annotations on the client side and maybe metadata on the server side. For example:

```csharp
// Raven will null the ParentReference Field when the document referred to by ParentReference is deleted
public class Bar
{
    [CascadeDeleteMember(CascadingDeleteBehavior.NullProperty)]
    public string ParentReference { get; set; }
}

// Raven will delete this document when the document referred to by ParentReference is deleted
public class Bar
{
    [CascadeDeleteMember(CascadingDeleteBehavior.DeleteSelf)]
    public string ParentReference { get; set; }
}

// Raven will remove the ID from the collection when its document is deleted
public class Bar
{
    [CascadeDeleteMember(CascadingDeleteBehavior.RemoveReference)]
    public List<string> OtherReferences { get; set; }
}
```

**Comment by ayende** [comment]
The easiest way to handle that is to have a naming convention for the documents.

Consider:

* `bar/1-A`
* `bar/1-A/items/001`
* `bar/1-A/items/002`
* `bar/1-A/notifications/2023-02-08`

And then you can issue a `delete starts with ("bar/1-A")`

There are several issues with your suggestion. The primary issue is that you assume that this is something that is valid on a single node, so we can ensure consistency.

RavenDB is a multi-master setup, so you can have a scenario where on Node A you have `delete bar/1-A` and another request on Node B to `insert related to bar/1-A`

That said, you _can_ handle that using the `BeforeDelete` even on the client side. 
That is something that you can add to your application.

**Comment by jstafford5380** [comment]
I hadn't considered this. I can take a look but I think it's going to take a decent amount of rework on my side to leverage this technique; I'm surprised I haven't come across this earlier in the documentation. I vaguely recall seeing IDs that look like this but not much else on the topic in practice. I have read the "[Knowledge Base: Document Identifier Generation](https://ravendb.net/docs/article-page/5.4/csharp/server/kb/document-identifier-generation)" and "[Working with Document Identifiers](https://ravendb.net/docs/article-page/5.4/csharp/client-api/document-identifiers/working-with-document-identifiers)" docs.

That said, how is this convention achieved in C#? Is it just custom IDs (ala `RegisterAsyncIdConvention`) or something else? How could this be used to help manage document IDs that are in collections (where one document holds relationships to multiple documents by storing their IDs in an array)? For what it's worth, a good portion of the IDs I'm using are semantic.

**Comment by ayende** [comment]
Yes, that is just a convention on naming the documents.
