### ISSUE TITLE
BUG: TestDriver runtime version is lower than installed version but won't run

### ISSUE THREAD

**Issue by cmitchell** [ravendb/ravendb#15929]
I posted the stacktrace for this in a issue in the jvm-client project because I ran into it while using java, but looking closer at the stacktrace and then looking at the actual code, it looks like the logic wasn't updated/robust to handle the change over from .NET 6.x to .Net 7.x 

Sorry to cross post -- here's the link to the original post.  https://github.com/ravendb/ravendb-jvm-client/issues/67

The logic that doesn't account for a major version change is at https://github.com/ravendb/ravendb/blob/96dd7a6cebfef6d882a224714b9b3e6bb2d19538/src/Raven.Embedded/RuntimeFrameworkVersionMatcher.cs#L55

This is a recent break -- 7.0.3 became the stable version of .Net on Feb 14, 2023.

Would it be possible for you to update the logic and release a bugfix version of the test-driver?

**Comment by ppekrol** [comment]
Answered in the original post: https://github.com/ravendb/ravendb-jvm-client/issues/67#issuecomment-1453120088
