### ISSUE TITLE
Unable to specify node tag when adding non-leader nodes

### ISSUE THREAD

**Issue by rwkarg** [ravendb/ravendb#15953]
https://github.com/ravendb/ravendb/blob/7ec9c6d998b4b18c5c98bf2d00466be501abffee/src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs#L397

This code will use the auto-generated `nodeInfo.NodeTag` unless this is the initial bootstrapped node of the cluster (though it's unclear how the node could be added to a cluster as the leader tag since there needs to be a leader already to join additional nodes to).

I would expect that passing in a node tag would result in the added node having the specified node tag.

For example, with the below call I would expect the newly added node to have the tag `EUB`
```
https://us-a.raven.example.com:8080/admin/cluster/node?url=https%3A%2F%2Fseu-b.raven.example.com%3A8080&watcher=false&tag=EUB 
```

This is useful for differentiating the physical location of the nodes from the tags (which are visible in many places) instead of needing to corss-reference back to the URL which is shown in fewer places.

Is there a technical reason or further dependencies that would prevent being able to specify the node tag on members/watchers?

**Comment by ayende** [comment]
The `nodeInfo` in question is coming from the _node to be added_.
The idea is that it is:
* A new node (then the `InitialTag` is relevant)
* A node that was removed and now added to the cluster (use the old tag)
* A node from another cluster - in which case it will be rejected.

**Comment by ayende** [comment]
Note that adding a new node to the cluster, it will use the value you have given.

**Comment by rwkarg** [comment]
This ended up being an issue with how query parameters are set in curl for `PUT` requests:
https://stackoverflow.com/questions/32980081/curl-command-line-encoding-of-query-parameters-for-an-http-put

Verified through the Traffic Watch that with the incorrect curl command, only the first parameter was being sent (the url of the new node) when the parameters were being directly included in the url for curl (works for `POST`, but not for `PUT`).

When properly crafting the curl request, the behavior works as expected.
