### ISSUE TITLE
Forcing revision creation - different behaviour between regular and embedded server

### ISSUE THREAD

**Issue by sakowiczm** [ravendb/ravendb#16022]
Hey Guys, 

Noticed different behaviour between the regular server (docker, 5.3-ubuntu-latest) and the embed version (RavenDB.Embedded 5.3.102) when forcing creation of a revision. To start with, in both cases I have a collection which does not create revisions automatically and there are no revisions created. When I try to `Create Revision` manually using Studio UI:
- on regular server - I can create revision no issue,
- on embedded server - I got the message `No new revision created. A revision with the lastest document content already exists` - but this document does not have any revisions yet (not visible in Studio UI or requesting it via code).

Any ideas?

**Comment by grisha-kotler** [comment]
Hi,

You are using 2 different versions. Server - 5.3.108 (latest).
We fixed the manual revision creation in 5.3.103.

Note that 5.3 is out of support, please use 5.4.

**Comment by sakowiczm** [comment]
Thank you!
