### ISSUE TITLE
Troubles with setup ravendb 5 using powershell DSC script 

### ISSUE THREAD

**Issue by josteinjhauge** [ravendb/ravendb#16505]
Hi, i cant find any good documentation on the rest of the setup after i have set up ravendb as a service. I have gotten raven to run as an service, but cant get it to register my license key or create my database with replication nodes. Its crucial to state that im trying to do this from a Powershell DSC script as this needs to be automated. Example of request to create database
$requestBody = @{
DatabaseName = "Test"
}
Invoke-WebRequest -Uri "$serverUrl/admin/databases" -Method POST -ContentType "application/json" -Body ($requestBody | ConvertTo-Json)

Example of how im trying to register the license key since it wont be read from my settings.json file where i use license.path as in the documentation: 
$requestBody = @{
License = $licenseKey
} | ConvertTo-Json

Invoke-WebRequest -Uri "$serverUrl/admin/license/register" -Method POST -ContentType "application/json" -Body $requestBody

Any sugestions of what i am doing wrong or how i can get it to work?

**Comment by ppekrol** [comment]
Hi, the endpoint is `/admin/license/activate` and I see that you are trying to hit `/admin/license/register`. The content needs to math following DTO:

```csharp
    public class License
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public List<string> Keys { get; set; }
    }
```

**Comment by josteinjhauge** [comment]
For the rest-api, whats rthe endpoint for creating replication nodes for the db?

**Comment by ayende** [comment]
You mean, adding a node to a database after it was created?

`PUT /admin/databases/node?name=$DB_NAME&node=$NODE_TAG`

**Comment by josteinjhauge** [comment]
Does the node you add using PUT /admin/databases/node?name=$DB_NAME&node=$NODE_TAG need to be registered es a service first?

**Comment by ppekrol** [comment]
There is no such requirement.
