### ISSUE TITLE
Adding nodes to existing cluster

### ISSUE THREAD

**Issue by josteinjhauge** [ravendb/ravendb#16512]
Hi, im trying to create a database with five replication nodes, so my question is: Can i create those nodes at the same time(in the curl where i create my db) or do i have to add them after the creation of the DB. I have tried the latest in my powershell script: 

 $replicationNodes = @("http://nodeA:8082", "http://nodeB:8082", "http://nodeC:8082", "http://nodeD:8082", "http://nodeE:8082")
                foreach ($nodeUrl in $replicationNodes) {
                    # $url = "http://localhost:8082/admin/databases/Fido/replication"
                    $url = "http://localhost:8082/admin/cluster/node"
                    $requestBody = @{
                        Url = $nodeUrl
                    } | ConvertTo-Json
                    Invoke-WebRequest -Uri $url -Method Put -ContentType "application/json" -Body $requestBody
                }

**Comment by ppekrol** [comment]
Hi,

I think that the best approach would be first to create a cluster with 5 nodes and afterwards create a database with replication factor set to 5 

Check here:

https://github.com/ravendb/ravendb/blob/35fdc911896c7981160c8a2b224e745d67a50af7/src/Raven.Server/Web/System/AdminDatabasesHandler.cs#L191

**Comment by josteinjhauge** [comment]
Ok, so using Curl I can pass a param called replicationfactor when creating the database and the order needs to be: 1.create cluster with 5 nodes using powershell, then create DB?

**Comment by ppekrol** [comment]
Correct

**Comment by josteinjhauge** [comment]
Invoke-WebRequest -Method Put -ContentType "application/json" -Body '{"DatabaseName": "Test"}' -Uri "http://localhost:8082/admin/databases?replicationFactor=5" like this or should replication factor be given in body?

**Comment by ppekrol** [comment]
LGTM

**Comment by josteinjhauge** [comment]
So the cmmand over wont work, it dosent create the database or any of the nodes, if i remove replicationFactor param it creates db on node A. So i have tried to add nodes to existing cluster:  
            $nodeCount = 4 
            $tags = @("B", "C", "D", "E")
            try {
                for ($i = 0; $i -lt $nodeCount; $i++) {
                    $nodePort = 8083 + $i 
                    $tag = $tags[$i]
                    Invoke-WebRequest -Method Put -URI "http://localhost:8082/admin/cluster/node?url=http://127.0.0.1:$nodePort&tag=$tag"
                    Start-Sleep -s 3
                }
            }

Only problem is that it only creates node B and not (C,D,E), is their a limitation here?

**Comment by ppekrol** [comment]
Have you tried checking what Studio is sending in those scenarios? There must be some diff in what you are sending and what Studio is.

**Comment by josteinjhauge** [comment]
will check

**Comment by josteinjhauge** [comment]
so i think the reason for the database with replicationfactor 5 failing is that not all of the nodes are available 
![image](https://github.com/ravendb/ravendb/assets/43235879/a43ecdb0-84bf-45cb-a2a5-9c4dcfc0a0a2)

**Comment by josteinjhauge** [comment]
and for the adding of nodes to the cluster i send requests to these url's: 
http://localhost:8082/admin/cluster/node?url=http://127.0.0.1:8083&tag=B
http://localhost:8082/admin/cluster/node?url=http://127.0.0.1:8084&tag=C
http://localhost:8082/admin/cluster/node?url=http://127.0.0.1:8085&tag=D
http://localhost:8082/admin/cluster/node?url=http://127.0.0.1:8086&tag=E
VS. what is being sent when im using the client: 
http://localhost:8082/admin/cluster/node?url=http%3A%2F%2F127.0.0.1%3A8083&watcher=false
http://localhost:8082/admin/cluster/node?url=http%3A%2F%2F127.0.0.1%3A8084&watcher=false
http://localhost:8082/admin/cluster/node?url=http%3A%2F%2F127.0.0.1%3A8085&watcher=false
http://localhost:8082/admin/cluster/node?url=http%3A%2F%2F127.0.0.1%3A8086&watcher=false

Is it maybe the tag thing that does it?

**Comment by josteinjhauge** [comment]
figured it out, the error had to do with a try\catch, but is their a way to check how many nodes are in a cluster

**Comment by ppekrol** [comment]
Try using `/cluster/topology` endpoint.
