### ISSUE TITLE
RavenDBClient : Database is not recreated after its deletion

### ISSUE THREAD

**Issue by fabricenoel44300** [ravendb/ravendb#16543]
Hello. I am facing a problem with client RavenDB. I used until now RavenDBClient v5.1.5 which is not supported anymore. With this version, the database on RavenDB server was automatically recreated after its deletion.

I recently updated RavenDB client to version 5.4.104. And now, the database is not recreated automatically any more. I have tested many versions of RavenDB client and I found that this behaviour happens since version 5.1.6. 

As v5.1.5 is not supported any more, we would like to update the RavenDB client but we would keep the possibility the recreate database automatically. 

What is the best way to do that ?

Kind regards

Fabrice Noël

**Comment by arekpalinski** [comment]
Hi Fabrice,

When you to expect a database to be recreated? Can you show the relevant piece of your code (in particular the deletion of database and initialization of document store)?
