### ISSUE TITLE
[Question] A client for Clojure

### ISSUE THREAD

**Issue by HassanYA** [ravendb/ravendb#16797]
Hi,

There is a Java a client for RavenDB and is maintained by Hibernating Rhinos, I think.

There is a community client for clojure but it is outdated and I like how RavenDB fits into the FP paradigm very well. Thus, I'd like to create a new one for Clojure. I have two ways to go about this:

1. Wrap the existing java client and expose some helpers
2. Integrate with the REST API, I found [this](https://ravendb.net/docs/article-page/5.4/csharp/client-api/rest-api) in the docs. But it lacks doc for index (apparently).

I am not sure which of the two is preferred. I have not dived into Java Client source but I prefer to defer from http (not sure if java client is using rest under the hood)

**Comment by ppekrol** [comment]
Hi @HassanYA 

That would be an awesome contribution and we would love to assist you with any questions you will have.

You are correct, the JVM client is maintained by us. From our perspective, writing a new client takes severe amount of time due to vast number of features that we are supporting. I think it would be best to reuse JVM client, because of the amount of work that was done there so you can focus on Clojure helpers only. That would be our recommendation.

**Comment by HassanYA** [comment]
Thanks for this, I'll try my best to reuse the jvm client and open new issue if any questions arise.

**Comment by HassanYA** [comment]
Hello,

I have been exploring the jvm client for the past two days. There is one thing that I would like some help with. 

In clojure, it's usually advised to "just use maps". Can I somehow insert a document whilst explicitly specifying the collection name? I saw in jvm client's source that the collection name is derived from the class name (using getSimpleName), In this case, all documents inserted will just  just go under a collection called "Maps".

Also, let me know if you'd rather, I put further questions on https://github.com/ravendb/ravendb-jvm-client instead of here.

**Comment by ppekrol** [comment]
hi,

I think it would be best to move the conversation there. Our JVM guy will be back from vacation tomorrow, so please re-post the Q there and we will answer you as soon as possible.

**Comment by ayende** [comment]
You can customize how RavenDB deal with that using:

        store.getConventions().setFindCollectionName(clazz -> "Test" + c + DocumentConventions.defaultGetCollectionName(clazz));

In this case, you'll get the class and can customize the type. 

You can handle this by overriding this method and providing your own `DocuemntConvnetion` here:

https://github.com/ravendb/ravendb-jvm-client/blob/v5.4/src/main/java/net/ravendb/client/documents/conventions/DocumentConventions.java#L635


` public String getCollectionName(Object entity)`

**Comment by HassanYA** [comment]
I'll check this out this evening and close the issue. Many thanks for the input, if anything new comes up, I'll post on the jvm repo

**Comment by ppekrol** [comment]
I'm closing this one, let's move to JVM repo.

**Comment by HassanYA** [comment]
Hi @ppekrol  @ayende 

If interested, the repo is on [ravenousdb](https://github.com/HassanYA/ravenousdb/tree/main). I'll probably publish this to maven and clojars on the weekend after some tests and allowing secure connections.

I hope this comment does not re-open the issue, 
Thanks for the support and cheers :)
