### ISSUE TITLE
Edit IRavenQueryable query generated in code

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#16817]
This is the search query with all the filtering and highlighting that gets generated in code - 

{from index 'Index' where boost(search(Field1, $p1), 25) and boost(search(Field1, $p2), 25) or search(Field2, $p3) and search(Field2, $p4) and (Field3all in ($p5)) include highlight(Field2,128,1,$p0)}

Is there a way to edit or change it in a way to wrap the searches within parenthesis ( ) before the Field3 AND condition? 

Like this - 

 {from index 'Index' where ( 
boost(search(Field1, $p1), 25) and boost(search(Field1, $p2), 25) or search(Field2, $p3) and search(Field2, $p4)
 ) 
and (Field3 all in ($p5)) include highlight(Field2,128,1,$p0)}

**Comment by ppekrol** [comment]
Check here: https://github.com/ravendb/ravendb/issues/16816#issuecomment-1624818446

**Comment by meghanajoshilw** [comment]
SubClause worked. Thanks!
