### ISSUE TITLE
Issue with grouping AND OR in raven query

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#16816]
Search results are skewed due to not being able to group ANDs ORs in the raven query that we generate using IRavenQueryable query.

This is the initial query that gets created in code - 
from index 'Index' 
where 
boost(search(Field1, 'red*'),25) AND boost(search(Field1, 'green*'),25) OR
search(Field2, 'red*') AND search(Field2, 'green*') 
AND Field3 all in (List of integers)_

When I modified the query in Raven studio like below which includes _parathesis_ around the search, then I see expected results - 
from index 'Index' 
where 
(
boost(search(Field1, 'red*'),25) AND boost(search(Field1, 'green*'),25) OR 
search(Field2, 'red*') AND search(Field2, 'green*') 
)
And Field3 all in (List of integers)

But I'm struggling to find a way to replicate that using a IRavenQueryable query in C# code. I'm not sure how to possibly group the searches together within the parenthesis and then apply the AND filtering on Field3.

![image](https://github.com/ravendb/ravendb/assets/133284420/3f9e7e33-5125-48bf-98b5-c8588dc523be)

  
You can see in the attached image how adding the parathesis by grouping AND OR the results count changes. The one on the left is expected but the one from right is what we have.  

Tried with this code as well but no luck. It generates the same RQL query without parenthesis.
 IAsyncDocumentQuery<QueryResult> query = query.Search(Field1, token).Boost(25).OrElse()
.Search(Field2, token).AndAlso().ContainsAll(Field3, "").Highlight(Field2, 128, 1, highlightingOptions, out highlightings); 
                                              

Any help is appreciated. Thanks!

**Comment by ppekrol** [comment]
Hi @meghanajoshilw 

I think you need to take leverage of `.OpenSubclause()` and `.CloseSubclause()` methods to achieve desired result. Have you tried that?

**Comment by meghanajoshilw** [comment]
That helped! Thank you.
