### ISSUE TITLE
OrderByScore() variation 

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#16931]
Can we modify the lucene score and then do an OrderByScore() in the query? 

Example - 

Lets say I've a query using one of the RavenDB Analyzers and its returns 100 results and the MetaData has their lucene score. Is there a way to take that score and multiply it with "X" to get the new "modified" score and then do an OrderByScore() on the results after? 

Note - We want to OrderByScore() and by "Date" as the additional factor (Relevance by Date). Meaning most recent dates should have a higher score than the older dates. So trying to see how we can manipulate the score in the query before we order them. 

Or is there a way to OrderByScore() and then Boost on the certain Date field? 

Thank you.

**Comment by ayende** [comment]
`order by score(), Date` ?? 

But that wouldn't do what you likely want it to do. The Date sorting would only impact values that have the same score.

Are you familiar with `boost` ? You can query using something like:

`
where [your clause] and (boost(Date between $weekAgo and $now, 10) or boost(Date between $yearAgo and $weekAgo, 5) or boost(Date < $yearAgo, 1)
`

That would add those values to the accounting

**Comment by meghanajoshilw** [comment]
Sounds good, thank you for your answer. 

We were in the middle of investigating the Boost option and now that you confirmed, I will go ahead and make changes accordingly. Thanks again!
