### ISSUE TITLE
How to patch/update all the properties on a document except one? 

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17049]
Hello, we've a document with more than 20 properties. And we want to update most of the properties except one. 
I was checking the patch syntax and looks like you can only do one property at a time. 

Is there a way to patch/update with an except? I'm hoping not having to write 20 patches which isnt the most efficient. The other option is load and store which is my last resort. 

Pls let me know if there's anything better. Thanks.

**Comment by ayende** [comment]
If you are modifying the entire document, basically, _why_ do you want to modify using patch and not store?

You can modify the document as you wish using patch, just need the lower level API.

```
           session.Advanced.Defer(new PatchCommandData("items/first", null,
                        new Raven.Client.Documents.Operations.PatchRequest
                        {
                            Script = @"
var self = this;
// do whatever you want here
// you write JS here
",
                            Values =
                            {
                                ["PageId"] = "home",
                            }
                        }, null));
```

Note that if you are using the `session.Advanced.Patch` API, multiple calls on the same objects will be merged into a single patch operation
