### ISSUE TITLE
BulkInsert specific fields 

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17057]
using (BulkInsertOperation bulkInsert= BulkInsert())
{                                   
       bulkInsert.Store(document, "DocumentID");
}

So currently we're using BulkInsert operation and Store to update the documents. But what I see is it updates all the 20 properties in that document. But I do not want to update the "Content" property. I want to update the rest 19 properties on the document. (everything except one).

Can we achieve this in BulkInsertOperation? or is there another efficient way? 

This is a continuation of - https://github.com/ravendb/ravendb/issues/17049
Unfortunately I couldn't write back on that so had to create another one!!

**Comment by ayende** [comment]
No, that is not possible `BulkInsert` updates the entire document. 
What is the scenario that you have here? How big is the `Content` field?
