### ISSUE TITLE
Patch an array from another input array

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17062]
Hello, I started trying patching and for most of the properties it worked great. 

I'm having some trouble with the script to patch an array with two fields - I see an Raven.Client.Exceptions.Documents.Patching.JavaScriptException

Document in RavenDB - 

 "Location": "",
  "Type": null,
   "Answers": [
        {
            "ID": 3,
            "Name": "Germany"
        },
        {
            "ID": 6,
            "Name": "France"
        },
        {
            "ID": 10,
            "Name": "Egypt"
        }       
    ],
    "@metadata": {

I was able to patch Location, Type on the document successfully. But since Answers is an array the script isnt working. This is the patch command - 

     session.Advanced.Defer(                                        
                                            new PatchCommandData("ID}", null, new PatchRequest
                                            {
                                                Script = 
                                                $" this.Location = '{newDoc.Location}'; " + 
                                                $"this.Type = '{newDoc.Type}';"                                                                  
                                            },
                                                    null)
                                        );

newDoc.Answers contains the set of (ID and Name) array values which I need to patch. I've tried a bunch of code syntaxes but no luck. Pls suggest any changes.

**Comment by ppekrol** [comment]
Hi there,

I do not see you are patching `Answers` at all in your patch? I might be missing something. 

I've used this document:
```
{
    "Location": "",
    "Type": null,
    "Answers": [
        {
            "ID": 3,
            "Name": "Germany"
        },
        {
            "ID": 6,
            "Name": "France"
        },
        {
            "ID": 10,
            "Name": "Egypt"
        }
    ],
    "@metadata": {
        "@collection": null
    }
}
```

and following patch:

```
o.Answers.push({ Hello : "World" })
```

Without any issues.
