### ISSUE TITLE
Patching an array doesnt work 

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17076]
Hi there, these are the patch commands that I've tried over the past 2 days with no luck. Any suggestions/tweaks is appreciated. Ideally I want to patch the entire array set at once not add item one at a time. Thank you! 

- session.Advanced.Defer(new PatchCommandData("DocumentID", null,
   new PatchRequest
   {
      Script = $"this.Attributes.push({document.Answers.Select(dn => new AnswerModel { AnswerID = dn.ID, Name = dn.Name })});"
   }, null));

- session.Advanced.Defer(new PatchCommandData("DocumentID", null,
    new PatchRequest
    {
        Script = "this.Answers.push(list)",
        Values = { ["list"] = $"{document.Answers.Select(dn => new AnswerModel { AnswerID = dn.ID, Name = dn.Name })}" }
    }, null));

- session.Advanced.Defer(new PatchCommandData("DocumentID", null,
     new PatchRequest
     {
         Script = "this.Answers.push(item)",
         Values = 
{
          ["item"] = $"AnswerID: {document.Answer.FirstOrDefault().ID}, 
          Name: {document.Answers.FirstOrDefault().Name}"
 }
     }, null));

-  session.Advanced.Defer(new PatchCommandData("DocumentID", null,
                                         new PatchRequest
                                         {
                                             Script = "this.Answers.push(item)",
                                             Values = { ["item"] = $"{document.Answers}" }
                                         }, null));

-  session.Advanced.Defer(new PatchCommandData("DocumentID", null,
                                         new PatchRequest
                                         {
                                             Script = "this.Answers.push(comment)",
                                             Values =
        {
            {
                "comment", new AnswerModel
                {
                    AnswerID = document.Answers.FirstOrDefault().ID,
                    Name = document.Answers.FirstOrDefault().Name
                }
            }
        }
                                         }, null));

- session.Advanced.Patch<Document, AnswerModel>("DocumentID",
                                         x => x.Answers,
                                         comments => comments.Add(new AnswerModel
                                         {
                                             Name = document.Answers.FirstOrDefault().Name,
                                             AnswerID = document.Answers.FirstOrDefault().ID
                                         }));

- session.Advanced.Defer(new PatchCommandData("DocumentID", null,
                                           new PatchRequest
                                           {
                                               Script = @"
                                                    var i = 0;
                                                    for(i = 0; i < $values.length; i++)
                                                    {
                                                        this.Answers.push($item);
                                                    }",
                                               Values =
                                               {                                                   
                                                    { "values", document.Answers },
                                                    { "item", document.Answers.FirstOrDefault() }
                                               }
                                           }, null));

This is the Array in raven which im trying to patch - 

  },
    "Answers": [
        {
            "AnswerID": 3,
            "Name": "London"
        },
        {
            "AnswerID": 6,
            "Name": "Spain"
        },
        {
            "AnswerID": 10,
            "Name": "Egypt"
        }
    ],

**Comment by ayende** [comment]
It's *really* hard to read what you are doing, but to start with, you are trying to do code generation via string iterpolation.
That is usually a bad thing.

This is what I would expect to work:

```
session.Advanced.Defer(new PatchCommandData("DocumentID", null,
  new PatchRequest {
    Script = "this.Answers.push(comment)",
      Values = {
        {
          "comment",
          new AnswerModel {
            AnswerID = document.Answers.FirstOrDefault().ID,
            Name = document.Answers.FirstOrDefault().Name
          }
        }
      }
  }, null));
```
