### ISSUE TITLE
Patching an array issue

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17083]
session.Advanced.Defer(new PatchCommandData("DocumentID", null,
                                           new PatchRequest
                                           {
                                               Script = "this.Answers.push(comment)",
                                               Values = {
                                                {
                                                  "comment",
                                                   new AnswerModel {
                                                    ID = 29,
                                                    Name = "London"
                                                  }
                                                }
                                               }
                                           }, null));

Its inserting null when I try that command. Not sure why. Am I missing anything?

Unfortunately I can not reply, close an issue or attach any image. - https://github.com/ravendb/ravendb/issues/17076

**Comment by garayx** [comment]
Hello
Unfortunately there is no enough information to answer your question,

Please send a unit test: https://ravendb.net/docs/article-page/5.4/Csharp/start/test-driver or hello-world application that demonstrates the issue.
