### ISSUE TITLE
[Prometheus] Monitoring endpoint not available on Professional license

### ISSUE THREAD

**Issue by sergiomcalzada** [ravendb/ravendb#17165]
Hi everyone,

I understand that this is a monetization decision, but really? Monitoring integration with Prometheus is not included in an already paid version? Would you consider making it available?

Kind regards.

**Comment by ppekrol** [comment]
hi @sergiomcalzada 

Could I ask you to contact sales@ravendb.net regarding this? I'm sure we can figure it out.
