### ISSUE TITLE
[Studio] Download logs

### ISSUE THREAD

**Issue by sergiomcalzada** [ravendb/ravendb#17336]
Would be great to "disable" download button once clicked

![image](https://github.com/ravendb/ravendb/assets/1726913/875262d2-6cef-4c60-988f-4671972f8507)

**Comment by ml054** [comment]
Reported in our official bug tracker: https://issues.hibernatingrhinos.com/issue/RavenDB-21411/Download-logs-block-button-after-click

@sergiomcalzada Thanks for sharing your feedback with us.
