### ISSUE TITLE
Links to newest Version in Studio do not work

### ISSUE THREAD

**Issue by oiBio** [ravendb/ravendb#17389]
When you klick on the "Newest Version" Links you get routed to https://ravendb.net/downloads
but this page does not exist (anymore?)

the correct link would be https://ravendb.net/download (without the s)

**Comment by ppekrol** [comment]
Hi @oiBio 
We were just deploying changes to the website, I think you probably hit a few min period when this was happening. Both of the links work for me, can you recheck?

**Comment by oiBio** [comment]
Ah okay I think i just hit that time frame ;-) 
now its working for me.
