### ISSUE TITLE
AsyncHelpers "leaks" in case of exception

### ISSUE THREAD

**Issue by OwnageIsMagic** [ravendb/ravendb#17381]
https://github.com/ravendb/ravendb/blob/5cedbcc9e3f20e19d8095dbf266e47ade65b9d48/src/Raven.Client/Util/AsyncHelpers.cs#L68-L80

`synch` is "leaked" in case of exception. I hope `ObjectPool` is using `WeakReference` (not checked), so it's not a real leak, but I see no reason not to move `Free` to `finaly` block.

**Comment by ayende** [comment]
That is by design, when there is an exception, the context is "poisoned", by holding the exception
This isn't an actual leak, by the way, it will be removed by the GC in a short while

**Comment by OwnageIsMagic** [comment]
Okay, here is another one
https://github.com/ravendb/ravendb/blob/5cedbcc9e3f20e19d8095dbf266e47ade65b9d48/src/Raven.Client/Util/AsyncHelpers.cs#L200
`_done` should be marked `volatile` cause it's changed from another thread. See last example here https://github.com/dotnet/runtime/blob/bb329211df5a017e11a3ea2617a688e70fc83df5/docs/design/specs/Memory-model.md

**Comment by murshex** [comment]
volatile isn't required when using async/await

**Comment by OwnageIsMagic** [comment]
@c0nd3v there is no single await in related class. Btw, await doesn't provide full memory fence (see https://github.com/dotnet/docs/issues/11360#issuecomment-1508596848 ).

----

Code here is safe because
`_ => _done = true` is posted to the same thread this variable is read.

**Comment by OwnageIsMagic** [comment]
> That is by design, when there is an exception, the context is "poisoned", by holding the exception This isn't an actual leak, by the way, it will be removed by the GC in a short while

@ayende returning to pool calls Reset, which would clear exception.
https://github.com/ravendb/ravendb/blob/5cedbcc9e3f20e19d8095dbf266e47ade65b9d48/src/Raven.Client/Util/AsyncHelpers.cs#L26
An I missing something?
