### ISSUE TITLE
Corax total records statistics value is unreliable

### ISSUE THREAD

**Issue by dstarosta** [ravendb/ravendb#17453]
I am using the latest stable version 6.0.

This issue happens to multiple indexes but here is the simplest of them.

```C#
    public UserSearchIndex()
    {
        SearchEngineType = Raven.Client.Documents.Indexes.SearchEngineType.Corax;

        Map = users =>
            from user in users
            select new UserProjection
            {
                Id = user.Id,
                DisplayName = user.DisplayName,
                SearchableDisplayName = user.DisplayName,
                Email = user.Email,
                CreationDate = user.CreationDate,
                LastAccessDate = user.LastAccessDate,
                Reputation = user.Reputation,
                VoteCount = user.VoteCount
            };

        Indexes.Add(x => x.SearchableDisplayName, FieldIndexing.Search);
    }
```

If I run a query that takes in an "offset" value, a "limit" value, a sort order (CreationDate desc but it does matter) but no where conditions, the `totalResults` value is always slightly larger than the "offset" value. The actual number of total records is over a million.

If I remove the "order" condition or add any "where" condition, then the stats are correct.

Lucene does not have this problem.

**Comment by ayende** [comment]
What is the query that you are running? What are the actual difference in results?

**Comment by redknightlois** [comment]
I can confirm I reproduced the error and have already a failing test for it. 

https://issues.hibernatingrhinos.com/issue/RavenDB-21525/The-client-API-is-sending-SkipStatistics-true-in-the-case-of-sorting-queries-even-if-stats-were-requested.

**Comment by arekpalinski** [comment]
Fixed in https://github.com/ravendb/ravendb/pull/17486
