### ISSUE TITLE
RavenDB-21648 WhatChanged for single entity

### ISSUE THREAD

**Issue by ThierryRosseau** [ravendb/ravendb#17618]
### Discussed in https://github.com/ravendb/ravendb/discussions/17324

<div type='discussions-op-text'>

<sup>Originally posted by **stevehansen** September 18, 2023</sup>
We are trying to do some simple generic IAudit logic, so before going to the database we want to set some properties on the changed object.

We are using the IDocumentStore.OnBeforeStore hook, which is invoked per entity but we want to get some information so we are using the session.Advanced.WhatChanged(), the problem is that this method will look for all changed entities.

When a small set of entities are loaded in the session the performance isn't that bad, but when we have a few hundred or thousand (which still seem small) the performance gets really bad. In our case we got the issue when using the RavenMigrations package to run some migrations, we loaded the whole collection to do the modification (about 1500 documents), the code also had to load some extra related entities and the memory usage spiked to almost 10GB during development.

![image](https://github.com/ravendb/ravendb/assets/2143488/ffc138c5-8579-4afa-9600-53bf02d13c61)

The code of course does some more but the root of the problem is the many WhatChanged() calls, that's why we are wondering if there is another option to get the result from it, ie the DocumentChanges for a single entity.</div>

**Comment by ayende** [comment]
https://github.com/ravendb/ravendb/pull/17620
