### ISSUE TITLE
Can the document ID be handled case sensitive?

### ISSUE THREAD

**Issue by JezhikLaas** [ravendb/ravendb#17645]
Hello,
the document ids in one of our collections depend on ids generated by external providers and are only unique if handled case sensitive. Can this be configured in RavenDB?
Thanks, Uwe

**Comment by mcrio** [comment]
I guess some workaround would be to base64 encode the original ids.

**Comment by JezhikLaas** [comment]
That's an idea, but we would loose the semantic of the id. A configuration option would be better.

**Comment by ayende** [comment]
No, case insensitivity is baked very deeply into the system
Do you _actually_ have ids that are different on case alone?
If that is the case, you can do something like append md5 / sha hash to the id. You'll get the semantic and uniquness

**Comment by JezhikLaas** [comment]
Sorry for the delay! We moved to encoding the ID base64, this works well. Yes, we actually have ids which differ only by case. We generate(d) the ids for these documents based on the value provided by the respective issuers according to https://health.ec.europa.eu/tobacco/product-regulation/systems-tobacco-traceability-and-security-features_en - these values have to be unique but, alas, only if you consider casing.
