### ISSUE TITLE
Extreme long query times (minutes) on RavenDB 6.0 (on Corax)

### ISSUE THREAD

**Issue by xinix00** [ravendb/ravendb#17676]
On simple queries, which take only 40ms at most on Lucene, they will take minutes on Corax (actually sometimes they "never" end). Even only Ordering and limit 0,25 will take up this amount of time.
Example of running queries (this one does do a search)
![image](https://github.com/ravendb/ravendb/assets/3684847/dd844e15-6674-4577-8414-ab0819626b0f)

If you still have my dataset, this is the query I run on the ArticleAll database:
```
from index 'ArticleAll' as result 
where 
    search(result.Query, $p0) 
    and (result.Hide = $p1) order by result.Name 
load 
    result.ArticleGroupId as articleGroup, 
    articleGroup.ArticleGroupParents as articleGroups[], 
    $p2 as language 
select { 
    Id : id(result), 
    Code : result.Code, 
    Name : result.Name[language.DefaultLanguage], 
    ArticleGroup : articleGroup.Name[language.DefaultLanguage], 
    ArticleGroupId : result.ArticleGroupId, 
    ArticleGroupParents : articleGroups.map(function(a){return a.Name[language.DefaultLanguage];}), 
    ArticleGroupParentIds : Array.from(new Set(articleGroups.map((function(a){return id(a);})))), 
    VBNCode : result.VBNCode } 
limit $p3, $p4
```
Parameters:
```
$p0 = "A"
$p1 = false
$p2 = "Config/Language" (don't know if I added this document)
$p3 = 0
$p4 = 25
```

Again on ARM64. It is on almost every larger set, in this case the doc count is 64.703. P.s. 6.0 has this bug, but also the latest nightly. (I tested 6.0 by "disabling" JIT (DOTNET_JITMinOpts=1)) The nightly has JIT enabled!

To add to it, last time I tested 5.4.108 with corax (which had the NULL facet bug) everything was working great.

Edit, simplified the query for you:
```
from index 'ArticleAll' as result 
where 
    search(result.Query, "ab*") 
    and (result.Hide = false)
select { 
    Id : id(result), 
    Code : result.Code, 
    VBNCode : result.VBNCode 
} 
limit 0, 25
```

This will also run "forever", I don't know when it ends, the queries in the screenshot above are now running 20 minutes. The weird part is, if I remove the Hide = false, it works like normal, if I remove the search() clause and only do the hide part it works like normal, but when I do them both it runs "forever"

**Comment by ayende** [comment]
Can you try:

```
from index 'ArticleAll' as result 
where 
    search(result.Query, "ab*") 
    and (result.Hide = false)
select { 
    Id : id(result), 
    Code : result.Code, 
    VBNCode : result.VBNCode 
} 
include timings()
limit 0, 25
```

And then send us the *raw* output of that?
Basically, that will show the query plan for the operation.

Note that we had to disable SIMD operations on ARM for now because of the .NET bug, which likely contributes heavily to the cost. 

That said, the query plan should be able to tell us what exactly is going on there.

**Comment by xinix00** [comment]
If disabling SIMD will make it so queries still run after 12 hours, I think it's better to wait for the 7.0.15 release of .NET. The set of articles is only 65.000 docs.

The above queries are still running, and the statistics only get visible after the query has run. I tried to explain that queries will run forever. I got more queries like this, without search() but with a larger "where" statement that will run forever, if I make a query a bit more complex, they will never return results. Lucene is working fine, but Corax isn't.

It was working fine however on 5.4.108 if that tells you anything.

I can't give you the timings since:
<img width="799" alt="image" src="https://github.com/ravendb/ravendb/assets/3684847/2687cbb8-2619-4eac-be6a-84b3899998c1">
I'm still waiting for the results for over 12 hours now...

**Comment by maciejaszyk** [comment]
Hi, during the investigation, I found a bug in the scalar version of our 'And' algorithm, which is run on ARM  inside Equal Match (TermMatch). This is why your query without `and result.Hide` was working just fine (even though we disabled optimizations).

I'm already working on the fix. You can track the progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-21689/Implementation-of-scalar-version-of-TermMatchs-PostingList-AndWith-has-infinity-loop.

Thanks a lot for reporting. :)

**Comment by xinix00** [comment]
This works now thanks. However, I now have wrong query results on "complex" queries (at least the query results differ on both Corax and Lucene). I will try to figure it out, but are you sure Corax is ready to be used or is it experimental?

Now I'm querying on a set with 90 results,

search h* gives me:
GYPS TEST (without a H)

search hy*
No results

search hyd*
HYDR TEST (but should be in the results above)

Also it looks like normal WHERE statements are acting different, I will try to find them out and post them seperately.

**Comment by maciejaszyk** [comment]
Can you share your queries?

**Comment by xinix00** [comment]
I think it is the way I'm currently indexing, guess that changed, I used a string[] to add terms to, which went fine in Lucene but I guess doesn't work in Corax (or works differently), I'm looking through terms to see if this is true.

I was indexing like this:

Query = new string[] {
                        result.OrderableName[language.DefaultLanguage],
                        result.OrderableDescription[language.DefaultLanguage],
                        result.Color
}

I will try to find this out in the evening, also I don't know if you changed the analyzer, which also could have caused this. Though I don't know why H, HY doesn't give me HYDR TEST, but HYD* does give me. But I will create a seperate issue, the initial issue is fixed :)
