### ISSUE TITLE
When do you want to upgrade packages from net6 to net8?

### ISSUE THREAD

**Issue by antontuz** [ravendb/ravendb#17791]
Hello, I'm asking this question because we use your db in our project. We would like to migrate to net 8 but we can't because of raven which use .net6. Tell me, please, will you upgrade the packages?

**Comment by ayende** [comment]
Are you talking about the RavenDB _client_ ? You should be able to update that right now and use that with .NET 8.0

**Comment by nthonymiller** [comment]
I recently upgrade my project to net8 and found that RavenDb worked perfectly fine.
