### ISSUE TITLE
Exception with Decimal Helper

### ISSUE THREAD

**Issue by Astrovolts** [ravendb/ravendb#17813]
Please note I am using all of the latest dependencies supporting .net framework 4.8

2023-12-04 23:09:35.9592 [ERROR; Root] The type initializer for 'Sparrow.Utils.DecimalHelper' threw an exception.
Sparrow
System.ArgumentException: Instance field '_flags' is not defined for type 'System.Decimal'
  at System.Linq.Expressions.Expression.Field (System.Linq.Expressions.Expression expression, System.String fieldName) [0x00052] in <d22af090bceb4be792f53595cf074724>:0 
  at Sparrow.Utils.DecimalHelper.CreateIsDoubleMethod () [0x0001a] in <5e51639af1624621be593671f72f4407>:0 
  at Sparrow.Utils.DecimalHelper..ctor () [0x00006] in <5e51639af1624621be593671f72f4407>:0 
  at Sparrow.Utils.DecimalHelper..cctor () [0x00000] in <5e51639af1624621be593671f72f4407>:0 
  
  my code is as follows:
`public static class RavenDBConnection
    {
        private const string CERTIFICATE_PASSWORD = "-";
        private static string CERTIFICATE_PATH = Path.GetFullPath("./certificate.pfx");

        public static X509Certificate2 GetCertificate()
        {
            return new X509Certificate2(CERTIFICATE_PATH, CERTIFICATE_PASSWORD);
        }
        public static void Initialize()
        {
            var certificate = GetCertificate();
            LazyStore = new Lazy<IDocumentStore>(() =>
            {
                var store = new DocumentStore
                {
                    Urls = new[] { "-" },
                    Database = "-",
                    Certificate = certificate,
                };
                return store.Initialize();
            });
        }

        private static Lazy<IDocumentStore> LazyStore;

        public static IDocumentStore Store => LazyStore.Value;
    }`

**Comment by ayende** [comment]
What version of RavenDB client are you using?
What is the exact framework version that you are using?

**Comment by Astrovolts** [comment]
RavenDb.Client 6.0.1 and .net framework 4.8
Raven file version 6.0.1.60003

**Comment by Astrovolts** [comment]
> What version of RavenDB client are you using? What is the exact framework version that you are using?

Is there a way that the sparrow library can be inspected to determine the cause of this issue?

**Comment by ppekrol** [comment]
Hi, I've managed to reproduce your issue. It only occurs on .NET Framework, works fine on .NET. Will try to find a solution for .NET Framework soon.

Meanwhile, is there a possibility for you to switch to .NET? Another workaround would be to avoid serializing and deserializing decimals for the time being.

**Comment by ppekrol** [comment]
https://github.com/ravendb/ravendb/pull/17819 I've opened a PR with the fix, after this is merged we will release a nightly build on MyGet

**Comment by Astrovolts** [comment]
> #17819 I've opened a PR with the fix, after this is merged we will release a nightly build on MyGet

Thank you for resolving this. Could you direct me to where I can download this build? I've looked all over and I haven't found any nightly builds for ravendb C# client

**Comment by mcrio** [comment]
Probably here https://myget.org/feed/ravendb/package/nuget/RavenDB.Client

p.s. on the downloads page there's a link to MyGet

**Comment by ppekrol** [comment]
@Astrovolts I've merged that PR, should be available on MyGet that @mcrio send you within 1h.
