### ISSUE TITLE
Index out of bounds of Array when storing object

### ISSUE THREAD

**Issue by Astrovolts** [ravendb/ravendb#17834]
Using .net framework 4.8.
Using the recently released nightly build on nuget that corrects the previously reported issue with flags and _flags.

`Index was outside the bounds of the array.
  at Raven.Client.Documents.Conventions.DocumentConventions.GetIdentityProperty (System.Type type) [0x00006] in <d5186281300b4fe4b2e2f5e1aa5e2869>:0 
  at Raven.Client.Documents.Identity.GenerateEntityIdOnTheClient.GetIdentityProperty (System.Type entityType) [0x00000] in <d5186281300b4fe4b2e2f5e1aa5e2869>:0 
  at Raven.Client.Documents.Identity.GenerateEntityIdOnTheClient.TryGetIdFromInstance (System.Object entity, System.String& id) [0x00015] in <d5186281300b4fe4b2e2f5e1aa5e2869>:0 
  at Raven.Client.Documents.Session.InMemoryDocumentSessionOperations.Store (System.Object entity) [0x00006] in <d5186281300b4fe4b2e2f5e1aa5e2869>:0 `

Object class is the following:
`public class PlayerObject
{
    public string Id { get; set; } 
    public InventoryObject Inventory { get; set; }
    public string ActiveShipId { get; set; }
    public HashSet<string> Fleet { get; set; }
    public PlayerObject() 
    {
        Inventory = new InventoryObject();
    }
}`

**Comment by ppekrol** [comment]
Hi @Astrovolts 

Can you share a repro maybe? Just tried that on net48 console app without any issues. Do you have any non-default conventions maybe there?

Here is a code that I've used:

```csharp
        static void Main(string[] args)
        {
            using (var store = new DocumentStore())
            {
                store.Urls = new[] { "http://live-test.ravendb.net" };
                store.Database = "DBX";

                store.Initialize();

                using (var session = store.OpenSession())
                {
                    session.Store(new PlayerObject());

                    session.SaveChanges();
                }
            }
        }

        public class PlayerObject
        {
            public string Id { get; set; }
            public InventoryObject Inventory { get; set; }
            public string ActiveShipId { get; set; }
            public HashSet<string> Fleet { get; set; }
            public PlayerObject() { Inventory = new InventoryObject(); }
        }

        public class InventoryObject { }
```

**Comment by Astrovolts** [comment]
Yes, this .net framework 4.8 build is running on linux and not windows.

**Comment by ayende** [comment]
To my knowledge, .NET Framework 4.8 is Windows only.
Can you try the above code and see if this reproduce the issue for you?

**Comment by Astrovolts** [comment]
> To my knowledge, .NET Framework 4.8 is Windows only. Can you try the above code and see if this reproduce the issue for you?

It's running on Wine, using linux as the operating system. .net framework is installed.
It works fine on my machine, but not on linux. That would be the environment issue and not a bug with the code?

**Comment by ayende** [comment]
I would expect something in the environment, yes.
If you can debug the code and find out what is going there, it would be really helpful.
I'm afraid that we can't reproduce or understand this

**Comment by Astrovolts** [comment]
Thank you, I do not know how to reproduce it because I do not manage the environment.
