### ISSUE TITLE
Subscriptions receiving error when using 'include' keyword with RQL

### ISSUE THREAD

**Issue by nthonymiller** [ravendb/ravendb#17845]
Creating a new subscription the follow RQL works correctly:

```
from 'Orders' as o
where o.ReferenceId == null 
and o.OrderStatus == 'Approved' 
and o.'@metadata'.'@refresh' == null 
```

However when the include keyword is used studio shows an error - **Failed to test subscription task**: 

![image](https://github.com/ravendb/ravendb/assets/5146546/df3e52bc-ed7e-4397-a378-4e670aeffce6)

```
from 'Orders' as o
where o.ReferenceId == null 
and o.OrderStatus == 'Approved' 
and o.'@metadata'.'@refresh' == null 
include o.SupplierId
```

**Comment by ayende** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-21804/Invalid-JSON-returned-from-the-Subscription-test-when-using-include-that-has-no-results

Okay, looks like this is a bug in the test feature when you are trying to include items but have nothing to include.
If you _have_ items to include, it will work.

**Comment by nthonymiller** [comment]
The query is from my own model, and the Supplier does exist. Due to the filtering of the metadata property I need to convert my subscription from Linq to RQL,

Here is my existing subscription creation which worked perfectly fine, except I need to filter out refresh which I don't believe I can do in a Linq query.

```
        await Store.Subscriptions.CreateAsync(new SubscriptionCreationOptions<Account.Domain.Order>
        {
          Name = subscriptionName,
          Filter = order => order.ReferenceId == null && order.OrderStatus == Account.Domain.OrderStatus.Approved,
          Includes = builder => builder
            .IncludeDocuments<Supplier.Domain.Supplier>(x => x.SupplierId)
            .IncludeDocuments<Tracking.Domain.Job>(x => x.JobId)
            .IncludeDocuments<Inventory.Domain.Product>(x => x.Items.Select(i => i.ProductId))
        });

```

**Comment by nthonymiller** [comment]
Using the RavenDb sample dataset, I receive the error with Subscriptions using:

```
from 'Orders' as o
where true
and o.'@metadata'.'@refresh' == null 
include o.Employee
```

**Comment by ayende** [comment]
Yes, that is a bug, we'll be fixing that.
Should affect only the try page, mind
