### ISSUE TITLE
Unable to query metadata property @refresh

### ISSUE THREAD

**Issue by nthonymiller** [ravendb/ravendb#17841]
Server Version: 6.0.0

Using the RavenDb sample database filtering @refresh metadata property does not work.

Steps to reproduce:
1. Generate Sample database.
2. Enable Refresh from settings
3. Update an Order, setting the refresh value to a valid date in UTC.
4. Write query to retrieve all Orders where @refresh is null

RQL: 
```
from 'Orders' as c
where c.'@metadata'.'@refresh' == null
```

No documents are returned

Trying to get Subscriptions to work

**Comment by ayende** [comment]
That is a query that test that the field _exists_ and is equal to `null`. You don't have the field, so need to run:

```
from 'Orders' as c
where true and not exists(c.'@metadata'.'@refresh')
```

This sort of query is typically used in subscriptions, where we don't care about the existence of the field, but for queries, it matter.
