### ISSUE TITLE
RavenDB.TestDriver not working with dotnet 8.0.0

### ISSUE THREAD

**Issue by alexeykorsakov** [ravendb/ravendb#17868]
Framework: 'Microsoft.NETCore.App', version '7.0.13' (x64)
.NET location: /usr/share/dotnet/
The following frameworks were found:
  8.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by ppekrol** [comment]
Hi, this is expected. Our server (used by the test driver) that you are using was compiled using .NET 7.0.13, so it requires exactly that (or newer) version of .NET 7.0 installed on the machine. You can read more about it here: https://ravendb.net/docs/article-page/6.0/csharp/server/Embedded#net-frameworkversion

We will be releasing version 6 of our Product compiled with .NET 8 around February.
