### ISSUE TITLE
Defining Index using AbstractMultiMapIndexCreationTask with @var causes index to fail to compile

### ISSUE THREAD

**Issue by nthonymiller** [ravendb/ravendb#17875]
I created an MultiMap Index 

```
public sealed class MyClassIndex : AbstractMultiMapIndexCreationTask<Class> 
{

  public MyClassIndex() 
  {
    AddMap<LanguageClass>(classes => from @class in classes where @class.Status == 'Active')
  }
}
```

Using `@class` causes the index to fail to compile:

Error Building database indexes Failed to create one or more indexes. Please see inner exceptions for more details. (Failed to compile index name = MyClassIndex)
System.AggregateException: Failed to create one or more indexes. Please see inner exceptions for more details. (Failed to compile index name = MyClassIndex)

Changing the variable from `@class` to `myClass` works. This previously worked in RavenDb 5x

**Comment by arekpalinski** [comment]
It looks as an issue that we have fixed recently: https://github.com/ravendb/ravendb/pull/17862

@Lwiel can you please check that?

**Comment by Lwiel** [comment]
It doesn't seem like correct LINQ syntax. Such index is created correctly on the newest version of 5.4.
```csharp
public sealed class MyClassIndex : AbstractMultiMapIndexCreationTask<Class> 
{
    public MyClassIndex()
    {
        AddMap<LanguageClass>(classes => from @class in classes where @class.Status == "Active" select new { Status = @class.Status });
    }
}
```

**Comment by Lwiel** [comment]
Can you please let us know if you still have this issue?
