### ISSUE TITLE
Setting ravenDB on MacOS

### ISSUE THREAD

**Issue by Tweek154** [ravendb/ravendb#17870]
I ran into a problem when I find the file named "Raven.server.exe" in folder "Server". I didn't see it when I download file from https://ravendb.net/download (MacOS/M1). Can anyone please help me to solve this problem and show me step by step to install it on my mac? Thank all for your help

**Comment by ayende** [comment]
Did you make sure you downloaded the right package? The `Raven.Server.exe` belongs only on the Windows builds, not MacOS ones
There, you should run either `run.sh` or `Raven.Server`

![image](https://github.com/ravendb/ravendb/assets/116915/d672b831-5a8f-44da-bee3-44912bd662a3)

**Comment by Tweek154** [comment]
Thanks you
