### ISSUE TITLE
Storing a DateTimeOffset property in an index will set the Offset to 00:00

### ISSUE THREAD

**Issue by stevehansen** [ravendb/ravendb#17901]
When a DateTimeOffset property is stored inside an index (StoreAllField or single field) for both Corax/Lucene indexes it will convert it to UTC time and store it like that instead of keeping the original value.

Loading the document directly, not storing the field (so it will fetch from document) will give the correct value (i.e. 2023-11-27T15:10:40.9052815+01:00) but the index just stores the UTC value (i.e. 2023-11-27T14:10:40.9052815Z).

```c#
using Raven.Client.Documents;
using Raven.Client.Documents.Indexes;
using Raven.TestDriver;
using Xunit;

namespace RavenDateTimeOffsetIssue;

public class Tests : RavenTestDriver
{
    public Tests()
    {
        ConfigureServer(new());
    }

    [Fact]
    public void Storing_DataTimeOffset_Should_Keep_Offset()
    {
        using var store = GetDocumentStore();

        store.ExecuteIndex(new SomeRecords_StoreCreatedAt());

        using (var session = store.OpenSession())
        {
            var explicitOffset = new DateTimeOffset(2021, 1, 1, 0, 0, 0, TimeSpan.FromHours(1));

            session.Store(new SomeRecord(null!, "First", explicitOffset));
            session.SaveChanges();
        }

        WaitForIndexing(store);

        using (var session = store.OpenSession())
        {
            var records = session.Query<SomeRecord, SomeRecords_StoreCreatedAt>().ProjectInto<SomeIndexRecord>().ToArray();

            Assert.Equal(1, records.Length);
            Assert.Equal(TimeSpan.FromHours(1), records[0].CreatedAt.Offset);
        }
    }
}

public record SomeRecord(string Id, string Name, DateTimeOffset CreatedAt);

public class SomeIndexRecord
{
    public string Id { get; init; }
    public string Name { get; init; }
    public DateTimeOffset CreatedAt { get; init; }
}

public class SomeRecords_StoreCreatedAt : AbstractIndexCreationTask<SomeRecord>
{
    public SomeRecords_StoreCreatedAt()
    {
        Map = records => from record in records
            select new SomeIndexRecord
            {
                Id = record.Id,
                Name = record.Name,
                CreatedAt = record.CreatedAt,
            };

        Store(nameof(SomeRecord.CreatedAt), FieldStorage.Yes);
    }
}
```

**Comment by Lwiel** [comment]
The value of `CreatedAt` field stored in the index and document is different, because when indexing field of type `DateTimeOffset` we use its `UtcDateTime` property, which already includes the offset. This means the offset value is not stored separately in the index. We do this to have common format (UTC) for all fields representing dates.

The default [projection behavior](https://ravendb.net/docs/article-page/5.4/csharp/client-api/session/querying/how-to-customize-query#projection) is to take the field value from index if it's stored there, otherwise to take it from document. That's why your projected result has default `Offset` value. Either not storing the `CreatedAt` field, or changing the projection behavior to get fields from document would make your query return correct results.

**Comment by arekpalinski** [comment]
@stevehansen Does the answer provided by @Lwiel make it clear for you? Did you manage to achieve the behavior you were looking for?

**Comment by stevehansen** [comment]
@arekpalinski @Lwiel not really, I understand that for search purposes it can be stored internally as UTC because it doesn't matter, but when I explicitly use Store to retrieve the value it shouldn't convert (or worse, lose information) the value at all.
The issue becomes more obvious if you also have a calculation in the index that is stored, e.g. ExpiresAt = CreatedAt.AddMonths(4) because you need the Store option for that, there is no workaround for those values

**Comment by maciejaszyk** [comment]
@stevehansen we are storing the exact same thing that we are indexing. In the case of dates, this is `DateTime`. For your purposes, I suggest setting `FieldIndexing` as `Exact`. In such a case, we will put the original string without any processing. Please keep in mind that when you set the `WHERE` clause, it will work on strings, not on dates. In such a scenario, I suggest creating an additional field with standard indexing and performing `WHERE` clauses on it.

```csharp
  [Fact]
    public void Storing_DataTimeOffset_Should_Keep_Offset()
    {
        using var store = GetDocumentStore();

        store.ExecuteIndex(new SomeRecords_StoreCreatedAt());
        var explicitOffset = new DateTimeOffset(2021, 1, 1, 0, 0, 0, TimeSpan.FromHours(1));

        using (var session = store.OpenSession())
        {
            var explicitOffset2 = new DateTimeOffset(2021, 1, 1, 0, 0, 0, TimeSpan.FromHours(-4));

            session.Store(new SomeRecord(null!, "First", explicitOffset));
            session.Store(new SomeRecord(null!, "Second", explicitOffset2));
            session.SaveChanges();
        }

        Indexes.WaitForIndexing(store);

        using (var session = store.OpenSession())
        {
            var records = session.Query<SomeRecord, SomeRecords_StoreCreatedAt>()
                .ProjectInto<SomeIndexRecord>()
                .ToArray();
            Assert.Equal(2, records.Length);
            
            records = session.Query<SomeRecord, SomeRecords_StoreCreatedAt>()
                .Where(x => x.CreatedAt < new DateTimeOffset(2021, 1, 1, 0, 0, 0, TimeSpan.FromHours(-3)))
                .ProjectInto<SomeIndexRecord>()
                .ToArray();
            
            WaitForUserToContinueTheTest(store);
            Assert.Equal(1, records.Length);
            Assert.Equal(TimeSpan.FromHours(1), records[0].CreatedAtProjection.Offset);
        }
    }

}

public record SomeRecord(string Id, string Name, DateTimeOffset CreatedAt);

public class SomeIndexRecord
{
    public string Id { get; init; }
    public string Name { get; init; }
    public DateTimeOffset CreatedAtProjection { get; init; }
    
}

public class SomeRecords_StoreCreatedAt : AbstractIndexCreationTask<SomeRecord>
{
    public SomeRecords_StoreCreatedAt()
    {
        Map = records => from record in records
            select new 
            {
                Id = record.Id,
                Name = record.Name,
                CreatedAt = record.CreatedAt, // required for `Where` clause to perform operations on dates, not strings
                CreatedAtProjection = record.CreatedAt // stores DateTimeOffset for projections
            };

        Index("CreatedAtProjection", FieldIndexing.Exact);
        Store("CreatedAtProjection", FieldStorage.Yes);
    }
}

```

**Comment by stevehansen** [comment]
We just index the field twice now, once as Exact (which is used for showing), and once as Default (for filtering).
