### ISSUE TITLE
Persistent ConcurrentDictionary for index locks

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [ravendb/ravendb#17917]
Hi,

In https://github.com/ravendb/ravendb/blob/v6.0/src/Raven.Server/Documents/Indexes/IndexStore.cs there is an `_indexLocks` which seems to be disposed only when `IndexStore` is disposed. If I'm understanding correctly we are retaining a `SemaphoreSlim` object persistently in memory for every index. While this is better from the sense of performance, as the number of indexes grows then cleaning the dictionary might be considered preferable.

I am the author of a library called [AsyncKeyedLock](https://github.com/MarkCiliaVincenti/AsyncKeyedLock) that handles such cleaning and I would be happy to make a PR to help with this, but I'm not sure whether you are willing to sacrifice some performance for memory.

**Comment by ayende** [comment]
In order for this to ever be a problem, you'll need to have more than thousands of indexes.
In our experience, even in the most demanding users will not have even a thousand indexes over the lifetime of the database.

The linked repository talks about using the for concurrency for things like account ids, which are unbounded. That isn't the scenario for us.
