### ISSUE TITLE
Raven testserver cannot run with .NET v8

### ISSUE THREAD

**Issue by jetzezoethout** [ravendb/ravendb#18083]
I was trying to update a project to .NET v8, but the `Raven.TestDriver` doesn't seem to be able to run with this version yet. A minimal example can be found [here](https://github.com/jetzezoethout/Raven-Test). The example is containerized to make sure that .NET v8 is the only runtime available.

On [this commit](https://github.com/jetzezoethout/Raven-Test/tree/2bf5b4d407237fe0875040308c5f7c19d126e1f7), run

```bash
docker build -t raven-test . && docker run --rm raven-test
```

This yields the following error:

```bash
  Failed ATest [156 ms]
  Error Message:
   System.InvalidOperationException : Could not find a matching runtime for '7.0.14+'. Available runtimes:
- 8.0.1
```

This makes sense, because the default framework version is seems to be `7.0.14+` in release `6.0.4` of Raven. However, setting the framework version in [this commit](https://github.com/jetzezoethout/Raven-Test/tree/323be70e7c810dfbcf4c4a390e3e389b4aac2498) also doesn't work. This yields the following error:

```bash
  Failed ATest [160 ms]
  Error Message:
   System.InvalidOperationException : Unable to start the RavenDB Server
Error:
You must install or update .NET to run this application.

App: /Tests/bin/Debug/net8.0/RavenDBServer/Raven.Server.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '7.0.14' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  8.0.1 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
```

**Comment by ppekrol** [comment]
https://github.com/ravendb/ravendb/issues/17868#issuecomment-1857407927
Wee will be releasing .NET 8 version of 6.0, the 6.0.100 next week.
