### ISSUE TITLE
Dictionary inconsistencies between store and patch for enum keys

### ISSUE THREAD

**Issue by loraderon** [ravendb/ravendb#18131]
*Edit*
Store always uses string keys and patch always uses integer keys no matter if `SaveEnumsAsIntegers` is specified or not.

-------

Store does not store enums as integers for dictionary keys when `SaveEnumsAsIntegers` is specified.

However, Patch seems to use integrers for dictionary keys which results in inconsistent data.

## Test case
```cs
void Main()
{
	//Raven.Embedded.EmbeddedServer.Instance.StartServer();
	using var store = Raven.Embedded.EmbeddedServer.Instance
		.GetDocumentStore(new Raven.Embedded.DatabaseOptions("db")
		{
			Conventions = new()
			{
				SaveEnumsAsIntegers = true,
			},
		});
	store.Initialize();

	using var session = store.OpenSession();
	var foo = new Foo
	{
		Days = {
			{ DayOfWeek.Monday, "monday-store" },
		}
	};

	session.Store(foo);
	session.SaveChanges();

	session.Advanced.Patch<Foo, string>(foo.Id, f => f.Days[DayOfWeek.Monday], "monday-patch");
	session.SaveChanges();

	Raven.Embedded.EmbeddedServer.Instance.OpenStudioInBrowser();
}

public class Foo
{
	public string Id { get; set; }

	public Dictionary<DayOfWeek, string> Days { get; set; } = new();
}
```

## Results
![image](https://github.com/ravendb/ravendb/assets/76928/ad939977-26f7-4e55-b137-cb8abd7de2ed)

**Comment by ppekrol** [comment]
We will take a look. Meanwhile as a workaround you could write your own JsonConverter for that type that contains dictionary.
https://issues.hibernatingrhinos.com/issue/RavenDB-22084/Dictionary-inconsistencies-between-store-and-patch-when-specifying-SaveEnumsAsIntegers
Custom converters (we are using JSON.NET for serialization), can be registered via DocumentConventions.Serialization.CustomizeJsonSerializer (and Deserializer) methods: https://ravendb.net/docs/article-page/6.0/csharp/client-api/configuration/serialization#customizejsonserializer

**Comment by loraderon** [comment]
I also noticed that the enums are not unique even after reduce. 

*Edit:*
Since it affects all enums (not only dictaionry keys) I started a discussion about it #18439

------

![image](https://github.com/ravendb/ravendb/assets/76928/8aed5d21-f0c2-4ce4-b259-08803bf907a9)

This index groups the results by day and spits out all the values.
```cs
public class FooIndex : AbstractIndexCreationTask<Foo, FooIndex.Result>
{
	public FooIndex()
	{
		Map = foos =>
			from f in foos
			from day in f.Days
			select new Result
			{
				Day = day.Key,
				Values = new[] { day.Value},
			};
		
		Reduce = results =>
			from result in results
			group result by new { result.Day } into g
			select new Result
			{
				Day = g.Key.Day,
				Values = g.SelectMany(x => x.Values).ToArray()
			};
	}
	
	public class Result
	{
		public DayOfWeek Day { get; set; }
		public string[] Values { get; set; }
	}
}
```

**Comment by ayende** [comment]
For reference, the issue is different: https://github.com/ravendb/ravendb/discussions/18439

**Comment by loraderon** [comment]
I just noticed that the value of `SaveEnumsAsIntegers` does not matter at all. Dictionary enum keys are always **stored** as strings and **patched** as integers.

![image](https://github.com/ravendb/ravendb/assets/76928/a7c6a58e-703c-4944-a37c-21d3dc140537)


```cs
public class DictionaryEnumKeysTests : RavenTestDriver
{
    [Fact]
    public void DictionaryEnumKeys()
    {
        using var store = GetDocumentStore();

        using (var session = store.OpenSession())
        {
            var foo = new FooDictionaryEnum
            {
                Days = new() { { DayOfWeek.Monday, "monday-store" } },
            };
            session.Store(foo);

            session.SaveChanges();

            session.Advanced.Patch<FooDictionaryEnum, string>(foo.Id.ToString(), f => f.Days[DayOfWeek.Monday], "monday-patched");

            session.SaveChanges();
        }

        OpenBrowser(store.Urls.First());
        WaitForUserToContinueTheTest(store);
    }

    public class FooDictionaryEnum
    {
        public string Id { get; set; }
        public Dictionary<DayOfWeek, string> Days { get; set; }
    }
}
```
