### ISSUE TITLE
Where to find RVN for MacOS? Or how to generate a proper Helm file?

### ISSUE THREAD

**Issue by dannyyy** [ravendb/ravendb#18153]
I wanted to prepare a `values.yaml` for a Helm Kubernetes installation to play a bit around. But I was not able to find the referenced `rvn` tool. 
I downloaded the server package and the tools package from the website for my MacBook M1, but haven't found a file that's named after `rvn` or behaves like that.

Usually, the Helm configuration file is well documented, which allows starting from a common example, and just to modify the keys which derive from the default. But there seems to be no documentation about the keys and their expected value.

Running the installation wizard doesn't really help, as almost every aspect that is container specific is not part of the assistant.

Does someone have an example values.yaml that I can use as a template? That is more or less complete?

**Comment by ayende** [comment]
In the macOS package, `rvn` is located under `Server/rvn`, next to the `Raven.Server` file.

**Comment by dannyyy** [comment]
I was literally blind. Thank you
