### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by AbdulovHell** [ravendb/ravendb#18160]
Hello. Im getting such error while trying to get a document from database. Same project works on windows and linux (tried on debian 10 and 11) but on Android 14.0 this problem occurs. RavenDB.Client 6.0.100 from NuGet.

```
[DOTNET] Object reference not set to an instance of an object.
[DOTNET]    at Raven.Client.Http.RequestExecutor.CreateHttpMessageHandler(X509Certificate2 certificate, Boolean setSslProtocols, Boolean useHttpDecompression, Boolean hasExplicitlySetDecompressionUsage, Nullable`1 pooledConnectionLifetime, Nullable`1 pooledConnectionIdleTimeout) in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 2099
[DOTNET]    at Raven.Client.Http.RequestExecutor.CreateClient() in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 2127
[DOTNET]    at Raven.Client.Http.RequestExecutor.<GetHttpClient>b__90_0() in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 239
[DOTNET]    at System.Lazy`1[[Raven.Client.Http.RequestExecutor.HttpClientCacheItem, Raven.Client, Version=6.0.100.0, Culture=neutral, PublicKeyToken=37f41c7f99471593]].ViaFactory(LazyThreadSafetyMode mode)
[DOTNET] --- End of stack trace from previous location ---
[DOTNET]    at System.LazyHelper.ThrowException()
[DOTNET]    at System.Lazy`1[[Raven.Client.Http.RequestExecutor.HttpClientCacheItem, Raven.Client, Version=6.0.100.0, Culture=neutral, PublicKeyToken=37f41c7f99471593]].CreateValue()
[DOTNET]    at System.Lazy`1[[Raven.Client.Http.RequestExecutor.HttpClientCacheItem, Raven.Client, Version=6.0.100.0, Culture=neutral, PublicKeyToken=37f41c7f99471593]].get_Value()
[DOTNET]    at Raven.Client.Http.RequestExecutor.GetHttpClient() in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 239
[DOTNET]    at Raven.Client.Http.RequestExecutor.get_HttpClient() in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 97
[DOTNET]    at Raven.Client.Http.RequestExecutor.<SendAsync>d__125`1[[Raven.Client.Http.Topology, Raven.Client, Version=6.0.100.0, Culture=neutral, PublicKeyToken=37f41c7f99471593]].MoveNext() in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 1189
[DOTNET]    at Raven.Client.Http.RequestExecutor.<SendRequestToServer>d__124`1[[Raven.Client.Http.Topology, Raven.Client, Version=6.0.100.0, Culture=neutral, PublicKeyToken=37f41c7f99471593]].MoveNext() in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 1107
[DOTNET]    at Raven.Client.Http.RequestExecutor.<ExecuteAsync>d__122`1[[Raven.Client.Http.Topology, Raven.Client, Version=6.0.100.0, Culture=neutral, PublicKeyToken=37f41c7f99471593]].MoveNext() in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 994
[DOTNET]    at Raven.Client.Http.RequestExecutor.UpdateTopologyAsync(UpdateTopologyParameters parameters) in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 557
[DOTNET]    at Raven.Client.Http.RequestExecutor.FirstTopologyUpdate(String[] initialUrls, Nullable`1 applicationIdentifier) in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 821
[DOTNET]    at Raven.Client.Util.AsyncHelpers.RunSync(Func`1 task) in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Util\AsyncHelpers.cs:line 73
[DOTNET]    at Raven.Client.Http.RequestExecutor.Execute[GetDocumentsResult](RavenCommand`1 command, JsonOperationContext context, SessionInfo sessionInfo) in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Http\RequestExecutor.cs:line 603
[DOTNET]    at Raven.Client.Documents.Session.DocumentSession.Load[SubscribeStat](String id) in D:\Builds\RavenDB-Stable-6.0\60012\src\Raven.Client\Documents\Session\DocumentSession.Load.cs:line 39
[DOTNET]    at SubscribeAPI.SubscribeControl.LoadSubscribe(String name) in C:\Users\HP\OneDrive\repos\SubStateBrowser\SubscribeAPI\SubscribeControl.cs:line 349
```

**Comment by arekpalinski** [comment]
Hi @AbdulovHell

The RavenDB Client API was not tested on Android, the communication with the Server with our recommended setup requires X509Certificates, which are known to be problematic on mobile platforms. The recommended architecture, to avoid communicating directly between mobile phone and database is to have an intermediary API in which RavenDB Client API can be used. By doing that you are decreasing a security risk of exposing your database to the world.

**Comment by AbdulovHell** [comment]
> By doing that you are decreasing a security risk of exposing your database to the world.

A hacked API is no better than an exposed certificate. both will give access to write/read a certain part of the database.

So... is there any chance that it will be fixed? Maybe there is another solution or I can try solve the problem myself (maybe I'm missing something, but I don't see it without debugging information from the nuget package)?

**Comment by ppekrol** [comment]
Hi @AbdulovHell 
At this point of time we would recommend using a intermediate API, as @arekpalinski wrote having a database exposed is an unusual and not recommended by us setup.

We would accept a PR from you with the fix, you could reference Sparrow and Raven.Client projects in your solution so it would be easier for you to debug the problem.

**Comment by AbdulovHell** [comment]
I made my own version of the client and encountered the same error, but now having the opportunity to see everything from the inside, I found the reason and solution for it.

The error occurs when you add a certificate to a collection that is not initialized (null). Details and solution are here:
https://github.com/dotnet/runtime/issues/73960#issuecomment-1216539011

The addition I suggest: 
Сheck ClientCertificates for null in [this place](https://github.com/ravendb/ravendb/blob/433e4e465ca9313af067c32e2142bb4d8a1277ad/src/Raven.Client/Http/RequestExecutor.cs#L2083), if it is null, throw an exception with information that it is necessary to add `<UseNativeHttpHandler>false</UseNativeHttpHandler>` to the project.

**Comment by ppekrol** [comment]
I've created an issue. We will throw a more meaningful exception there.

Issue link: https://issues.hibernatingrhinos.com/issue/RavenDB-22308/Throw-meaningful-exception-when-HttpClientHandler-does-not-support-certificates

Thanks for investigation!
