### ISSUE TITLE
Dictionary Collection Values Being Altered After Patch Operation

### ISSUE THREAD

**Issue by oiBio** [ravendb/ravendb#18233]
We've encountered an unexpected behavior in RavenDB when using patch operations on documents containing a 'Dictionary<string,object>' to store dynamic user content. Specifically, patching to remove certain key-value pairs inadvertently alters the structure of nested collections within the dictionary, such as lists of strings, converting their values into empty arrays. This issue does not occur when using the store command for similar operations.

**Illustration of the Issue:**

**Before Patch Operation:**
The dictionary contains a mix of single values and collections, represented accurately in RavenDB Studio:

```
{
    "Dictionary": {
        "intValue": 1,
        "fuu": "bar",
        "listOfStrings": [
            "Value 1",
            "Value 2"
        ]
    }
}
```
**After Patch Operation:**
Following a patch operation to remove the "fuu" key-value pair, the collection within the dictionary (listOfStrings) is disrupted, with its contents replaced by empty arrays:

```
{
    "Dictionary": {
        "intValue": 1,
        "listOfStrings": [
            [],
            []
        ]
    }
}
```
This issue does not occur when employing the store command for similar modifications, where the listOfStrings retains its original values.

**Steps to Reproduce:**

1. Initialize an instance of RavenDB's EmbeddedServer and set up a document store.
2. Create and store a document containing a Dictionary<string, object> with various data types, including a list of strings.
3. Apply a patch operation to remove a key-value pair from the dictionary.
4. Observe the post-patch structure of the dictionary, noting particularly the alteration of nested collections.

**Expected Behavior:**

The patch operation should selectively remove the specified key-value pair without impacting the structure or content of other dictionary entries, especially nested collections.

**Actual Behavior:**

The patch operation not only removes the specified entry but also disrupts the integrity of nested collections within the dictionary, transforming them into empty arrays.

**Example Code for Reproduction:**

```

EmbeddedServer.Instance.StartServer();
using var store = EmbeddedServer.Instance.GetDocumentStore("patch-test");


var idForPatchModel = "Model/1";
var idForStoreModel = "Model/2";

var originalDict = new Dictionary<string, object>
            {
                { "string", "No Problem" },
                { "listOfStrings", new List<string>() {"Value 1", "Value 2"} }
            };


using (var session = store.OpenSession())
{
    session.Store(new Model() { Dictionary = originalDict }, idForPatchModel);
    session.Store(new Model() { Dictionary = originalDict }, idForStoreModel);
    session.SaveChanges();
}


using (var session = store.OpenSession())
{
    using var stream = session.Advanced.Stream(session.Query<Model>()
        .Where(e => e.Id == idForPatchModel));
    while (stream.MoveNext())
    {
        var newDict = stream.Current.Document.Dictionary;
        newDict.Remove("string");
        // Removes all Entries in the Document of Dictionary["listOfStrings"]
        session.Advanced.Patch(idForPatchModel, (Model m) => m.Dictionary, newDict);
    }

    session.SaveChanges();
}

using (var session = store.OpenSession())
{
    using var stream = session.Advanced.Stream(session.Query<Model>()
        .Where(e => e.Id == idForStoreModel));
    while (stream.MoveNext())
    {
        var model = stream.Current.Document;
        model.Dictionary.Remove("string");
        session.Store(model, stream.Current.Id);    // This works...
    }

    session.SaveChanges();
}


// As you can see, the values of idForPatchModel are gone
EmbeddedServer.Instance.OpenStudioInBrowser();

class Model
{
    public string Id { get; set; }
    public Dictionary<string, object> Dictionary { get; set; } = new();
}
```

We have adopted the use of the store method as a temporary workaround. Nonetheless, we are eager to resolve this discrepancy to leverage patch operations without compromising the integrity of nested collections within our dictionaries.

**Comment by ayende** [comment]
The reason for this issue is that you are mixing a couple of features in an unexpected way.
You are storing `Dictionary<string,object>` and when you get it back, we use dynamic types for this. So the value is actually:

![image](https://github.com/ravendb/ravendb/assets/116915/b3187043-6ab0-4979-a9f8-246f027dbbc7)


And it isn't using a `string` directly, but rather:

![image](https://github.com/ravendb/ravendb/assets/116915/6bfa3d8e-dc34-47f5-8b15-9a7648e8edaa)


Which wrap it.

The serializer that is used by the `Patch` command isn't able to dig deeper into that, since you are mixing both dynamic and static types.

The solution for that is to switch to dynamic types directly, you need to change a single line of code:

```
session.Advanced.Patch("items/1", (Model m) => (object)m.Dictionary, JObject.FromObject(newDict));
```

And that would work for you.
