### ISSUE TITLE
InvalidQueryException

### ISSUE THREAD

**Issue by saracohenveritone** [ravendb/ravendb#18273]
Hi,
I'm using RavenDB client c#.
I want to write a query with a filter of "where 1=1" like we can do in sql,
But I get InvalidQueryException error.
I need this option because I'm using a generic function that accepts the expression of the where clause as a optional parameter
so when it is null
I would like to write something like this:
`var result = session.Query<T>()
                    .Statistics(out QueryStatistics stats)
                    .Where(wherePredicate?? a => a != null)
                    .OrderByDescending(keySelector).FirstOrDefault();`
Thanks

**Comment by ppekrol** [comment]
Hi, could you write maybe some simple piece of code or a unit test that demonstrates what you want to do? It would be way easier then for us to figure out how to solve it.

Something that pops up into my mind at the moment is that maybe you need to do sth like:
```csharp
IQueryable<T> query = session.Query<T>().Statistics(out QueryStatistics stats);
if (wherePredicate != null)
    query = query.Where(wherePredicate);

query = query.OrderByDescending(keySelector);

var result = query.FirstOrDefault();
```

**Comment by saracohenveritone** [comment]
It exactlly what I did after I got the error
but why can't I do it as I wrote int the question?

**Comment by ayende** [comment]
You may be able to do:  ` .Where(wherePredicate?? a => true)`

But in general, we don't evaluate the where clause, we process the index, so `1 = 1` is not something that we expect to run.

**Comment by saracohenveritone** [comment]
` .Where(wherePredicate?? a => true)` is not working
It throws another exception

**Comment by ayende** [comment]
Then add that in an if statement, instead.
