### ISSUE TITLE
Default SearchEngineType

### ISSUE THREAD

**Issue by jmajoor** [ravendb/ravendb#18430]
According to the documentation [SearchEngineType](https://ravendb.net/docs/article-page/6.0/csharp/server/configuration/indexing-configuration#indexing.static.searchenginetype) defaults to `Lucene`. Both static and auto indexes are by default Lucene indexes.

However when I started a new database and created some indexes, they are all `Corax` indexes.

The default should be `Lucene` as documented otherwise it should be listed as a major breaking change in the server.
And if it is a major breaking change then it should list all the settings that are required to get the database into a lucene compatible state.

**Comment by arekpalinski** [comment]
Hi @jmajoor 

I believe you use  a Community license. Is that correct? As noted on the page https://ravendb.net/buy, the Community license defaults to Corax:

![image](https://github.com/ravendb/ravendb/assets/376551/b58e117f-710a-4004-8831-28ecde132852)

The instructions of how to change the search engine can be found here:
https://ravendb.net/docs/article-page/6.0/csharp/indexes/search-engine/corax#selecting-the-search-engine

**Comment by jmajoor** [comment]
Yes, this is on my Developer license. Since I already had my developer license, I didn't see this very subtle comment.
