### ISSUE TITLE
index paging with corax when order by is set on multiple fields doesn't work

### ISSUE THREAD

**Issue by KresoJ** [ravendb/ravendb#18454]
`{"Query":"from index 'FieldsListIndex' order by Archived, CreatedOn desc select CropRotations, ActiveCropRotation, id() as Id, ArchivedOn, CreatedOn limit $p0, $p1","QueryParameters":{"p0":60,"p1":20}}`

every returned page (parameter p0) contains many identical records when index is switched to Corax. With lucene it works fine, also works fine if order by is only on one column. 

example: 
- from index 'FieldsListIndex' order by Archived,CreatedOn desc select CropRotations, ActiveCropRotation, id() as Id, Name, SoilTextureInfo, GeoInfo, Info, ExternalId, ArchivedOn, CreatedOn limit 10,5

returns "fields-51-C", "fields-34-C", "fields-27-C", "fields-26-C", "fields-24-C"

- from index 'FieldsListIndex' order by Archived,CreatedOn desc select CropRotations, ActiveCropRotation, id() as Id, Name, SoilTextureInfo, GeoInfo, Info, ExternalId, ArchivedOn, CreatedOn limit 5,5

returns "fields-109-C", "fields-83-C", "fields-70-C", "fields-51-C", "fields-27-C"

record fields-27-C is returned on both pages and on many other (Archived is bool)

**Comment by arekpalinski** [comment]
Hi @KresoJ 

What version of RavenDB did you test it on? We released version 6.0.102 today which contains some fixes in similar area in Corax. Could you check it?

**Comment by KresoJ** [comment]
Thank you @arekpalinski, we are on 6.0.101 now. I will upgrade later today and try.

**Comment by KresoJ** [comment]
Unfortunately, the issue is still there.

**Comment by arekpalinski** [comment]
Ok. Do you think you could narrow it down to a failing test - https://ravendb.net/docs/article-page/6.0/csharp/start/test-driver?

**Comment by KresoJ** [comment]
Sure, will do that. Probably not before Thursday.

**Comment by KresoJ** [comment]
`using System;
using Raven.Client.Documents.Indexes;
using System.Linq;
using Raven.TestDriver;
using Xunit;
using Raven.Client.Documents;
namespace Fields.Tests.RavenDB
{
    public class CoraxMultipleOrderBy : RavenTestDriver
    {
        [Fact]
        public void CoraxMultipleOrder_SearchEngine_Test()
        {

            var store = GetDocumentStore();

            store.ExecuteIndex(new OrderByIndexLucene());
            store.ExecuteIndex(new OrderByIndexCorax());

            using (var session = store.OpenSession())
            {
                for (int i = 0; i < 100; i++)
                {
                    session.Store(new TestDocument
                    {
                        Name = "Name_" + i.ToString(),
                        DateCreated = new DateTime(2000, 1, 1).AddDays(i),
                        Archived = i % 2 == 0
                    });
                }

                session.SaveChanges();
            }

            WaitForIndexing(store);

            using (var session = store.OpenSession())
            {
                var luceneDocs = session.Query<TestDocument, OrderByIndexLucene>()
                    .OrderBy(x => x.Archived).ThenByDescending(x => x.DateCreated).Skip(10).Take(10)
                    .ToList();

                var coraxDocs = session.Query<TestDocument, OrderByIndexCorax>()
                    .OrderBy(x => x.Archived).ThenByDescending(x => x.DateCreated).Skip(10).Take(10)
                    .ToList();

                Assert.Equal(luceneDocs, coraxDocs);

            }

        }

        private class OrderByIndexLucene : AbstractIndexCreationTask<TestDocument>
        {

            public OrderByIndexLucene()
            {
                SearchEngineType = Raven.Client.Documents.Indexes.SearchEngineType.Lucene;

                Map = entities => from entity in entities
                                  select new
                                  {
                                      entity.Id,
                                      entity.Name,
                                      entity.Archived,
                                      entity.DateCreated
                                  };

            }
        }

        private class OrderByIndexCorax : AbstractIndexCreationTask<TestDocument>
        {

            public OrderByIndexCorax()
            {
                SearchEngineType = Raven.Client.Documents.Indexes.SearchEngineType.Corax;

                Map = entities => from entity in entities
                                  select new
                                  {
                                      entity.Id,
                                      entity.Name,
                                      entity.Archived,
                                      entity.DateCreated
                                  };

            }
        }

        public class TestDocument
        {
            public string Id { get; set; } = null!;
            public bool Archived { get; set; }
            public DateTime DateCreated { get; set; }
            public string Name { get; set; } = null!;
        }


    }



}`

**Comment by KresoJ** [comment]
`using System;
using Raven.Client.Documents.Indexes;
using System.Linq;
using Raven.TestDriver;
using Xunit;
using Raven.Client.Documents;
namespace Fields.Tests.RavenDB
{
    public class CoraxMultipleOrderByDuplicates : RavenTestDriver
    {
        [Fact]
        public void CoraxMultipleOrder_SearchEngine_Test2()
        {

            var store = GetDocumentStore();

            store.ExecuteIndex(new OrderByIndexCorax());

            using (var session = store.OpenSession())
            {
                for (int i = 0; i < 100; i++)
                {
                    session.Store(new TestDocument
                    {
                        Name = "Name_" + i.ToString(),
                        DateCreated = new DateTime(2000, 1, 1).AddDays(i),
                        Archived = i % 2 == 0
                    });
                }

                session.SaveChanges();
            }

            WaitForIndexing(store);

            using (var session = store.OpenSession())
            {

                var page1 = session.Query<TestDocument, OrderByIndexCorax>()
                    .OrderBy(x => x.Archived).ThenByDescending(x => x.DateCreated).Skip(0).Take(10)
                    .ToList();

                var page2 = session.Query<TestDocument, OrderByIndexCorax>()
                    .OrderBy(x => x.Archived).ThenByDescending(x => x.DateCreated).Skip(10).Take(10)
                    .ToList();

                Assert.NotEqual(page1.First().Id, page2.First().Id);

            }

        }


        private class OrderByIndexCorax : AbstractIndexCreationTask<TestDocument>
        {

            public OrderByIndexCorax()
            {
                SearchEngineType = Raven.Client.Documents.Indexes.SearchEngineType.Corax;

                Map = entities => from entity in entities
                                  select new
                                  {
                                      entity.Id,
                                      entity.Name,
                                      entity.Archived,
                                      entity.DateCreated
                                  };

            }
        }

        public class TestDocument
        {
            public string Id { get; set; } = null!;
            public bool Archived { get; set; }
            public DateTime DateCreated { get; set; }
            public string Name { get; set; } = null!;
        }


    }



}`

**Comment by KresoJ** [comment]
Hi @arekpalinski,
 the first test compares lucene and corax for the same data, and the second one detects the same document on different pages with corax engine.

**Comment by arekpalinski** [comment]
Thanks @KresoJ! 

@maciejaszyk can you check it please?

**Comment by maciejaszyk** [comment]
Hi @KresoJ,
great tests, I've found the bug and pushed the fix: https://github.com/ravendb/ravendb/pull/18470
