### ISSUE TITLE
Healthchecks with Docker Compose etc.

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#18707]
Typically this requires wget or curl in the docker container. Is there a way to get this?

Hoping to do something like this:

```
    # healthcheck:
    #   test: ${DOCKER_HEALTHCHECK_TEST:-curl --fail localhost:8080/setup/alive || exit 1}
    #   interval: "60s"
    #   timeout: "3s"
    #   retries: 2
```

So that I can verify that it is up in our test environment before executing migrations etc.

**Comment by ayende** [comment]
Not sure that I'm following, with the default `ravendb/ravendb` you have `curl` inside the machine?

**Comment by ayende** [comment]
I mean, you already have `curl` there, isn't that enough for your needs?

**Comment by JohnGalt1717** [comment]
Hrm.... it wasn't there and neither was wget inside the container with docker exec -it {container_name} bash before but a repull and exec and it's now there (I know I was in the container because rvn worked)

Thanks and sorry for the noise.
