### ISSUE TITLE
CORAX: in() query, different output as Lucene

### ISSUE THREAD

**Issue by xinix00** [ravendb/ravendb#18742]
.Where(c => c.SupplierId == null)    Works, only gives results where SupplierId == null
.Where(c => c.SupplierId.In([null]))     Doesn't work anymore, expected the same as above, but throws exception

When expected please let me know. Tested on Corax 6.0.104.

P.s. did not test it on Lucene 6.0.104, but know it was working on 5.x Lucene whatever I was using at the time.

**Comment by Lwiel** [comment]
It's a bug, I've created an issue for this - https://issues.hibernatingrhinos.com/issue/RavenDB-22537/Corax-In-query-doesnt-handle-null-values

**Comment by Lwiel** [comment]
It got fixed in https://github.com/ravendb/ravendb/pull/18779, next RavenDB 6.0 release will include this fix.
