### ISSUE TITLE
could not understand expression for a simple List.Contains / List.Any

### ISSUE THREAD

**Issue by ssteiner** [ravendb/ravendb#18838]
Here's my object model

```
public class PhoneBookCategory
{
    public string Id { get; set; }

    public string Name { get; set; }

    public List<string> PhoneBookIds { get; set; }
}

public class PhoneBook
{
    public string Id { get; set; }
	
	public string Name { get; set; }
}

```

I'm trying to find all `Phonebook` documents contained in the `PhoneBookIds` collection. I've tried these queries:

```
var pbc = new PhoneBookCategory
{
    Name = "something",
    PhoneBookIds = new ["PhoneBooks/1-A", "PhoneBooks/2-A"]
}
var query= session.Query<PhoneBook>();
var dbItems = query.Where(u => pbc.CategoryIds.Contains(u.Id)).ToList();
```

That results in 

> Could not understand expression: from 'PhoneBooks'.Where(u => value(RavenDbTest.Helpers.DataPreProcessor+<>c__DisplayClass3_0).category.PhoneBookIds.Contains(u.Id))

I did a bit of googling, and found the suggestion to use the `Any` operator instead, so I tried this:

` var dbItems = categoryTable.Where(u => pbc.CategoryIds.Any(x => x == u.Id)).ToList();`

I get pretty much the same error

> Could not understand expression: from 'PhoneBooks'.Where(u => value(RavenDbTest.Helpers.DataPreProcessor+<>c__DisplayClass3_0).category.PhoneBookIds.Any(id => (id == u.Id)))

So, what am I doing wrong? Seems a pretty basic lookup on the Id property.

**Comment by ayende** [comment]
You are trying to do something pretty odd, because you are checking the document _against_ itself.

If we were able to translate this query, it would look something like:

```
from PhoneBookContacts as u
where u.CategoryId.Contains(u)
```

In other words, you are trying to force us to do a query that would require evaluating each document directly.

What is the actual query that you are trying to execute? None of the code samples you showed are complete.

**Comment by ssteiner** [comment]
I adapted my questions.. I'm hoping it now reflects what I want to do: I want to check if the there's a `PhoneBook` whose Id is "PhoneBooks/1-A" and another whose Id is "PhoneBooks/2-A". I'd expect the found PhoneBook objects in the `dbItems` collection. If `dbItems.Count < pbc.PhoneBookIds.Cound`, then I know that one of the Ids is not a valid PhoneBook.

**Comment by ayende** [comment]
Isn't that just:

```
session.Query<PhoneBookCategory>()
  .Where(x=>x.PhoneBookIds.In("PhoneBooks/2-A", "PhoneBooks/1-A"))
  .ToList()
```

**Comment by ssteiner** [comment]
Yeah that seems to work. It also works for a single valued property, but it's kinda weird having to use a different syntax than you'd normally use as a C# dev.

**Comment by ayende** [comment]
The issue is where you are taking the values from, and how you look at them.

**Comment by ssteiner** [comment]
If I had one wish for RavenDb, it was to understand more of the standard Linq stuff. I can search in EFCore using the exact same expressions I'm using when searching a List<T> in plain code. That makes working with a document database really simple. I've worked so far with EFCore, LiteDb, MongoDb and RavenDb and EFCore really shines in that department.

In LiteDb, you can also append stuff to the query - at times I had to write my own filters that get appended to filters created from expressions.

```
    internal static ILiteQueryable<T> FilterReferencedSubtableContains<T>(ILiteQueryable<T> query, string subtableProperty, List<string> ids)
    {
        var bsArray = new BsonArray();
        foreach (var id in ids)
            bsArray.Add(id);
        return query.Where(Query.In($"$.{listProperty}[*].$id ANY", bsArray));
    }
```

**Comment by ayende** [comment]
Note that certain operations (like some of the things you tried above) are not permitted because they would require evaluating each row.

Appending items to the query is possible, you can switch from Linq to DocumentQuery at any time using `ToDocumentQuery()`, giving you the choice of lower level API.

See also this:
https://github.com/ayende/RaccoonBlog/blob/master/RaccoonBlog.Web/Infrastructure/Common/QueryableExtensions.cs#L16

**Comment by ssteiner** [comment]
`DocumentQuery()` is indeed flexible enough for me. Did my entire generic searching code with it and converted To/From DocumentQuery a bunch of times and mixed the DocumentQuery with the Query approach.
