### ISSUE TITLE
generic search - how to build the query

### ISSUE THREAD

**Issue by ssteiner** [ravendb/ravendb#18844]
My app has a way to dynamically  search. The user can select which field to search, the comparison operator (equalTo, notEqualTo, moreThan, lessThan, moreThanOrEqual, lessThanOrEqual, startsWith, endsWith, contains, isEmpty, isNotEmpty) and the operator (and, or). You'll find the class model at the bottom of the post.

Now, I'd need to turn these into something I can append to an `IRavenQueryable`. My generic solution, which is based on Linq doesn't work here because RavenDb cannot translate the expressions. E.g. it doesn't handle string.StartsWith, you can't do a .Select to select a single property on a subdocument, and I guess there's more that will eventually blow up in my face.

So, I'm curious how would I go about translating this fnctionality to RavenDb? 

The class model for this generic search is this

```
public class GenericSearchParameters 
{
    public BooleanOperator? Operator { get; set; }

    public List<GenericSearchParameter> SearchParameters { get; set; }

    public bool? SortAscending { get; set; }

    public string SortBy { get; set; }
}

public enum ComparisonOperator
{
    EqualTo,
    NotEqualTo,
    MoreThan,
    LessThan,
    MoreThanOrEqualTo,
    LessThanOrEqualTo,
    StartsWith,
    EndsWith,
    Contains,
    IsEmpty,
    IsNotEmpty
}

public enum BooleanOperator
{
    And,
    Or
}

public class GenericSearchParameter
{
    // the user has a dropdown, showing all properties of a document, and will select one
    public string FieldName { get; set; }
    // value to search for. Contains a string or a List<string> (List<string> is allowed for any FieldName that holds a collection, not a single value)
    public dynamic FieldValue { get; set; }
    // helper property that gets the string value of the search term
    public string FieldValueString => FieldValue?.ToString();
    // helper property that extracts the list from FieldValue
    public List<string> FieldValueCollection
    {
        get
        {
            if (FieldValue is Newtonsoft.Json.Linq.JArray array)
            {
                var list = new List<string>();
                var jArray = array;
                foreach (var child in jArray.Children())
                {
                    list.Add(child.ToString());
                }
                return list;
            }
            return null;
        }
    }

    public ComparisonOperator? FieldOperator { get; set; }
}
```

**Comment by Lwiel** [comment]
Have you tried using [DocumentQuery](https://ravendb.net/docs/article-page/6.0/csharp/client-api/session/querying/document-query/what-is-document-query)? You could start with `session.Advanced.DocumentQuery<YourType>()` and apply filtering based on user input.

**Comment by ssteiner** [comment]
How is `DocumentQuery` different from using `IRavenQueryable`? All the extension methods are still typed.  E.g. let's take this filtering example:

```
List<Employee> employees = session.Advanced
    .DocumentQuery<Employee>()
    .WhereEquals(x => x.FirstName, "Robert")
    .ToList();
```

Here you filter on the 'FirstName? property of an Employee object. So we have the type at compile time. What I want to do is work not knowing the type at compile time. So something like this:

```
List<T> items = session.Advanced
    .DocumentQuery<T>()
    .WhereEquals(x => "firstname", "Robert")
    .ToList();
```

where `T` is of type class, and that's all I know about T.
In LiteDb or MongoDb I have builder objects that allow me to construct generic queries - I've not found anything comparable for RavenDb yet.

**Comment by ppekrol** [comment]
Have you tried the overloads without Expression for DocumentQuery e.g.

```
session.Advanced.DocumentQuery<object>(collectionName: "Companies")
                        .WhereEquals("FieldName", "ABC")
                        .ToList();
```

?

Regarding the `T`, since we do have overloads that are not typed, then with them it should allow you to achieve what you want, so instead of 'object' that I've passed, you can use 'T' there.

**Comment by ssteiner** [comment]
No I wasn't aware of those. In the end, would the individual list items (that your query gets) still be castable to `T` or how'd you extract them?

**Comment by ppekrol** [comment]
if you will do 

```
session.Advanced.DocumentQuery<T>()
                        .WhereEquals("FieldName", "ABC")
                        .ToList();
```

then the query will return exactly the type you want, so it should be fine for you?

**Comment by ssteiner** [comment]
Yeah that looks fine. Give me some time to run a few tests.
Any reason why these generic operations are only on DocumentQuery?

**Comment by ppekrol** [comment]
Due to LINQ nature, everything is super-strongly typed, so most of the methods that you can use are not our extensions, those are extensions from System.Linq namespace for IQueryable. What we do is a pretty complex translation from the expression that is being built by LINQ to our own query language - RQL.

The DocumentQuery gives you builder-like approach, so it is more flexible for those kind of scenarios that you have.

**Comment by ssteiner** [comment]
So, I'm making my first steps with a DocumentQuery. For starters I used 
`session.Advanced.DocumentQuery<T>().Search("Name", "category")`

I have two documents, one with Name = 'updated category 1', and one with name 'Category2'. The `Search `only picks up the first document. So, how'd I search irrespective of case? I thought `Search` were case insensitive, at least the documentation [says so](https://ravendb.net/docs/article-page/6.0/csharp/client-api/session/querying/text-search/full-text-search).

Looking at the query in the debugger, I see it translates to this RQL

`from 'PhoneBookCategories' where search(Name, $p0)`

When I use `WhereStartsWith` instead of `Search`, that seems to search in a case insensitive matter.

**Comment by ppekrol** [comment]
By default search is using StandardAnalyzer which during tokenization process will convert 'Category2' into 'category2' term. That is why you cannot find what you are looking for. You would have to switch the analyzer or implement one that suits your needs yourself.

You can read more about analyzers here: https://ravendb.net/docs/article-page/6.0/csharp/indexes/using-analyzers
And if you want to write one yourself: https://ravendb.net/docs/article-page/6.0/csharp/studio/database/settings/custom-analyzers

**Comment by ppekrol** [comment]
BTW, inside the Indexes view in Studio you can take a peek at terms: 
![image](https://github.com/user-attachments/assets/ae78a277-a7b0-4bbe-aeac-a9115289661c)

Sth that also might be handy for you is the ability to include explanations: https://ravendb.net/docs/article-page/6.0/csharp/client-api/session/querying/debugging/include-explanations

**Comment by ssteiner** [comment]
hmm... so in the analyzer page, it states for `StandardAnalyzer`

> Converts to lower-case letters so that searches aren't case-sensitive.

Am I reading this wrong? I'd expect that if somebody states 'searches aren't case sensitive' that it doesn't matter how the search term or the contents of the document are cased.

Yet, this doesn't seem to be the case. 

And how'd I set a custom analyzer on a search operation / document type? I don't need to further down the rabbit hole and create separate handling per property.

**Comment by ppekrol** [comment]
You can only use custom analyzers in static indexes, but regarding the StandardAnalyzer.

If we have two documents:
`Name = updated category 1` => document-1
and
`Name = Category2` => document-2

then the StandardAnalyzer will produce following terms:
`updated `, `category `, `1` => document-1
`category2` => document-2

So we will end up with 4 terms, 3 pointing to document-1 and 1 pointing to document-2. That is why your query `session.Advanced.DocumentQuery<T>().Search("Name", "category")` cannot find the `document-2`, because there is no term like that pointing towards that document.

What you could do in your case is to consider using `*`
```
from 'PhoneBookCategories'
where search(Name, 'category*')
```

**Comment by ssteiner** [comment]
so I take it the category* means 

starts with 'category'

And if I require an actual `Contains`, then I'd be writing

session.Advanced.DocumentQuery<T>().Search("Name", "*category*")

so that it also picks up a document with Name = "some categorized name", correct?

**Comment by ayende** [comment]
In general, `search` already breaks apart the terms for you. 
So if you are working on word boundary, you don't need that.

If you want to do textual contains, you can use `*` there, yes.

**Comment by ssteiner** [comment]
okay, so I managed to do all my querying using `DocumentQuery()`
