### ISSUE TITLE
Loading a document whose type you only known at runtime.

### ISSUE THREAD

**Issue by ssteiner** [ravendb/ravendb#18848]
Is there a way to load a document whose Id I know, but whose type I only know at runtime?
I'm trying to write a generic 'look up references' solution. The `Include` command can take a string path, so the include part is covered, but the `Load` operation is typed only. I'd like to avoid writing a humongous if/then/else to load referenced documents .

**Comment by ayende** [comment]
`session.Query<object>(yourId)` should work, no?

**Comment by ssteiner** [comment]
Yes that seems to be working just fine. Thanks
