### ISSUE TITLE
Storing Raw Json / lightly typed object

### ISSUE THREAD

**Issue by ssteiner** [ravendb/ravendb#18855]
I'm trying to store the configuration for my plugin systems. I have about a dozen plugins which are loaded at runtime. Every plugin has its own configuration object which derives from this:

```
class BaseConfiguration
{
    public Guid Id {get; set;}
    public string Name {get; set;}
}
```

In other NoSql databases (I know LiteDb and MongoDb) I can extract a `BsonDocument `and convert it to a JSON string (and give that string to the plugin which is able to process it and create a new `PluginName_Configuration: BaseConfiguration` object from it. When storing data, the plugin can give me a json string that I then store. Is there a way to do this with RavenDb? Note that every config has a unique Id so unique Ids aren't a thing.

Also, as a start I tried to just save a BaseConfiguration - which fails

`Cannot set identity value 'BaseConfiguration/1-A' on property 'Id' for type 'NoSqlModels.BaseConfiguration' because property type is not a string`

The `Id` of the object I'm trying to save is a `Guid.NewGuid()` so it's filled out and I expected RavenDb to just use it as Id. What do I need to do for RavenDb to accept my filled out Guid?  Note that I'm using string Ids for all other entities, but this one I cannot change.

**Comment by ppekrol** [comment]
Underneath we are using Newtonsoft.Json, so you can use JObject for that, or if you want to go really low, our internal type BlittableJsonReaderObject, but please mind that this instance cannot be used outside of the session.

```csharp
                using (var session = store.OpenSession())
                {
                    var tempUser = session.Load<JObject>("users/3");
                }

                using (var session = store.OpenSession())
                {
                    var tempUser = session.Load<BlittableJsonReaderObject>("users/3");
                }
```

**Comment by ayende** [comment]
You should be able to just save that `PluginName_Configuration`, and let RavenDB handle the rest.
You may want to direct them all to the same collection, but there is no problem in storing them in a polymorphic collection

**Comment by ssteiner** [comment]
So I was using what @ppekrol wrote, using JObject to store my object. It works fine, but I have an issue nonetheless: This is an example of a document

`{"Id":"dc642722-dcda-4048-b052-bbd7ec9e946c","Name":"some plugin","SpecialConfig":{"Value1":"val1","Value2":"val2"}}`

then stored as follows:

```
            var newConfig = JObject.Parse(jsonString);
            await context.Session.StoreAsync(newConfig).ConfigureAwait(false);
            await context.Session.SaveChangesAsync().ConfigureAwait(false);
```

All that works fine, but if I check what was added in the studio, the document is there, but the key is something completely different from the Id I provided (dc642722-dcda-4048-b052-bbd7ec9e946c). How can I make it use the `Id` property I provided as key? I was under the impression that without any special configuration, `Id` would always end up being the key.

**Comment by ayende** [comment]
`await context.Session.StoreAsync(newConfig, "dc642722-dcda-4048-b052-bbd7ec9e946c")`

For dynamic values, we aren't taking the `Id` from it.
There is a conventions to get it (`AsyncDocumentIdGenerator`), but in general, just pass it directly.

**Comment by ssteiner** [comment]
Ahh, we're getting closer now. The only issue still remaining is replacing a document. When I call the same

`await context.Session.StoreAsync(newConfig, "dc642722-dcda-4048-b052-bbd7ec9e946c")`

and the Id is known, I'm getting a 

`Document dc642722-dcda-4048-b052-bbd7ec9e946c has change vector A:632-8eBxJu1JykyJfwzXBJ1THQ, but Put was called with expecting new document. Optimistic concurrency violation, transaction will be aborted.`

I then figured, I could just get the change vector from the existing entry, so I rewrote my 'Upsert' method as follows:

```
var existingConfig = await context.Session.LoadAsync<JObject>(id.ToString()).ConfigureAwait(false);
if (existingConfig != null)
{
    var changeVector = context.Session.Advanced.GetChangeVectorFor(existingConfig);
    await context.Session.StoreAsync(newConfig, changeVector, id).ConfigureAwait(false); // storing with the same id will overwrite it
}
else
{
    await context.Session.StoreAsync(newConfig, id).ConfigureAwait(false); // storing with the same id will overwrite it
}
await context.Session.SaveChangesAsync().ConfigureAwait(false);
```

However, that just gets me

> Attempted to associate a different object with id '5602ea1a-00f0-46f9-a48c-39d1ffe32b8a'

So how'd I replace my generic object? (I did use patch for my regular updates so I never hit this issue)

**Comment by ayende** [comment]
This is because you configured you session to use optimistic concurrency.
If you are just reading the value and overwriting it, just disable that.

If you still need it, there are a few options you can use here:

```
var existingConfig = await context.Session.LoadAsync<JObject>(id.ToString()).ConfigureAwait(false);
if (existingConfig != null)
{
   existingConfig.Merge(newConfig);
}
else
{
    await context.Session.StoreAsync(newConfig, id).ConfigureAwait(false); // storing with the same id will overwrite it
}
await context.Session.SaveChangesAsync().ConfigureAwait(false);
```

That would rely on the `JObject.Merge` to keep the same instance.

You can also force it to _not_ check:

```
    await context.Session.StoreAsync(newConfig, null, id, ConcurrencyCheckMode.Disabled).ConfigureAwait(false); 
```

**Comment by ssteiner** [comment]
Thanks
`existingConfig.Merge(newConfig)` did the trick. 

The StoreAsync method you mentioned is not public though - I saw it looking through the source, but it's not exposed in RavenDB.Client v 6.0.104.

**Comment by ayende** [comment]
Passing `null` for the `changeVector` overload will do the same trick.

**Comment by ssteiner** [comment]
Not here.. I have three `StoreAsync `methods:

```
public Task StoreAsync(object entity, CancellationToken token = default(CancellationToken))
{
    string id;
    bool flag = GenerateEntityIdOnTheClient.TryGetIdFromInstance(entity, out id);
    return StoreAsyncInternal(entity, null, null, (!flag) ? ConcurrencyCheckMode.Forced : ConcurrencyCheckMode.Auto, token);
}

public Task StoreAsync(object entity, string changeVector, string id, CancellationToken token = default(CancellationToken))
{
    return StoreAsyncInternal(entity, changeVector, id, (changeVector != null) ? ConcurrencyCheckMode.Forced : ConcurrencyCheckMode.Disabled, token);
}

public Task StoreAsync(object entity, string id, CancellationToken token = default(CancellationToken))
{
    return StoreAsyncInternal(entity, null, id, ConcurrencyCheckMode.Auto, token);
}
```

It's the `StoreAsyncInternal` method that has 5 parameters and that's not exposed.

**Comment by ssteiner** [comment]
One last question if I may: I've used the `FindCollectionName` to specify the desired name of my collection. If I were to have different collections that I want to treat this way - is there a way to somehow specify the collection name for a `Load`? Other NoSql Dbs I know have this `session.GetCollection<T>(string collectionName)` concept that allows you to 'select' a collection.

**Comment by ppekrol** [comment]
For that purpose we do have sth that we are calling a 'collection query', basically if you do `session.Query<T>().ToList()` - since there is no where statement, this will perform an optimization and just return the documens from T collection directly. It also supports adding `.Where(x => x.Id == "sth")` and you can stream the results via `session.Advanced.Stream` method.

**Comment by ssteiner** [comment]
But wouldn't `session.Query<T>().ToList()` return everything in the collection belonging to T? (e.g. if T is of type Document, the collection name would be 'documents'). With MongoDb for instance, I could write a `BSonDocument` to a collection named 'hello' and another BSonDocument to a collection named 'world' (they use `BsonDocument` instead of `JObject`). With RavenDb it's one collection per Type, no? I seem to recall seeing one api that took a collectionName as optional parameter, but don't recall which one. And it was only one, not everywhere.

I think I found something where you can manually assign the collection Name upon insert:

`session.Advanced.GetMetadataFor(apple)[Constants.RavenEntityName] = "Fruits";`

So that way, you could have one `JObject` in one collection and the other in another.

So assuming you'd have two collections one named 'hello', the other 'world' both of type JObject, how would you query only documents that are in the collection 'hello' or 'world'? session.Query<T>() wouldn't do it, it would look in the collection 'Ts' (named DocumentConventions.DefaultGetCollectionName(typeof(T))) and not find anything because that collection doesn't exist. Are am I missing something?

**Comment by ppekrol** [comment]
I think what you are looking for is:
```
session.Advanced.DocumentQuery<JObject>(collectionName: "MyCollection")
```

Also you can index polymorphic data if needed: https://ravendb.net/docs/article-page/6.0/csharp/indexes/indexing-polymorphic-data

**Comment by ssteiner** [comment]
Ahh, `DocumentQuery` to the rescue yet again.
