### ISSUE TITLE
Building a generic Search for IRavenQueryable

### ISSUE THREAD

**Issue by ssteiner** [ravendb/ravendb#18856]
I'm trying to build a Search operation, where I don't need an expression to identitfy the property I want to search on.

so the method should look like this:

`public static IRavenQueryable<T> Search<T>(this IQueryable<T> self, string fieldName, string searchTerms, decimal boost = 1m, SearchOptions options = SearchOptions.Guess, SearchOperator @operator = SearchOperator.Or)`

So I took the existing implementation

```
public static IRavenQueryable<T> Search<T>(this IQueryable<T> self, Expression<Func<T, object>> fieldSelector, string searchTerms, decimal boost = 1m, SearchOptions options = SearchOptions.Guess, SearchOperator @operator = SearchOperator.Or)
{
    MethodInfo method = (MethodInfo)MethodBase.GetCurrentMethod();
    return (IRavenQueryable<T>)self.Provider.CreateQuery(Expression.Call(null, method, self.Expression, fieldSelector, Expression.Constant(searchTerms), Expression.Constant(boost), Expression.Constant(options), Expression.Constant(@operator)));
}
```

And adapted it as follows::

```
public static IRavenQueryable<T> Search<T>(this IQueryable<T> self, string fieldName, string searchTerms, decimal boost = 1m, SearchOptions options = SearchOptions.Guess, SearchOperator @operator = SearchOperator.Or)
{
    MethodInfo method = (MethodInfo)MethodBase.GetCurrentMethod();
    var info = typeof(T).GetProperty(fieldName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
        ?? throw new Exception($"{fieldName} is not a valid property on {typeof(T).Name}");
    var parTarget = Expression.Parameter(info.DeclaringType, "target");
    var exprGetter= QueryableExtension.GetGetter<T, object>(fieldName);
    return (IRavenQueryable<T>)self.Provider.CreateQuery(Expression.Call(null, method, self.Expression, exprGetter, Expression.Constant(searchTerms), Expression.Constant(boost), Expression.Constant(options), Expression.Constant(@operator)));
}

public static Expression<Func<T, P>> GetGetter<T, P>(string propName)
{
    var parameter = Expression.Parameter(typeof(T));
    var property = Expression.Property(parameter, propName);
    return Expression.Lambda<Func<T, P>>(property, parameter);
}

```

However, that immediately throws

> System.ArgumentException: 'Expression of type 'System.Func2[NoSqlModels.PhoneBookCategory,System.Object]' cannot be used for parameter of type 'System.String' of method  'Raven.Client.Documents.Linq.IRavenQueryable1[NoSqlModels.PhoneBookCategory] Search[PhoneBookCategory](System.Linq.IQueryable`1[NoSqlModels.PhoneBookCategory], System.String, System.String, System.Decimal, Raven.Client.Documents.SearchOptions, Raven.Client.Documents.Queries.SearchOperator)' (Parameter 'arguments[1](https://github.com/ravendb/ravendb/blob/f6d8087c8b59b7c484ab96e064c904902d94a648/src/Raven.Client/Documents/LinqExtensions.cs#L32)')'

So, it seems the method is trying to call itself. Given that RavenDb's native extension method works, I'm wondering where I'm going wrong.

**Comment by maciejaszyk** [comment]
Maybe let's make this task simpler, and your overload will generate only the expression that you will pass to our method?

e.g:
```csharp
public static IRavenQueryable<T> Search<T>(this IQueryable<T> self, string fieldName, string searchTerms, decimal boost = 1m, SearchOptions options = SearchOptions.Guess, SearchOperator @operator = SearchOperator.Or)
    {
        var exprGetter= GetGetter<T, object>(fieldName);
        return self.Search(exprGetter, searchTerms, boost, options, @operator);
    }

    public static Expression<Func<T, P>> GetGetter<T, P>(string propName)
    {
        var parameter = Expression.Parameter(typeof(T));
        var property = Expression.Property(parameter, propName);
        return Expression.Lambda<Func<T, P>>(property, parameter);
    }
```

**Comment by ssteiner** [comment]
Geez - I came up with the `GetGetter` method late, I had another approach first which got me `Expression<T,TProperty>` and it didn't cross my mind to just try and call the method I originally targeted now that I had the proper parameter for it. Of course what you proposed works like a charm. Thanks :)
Might in fact make a good addition to LinqExtensions.cs ;) I already implemented another few useful ones for sorting ..
