### ISSUE TITLE
moving property from one collection to another

### ISSUE THREAD

**Issue by ssteiner** [ravendb/ravendb#18955]
I'm currently looking into migrations on RavenDb with Raven.Migrations which uses Patch commands to modify collections. So I'm going through the scenarios we encountered in the relational world in the past couple of years, and one of the scenarios we had was 'we need to move a property from one document to another'.  In the relational world, with EFCore and migrations, I wrote something like this:

`migrationBuilder.Sql("UPDATE ap SET ap.PrivateCallingNumberDialPlanId = l.PrivateCallingNumberDialPlanId FROM Alcatelprofiles ap INNER JOIN Locations l on l.AlcatelProfileId = ap.Id AND l.PrivateCallingNumberDialPlanId is not null");`

This would take the value `PrivateCallingNumberDialPlanId` on the `Location` document, and move it to the `AlcatelProfile` document if some conditions are satisfied. Looking at the RQL syntax, it seems to me this is meant for one collection and one collection only (makes sense given that the data is denormalized). But before I start to manually deconstruct this, I was just wondering whether I'm maybe missing something that would make my life easier given that I'm just starting out my journey with RavenDb.

**Comment by ayende** [comment]
You can mutate other documents as part of the patch.

Here is a similar example:

```
from Locations as l 
where exists(l.PrivateCallingNumberDialPlanId)
update 
{
   let ap = load(l.AlcatelProfileId);
   ap.PrivateCallingNumberDialPlanId = l.PrivateCallingNumberDialPlanId;
   put(l.AlcatelProfileId, ap);
  delete l.PrivateCallingNumberDialPlanId;
}
```

You mutate (and auto save) the `Locations` document, and `load` and `put` the associated document explicitly.

**Comment by ssteiner** [comment]
That looks promising. Is there a syntax reference somwehere for the `put` command? I found the `load` command, but not the `put` c command.

**Comment by ayende** [comment]
It's just JavaScript, full docs here: https://ravendb.net/docs/article-page/6.0/Csharp/server/kb/javascript-engine

In general, you have:

```
Documents:
load(documentIdToLoad) - loads document by ID
put(documentId, document) - puts document with given name and data
del(documentIdToRemove) - deletes document by ID
Counters:
counter(document/documentId, name) - get the counter value by document/document ID
incrementCounter(document/documentId, name, value = 1) - increment a counter by document/document ID
deleteCounter(document/documentId, name) - delete a counter by document/document ID
Time Series:
timeseries(document/documentId, name).get(from, to) - get timeseries entries
timeseries(document/documentId, name).append(timestamp, values, tag = null) - add a new entry to a timeseries
timeseries(document/documentId, name).delete(from, to) - delete entries from a timeseries
General:
output(message) - output debug info when testing
```

**Comment by ssteiner** [comment]
Thanks. By the way, slight typo in your solution - line 2 of the script shouldn't end with a ;.

**Comment by ayende** [comment]
Thanks, fixed
