### ISSUE TITLE
error in the patching documentation? Undefined args.EmployeeToUpdate in the update by dynamic query

### ISSUE THREAD

**Issue by ssteiner** [ravendb/ravendb#18956]
Am I just not getting something in this sample or does the example leave out how the `args.EmployeeToUpdate` is supplied in 
[this example](https://ravendb.net/docs/article-page/4.0/csharp/client-api/operations/patching/set-based#update-by-dynamic-query)?

**Comment by ppekrol** [comment]
Hi, you are looking at 4.0 documentation, have you checked our latest one? https://ravendb.net/docs/article-page/6.0/csharp/client-api/operations/patching/set-based#update-by-dynamic-query

**Comment by ppekrol** [comment]
There is also an example there with parameters that might be helpful:
https://ravendb.net/docs/article-page/6.0/csharp/client-api/operations/patching/set-based#updating-by-document-id-using-parameters

**Comment by ssteiner** [comment]
Urgh, indeed you caught me. I'm already using the approach with parameters in my code. Not the first time I ended up in an old version of the documentation by accident. If I get the wrong language, I generally find out quickly because of the syntax, but here, RQL is RQL.
