### ISSUE TITLE
Insert and query directly No results

### ISSUE THREAD

**Issue by 17723010593** [ravendb/ravendb#19177]
I've executed the Add Query method many times, and sometimes I can't get the value, but the database has been added successfully

![image](https://github.com/user-attachments/assets/838dc891-3667-4e2b-bc41-9ba42d21d46c)

**Comment by arekpalinski** [comment]
Indexes in RavenDB are BASE (https://ravendb.net/docs/article-page/6.0/csharp/client-api/faq/transaction-support#base-for-query-operations).

Please read more about the concept of staleness in the following article: https://ravendb.net/docs/article-page/6.0/csharp/indexes/stale-indexes

Basically there is small delay after you store a document and when it becomes available in the query results. In your case the query will be handled by auto index (which will be created on the first querying attempt - https://ravendb.net/docs/article-page/6.0/csharp/client-api/session/querying/how-to-query). 

Please note there is a way to explicitly wait for non stale results - https://ravendb.net/docs/article-page/6.0/csharp/indexes/stale-indexes#explicitly-waiting-for-non-stale-results. Although it real world applications this isn't needed, or it's used only in very specific scenarios. One common usage of `WaitForNonStaleResults()` are the tests, where the things are happening really fast so then you might want to customize all queries to wait until an indexing is completed before returning query results.
