### ISSUE TITLE
Unable to Restore Administrator Permissions After Changing Certificate to Read/Write

### ISSUE THREAD

**Issue by M4xymS** [ravendb/ravendb#19620]
When changing the permissions of a certificate from "**Administrator**" to "**Read/Write**," the option to restore the certificate's permissions back to "**Administrator**" **disappears**. This makes it **impossible** to revert the certificate's access level

**Steps to Reproduce:**

1. Open the certificate management panel.
2. Change the permissions of a certificate from "Administrator" to "Read/Write."
3. Attempt to change the permissions back to "Administrator."

**Expected Behavior:**
The option to restore the certificate's permissions to "Administrator" should remain available at all times.

**Observed Behavior:**
After changing the certificate's permissions to "Read/Write," the "Administrator" option is no longer available.

**Environment:**

- **Version**: RavenDB 6.2
- **Browser**: Google Chrome v130.0.6723.119
- **OS**: Windows 11

**Comment by ayende** [comment]
I cannot reproduce, see:

![image](https://github.com/user-attachments/assets/76e03011-bb35-432c-826c-e299cef94b73)

**Comment by M4xymS** [comment]
After retesting again it works, my mistake. closing.
