### ISSUE TITLE
Put compare exchange through session

### ISSUE THREAD

**Issue by adambajguz** [ravendb/ravendb#19707]
Hello Raven Team,
I was looking for a put compare exchange operation in `<SessionInstance>`.Advanced.ClusterTransaction` and I didn't find it. I looked into this file:

https://github.com/ravendb/ravendb/blob/bf82e4e6d46b11a3d55f7d45685babf19b697bb7/src/Raven.Client/Documents/Session/ClusterTransactionSession.cs#L455C1-L490C112

and I think it is doable. What do you think?

**Comment by karmeli87** [comment]
Hi,

I think what you are looking for is `CreateCompareExchangeValue`.
https://ravendb.net/docs/article-page/6.2/Csharp/client-api/session/cluster-transaction/compare-exchange#example

**Comment by adambajguz** [comment]
Hi, but this method on SaveChanges() throws a ConcurrencyException if the key already exists.
What I'm looking for is an ability to update the compare exchange value.


What I'm currently using for a workaround is

```csharp
 BlittableJsonReaderObject entityToInsert =
                    CompareExchangeValueBlittableJsonConverter.ConvertToBlittable(realKey, dao, _session);

                PutCompareExchangeCommandData putCommand = new(
                    realKey, entityToInsert, loadedEntry?.Index ?? 0);

                _session.Advanced.Defer(putCommand);
...

        private static class CompareExchangeValueBlittableJsonConverter
        {
            public static BlittableJsonReaderObject ConvertToBlittable(string key, object _value, IAsyncDocumentSession session)
            {
                return ConvertToBlittable(
                    key,
                    _value,
                    session.Advanced.DocumentStore.Conventions,
                    session.Advanced.Context);
            }

            public static BlittableJsonReaderObject ConvertToBlittable(string key, object value, DocumentConventions conventions, JsonOperationContext context)
            {
                object? entity = ConvertToBlittable(value, conventions, context, conventions.Serialization.CreateSerializer());

                DynamicJsonValue djv = new()
                {
                    ["Object"] = entity
                };

                return context.ReadObject(djv, key);
            }

            private static object? ConvertToBlittable(object value, DocumentConventions conventions, JsonOperationContext context, IJsonSerializer jsonSerializer)
            {
                if (value is null)
                {
                    return null;
                }

                if (value is ValueType or
                    string or
                    BlittableJsonReaderArray)
                {
                    return value;
                }

                return conventions.Serialization.DefaultConverter.ToBlittable(value, context);
            }
        }
```
and it works.

Create is create, what is missing is update or put (create or update aka. upsert).

**Comment by karmeli87** [comment]
Compare Exchange values are tracked by the session.

So you need simply to get it with `session.Advanced.ClusterTransaction.GetCompareExchangeValue`, modify it as needed and everything is handled when you do `SaveChanges`.

You can reference to this test on how to work with that
https://github.com/ravendb/ravendb/blob/25ce3dca43df008b6772a2e2356f956230bbcbde/test/SlowTests/Issues/RavenDB_14034.cs#L23

**Comment by adambajguz** [comment]
ok, I must have done sth wrong
