### ISSUE TITLE
InvalidCastException is only thrown if document has already been loaded

### ISSUE THREAD

**Issue by loraderon** [ravendb/ravendb#19703]
If we are trying to load a document into the wrong type when it has already been loaded an `InvalidCastException` is thrown, but if the document has not been loaded by the session yet no `InvalidCastException` is thrown and the loaded document is silently deserialized into that type.

```cs
using System;
using Tests.Infrastructure;
using Xunit;
using Xunit.Abstractions;

namespace FastTests.Client
{
    public class LoadInvalidCasts : RavenTestBase
    {
        public LoadInvalidCasts(ITestOutputHelper output) : base(output)
        {
        }

        [RavenTheory(RavenTestCategory.ClientApi)]
        [RavenData(SearchEngineMode = RavenSearchEngineMode.All)]
        public void InvalidCastWhenLoadingWrongEntityAfterEntityWasLoadedCorrectly(Options options)
        {
            var store = GetDocumentStore(options);

            var fooId = "foos/1";
            using (var session = store.OpenSession())
            {
                session.Store(new Foo { Id = fooId, Name = "Foo", });
                session.SaveChanges();
            }

            using (var session = store.OpenSession())
            {
                var loaded = session.Load<Foo>(fooId);
                Assert.Equal("Foo", loaded.Name);

                Assert.Throws<InvalidCastException>(() =>
                {
                    var loaded = session.Load<Bar>(fooId);
                    Assert.Null(loaded?.Name);
                }); // ✅
            }
        }

        [RavenTheory(RavenTestCategory.ClientApi)]
        [RavenData(SearchEngineMode = RavenSearchEngineMode.All)]
        public void InvalidCastWhenLoadingWrongEntity(Options options)
        {
            var store = GetDocumentStore(options);

            var fooId = "foos/1";
            using (var session = store.OpenSession())
            {
                session.Store(new Foo { Id = fooId, Name = "Foo", });
                session.SaveChanges();
            }

            using (var session = store.OpenSession())
            {
                Assert.Throws<InvalidCastException>(() =>
                {
                    var loaded = session.Load<Bar>(fooId);
                    Assert.Null(loaded?.Name);
                }); // 💥
            }
        }

        private class Foo
        {
            public string Id { get; set; }
            public string Name { get; set; }
        }
        private class Bar
        {
            public string Id { get; set; }
            public string Name { get; set; }
        }
    }
}
```

**Comment by ppekrol** [comment]
This is by design, session will allow you to deserialize document into any type. You can use 'OnBeforeConversionToEntity' event to throw an exception.

**Comment by loraderon** [comment]
> This is by design, session will allow you to deserialize document into any type.

Can I ask why? I see no information regarding this behavior in the documentation for Load https://ravendb.net/docs/article-page/6.2/csharp/client-api/session/loading-entities.
And why does it depend on if the document has already been loaded or not?

**Comment by ppekrol** [comment]
After first load session registers the entity and starts tracking the changes to that object instance, allowing to change the entity type in the middle of tracking would violate a lot of constrains when it comes to tracking. You can use `Evict` method to remove that entity from the session entirely.

**Comment by loraderon** [comment]
Would it make sense to have a property that can modify this (with the default being the current behavior)?

I could probably take a look at creating such a PR but not really sure about the wording (LoadTypeProtection.AfterLoad & LoadTypeProtection.Always ..?) and if it should be on `SessionOptions` or `DocumentConventions`.

**Comment by ppekrol** [comment]
We had many issues with that in the past, that is why it was removed in 4.0. If needed you can use 'OnBeforeConversionToEntity' event (either global in IDocumentStore or per Session) and assert `Raven-Clr-Type` there from the metadata. I would suggest going this way.

**Comment by ayende** [comment]
Note that if this would work in the manner you want, I think, if you set the session to `NoTracking`.
